editorial: Separate producer from platform requirements in Levels
slsa-framework/slsa pull request #1009
Opened 2023-12-12 18:18 UTC by marcelamelara

This PR adds a separate "Build Platform Requirements" row in each table of levels.md, more clearly defining what SW producers vs. build platform are responsible for at each level. 

This change more closely matches the current separation in requirements.md, and also facilitates adding requirements for each role in higher/newer Build Track levels.

2023-12-12 18:33 UTC, marcelamelara commented
cc @joshuagl since I added this to the v1.1 directory (please let me know, if this shouldn't be part of those changes)

2023-12-13 15:52 UTC, jkjell approved these changes
I really like the clarity this separation of responsibilities brings!

2023-12-13 15:52 UTC, jkjell commented on docs/spec/v1.1/levels.md
> +    determined by the package ecosystem.
Perhaps we could also add something like:

>Additionally, leveraging a [SECURITY-INSIGHTS.yml](https://github.com/ossf/security-insights-spec/blob/main/specification.md) can offer machine-readable information about the expected location to retrieve a provenance document.

2023-12-13 21:40 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +    determined by the package ecosystem.
> Perhaps we could also add something like:
> 
> > Additionally, leveraging a [SECURITY-INSIGHTS.yml](https://github.com/ossf/security-insights-spec/blob/main/specification.md) can offer machine-readable information about the expected location to retrieve a provenance document.

This sounds like an implementation suggestion rather than part of the levels specification, so I don't think it belongs on this page. I'd suggest we move discussion into a new PR since adding it here would change this from an editorial PR to a content one.

2023-12-13 21:40 UTC, kpk47 approved these changes

2023-12-13 22:34 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +    determined by the package ecosystem.
Agree with @kpk47 . I like this suggestion, but also think it goes beyond the scope of this PR.

2023-12-14 17:20 UTC, MarkLodato commented on docs/spec/v1.1/levels.md
>      of the provenance.
Hmm, this isn't a producer requirement though. It's more of an "ecosystem" requirement.

That said, the original bullet wasn't clear to begin with. We really need to rework verification for v1.1. The intent of this bullet (which doesn't really come across) is that merely publishing provenance is not sufficient at L2. Something needs to check that provenance, and only then does it "become" L2. But this really needs to be fleshed out...

Not sure how best to align with this PR though.

2023-12-14 20:24 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
>      of the provenance.
I see, that's important nuance. 

As @MarkLodato points out, this isn't within the scope of this PR, but a question that immediately comes to mind with this "ecosystem requirement" is how anyone in the ecosystem would verify that the provenance has been checked? It sounds like a VSA generated by a downstream entity is part of this requirement. 

One way that I can think to resolve this in the context of this PR might be to add a third row starting at L2 that is for "Consumer Requirements", and reword the requirement:

```suggestion
-   Ensure that provenance, including its authenticity, is verified. This may be delegated to a third-party verifier. 
     Note: this requirement will be refined in a future version of the spec.
```

I am a little worried that this change turns this PR into a content PR, rather than merely an editorial PR. I'm also wondering if this PR should be part of v1.0 or v1.1.

2023-12-14 21:14 UTC, MarkLodato commented on docs/spec/v1.1/levels.md
>      of the provenance.
v1.1 sounds seems right to me (let's leave v1.0 stable), as does sticking to only editorial changes in this PR.

Instead of adding separate rows per party, have you considered prefixing each bullet with the party? Would that achieve the same effect without having too many rows? For example:

-   **Software producer:** Run builds on a hosted build platform that meets Build L2 requirements.
-   **Build platform:** Generate and sign the provenance itself. [...]
-   **Consumer:** Validate the authenticity of the provenance.

Here "Consumer" might not be a perfect fit, but perhaps it's good enough for this PR and we can iterate later?

2023-12-14 22:50 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
>      of the provenance.
I'm fine prefixing bullets with the party if we're going beyond producer/platform requirements. That will certainly keep the tables a little more concise.

FWIW, I think that "consumer" does make a lot of sense here because it sets us up for making more explicit verification requirements. For example, IMO, consumers of artifacts should always check the authenticity of the provenance for each consumed artifact (whether that's as a dependency or as an application), or delegate this task to a trusted verifier. That said, there might be other verification scenarios that don't pertain to the consumer at L2, so I agree that this needs to be iterated over some more.

2023-12-14 23:12 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +-   **Build platform:** Automatically generate [provenance] describing how
I don't like the inconsistency in this presentation. I think it would be best to standardize on the format
```
**Actor:** Requirement
**Actor2:** Requirement
**Actor2:** Requirement
...
```

2023-12-15 17:20 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +-   **Build platform:** Automatically generate [provenance] describing how
The main goal of this PR is to present a more clearly visible split between the different actors, which IMO a single list of bullets (which is the current format) doesn't do very well. Can we compromise on something like this?

```
- **Actor1**:
   - Requirement1
   - Requirement2
- **Actor2**:
   - Requirement1
- **Actor3**:
   - Requirement1
   - Requirement2
```

2023-12-19 15:51 UTC, MarkLodato approved these changes

2023-12-19 15:51 UTC, MarkLodato commented on docs/spec/v1.1/levels.md
> +-   **Software producer:**
suggestion: Remove the bold on each entry (not longer needed if it's not inline with the text) and remove blank lines between bullets to make it a "compact" list. Here's a screenshot of what it would look like with those changes:

![image](https://github.com/slsa-framework/slsa/assets/58860/87f6e846-5045-4cac-a00a-f6cb8a8b6bff)

2023-12-19 17:31 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +-   **Software producer:**
done.

2023-12-19 19:21 UTC, arewm requested changes

2023-12-19 19:21 UTC, arewm commented on docs/spec/v1.1/levels.md
> +        determined by the package ecosystem.
One key difference between this section and requirements.md is that the specification indicates

> The producer MUST select a build platform that is capable of reaching their desired SLSA Build Level.

This is slightly stronger than following a consistent build process. It is an assumption that is tied in to the fact that producers have to distribute provenance. 

```suggestion
    -   Follow a consistent build process so that others can form
        expectations about what a "correct" build looks like.
    -   Run builds on a hosted build platform that meets Build L1
        requirements.
    -   Distribute provenance to consumers, preferably using a convention
        determined by the package ecosystem.

```

2024-01-02 17:01 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +        determined by the package ecosystem.
Makes sense to me. I'm ok with adding in the extra bullet point as long as this still counts as a purely editorial change. @MarkLodato ?

2024-01-02 18:41 UTC, MarkLodato commented on docs/spec/v1.1/levels.md
> +        determined by the package ecosystem.
I'm fine with that.

2024-01-02 22:12 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +        determined by the package ecosystem.
One fine point to mention though, is that the "hosted" build platform is not an L1 requirement, so that's the only edit I'd make to the extra bullet point.

2024-01-06 00:09 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +    -   Run builds on a hosted build platform that meets Build L2
```suggestion
    -   Run builds on a **hosted** build platform that meets Build L2
```

2024-01-08 08:29 UTC, joshuagl approved these changes
I really like how this has turned out, thanks Marcela and all the reviewers for iterating on this!

2024-01-08 08:29 UTC, joshuagl commented on docs/spec/v1.1/levels.md
> +        some equivalent platform that ensures the trustworthiness of the
Nit: the "platform [...] use platform" jars a little, could we do something like:
```suggestion
        some equivalent system that ensures the trustworthiness of the
```

2024-01-08 08:29 UTC, joshuagl commented on docs/spec/v1.1/levels.md
> +
```suggestion
```
The other entries are a single list with each top-level bullet being an actor and the sub-bullets being requirements on the actor. Removing this line collapses L1 to match the other lists.

2024-01-08 17:56 UTC, marcelamelara commented
The last set of recommended changes are in. Thank you all for the feedback!

2024-01-09 11:15 UTC, merged