Content: Add draft of the Source track.
slsa-framework/slsa pull request #1037
Opened 2024-03-13 18:36 UTC by kpk47

This change adds the working draft of SLSA's Source track. It includes basic terminology, level requirements, and an attestation format.

2024-03-14 16:54 UTC, ramonpetgrave64 commented on docs/spec/v1.1/levels.md
> +The project is stored and managed through a source control platform that ensures the change history's integrity..
```suggestion
The project is stored and managed through a source control platform that ensures the change history's integrity.
```

2024-03-15 09:58 UTC, laurentsimon commented on docs/spec/v1.1/levels.md
> +**[Retained history]** The change history MUST be preserved as long as the source is hosted on the source control system. The source MAY migrate to another source control system, but the organization
nit: you could provide a use case to motivate it, like if a secret must be deleted from history

2024-03-15 09:58 UTC, laurentsimon commented on docs/spec/v1.1/source-att.md
> +| `historyRetained` | FeatureHistory | L2+ | Whether this project retains its version history.
So _only_ the platform is able to provide the feature of history retention? What if a company mirrors a project that has no source level, but performs the retention themselves? Should they not be able to create a source attestation themselves?

2024-03-15 09:58 UTC, laurentsimon commented on docs/spec/v1.1/source-att.md
> +Source L2+ MUST be generated by the trusted version control platform.
this seems a bit constraining. How about relaxing it a bit: the platform MUST provide access to the information (e.g., via API). The platform SHOULD generate the attestation, but other party MAY generate it using platform's API, etc.

2024-03-15 09:58 UTC, laurentsimon commented on docs/spec/v1.1/source-att.md
> +| `codeReview` | FeatureHistory | L3+ | Whether this project requires code review.
These fields are a "summary" of a policy enforced by the platform. However there are many cases where you need to have a different kind of attestation that simply enumerates the list of commits and their reviewers:
1. When the policy (containing _who_ should be allowed to review) is not useable by consumers. That's the case for most small open-source projects. From a consumer's point of view. there is _no_ way to detect whether identities are the same person or not. Yet, we want to enable consumers to know about _who_ reviewed the code, to enable them to make their own judgment.
2. There are a lot of corner cases in practice. Example: someone edits a PR and then LGTM. This is common on dependabot or other automated PRs. user must be able to customize their policy and risk tolerance. 

I think we need to separate _policy_ from the _facts_. Example: in the build track, the builder creates an attestation which is a list of _facts_: the repo, the commit, etc. There is _no_ policy involved, ie no interpretation. That is left to consumers, ie they decide if the right repo was used, etc. The VSA (or other attestation)'s role is for an org (or project) to hide the details.

Similarly, here, there are facts to report: the settings, who reviewed each PR, etc. These fields should be part of the source attestation.

Then come the policy, which is _who_ is able to review. In the current proposal, the attestation is essentially a VSA, not an attestation about facts. The VSA is created by the CVS platform, which is totally fine. But there are cases where this cannot be the case, and we should enable these other use cases.

2024-03-15 09:58 UTC, laurentsimon commented on docs/spec/v1.1/source-reqs.md
> +The version control platform MUST provide at least:
The model here seems a bit constraining. Not every CVS is in charge of reviews. Think gerrit on GitHub. can we capture that?

2024-03-18 02:04 UTC, ianlewis commented on docs/spec/v1.1/source-att.md
> +| `codeReview` | FeatureHistory | L3+ | Whether this project requires code review.
+1

I think for code review we should have some other trusted way to determine if code was reviewed and verify that way. `Reviewed-by` trailers are an example, though it may be hard to trust them. Maybe you could also verify via an API who's information can't be trivially modified.

2024-03-19 22:00 UTC, kpk47 commented on docs/spec/v1.1/source-att.md
> +| `codeReview` | FeatureHistory | L3+ | Whether this project requires code review.
Are you proposing attestations for each review/commit/PR? We discussed that option in the Google Doc version but rejected it because it would be cumbersome to manage all those attestations. And since they'd ultimately come from the source platform, we wouldn't gain much since you have to trust the source platform in either case.

2024-03-20 09:38 UTC, laurentsimon commented on docs/spec/v1.1/source-att.md
> +| `codeReview` | FeatureHistory | L3+ | Whether this project requires code review.
> Are you proposing attestations for each review/commit/PR

No. I'm proposing an attestation that _lists_ PRs. The one you have here is fine as well, but it's an opinionated attestation based on a policy evaluation.

2024-03-20 15:19 UTC, kpk47 commented on docs/spec/v1.1/source-reqs.md
> +## Infrastructure Requirements
I moved these requirements up into Infrastructure Requirements.

2024-03-20 15:19 UTC, kpk47 commented on docs/spec/v1.1/source-reqs.md
> +The version control platform MUST provide at least:
@laurentsimon Again, this is about where you draw the box. I'd rather just draw the box around all the trusted source components and call it a day. I would need to understand the purported benefit of further detail to change my mind.

@ianlewis I don't think it's practical to relegate code review checks to end user policy evaluation. See my other comment for more detail. What benefit do you see to commit signing here? Are you proposing that reviewers sign the commits? IIUC such a scheme is impractically difficult to implement because each signature effectively creates a new commit that invalidates the previous one. If we want to go in that direction, we'd probably want [gittuf](https://gittuf.dev/), but I think even that system is too complex for most projects.

2024-03-20 16:39 UTC, laurentsimon commented on docs/spec/v1.1/source-att.md
> +| `historyRetained` | FeatureHistory | L2+ | Whether this project retains its version history.
All I'm saying is that we're saying _only_ the source platform is allowed to generate these attestations, whereas there are cases where some claims (retentions) may not be possible and projects _may_ be struck at a level below what they could. So I suppose consumers will need to take in these low-level attestations without retention, and store the code themselves, and create a new attestation for it? (something along these lines)

I'm not trying to say this does not work, I'm trying to understand how this fits in the overall picture and how consumers will use it.

2024-03-20 16:41 UTC, laurentsimon commented on docs/spec/v1.1/source-att.md
> +| `codeReview` | FeatureHistory | L3+ | Whether this project requires code review.
You're correct there are timing considerations, but if an consuming entity wants to do that verification, we should not prevent them from doing so. Otherwise they'll just be using scorecard or other mechanisms for all open-source projects. Tracking bugs seems good to me, thanks!

2024-03-20 16:47 UTC, kpk47 commented on docs/spec/v1.1/source-att.md
> +| `historyRetained` | FeatureHistory | L2+ | Whether this project retains its version history.
Ah, I misunderstood your comment. The source track is scoped to how the project maintains itself. If the project is unwilling or unable to retain its source code, then it's L1 until that situation changes. Although it may seem harsh, there is no alternative in the scope of the source track -- we can't tell developers they aren't allowed to delete their code. 

If someone else wants to retain the source code for their own use, that's a dependency concern. If someone wants to republish the source code with their own guarantees layered on top (e.g. retention), then they're effectively creating a new project and should generate its attestations from its source control platform.

2024-03-20 16:58 UTC, laurentsimon commented on docs/spec/v1.1/source-att.md
> +| `historyRetained` | FeatureHistory | L2+ | Whether this project retains its version history.
I think that answers my question, thanks

2024-03-20 19:44 UTC, arewm requested changes
Thanks for this extensive draft!

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/source-att.md
> +[Provenance generation](requirements#provenance-generation) for details.
This seems odd to put here as the references for what needs to be met are not explicitly defined. The requirements for provenance generation are not tied to the levels of the source track directly and the requirements in the build track are additionally tailored to the generation of the build provenance (i.e. around completeness). 

If you want to cross-reference specific criteria in generating attestations, would it be possible to extract these to a separate and common location and then reference those requirements from both the source and build tracks?

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/source-att.md
> +| `codeReview` | FeatureHistory | L3+ | Whether this project requires code review.
> Otherwise you enforce the policy "were all changes reviewed by someone who can approve changes now" as opposed to "were all changes reviewed by someone who could approve changes at the time."

> You're correct there are timing considerations, but if a consuming entity wants to do that verification, we should not prevent them from doing so.

These timing considerations would be a tool in being able to retract policy-based approvals. These retractions are hard because you don't want to invalidate _all_ prior approvals by an entity. There are many situations where an individual leaves organizations on good terms and all prior validations hold. There are likely fewer situations where an individual leaves and organization and at least _some number_ of their prior validations are retracted.

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/source-att.md
> +| `since` | string | ISO 8601 representation of the timestamp at which the feature was last enabled.
How would an entity outside of the version control platform be able to know when the feature was last enabled? They would likely have to query the platform and the current value would easily not have been the value when the commit was made.

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/source-reqs.md
> +## Infrastructure Requirements
Should we define who the infrastructure providing entity is to know how it is applied?

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/source-reqs.md
> +-   **[Immutable reference]** There exists a way to indefinitely reference this particular, immutable revision. This is usually {project identifier + revision ID}. When the revision ID is a digest of
Indefinitely feels like the wrong word. Would deterministically be better? This sentence (also above in levels.md) also effectively defining "immutable reference" as "immutable revision" -- is there a different term we can use instead of immutable revision? Or should we drop that?

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/source-reqs.md
> +## Levels
Do we want to mirror the layout for the build levels here? For example, but not limited to the use of tables?

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/source-reqs.md
> +Benefits: N/A
Do we need this explicit mention of level 0? If it is beneficial, should we add it to the build track too?

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/source-reqs.md
> +## Levels
Are there other entities involved in achieving these levels other than the infrastructure providers? Can we split the levels out?

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/terminology.md
> +| Source | An identifiable set of text and binary files and associated metadata usually used as input for the build system (see SLSA Build Track).
No action. Just an observation... we mention binary files here explicitly. This has the potential to be relevant in any future dependency track that might require the dependencies to meet certain criteria (i.e. provenance).

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/terminology.md
> +| Revision | The canonical source at a given point in time as identified by the version control system. Git identifies revisions by digest, but other version control systems may use other identifiers
```suggestion
| Revision | The canonical source at a given point in time as identified by the version control system. As an example, git identifies revisions by digest.
```
Do you want to be more specific about what that digest is?

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/terminology.md
> +| Change | A set of modifications to one or more source files and associated metadata. Change metadata MUST include any information required to situate the change in relation to other changes (e.g. p
Would a word like locate be better than situate? Also `Revision` capitalization is inconsistent with later use.

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/terminology.md
> +| Untrusted person | A human who has limited access to the project. They MAY be able to read the source. They MAY be able to propose or review changes to the source. They MAY NOT approve changes to t
Can we merge any of these with the earlier `Roles` section or are these explicitly unique to source?

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/terminology.md
> +### Source model
The build model introduces the space. Do you want to do something similar for the source model?

2024-03-20 19:44 UTC, arewm commented on docs/spec/v1.1/terminology.md
> +### Source model
What is the logic behind putting the source model here? Just that the source track would come before the build track?

Should we create a subheading for models and then alphabetize the various models within it?

2024-03-20 20:04 UTC, laurentsimon commented on docs/spec/v1.1/source-att.md
> +APIs provided by the source control platform.
> Who is an authorized party? Is it acceptable for the build platform to generate the source attestation?

An authorized party is in the eye for the receiver, ie it's whomever the receiver trusts to generate it. For example, an organization like Google could create the attestation using underlying GitHub APIs, and that attestation would be trusted internally at Google. Other orgs might not trust it and might generate their own.

So yes a builder may generate it you shift left.

> Is this only allowable

I think it's allowable. If the trusted platform generates it and you trust it, you need not re-generate it. If the version control does not support the generation but supports API, then another entity would generate it. If you don't trust the platform to generate it, you may also re-generate it (although that only makes sense if we consider "fact" attestations https://github.com/slsa-framework/slsa/pull/1037#discussion_r1526020307, else you have to trust the provider for both identity and enforcement, in which case re-generating it does not seem to provide additional benefits).

2024-03-21 00:41 UTC, ramonpetgrave64 commented on docs/spec/v1.1/source-reqs.md
> +-   Audit logs
Yes, maybe `Audit logs against the changes of in the Features`

2024-03-21 06:34 UTC, laurentsimon commented on docs/spec/v1.1/source-reqs.md
> +The version control platform MUST provide at least:
> @laurentsimon Again, this is about where you draw the box. I'd rather just draw the box around all the trusted source components and call it a day. I would need to understand the purported benefit of further detail to change my mind.

My only suggestion would be to clarify the description of `Version Control System` to accommodate 3P review systems. That's what prompted my comment. The current description only mentioned self-contained platforms like Github and Gitlab.

2024-03-26 22:40 UTC, kpk47 reviewed
I still have a few of the meatier comments to address, but I want to check that you think I'm heading in the right direction.

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/source-att.md
> +The version control platform is completely trusted in SLSA. Attestations for
I mean that the source platform is central to the source track in the same way the build platform is central to the build track. We trust the platform to record the source, proposed changes, and change history faithfully. 

Does this sentence make more sense to you now that I've renamed the platform to `source control platform`?

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/source-att.md
> +| `since` | string | ISO 8601 representation of the timestamp at which the feature was last enabled.
My intention isn't to track per-commit. Rather, we choose a point in the change history and decide that everything after that point should meet the desired SLSA level. In practice, I expect this to mean that projects adopt a SLSA level and then never regress below it, but I don't think that's realistic in practice. The best solution I could come up with is recording how long the different protections have been in effect, which lets consumers write policies that detect level regressions.

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/source-reqs.md
> +-   **[Immutable reference]** There exists a way to indefinitely reference this particular, immutable revision. This is usually {project identifier + revision ID}. When the revision ID is a digest of
Changing "indefinitely" to "deterministic" SGTM, but I disagree on changing "immutable." What we want is to prevent changes to revisions. Git prevents those changes by using the commit digest as the commit ID. The point of this language is to disallow any version control system that has mutable revisions. (I'm not aware of any, but I think writing defensively makes sense here.)

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/source-reqs.md
> +The version control platform MUST provide at least:
Done.

The change is in terminology.md.

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/source-reqs.md
> +## Levels
I'm not convinced we need them. The tables in the Build track are for displaying which requirements apply to each level, but we only have one requirement here tied to a level.

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/source-reqs.md
> +## Levels
I think we've got the right split here. The section above is what features the infrastructure provider must support, and this section is which of those features project owners/admins must enable at each level. What other entity should be involved?

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/source-reqs.md
> +Benefits: N/A
Done.

L0 is already in the table in levels.md, so no need to repeat it here.

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/terminology.md
> +### Source model
Alphabetizing SGTM.

We might want to reorganize this page before finalizing the next release. It's pretty hard to read.

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/terminology.md
> +| Revision | The canonical source at a given point in time as identified by the version control system. Git identifies revisions by digest, but other version control systems may use other identifiers
Done

I clarified that we mean tree hash, not commit hash. I think I noted that fact somewhere else in the PR, but I can't find it at the moment.

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/terminology.md
> +| Change | A set of modifications to one or more source files and associated metadata. Change metadata MUST include any information required to situate the change in relation to other changes (e.g. p
I think situate is the correct word. In my mind, locating doesn't include context but situate does. We want to know (at least) the parent revision, so we want some added context.

2024-03-26 22:40 UTC, kpk47 commented on docs/spec/v1.1/terminology.md
> +| Untrusted person | A human who has limited access to the project. They MAY be able to read the source. They MAY be able to propose or review changes to the source. They MAY NOT approve changes to t
I think this page needs a bit reformatting, or maybe we break it up into several pages. For now, I moved the existing Roles section to a subsection of the build model and kept these roles as a subsection of the source model.

2024-03-28 00:52 UTC, arewm reviewed
This feels like it is going in the right direction. The biggest uncertainty to me is whether we want to introduce an additional attestation for source.

2024-03-28 00:52 UTC, arewm commented on docs/spec/v1.1/levels.md
> +### Source L0: No guarantees
Change Source `LX` and Build `LX` should be an additional subheading lower `####`

2024-03-28 00:52 UTC, arewm commented on docs/spec/v1.1/levels.md
> +**[Retained history]** The change history MUST be preserved as long as the source is hosted on the source control system. The source MAY migrate to another source control system, but the organization
That's fair. I don't have any suggestions on how to make this better off hand...

2024-03-28 00:52 UTC, arewm commented on docs/spec/v1.1/levels.md
> +-   **[Atomic change sets]** Changes are recorded in the change history as a single revision that consists of the net delta between the proposed revision and the parent revision. In the case of a non
Some communities are very adamant about _never_ squashing commits, instead using commits to describe logical bits of change and then just merging them all in to preserve the blame. While this might introduce some risk (i.e. by creating reachable malicious commits), that risk can be mitigated if all commits are reviewed during the process. 

While squash+merge might be a best practice from a security perspective, I am not sure whether we can be overly prescriptive of it as a requirement for this track/level.

2024-03-28 00:52 UTC, arewm commented on docs/spec/v1.1/levels.md
> +## Source Track
New discussion opened

2024-03-28 00:52 UTC, arewm commented on docs/spec/v1.1/levels.md
> +Organizations that are unwilling or unable to host their source on a version control platform. If possible, skip to Level 2.
Ah, thanks. I should have started the review by looking at the terminology. As long as we are being clear and consistent, it should be fine for the first draft.

2024-03-28 00:52 UTC, arewm commented on docs/spec/v1.1/source-att.md
> +The version control platform is completely trusted in SLSA. Attestations for
For the build track, the platform is trusted to the extend that it accurately represents the content represented in the attestation. The platform itself isn't _necessarily_ trusted, but its identity is associated with the attestation and therefore the trust can be assessed by a consumer. 

Maybe this doesn't translate as well for the source track because there isn't a trusted control plane in the same way that there is one for build. Maybe this first sentence just isn't needed as it is assumed that the generator of the attestation will be trusted?

2024-03-28 00:52 UTC, arewm commented on docs/spec/v1.1/source-att.md
> +Source level a project satisfies, if any.
It was a challenge to not have an attestation format at all. Instead, just to make the source track about measurable properties. Whomever wants to measure these properties can report to their validity as desired (i.e. a VSA, API, etc.)

2024-03-28 00:52 UTC, arewm commented on docs/spec/v1.1/source-att.md
> +| `since` | string | ISO 8601 representation of the timestamp at which the feature was last enabled.
Sure. This challenges the ability for an entity that isn't the source control platform to be able to generate the data required for an attestation. Any other entity wouldn't be continuously watching the configurations to be able to know if the features have been switched off. If the systems only check for the presence at the time of a build, for example, then there is no way for that system to know that the setting wasn't disabled temporarily, a commit or two deleted, and then reenabled before the build.

2024-03-28 00:52 UTC, arewm commented on docs/spec/v1.1/source-reqs.md
> +-   **[Immutable reference]** There exists a way to indefinitely reference this particular, immutable revision. This is usually {project identifier + revision ID}. When the revision ID is a digest of
I don't have a better word/phrase/definition. I was just always told to not use words in their own definition. I don't have a better phrasing for now, so we can just leave the change at deterministically.

2024-03-28 20:37 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +### Source L0: No guarantees
Done

2024-03-28 21:09 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +-   **[Atomic change sets]** Changes are recorded in the change history as a single revision that consists of the net delta between the proposed revision and the parent revision. In the case of a non
I wasn't aware that there are communities that feel strongly about merge strategies. I'm not sure what's best here, so I've opened https://github.com/slsa-framework/slsa/issues/1040.

2024-03-28 21:16 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +**[Different persons]** The organization strives to ensure that no two user accounts correspond to the same person. Should the organization discover that it issued multiple accounts to the same perso
I've added a definition to terminology.md based on the definition from the Build track (which unfortunately is on requirements.md rather than the terminology page).
```
A package's <dfn>producer</dfn> is the organization that owns and releases the    
software. It might be an open-source project, a company, a team within a          
company, or even an individual. 
````

2024-03-28 21:19 UTC, kpk47 commented on docs/spec/v1.1/source-att.md
> +The version control platform is completely trusted in SLSA. Attestations for
Good idea. I dropped the first sentence.

2024-03-29 19:16 UTC, adityasaky commented on docs/spec/v1.1/source-attestation.md
> +| `projectID` | string | L1+ | Immutable project ID. For example, the SLSA Specification's project ID is `www.github.com/slsa-framework/slsa`.
Repositories and usernames / orgs can be renamed, so I don't know if immutable works here.

2024-03-29 19:16 UTC, adityasaky commented on docs/spec/v1.1/source-attestation.md
> +title: Source Attestations
I wonder if a generalized VSA (with some tweaks as to what's being "verified") or SCAI (more directly as a series of arbitrary claims) would work here? From my read, this is really just making a series of controls claims about the source control platform. I'd also clarify the name / description to avoid confusion further down the line for attestations that may be more directly source pertinent.

2024-03-29 19:16 UTC, adityasaky commented on docs/spec/v1.1/source-attestation.md
> +| `revisionID` | string | L1+ | Immutable revision ID. In git terminology, this is the commit hash.
Is this or digest below going to match the subject of the attestation?

2024-03-29 19:16 UTC, adityasaky commented on docs/spec/v1.1/source-attestation.md
> +| `revisionID` | string | L1+ | Immutable revision ID. In git terminology, this is the commit hash.
Also, could this be a tag object ID or must it always be resolved to a commit?

2024-03-29 19:20 UTC, laurentsimon commented on docs/spec/v1.1/levels.md
> +    -   The identities of the submitter, reviewers (if any), and merger (if different to the uploader)
I don't think so. In the case of GitHub I would expect it to be a GitHub handle

2024-03-29 19:23 UTC, laurentsimon commented on docs/spec/v1.1/levels.md
> +Trusted robots MAY be exempted from the code review process. It is RECOMMENDED that trusted robots so exempted be run only software built at Build L3+ from sources that meet Source L3.
I think it means a trusted robot must be running software that is at least SLSA L3 for both build and source track. I suppose we may also need to say that it's necessary but not sufficient?

2024-03-29 19:25 UTC, adityasaky commented on docs/spec/v1.1/levels.md
> +    -   The identities of the submitter, reviewers (if any), and merger (if different to the uploader)
At this level, only a VCS is required without the accompanying host platform, which is why I'm reading this to mean raw commits...I suppose my question is more about email in the commit metadata vs signature.

2024-03-29 19:25 UTC, adityasaky commented on docs/spec/v1.1/levels.md
> +    -   Timestamp of the reviews (if any)
With only a VCS and no review / host platform, what does a review look like? should this be taken out at this level?

2024-03-29 22:57 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +    -   The identities of the submitter, reviewers (if any), and merger (if different to the uploader)
I don't think we need to be prescriptive about how to represent identities at L1 -- this level isn't meant to be trustworthy. However, if I were presented with a commit from a L1 project where the email in the commit metadata conflicts with the signature, I'd expect the signature to take priority.

2024-03-29 22:57 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +    -   Timestamp of the reviews (if any)
I had considered removing this line until L2, but I couldn't figure out how to do so without creating ambiguity. (E.g. would L2 have a different metadata format? Or maybe it would change a field from optional to required?) It seemed clearer to put the full metadata definition in L1 and note that reviews may not be present.

To your other question: code reviews can happen outside review/host platforms. The review could happen over a mailing list, and the metadata could be a `Reviewed by` line in the commit. Remember, metadata at L1 is not trustworthy.

2024-03-29 22:57 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +Most popular version control systems meet these requirement, such as git, Subversion, Mercurial, and Perforce.
Done

2024-03-29 22:57 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +Trusted robots MAY be exempted from the code review process. It is RECOMMENDED that trusted robots so exempted be run only software built at Build L3+ from sources that meet Source L3.
Sorry, the "be" is an extra word. Does it make more sense now?

I also added a note that Build L3+ and Source L3 are not sufficient.

2024-03-29 22:57 UTC, kpk47 commented on docs/spec/v1.1/source-attestation.md
> +title: Source Attestations
I think one of the great mistakes in SLSA v1.0 was providing an attestation format without specifying what information we're trying to convey. I don't intend to repeat that mistake, so I've intentionally avoided specifying a format here. That specification can come later.

Kindly refrain from calling my work not pertinent, and I'll refrain from calling you impertinent. I've named the attestation to match the track. That's the shorthand we've been using in meetings, and it seems like a logical enough choice to me. Should SLSA need to free up "source" in its namespace in the future, we can deal with it then.

2024-03-29 22:57 UTC, kpk47 commented on docs/spec/v1.1/source-attestation.md
> +| `projectID` | string | L1+ | Immutable project ID. For example, the SLSA Specification's project ID is `www.github.com/slsa-framework/slsa`.
Done

2024-03-29 22:57 UTC, kpk47 commented on docs/spec/v1.1/source-attestation.md
> +| `revisionID` | string | L1+ | Immutable revision ID. In git terminology, this is the commit hash.
> Is this or digest below going to match the subject of the attestation?

The digest below.

> Also, could this be a tag object ID or must it always be resolved to a commit?

I've been avoiding tying anything to tags because they're mutable. Do we gain something by using tags here?

2024-03-29 23:08 UTC, adityasaky commented on docs/spec/v1.1/source-attestation.md
> +title: Source Attestations
Apologies! I did not mean any disrespect or insult with the word "pertinent". I think your work on this has been tremendous and I appreciate it!

To clarify, I was wondering if we wanted to distinguish between attestations for source platform specific claims and those that may apply (I was thinking "pertain" earlier) more specifically to the source itself.

2024-03-29 23:41 UTC, laurentsimon commented on docs/spec/v1.1/source-attestation.md
> +| `projectID` | string | L1+ | Immutable project ID. For example, the SLSA Specification's project ID is `www.github.com/slsa-framework/slsa`.
note that it's possible to provide an immutable ID: GitHub does support immutable user and repository IDs.

2024-03-29 23:52 UTC, kpk47 commented on docs/spec/v1.1/source-attestation.md
> +title: Source Attestations
No worries at all, and apologies for my terse response.

> To clarify, I was wondering if we wanted to distinguish between attestations for source platform specific claims and those that may apply (I was thinking "pertain" earlier) more specifically to the source itself. I'm fine with clarifying this later if the need arises.

Thank you for clarifying. I see what you mean now -- this track is more about development practices than it is about the source itself, and "source" is a rather generic name for such a specific track. I'd like the track and attestation names to match because the alternative may be confusing, but I'm not opposed to renaming the track. I opened #1041 to discuss.

2024-03-31 16:55 UTC, adityasaky commented on docs/spec/v1.1/source-attestation.md
> +title: Source Attestations
> I think one of the great mistakes in SLSA v1.0 was providing an attestation format without specifying what information we're trying to convey. I don't intend to repeat that mistake, so I've intentionally avoided specifying a format here. That specification can come later.

Understood. To me, it does read a lot like an attestation predicate proposal (that you could, for example, create a proto definition for in in-toto/attestation), especially next to the build provenance doc. Should this be tweaked in the meantime until we decide how this information is specifically communicated in an attestation?

2024-03-31 16:59 UTC, adityasaky commented on docs/spec/v1.1/levels.md
> +Trusted robots MAY be exempted from the code review process. It is RECOMMENDED that trusted robots so exempted be run only software built at Build L3+ from sources that meet Source L3.
> Sorry, the "be" is an extra word. Does it make more sense now?

Yep, thanks!

2024-03-31 17:11 UTC, adityasaky commented on docs/spec/v1.1/source-attestation.md
> +| `revisionID` | string | L1+ | Immutable revision ID. In git terminology, this is the commit hash.
> The digest below.

got it.

FWIW, I could also see both the revision ID and the tree ID listed in the subject as digests (the algorithm would be `gitCommit` and `gitTree` rather than `sha1` so there wouldn't be a collision). I'm mentioning it now but it can likely wait until the exact format for the predicate is decided, per the other thread.

> I've been avoiding tying anything to tags because they're mutable. Do we gain something by using tags here?

A tag object ID (ie its SHA-1 hash) is immutable while a tag reference is not. I'm primarily asking for cases where a source attestation is created for a release identified by a tag object. If we expect the field to be a commit ID, we should maybe call out that tag objects for a release must be resolved to the commit they point to (also, there's an edge case here because a tag object can point to any git object type, not just commits, so maybe that should be called out too).

2024-04-01 15:14 UTC, arewm commented on docs/spec/v1.1/levels.md
> +    -   The identities of the submitter, reviewers (if any), and merger (if different to the uploader)
+1

There are multiple use cases for identities. 
* You may be interested in associating the identity with an individual that you can reach out to for further discussion, etc. 
* It may not _necessarily_ about the identity itself, but more about adding the entropy to uniquely associate commits based on _some_ consistent identifier so that you can more easily apply policy rules to find other instances of the same committer.

2024-04-01 15:30 UTC, arewm commented on docs/spec/v1.1/levels.md
> +Trusted robots MAY be exempted from the code review process. It is RECOMMENDED that trusted robots so exempted run only software built at Build L3+ from sources that meet Source L3. Note: Meeting Bui
This first sentence makes sense, but I am not sure where the recommendation is coming from. It seems unrelated to the track and more related to some applications of SLSA.

2024-04-01 15:30 UTC, arewm commented on docs/spec/v1.1/source-attestation.md
> +title: Source Attestations
If you are focusing on the specific information that you are trying to convey, do we need to call this an attestation?

This feels like a similar point that I was trying to make in https://github.com/slsa-framework/slsa/pull/1037#discussion_r1532643046 -- Instead of focusing on a format for track attestations, we should instead focus on the ability to track adherence to the levels based on specific measurable properties. 

I was interpreting this section as a proposal for a formal attestation predicate.

2024-04-11 02:17 UTC, kpk47 commented on docs/spec/v1.1/source-att.md
> +| `codeReview` | FeatureHistory | L3+ | Whether this project requires code review.
This conversation is now tracked in https://github.com/slsa-framework/slsa/issues/1042, so I'm resolving this thread.

2024-04-11 02:19 UTC, kpk47 commented on docs/spec/v1.1/source-att.md
> +[Provenance generation](requirements#provenance-generation) for details.
I'm coming around to the idea that the source track doesn't need its own attestation, so I'm removing this line for now.

2024-04-11 02:31 UTC, kpk47 commented
@adityasaky @arewm I think we should go back to the drawing board with the source attestation/evidence, so I've removed it from this PR. Let's get the level spec to a place we're happy merging, and then I'll open a new PR where we can continue working on the attestation/evidence requirements.

2024-04-11 03:04 UTC, adityasaky commented
Sounds good!

2024-04-11 11:39 UTC, joshuagl reviewed
Apologies for being late to review this. It's fantastic to see the beginnings of a Source track emerge. Thank you for the continued effort on this @kpk47.
This feels equivalent to what we had in v0.1, only compressed into 3 levels instead of 4 and with more affordances for changes from robots. Does that assessment feel fair/accurate to you?

Most of my comments are related to presentation, the requirements feeling so close to the v0.1 version is a great baseline.

The formatting and structure of the Levels changes don’t match the existing Build track levels. 
Build levels are broken down into producer and platform requirements (see change from benefits to focus in https://github.com/slsa-framework/slsa/commit/cc812c33a03ec98f8bdb9b22304a38b130e9f23e) and are a descriptive overview requirements, whereas the newly added source requirements are detailed and specific enough that they run the risk of seeming authoritative and contradictory to the track text.

The formatting and structure of the Source requirements doesn’t match the “Producing artefacts” document, where the requirements are in a table with check marks for which level they apply to (and further, there are tables per requirement category: provenance generation and isolation, I’m not sure this split makes sense for the source track).

Note: we should update future-directions to remove the source track and/or update it to mention what could come next. Threats and mitigations should be updated too.

Final thought, is adding a new level appropriate for a minor release, or should we consider a major release for this?

2024-04-11 12:33 UTC, lehors commented
> Final thought, is adding a new level appropriate for a minor release, or should we consider a major release for this?

We've talked about this on Monday's call actually. We agreed to punt on this issue for now and wait until we decide to publish the next version of the spec. We can then discuss what change to the version number is the most appropriate based on what ends up being in the spec. For now we can still work on "1.1" without it being binding.

2024-04-18 13:46 UTC, MarkLodato commented on docs/spec/v1.1/levels.md
> +The project is stored and managed through a source control platform that ensures the change history's integrity.
I suggest describing things at a higher level of abstraction and explaining the value that this level gives. See Build track as examples. Maybe something like:

```suggestion
The source code and its change history metadata are retained and authenticated to allow trustworthy auditing and analysis of the source code.
```

2024-04-18 13:47 UTC, MarkLodato commented on docs/spec/v1.1/levels.md
> +Trusted robots MAY be exempted from the code review process. It is RECOMMENDED that trusted robots so exempted run only software built at Build L3+ from sources that meet Source L3. Note: Meeting Bui
This topic (trusted robots) probably warrants further discussion and more guidance in the spec. Maybe just add a TODO to flesh it out? I doubt we'll get it right on the first try.

2024-04-24 22:31 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +    -   The identities of the submitter, reviewers (if any), and merger (if different to the uploader)
I created an `Outstanding TODO` section at the top and added an item there about identities.

2024-04-24 22:33 UTC, kpk47 commented on docs/spec/v1.1/levels.md
> +Trusted robots MAY be exempted from the code review process. It is RECOMMENDED that trusted robots so exempted run only software built at Build L3+ from sources that meet Source L3. Note: Meeting Bui
Added a TODO

2024-04-24 22:35 UTC, kpk47 commented on docs/_data/nav/v1.1.yml
That makes sense. I've consolidated all the new content into source-requirements.md and reverted all the other files to HEAD.

2024-04-24 22:48 UTC, kpk47 commented on docs/spec/v1.1/terminology.md
> +| Term | Description
I reordered the terms conceptually.

2024-04-24 22:48 UTC, kpk47 commented on docs/spec/v1.1/terminology.md
> +| Role | Description
I did my best to reorder the roles conceptually, but it's a little tricky since none of the terms appear in other definitions. I'm open to other orderings.

2024-05-02 19:29 UTC, MarkLodato commented
I'm going to take this PR over ([context](https://openssf.slack.com/archives/C03NUSAPKC6/p1714401798123519)). My goal is to get it submitted so that we have something to iterate on. It's not going to be perfect. The intent is that folks can open PRs to address specific points, rather than having one mega-PR for everything.

2024-05-02 21:44 UTC, zachariahcox reviewed
@chkimes and I collaborated on this review. 
Thanks for putting this together!

2024-05-02 21:44 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Merger | The role that applies a change to the source. This person may be the proposer or a different trusted person, depending on the version control platform.
There is an actor who "clicked the merge button", but this may or may not be the identity of the actor that authenticated to push the changes. 

For example, I may click the merge button to add a PR to a GitHub Merge Queue, but the Merge Queue's service principal is the identity who eventually pushes the ref update of the main branch.
This is because merge-queue-like systems contain the contents of multiple contributors and change sets.

2024-05-02 21:44 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +The version control system MUST provide at least:
This section may be mixing concerns between the VCS and the source control platform (SCP). 

Git commit metadata is forgeable from the perspective of the SCP. 
The SCP typically provides an identity / authz layer which is separate from the git content it manages, and it maintains its own timestamps for when activities happened from its perspective. EG: a commit may claim it was authored last year, but all the SCP knows for sure is that it was uploaded last week. 

Authentic contributions will typically be built in terms of the SCP's identity and timestamp models, not the VCS's.

2024-05-02 21:44 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +Intended for: Organizations that are unwilling or unable to host their source on a source control platform. If possible, skip to Level 2.
> host their source on a source control platform

Would this include self-hosted versions of SCPs?

2024-05-02 21:44 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +**[Retained history]** The change history MUST be preserved as long as the source is hosted on the source control system. The source MAY migrate to another source control system, but the organization
verified timestamps are provided by the SCP, so when I migrate the source to a new SCP, I think this means that the org must keep the original repo around to keep the "true" timestamps. 
Or else, we may be saying that SCPs must provide a way to export the verified timestamps somehow. We should consider making that clearer here, and I'm not sure which way is better! I'm not sure SCPs would import timestamps like that.

2024-05-02 21:44 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +**[Code review]** All changes to the source are approved by two trusted persons prior to submission. User accounts that can perform code reviews MUST use two-factor authentication or its equivalent.
Should a robot approval count or must it always be human?

2024-05-02 21:44 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +-   **[Context-specific approvals]** Approvals are for a specific context, such as a repo + target branch + revision in git. Moving fully reviewed content from one context to another still requires r
> you do not need to review each change to cut a release branch

This seems really tricky. 
If I create a new release ref that points to the tip of main, I must ensure that the tip of main complies with all requirements that govern the release ref. 
It's normal for the requirements to be different between those contexts. 

> Moving fully reviewed content from one context to another still requires review, except for well-understood automatic processes

This makes sense to me. I'm not sure the example expresses this though.

2024-05-02 21:44 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +Trusted robots MAY be exempted from the code review process. It is RECOMMENDED that trusted robots so exempted be run only software built at Build L3+ from sources that meet Source L3.
```suggestion
Trusted robots MAY be exempted from the code review process. It is RECOMMENDED that an exempted trusted robot artifact be built at Build L3+ from sources that meet Source L3.
```

2024-05-02 21:44 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +r changes (e.g. parent revision).
```suggestion
```

2024-05-02 21:44 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Change | A set of modifications to one or more source files and associated metadata. Change metadata MUST include any information required to situate the change in relation to othe| Version Control
```suggestion
| Change | A set of modifications to one or more source files and associated metadata. Change metadata MUST include any information required to situate the change in relation to other changes (e.g. parent revision).
| Version Control System | Software for tracking and managing changes to source. Git and Subversion are examples of version control systems.
```

2024-05-06 17:09 UTC, Nikokrock commented on docs/spec/v1.1/source-requirements.md
> +**[Code review]** All changes to the source are approved by two trusted persons prior to submission. User accounts that can perform code reviews MUST use two-factor authentication or its equivalent.
From my point, it is not always a human (some sources might not be easily read by a human, for example). Or in case of merges, depending on the way you handle your merge processes, a robot might be able to review if the change can be approved or not.

2024-05-06 17:13 UTC, Nikokrock commented on docs/spec/v1.1/source-requirements.md
> +| Revision | The canonical source at a given point in time as identified by the version control system. As an example, you can identify a git revision by its tree hash.
I agree git does not have a verifiable timestamp but SCP should have one ? (so maybe the example is wrong). Time is an important point in case you detect an attack such as XZ and need to go back to a "safe" point.

2024-05-13 13:48 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Revision | The canonical source at a given point in time as identified by the version control system. As an example, you can identify a git revision by its tree hash.
```suggestion
| Revision | A specific state of a repository as identified by the version control system. As an example, you can identify revision of a git repository by its tree id. 
```

2024-05-13 13:52 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Revision | The canonical source at a given point in time as identified by the version control system. As an example, you can identify a git revision by its tree hash.
@Nikokrock it's true that the SCP should have a timestamp for when a revision was uploaded, but 1) not all SCPs provide that feature, and 2) (to me) that information seems separate from what defines the revision itself. I think I can upload the same revision of a repository to multiple SCPs. They would all have different "receive" timestamps but should be considered "the same code" imo.

2024-05-13 14:37 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +The SLSA Source Track mitigates [Threat A ("Submit unauthorized change")](/spec/v1.0/threats#a-submit-unauthorized-change), scoped to a code repository and the organization that owns that repository.
(The "Threat A" url references a deleted ref.)

It seems to me that the source track (similar to the build track) should start with generating provenance at the lower levels, then move to implementation of specific policies at higher levels. 
The revision of a consumed repository is a kind of artifact like any other software dependency and as such should come with all its paperwork. The "build process" of a repository revision is the pull request, and the result of a completed pull request should be a new revision accompanied by provenance claims. 

This example appears to be covering the requirements and benefits of a specific policy, similar to the ["Build Level 1" dedicated infrastructure requirement](https://slsa.dev/spec/v1.0/levels#build-l1). 
> Concretely: an attacker must compromise the accounts of two organization members to publish code in a Source Level 3-conformant repository, and the evidence of those unauthorized changes cannot be destroyed without further attacks.


At a minimum, consumers of a repository revision will want to know the following provenance claims: 
1. Who contributed these changes (according to the SCP)? 
2. When did they do so (according to the SCP)? 
3. What policy compliance claims are associated with this revision (according to the SCP)? 


Based on this, it seems to me that a focused adaptation of the excellent ["build track" summary](https://slsa.dev/spec/v1.0/levels#build-track) would work well here. EG:


The SLSA **SOURCE** track describes increasing levels of trustworthiness and completeness in a **repository revision's** provenance. Provenance describes what **Source Control Provider produced the revision**, what process was used, and who the contributors were. The lowest level only requires the provenance to exist, while higher levels provide increasing protection against tampering of the **version control system, the provenance, or the revision**.

The primary purpose of the **source** track is to enable [verification](https://slsa.dev/spec/v1.0/verifying-artifacts) that the **revision followed the expected process**. Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each **source revision's** actual provenance to those expectations. Doing so prevents several classes of [supply chain threats](https://slsa.dev/spec/v1.0/threats).

2024-05-15 13:45 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +**[Code review]** All changes to the source are approved by two trusted persons prior to submission. User accounts that can perform code reviews MUST use two-factor authentication or its equivalent.
We've talked in the past about how we might modify review constraints in the face of robots, I believe it was deemed out of scope for this first PR. Previous discussion includes:

- https://github.com/slsa-framework/slsa/issues/196
- https://github.com/slsa-framework/slsa/issues/956
- https://github.com/slsa-framework/slsa/issues/287

I know some organisations allow robots to automatically merge dependency updates if the change doesn't introduce a breakage. I think that makes sense so long as there are additional controls (i.e., the WIP dependency track in #961) on what changes the robot can introduce.

2024-06-10 12:18 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +The SLSA Source Track mitigates [Threat A ("Submit unauthorized change")](/spec/v1.0/threats#a-submit-unauthorized-change), scoped to a code repository and the organization that owns that repository.
Something like that seems reasonable to me.

The one question I have is, you describe the provenance as indicating who the contributors were for a given revision, is that meant to exclude some attestation that describes the state of the repo as a whole?

I think we also need something that describes the state of a the repository as a whole over its lifetime so that consumers don't _need_ to process each specific revision.

Perhaps the intent is to think of 'provenance' broadly here where it might include a couple of different attestation types to achieve those goals?  In which case we'd just need to tweak the language some to make that more clear?

On a related note: do we like the term 'provenance' here?  Will that wind up being confused with https://slsa.dev/provenance

2024-06-10 12:28 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Merger | The role that applies a change to the source. This person may be the proposer or a different trusted person, depending on the version control platform.
I think the intent here is whomever pushed the merge button (they eventually cause the Merge Queue to update the main branch).

Do you have any suggestions for alternate language?

2024-06-10 12:30 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +The version control system MUST provide at least:
Is the best fix to remove the distinction between the two in this section and state that it's all the responsibility of the SCP who _may_ implement these features via the VCS as appropriate?

2024-06-10 12:34 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +Intended for: Organizations that are unwilling or unable to host their source on a source control platform. If possible, skip to Level 2.
IMO this should only apply to folks who are using 'bare' VCS and that self-hosted SCPs should be eligible for higher levels with the caveat that the trust story will be murkier.  E.g. much easier for a consumer to 'trust' the hosted GitHub/GitLab/etc... solution vs the one I've spun up myself.  But it shouldn't be impossible.

Seem fair?

2024-06-10 12:39 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +**[Retained history]** The change history MUST be preserved as long as the source is hosted on the source control system. The source MAY migrate to another source control system, but the organization
Does this come back to the question above of how important the actual time is? (I can see that going either way).

Assuming it _is_ important we would seem to need some ability to track the original times when moving between SCPs?  Should we be evaluating some option for preserving this data that doesn't rely on the SCP itself?  E.g. if we had a per commit attestation a Time Stamp Authority could provide a verified timestamp that could easily migrate to a new SCP.

On a related note, in "MUST retain the change history if possible" I find "MUST" and "if possible" to be contradictory?  Do we resolve this problem by just downgrading "MUST" to "SHOULD"?

2024-06-10 13:17 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +**[Retained history]** The change history MUST be preserved as long as the source is hosted on the source control system. The source MAY migrate to another source control system, but the organization
So I see your point, it's not strictly contradictory; but I think it is confusing?

In this case it's certainly _possible_ for an SCP to implement some feature that imports the time in a secure fashion and we'll be asking the SCPs to implement other things to implement this spec.  So why bother with the "if possible" qualifier?  Should we be more specific on what cases don't need to retain this information?  Perhaps "importing code from an SCP that does not support or does not have change history".

2024-06-10 13:36 UTC, TomHennen commented on docs/spec/v1.1/levels.md
> +#### Source L1: Version controlled
I think defining L1 as requiring version control would settle the debate about if a source tarball counts as version control (it shouldn't)?

2024-06-10 13:47 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +The SLSA Source Track mitigates [Threat A ("Submit unauthorized change")](/spec/v1.0/threats#a-submit-unauthorized-change), scoped to a code repository and the organization that owns that repository.
I'm also realizing that the build track specifies how the information about the build is communicated (provenance) but the source track currently doesn't.  That seems like a gap that should be filled (which would hopefully help address some of these points?)

2024-06-10 14:07 UTC, lehors commented on docs/spec/v1.1/source-requirements.md
> +**[Retained history]** The change history MUST be preserved as long as the source is hosted on the source control system. The source MAY migrate to another source control system, but the organization
Upon further reflection I think you're right. 
Even if "MUST... if possible" can be interpreted as stronger than SHOULD the reality is that SHOULD already carry the intent we want and there is no real value in getting into the details of the cases where this might not be done.
For the sake of simplicity let's just change it to a SHOULD and drop the "if possible".

2024-06-10 18:25 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +The SLSA Source Track mitigates [Threat A ("Submit unauthorized change")](/spec/v1.0/threats#a-submit-unauthorized-change), scoped to a code repository and the organization that owns that repository.
> is that meant to exclude some attestation that describes the state of the repo as a whole

Yes, there are (typically) many commits in a repo that are invalid, illegal, incomplete or malicious. When you checkout a repo revision for a build, you'll mostly want to know about the version you got. Info about other branches, other revisions, other commits, other points in time is probably not relevant to the choice about whether or not _this_ revision is good to use. 

> something that describes the state of the repository as a whole over its lifetime
Can you talk a little more about how you'd use this kind of data? I guess I'm thinking mostly of ci/cd scenarios: EG, if I fetched a revision of a repo with sha abc123. I'm not sure it would be very relevant to me to know things about the whole repo, like whether the main ref is protected, or when the rules were last changed for the dev branch, etc. Mostly I'll want to know which rules were processed to allow the current revision I have to exist.

2024-06-10 20:14 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +The SLSA Source Track mitigates [Threat A ("Submit unauthorized change")](/spec/v1.0/threats#a-submit-unauthorized-change), scoped to a code repository and the organization that owns that repository.
> Can you talk a little more about how you'd use this kind of data? I guess I'm thinking mostly of ci/cd scenarios: EG, if I fetched a revision of a repo with sha abc123. I'm not sure it would be very relevant to me to know things about the whole repo, like whether the main ref is protected, or when the rules were last changed for the dev branch, etc. Mostly I'll want to know which rules were processed to allow the current revision I have to exist.

Yes exactly.  And that's what the original (3 years old 😨 ) [Source Control Attestation proposal](https://docs.google.com/document/d/10B-8R3NIGvcPuoIhqb-p18oOe78m6SiiukfE7NyvnYQ/edit?usp=sharing) was trying to get at.

Which isn't to say that it should exclude some ability to reason about any particular commit, they're just separate problems.

As I understand it (and I haven't been paying strict attention to this effort) the latest thinking was that it's useful to have _both_ capabilities.  E.g. 1. some ability for a consumer to determine if the current revision of source is 'good' and 2. some ability for motivated systems or people to determine _why_ 1 is true.

I noticed one of the changes to this PR actually removed the notional attestation format from this PR, so it looks like resolution of that problem is being deferred?

2024-06-11 12:56 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +The SLSA Source Track mitigates [Threat A ("Submit unauthorized change")](/spec/v1.0/threats#a-submit-unauthorized-change), scoped to a code repository and the organization that owns that repository.
FWIW that doc is shared with https://groups.google.com/g/slsa-discussion.  Everyone should be able to join that group to read it.  My work org doesn't let me share docs with the entire public :(.

2024-06-11 13:12 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +Intended for: Organizations that are unwilling or unable to host their source on a source control platform. If possible, skip to Level 2.
I think self-hosted should be permitted, thinking specifically of projects like freedesktop.org and gnome.org. 

As we're focused on preventing malicious changes through a single account compromise I think an important aspect of the SCP is that the developer account/identity can't make arbitrary/non-observable changes the SCP in order to introduce changes which otherwise wouldn't be allowed. Ideally this would be a achieved through separate ops/admin account, or better yet team, to manage the SCP.

2024-06-11 13:59 UTC, adityasaky reviewed
Just a few comments, I don't expect any of them to block moving forward with this PR with a series of TODOs for us to iterate on.

2024-06-11 14:15 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Merger | The role that applies a change to the source. This person may be the proposer or a different trusted person, depending on the version control platform.
Maybe "The _identity of the person_ that applies a change to the source. This person may be the proposer or a different trusted person, depending on the version control platform." ?

2024-06-11 15:34 UTC, TomHennen commented
Hey all, in an effort to unblock merging of _this_ PR, so that other issues can be addressed individually (and hopefully more quickly?) I've put together [this document](https://docs.google.com/document/d/13Xt8mA_2b00McGX2vkyhu4GQdFAqtXPu7YXE8ZA6ISE/edit?usp=sharing&resourcekey=0-EqfHF79tUWAKp4PzsE3z1A) (request access or join https://groups.google.com/g/slsa-discussion for access[^1]) to try to tease apart PR blockers from "things that should be addressed before this becomes finalized".

Once we're agreed on TODOs we can turn them into issues and get stuff merging.

Please chime in?

See also [this thread in slsa-specification](https://openssf.slack.com/archives/C03NUSAPKC6/p1718045606647179).

FYI @joshuagl @adityasaky @Nikokrock @zachariahcox

[^1]: Sorry, trying to work with my corp 'firewall' policy.

2024-06-11 15:52 UTC, TomHennen commented on docs/spec/v1.1/levels.md
> +#### Source L1: Version controlled
I think the value is also unclear because the spec doesn't yet indicate how the SLSA Source Track metadata is propagated.  Part of the value proposition for Build L1 was that it got people on the path to propagating that metadata?

Maybe there's something similar to do here?

2024-06-11 18:09 UTC, TomHennen commented
> I appreciate the effort but I've got to ask: why not opening issues on github instead? Is it that you think commenting on a Google doc is easier/better? (I really don't mean to start a tool war btw)

Exactly.  I really didn't care, I just started there to get things straight in my head.  @joshuagl suggested we can leave it in the doc until we resolve the merge blockers to this PR.

Then I'd better very happy to convert everything to GitHub issues.

2024-06-11 19:18 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Merger | The role that applies a change to the source. This person may be the proposer or a different trusted person, depending on the version control platform.
It seems to me that protected refs should not be writable by actors other than the SCP service principal (side note: this is unfortunately not the case for gh today).
If a protected ref _is_ written by something other than the SCP SP, that's generally a big red flag. 
 
I'd propose "Merger: the human or Trusted Robot that applies a change to the source."

Git digression: 
For most of these security levels, you'd want this to exclusively be the SCP. If a random human was the last pusher to a release ref, you'd probably want to go look through audit logs to see what happened, why did they bypass pr rules, etc.

One downside of this approach is that it makes your push history look very robotic.
We handle mq merges with special ux treatment to help call out that the mq ref was full of mergeable prs.

2024-06-11 19:25 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Merger | The role that applies a change to the source. This person may be the proposer or a different trusted person, depending on the version control platform.
So I think we might be talking about different things, and maybe we want to capture both?

1. The service principle (am I using this right?) of the entity (user or robot) that actually authorized the changes to the underlying VCS.
2. The service principle of the entity that _triggered_ the change in the first place (which might operate in practice by putting some work on a queue for the trusted robot you mention)

Num 1 is helpful if we care about which accounts have broad scope to tamper with source.

Num 2 is helpful if we want the accounts involved in the review of the change itself.

So in the case you describe (1) would be the SCP SP, (2) would be the account of the person that caused the SCP SP to make that change.

2024-06-11 21:29 UTC, TomHennen commented
FYI it was suggested we try to reach agreement on what's needed to submit _this_ PR by the end of the community meeting Monday.  There would still be much more to do to get the final version 'public'.

2024-06-14 09:30 UTC, joshuagl commented
I rebased the PR on main and pushed a commit to resolve the linter warnings. Let's figure out remaining minor changes to land this PR and then build on it in future PRs like #1066.

2024-06-26 13:28 UTC, zachariahcox approved these changes
This is good progress. 
I vote to merge this one and address the remaining questions with subsequent prs: https://github.com/slsa-framework/slsa/labels/source-track

2024-06-26 13:36 UTC, TomHennen approved these changes

2024-06-26 13:37 UTC, TomHennen commented
> 

+1

I think we can merge this which will unblock additional changes.

IIUC after Monday's meeting @joshuagl was looking for someone like @mlieberman85 to review, approve, and merge.

WDYT Mike?

2024-06-26 14:17 UTC, joshuagl approved these changes
I think merging this PR as-is is a good path forward. I started to cherry-pick @Nikokrock's top commit from #1082, but it failed the linting phase and the edits I had to make touched a lot of lines.

It seems to me the easiest way to progress is to merge this PR and iterate in future smaller PRs, alleviating the need for managing the significant git history in this branch or requiring a maintainer to edit this branch.

@arewm @lehors @mlieberman85 let us know if you disagree with this approach, otherwise I will plan to merge this by EOD (UTC+1) on Friday.

2024-06-26 20:28 UTC, lehors approved these changes
LGTM. Thanks.

2024-06-28 15:56 UTC, arewm approved these changes
I am fine with this as a first draft since we removed the content on the attestations.

2024-06-28 16:17 UTC, merged