content: Add attested build environments level
slsa-framework/slsa pull request #1051
Opened 2024-05-03 22:39 UTC by marcelamelara

This (draft) PR introduces the following spec changes associated with #975. Per https://github.com/slsa-framework/slsa/issues/975#issuecomment-1773315232 and https://github.com/slsa-framework/slsa/issues/975#issuecomment-1852559183 the spec enhancements are being proposed as a *new Build track level*.  The spec changes introduced in this PR are meant to be complementary to possible requirements being developed in parallel in #977 .

Spec changes:
- [x] Add new level to levels.md
- [ ] Add new requirements to requirements.md
- [ ] Add related terminology to terminology.md
- [ ] Add build platform threat model to threats.md
- [ ] Update verifying build platforms page in verifying-systems.md
- [ ] Update future directions in future-directions.md

Fixes #975 CC @chkimes

2024-05-09 00:58 UTC, deeglaze commented on docs/spec/v1.1/levels.md
> +that supports hardware capabilities for attestesting to the state of the
```suggestion
that supports hardware capabilities for attesting to the state of the
```

2024-05-10 19:56 UTC, arewm requested changes
The SLSA build track does not have a requirement for completeness of resolved dependencies as of today (L3). If feels like we should work to achieve that completeness before we further harden the build environment. It may be possible to add complete provenance _alongside_ the other changes, but that feels like too much change from L3 to L4.

2024-05-10 19:56 UTC, arewm commented on docs/spec/v1.1/levels.md
> +Build L4 usually requires significant changes to existing build platforms.
There are no prior examples to be able to assess the truthfulness of this statement. Significant changes could be required for any increased level.

2024-05-10 19:56 UTC, arewm commented on docs/spec/v1.1/levels.md
> +        produce a [verification summary] about the check.
What would this look like? I would expect that the build system would create a build environment attestation on the artifact. I feel like it is a lot to ask for a producer to verify it and publish the VSA. Or does this not have to be a human/manual process?

2024-05-10 19:56 UTC, arewm commented on docs/spec/v1.1/levels.md
> +    -   Each build image (i.e., VM or container) made available to software
The VMs must be built on a SLSA Build L3+ platform as well? What does this mean in practice?

2024-05-10 19:56 UTC, arewm commented on docs/spec/v1.1/levels.md
> +        verification.
The provenance for _what_ must be distributed the build image? This is already a requirement for build L1-3: https://slsa.dev/spec/v1.0/requirements#distribute-provenance . Is the intention for this provenance to be verified somehow?

2024-05-10 19:56 UTC, arewm commented on docs/spec/v1.1/levels.md
> +        build image MAY be best-effort.
How would this distribution happen? Are we trying to add recursive SLSA into this requirement? Is that too much to do?

2024-05-10 19:56 UTC, arewm commented on docs/spec/v1.1/levels.md
> +        verification.
These changes are proposed to be part of the build track but we are now adding additional required attestations into the mix (this attestation + the producer's VSA mentioned earlier). I know that we do not have a 1:1 relationship between attestations and tracks, but this seems to be muddling the simplicity of the build track. Would this proposal be better as its own track?

2024-05-10 19:56 UTC, arewm commented on docs/spec/v1.1/levels.md
> +        with a key that is only accessible within the build image.
Does this need to be included in the attestation? 

Can you clarify the presence of the key? I assume that you are not trying to say that the encryption key should be present in the image used to run the VM/container as then it would be reused for multiple running instances of the build.

2024-05-10 19:56 UTC, arewm commented on docs/spec/v1.1/levels.md
> +        or container instance), its SLSA Provenance MUST be verified.
What are the criteria for verification here? Is it just the identity or is there more verification needed than that? Are we supposed to verify that it has met some SLSA level?

2024-05-10 19:56 UTC, arewm commented on docs/spec/v1.1/levels.md
> +        -   The boot process and state of disk image MUST be verified, and
This verification feels different than the previously mentioned one. Is it?

2024-05-10 19:56 UTC, arewm commented on docs/spec/v1.1/levels.md
> +| [Build L4]  | Attested build environment | Tampering before the build
Can you propose what the addition to requirements.md would look like? I think that is where the _core_ specification is maintained.

2024-05-13 17:19 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +that supports hardware capabilities for attestesting to the state of the
Thanks for catching this!

2024-05-14 21:32 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +Build L4 usually requires significant changes to existing build platforms.
Fair point. It's true that L3 already has a very similar statement, and we still wanted to be explicit about the fact that this L4 would require additional significant changes on top of L3. We can be more precise in what we mean here: for example, one of the significant requirements is hardware with very particular features (e.g., TPM or TEE support). Would that be more helpful here?

2024-05-14 21:39 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +        produce a [verification summary] about the check.
The main goal of the proposed requirements is to make tampering _prior_ to a build detectable. That is, at any point from when a build image is itself created/released to the point where a VM is deployed and waiting for a new build job to come in. This means the build platform will actually generate its attestations before and independently of the artifact. We have a figure showing this sequence which I think would be helpful in clarifying things. 

I'll note that the point of using hardware-based integrity measurements and attestation for this is to reduce the amound of manual self-attestation and verification that needs to happen on the part of the build platform and producer. I'll also note that this requirement is a SHOULD, so producer's aren't strictly required to check these attestations.

2024-05-15 23:15 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +| [Build L4]  | Attested build environment | Tampering before the build
Yes! Edits to requirements.md are part of this PR, and I plan to have a first draft of those ready by the end of this week. I might move some of the content from the current L4 description into that doc.

2024-05-15 23:25 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +        build image MAY be best-effort.
We aren't trying to add recursive SLSA in this requirement. The intent here is to clarify that while SLSA Provenance _is_ required for the build image creation, SLSA Provenance for pre-installed software (e.g., the Linux kernel, packages etc) isn't expected of the build platform.

2024-05-15 23:38 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +    -   Each build image (i.e., VM or container) made available to software
Yes, we're using the creation process of the VM image to bootstrap a first degree of trust in the build environment. Today we're already placing trust in GHA to configure an L3 platform, so say GHA VM images were themselves built on GHA, this requirement would give us assurances that the VM images were built with the same L3 integrity. It's a bit recursive, much like building gcc with gcc is, but the guarantees provided by the rest of the requirements become significantly weakened if we didn't have integrity for the build environment's build process. This is because the Provenance of the VM image gives us the good known value that can be later check against when the VM is then deployed.

2024-05-15 23:44 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +    -   Each build image (i.e., VM or container) made available to software
I should also add that this the conditions for meeting requirement are meant to be binary. That is, L4 is achieved iff the VM image is built on a SLSA Build L3+ platform. We believe this is necessary to avoid the issue of resolving what the transitive SLSA level would be.

2024-05-17 20:30 UTC, MarkLodato commented on docs/spec/v1.1/levels.md
> +    -   Each build image (i.e., VM or container) made available to software
I recommend removing these requirements. In my mind, the requirement should be relatively simple: there is a hardware-backed attestation (SEV-SNP, TDX, or equivalent) attesting to:
- the entire initial state of the build environment (bootloader, kernel, filesystem, etc)
- all of the inputs to the build

The properties of those inputs, such as the VM, seem outside the scope. There are many inputs to the build, and I would assume that we should verify each of those separately as part of some "transitive SLSA" verification.

2024-05-17 20:30 UTC, MarkLodato commented on docs/spec/v1.1/levels.md
> +<dt>Benefits<dd>
An alternate framing would be that it removes almost all of the build platform from the root of trust. All that's left is the hardware vendor and physical access.

2024-05-17 22:04 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +| [Build L4]  | Attested build environment | Tampering before the build
Ah. I can see how this is ambiguous. While the main goal is to provide stronger protections during the build, what we really meant here is tampering before _build execution_, i.e., tampering with the build environment, specifically during the stages when the build environment is created and deployed, but before the tenant's build is actually executed. Perhaps something like "Tampering during build via build environment" would be clearer here?

2024-05-17 22:34 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +    -   Each build image (i.e., VM or container) made available to software
Agreed, I realized looking at this again more recently that this list really enumerates low-level mechanisms for achieving the high-level properties, rather than stating those high-level properties. My thinking is that a lot of the content currently here would ultimately move to the requirements.md description.

> The properties of those inputs, such as the VM, seem outside the scope. There are many inputs to the build, and I would assume that we should verify each of those separately as part of some "transitive SLSA" verification.

I generally agree with the notion that inputs/dependencies to the build should be verified separately. At the same time, the properties of the VM specifically are needed to check the initial state of the build environment. That is, in order for the platform or a strict producer to verify the initial state of the build environment it needs to have good known reference values to check against. The SLSA L3 Provenance for the build image's build provides this good known value, with strong integrity assurances, that can then be bootstrapped to gain trust in the integrity of the initial state of the build environment.

2024-05-17 22:42 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +<dt>Benefits<dd>
At a high level, this is true, and we should probably keep this section more concise than it currently is. We did want to capture some of the nuance of doing this practice, though. For example, you actually need to still place a fair amount of trust in the cloud provider that's hosting the VMs running the builds to not tamper with components like the host OS or the vTPM implementation being used to check the integrity of the build environment.  The other part we wanted to emphasize is the machine-checkable aspect of relying on the attestable hardware, compared to the expectations for verification at L3. Maybe this nuance doesn't need to be covered in such detail here?

2024-05-20 23:05 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +    -   Each build image (i.e., VM or container) made available to software
> there is a hardware-backed attestation (SEV-SNP, TDX, or equivalent) attesting to ... all of the inputs to the build

@MarkLodato Thinking about this some more as I reformulate the requirements. What do you mean by "inputs to the build"? Is this about the completeness of external parameters in the Provenance? If so, this requirement as stated implies that the Provenance itself should be signed by the hardware root of trust.

2024-05-23 00:19 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +        verification.
You raise a valid point about preserving the simplicity build track, and the types of attestations being a part of that. The intent here is to actually encapsulate the hardware-based attestations inside an in-toto attestation, to at least ensure we remain within the SLSA attestation model. So at Build L4 there would be two types of in-toto attestations that would be generated: SLSA Provenance and SCAI encapsulating the hardware-based attestations. We think this approach helps us keep the attestation types limited to a select few. I'll add a TODO item to include examples of these attestations to illustrate what we would expect, and that'll hopefully clarify some of these questions.

On the question of converting this workstream into its own track, our original proposal went down that path. But we got some very convincing feedback from some in the community that that would actually introduce more complexity than is necessary in SLSA overall when the Build Track already pertains to properties of the build platform.

2024-05-23 00:32 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +        or container instance), its SLSA Provenance MUST be verified.
The main aspect to verify here is the identity/hash of the build image against what's recorded in the Provenance. Checking the SLSA level of the Provenance here gives extra assurances about the trustworthiness of the hash. In practice, this check would follow the standard [verification flow](https://slsa.dev/spec/v1.0/verifying-artifacts#step-1-check-slsa-build-level).

2024-05-23 16:09 UTC, chkimes commented on docs/spec/v1.1/requirements.md
> +-   When creating a new build environment:
I just got to the terminology file, I think just "creating a new build image" would be appropriate given that terminology

2024-05-23 16:49 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +        attestations MUST be authenticated by a hardware root of trust.
There's actually [a note](https://github.com/slsa-framework/slsa/pull/1051/files#diff-5f5f50825551c8161c1c73587ac6823a7d81ded3fa19d597147ec06c238bdcf8R393) at the end of the requirements clarifying that virtual hardware also works. Do you think that's enough, or is it worth clarifying up front?

2024-05-23 16:53 UTC, marcelamelara commented on docs/spec/v1.1/requirements.md
> +of the entire initial state of the build environment (i.e., VM/container
To clarify, you specifically mean the case where a container is used within a VM, right? My intent here was more to cover the scenario in which container-only build images are used. Whether or not containers are sufficient to achieve L3, I think is a related but separate question.

2024-05-23 16:54 UTC, marcelamelara commented on docs/spec/v1.1/requirements.md
> +-   When creating a new build environment:
Good catch, this bullet point should say "build image". In terms of unloading the term "image" more, I'm thinking we could use the term "filesystem" whenever the text says "disk image". wdyt?

2024-05-24 15:16 UTC, deeglaze commented on docs/spec/v1.1/levels.md
> +    -   Each build image (i.e., VM or container) made available to software
This text also presupposes that all builders run in VMs. Are we categorically rejecting remote attestations from physical TPMs on non-virtual machines?

2024-05-24 16:30 UTC, deeglaze requested changes

2024-05-24 16:30 UTC, deeglaze commented on docs/spec/v1.1/requirements.md
> +    -   The build environment's deploy-time attestation and uniqueness of its
What does this mean? I imagine that the SLSA L4 attestation signing key would be deleted from memory after use from a previous build job, so yes you'd need to re-establish the attestation with the key management service, but only AFTER the build request has completed. You don't want the key material in memory while an untrusted build process is taking place, even if it is isolated.

Who does the build environment attestation verification? It seems like the build job is accepting itself from this wording. The build requester would not necessarily be the one with an appropriate attestation verification policy to apply before even initiating a build request, but maybe that's what you meant? Is a build request supposed to happen over an attested channel?

2024-05-24 16:30 UTC, deeglaze commented on docs/spec/v1.1/requirements.md
> +    by a hardware root of trust (e.g., [TPM] or [trusted execution
```suggestion
    by a DRTM (e.g., [TPM] or [trusted execution
```

2024-05-24 16:30 UTC, deeglaze commented on docs/spec/v1.1/requirements.md
> +-   Boot, disk, deploy- and request-time attestations MUST be authenticated
I don't think request-time attestation is what's desirable. Although it could be an enhancement for tenant confidentiality, i.e., "I don't want to release my code to a builder I haven't vetted."
For build integrity, we want response-time attestation in order for both input and output resource descriptors to be cryptographically bound to the attestation. This prevents replay attacks given that the attestations are meant to be verified offline (i.e., not during the build process where the environment could respond to a cryptographic challenge for freshness).

2024-05-24 16:30 UTC, deeglaze commented on docs/spec/v1.1/levels.md
> +        environment attestations prior to passing control of the build to
When you say "prior to", do you mean that there is a separator event between boot to the build executor and the executor running any build request? That's my expectation, but this also seems like there could be a temporal prior, where an attestation verification service must do this verification before providing a ticket (for example) to permit the build request to proceed. I don't think the latter is desirable. See my later comment about response-time attestations.

2024-05-24 16:30 UTC, deeglaze commented on docs/spec/v1.1/terminology.md
> +| Build image | The run-time context within a build environment, such as the VM or container image. Individual components of a build image are provided by both the hosted build platform and tenant, a
This definition of build image as including parts from a tenant seems contrary to prior uses of the term to mean specifically the image of the build environment.

I would advise checking prior instances of "build image" and disambiguate them with "build environment image" and "tenant build image". A build platform will attest to itself, but it may also mount a container including a tenant's build toolchain for executing a build request, so that's an important distinction to make.

2024-05-24 16:30 UTC, deeglaze commented on docs/spec/v1.1/terminology.md
> +| Build executor | The platform-provided program dedicated to executing the tenant’s build definition, i.e., running the build, within the build image.
Clarify that the build executor must be a measured component of the build environment image.

2024-05-24 16:30 UTC, deeglaze commented on docs/spec/v1.1/terminology.md
> +| Build request | The process of assigning a build to a pre-provisioned build environment on a hosted build process.
I always think of requests as messages. Perhaps,

"A user-provided message to the build platform that is used to assign a build to a pre-provisioned build environment on a hosted build process."

But this could be splitting hairs.

2024-06-10 22:08 UTC, marcelamelara commented
@mdwood-intel @pdxjohnny PTAL

2024-06-11 19:06 UTC, marcelamelara commented on docs/spec/v1.1/requirements.md
> +  <th>L1<th>L2<th>L3<th>L4
This isn't an html style I've seen before either, but this is used through all the docs, apparently, and renders well.

2024-06-12 06:32 UTC, lehors commented on docs/spec/v1.1/requirements.md
> +  <th>L1<th>L2<th>L3<th>L4
The end tag of many HTML elements is optional, that is the case of the `th`, `td`, and `tr` elements. There is nothing wrong with this. It is very common in HTML written by hand because it saves a lot of typing and possible errors.

https://html.spec.whatwg.org/#optional-tags

2024-06-24 13:56 UTC, joshuagl commented on docs/spec/v1.1/requirements.md
> +The build platform generated an authenticated attestation to the integrity
That is, generating an _in-toto_ attestation about the entire initial state of the build environment?

We may run into confusion here between attestation and attestation:

> The process of vouching for the accuracy of information.

from [TCG Glossary](https://trustedcomputinggroup.org/wp-content/uploads/TCG-Glossary-V1.1-Rev-1.0.pdf), and

> An authenticated statement (metadata) about a software artifact or collection of software artifacts.

from [SLSA Terminology](https://slsa.dev/spec/v1.0/terminology)

It might be worth adding a note to clarify to readers who have familiarity with both terms.

2024-06-24 13:56 UTC, joshuagl commented on docs/spec/v1.1/requirements.md
> +MUST be detectable by the platform itself and the build.
"an the build."... executor? agent?

2024-06-24 13:56 UTC, joshuagl commented on docs/spec/v1.1/terminology.md
> +4.  Finally, the *build executior* running within the environment executes
```suggestion
4.  Finally, the *build executor* running within the environment executes
```

2024-06-24 13:56 UTC, joshuagl commented on docs/spec/v1.1/levels.md
> +Build L4 usually requires significant changes to existing build platforms.
How about:
```suggestion
Build L4 may require significant changes to existing build platforms.
```
and then list some of the requirements?

2024-06-26 07:09 UTC, mkulke commented on docs/spec/v1.1/levels.md
> +        attestations MUST be authenticated by a hardware root of trust.
In a TEE featuring a vTPM there should still be a hardware root of trust. The vTPM would be linked to signed HW evidence, for by example by mixing a hash of the vTPMs AKpub into the report-data field of a TEE's attestation report.

So, the original statement sounds fine to me. I assume a HW RoT is key and not something that can be supplanted by sw.

2024-06-26 14:43 UTC, pdxjohnny commented on docs/spec/v1.1/requirements.md
> +-   When creating a new build environment:
Hibernation and other things probably are affected by bootability of an image. It would be good to ensure container terminology and vm terminology are distinct as it loos like both cases are being captured: https://github.com/slsa-framework/slsa/pull/1051/files#r1612031706

2024-07-02 13:38 UTC, TomHennen commented on docs/spec/v1.1/levels.md
> +Build L4 usually requires significant changes to existing build platforms.
I'm sympathetic to view that we can just repeat the language from L3 (unless we also want to rewrite the L3 'intended for' section).  Maybe with the caveat "significant changes to existing _L3_ builds platforms"?

I think the requirements below do a fine job of getting into the details.

2024-07-02 13:49 UTC, TomHennen commented on docs/spec/v1.1/levels.md
> +        attestations MUST be authenticated by a hardware root of trust.
I do wonder if there's a useful middle ground where vTPMs that aren't hardware backed can still provide meaningful value.  If this level requires full hardware backed support would that be too big a step?

2024-07-02 14:02 UTC, TomHennen commented on docs/spec/v1.1/levels.md
> +<dt>Benefits<dd>
I see the importance of capturing the nuance.  I think what Mark might be getting at is that the benefits as currently enumerated are a bit abstract.

E.g. "Greatly reduces trust in a hosted build platform by increasing observability into the level of integrity of the build environment."

Could this instead be something like "Greatly reduces the TCB of a hosted build platform by preventing tampering with the build execution environment, leaving only the OS and vTPM in scope" or something like that?

2024-07-02 14:11 UTC, TomHennen commented
Have we considered that there may be other ways, like reproducible builds, to remove trust in the hosted build platform?  Would that provide equivalent (possibly better?) guarantees? 

Does encoding hardware trust as a discrete build level remove that option from folks?  Perhaps reproducible builds could listed as _a_ way to achieve these goals?  (It would require a fair amount of re-wording...)

2024-07-02 14:40 UTC, lumjjb commented on docs/spec/v1.1/levels.md
> +        attestations MUST be authenticated by a hardware root of trust.
I think another potential middle ground is a HSM where authentication requires certain authentication requirements (whether secure/measured boot, validating PCRs, some validated token, etc.)?

2024-07-02 14:46 UTC, mkulke commented on docs/spec/v1.1/levels.md
> +        attestations MUST be authenticated by a hardware root of trust.
In this case I'd explicitly state here that "software vTPMs" are valid too. sth like: 

> All attestations MUST be authenticated a root of trust. A valid of root of trust might be anchored in a dedicated HW module or might be formed via a chain of cryptographic signatures. 

The latter would be referring to vTPMs that are provisioned by a cloud service provider on tenant VMs and for which you'd get a CSP-provided cert-chain to verify.

2024-07-02 21:24 UTC, EricBurnett commented on docs/spec/v1.1/levels.md
> +        measurements of the entire initial state of the build environment
I'm worried that this definition **precludes any sort of distributed build from ever meeting SLSA L4** - it seems to assume that a build is always hermetic within a single build environment, and so easily described as `host + VM + filesystem + command -> output`. Almost all of the high-trust builds produced by Google, for example, are produced via distributed systems across multiple hosts, where the network, virtual filesystems, etc are inextricably linked to the process. Many could not be produced on any single machine in any reasonable amount of time, if at all. (Needing many TiBs of scratch space in total, many core-days of work, etc.)

I'd have no objection to defining a SLSA framework for hermetic single-host builds, if that is independently useful, but for "L4" where the implicit assumption is that all high-trust builders should aim to achieve it, I'm not yet convinced that this is the correct successor to L3. Though even here, "trust of software" seems still necessary, in that I don't know how to go from a description of a build to a fully realized set of input files without _already_ having to have trusted that some build platform software has interpreted it correctly.

Perhaps the right target is a broadened version of the same: a chain of hardware-rooted build attestations to what software was running on each node leveraged in the build process, with that software in turn attesting what environment it set up locally, etc? This would make it easier to be "tamper evident" for hardware attacks, though still require trusting that the build platform software is sufficiently bug- and backdoor-free.

Failing that, @TomHennen 's comment elsewhere about "independently reproducible" might be a better choice for L4. Though that may also fail on practicality grounds: I'm not sure of many systems that have ever achieved multi-party bitwise reproducibility (I don't think [Debian](https://wiki.debian.org/ReproducibleBuilds) is there yet?), and I don't know what that would look like for closed-source systems that only execute on one build platform in practice.

2024-07-02 22:26 UTC, marcelamelara commented
I need to catch up to most comments, but want to respond to a few recent ones first:

> Have we considered that there may be other ways, like reproducible builds, to remove trust in the hosted build platform? Would that provide equivalent (possibly better?) guarantees?

This question keeps coming up, and I've been thinking about this a LOT recently. Our stance so far has been that reproducible builds and (hardware-)attested builds are not mutually exclusive, nor is one better than the other. Both approaches reduce trust in the build platform, but they do so in different ways. My thinking is because they're fundamentally solving different problems. 

The similarities: Reproducible builds gives a producer or consumer assurances that a specific build process is consistent and was _very likely_ not tampered with because you can compare the build results. Relying on trusted hardware can give all parties cryptographically verifiable evidence that the build environment that ran your build wasn't tampered with because you can check the hardware-backed attestations for it. 

The differences: The outcome of using reproducible builds and hardware-attested builds ends up being pretty much the same: "was my build tampered with?" But I see a few fundamental differences in the trust model. In the former, the build platform at an organizational level doesn't need to be fully trusted. The more distinct, independent rebuilders you use, the stronger your assurances are, assuming enough rebuilders aren't colluding.

In the latter, the build platform _system_ doesn't need to be fully trusted. As long as you trust the hardware-based mechanisms, your assurances come from being able to trace a particular build back to a specific compute environment and check the contents of the attestations against the expected good known integrity values for that software.

> Does encoding hardware trust as a discrete build level remove that option from folks? Perhaps reproducible builds could listed as a way to achieve these goals? (It would require a fair amount of re-wording...)

As I describe above, I think the answer here should be no, because they aren't quite solving the same problem. In fact, we're intentionally vague about reproducible builds because we think there are scenarios where one approach may be enough depending on your threat model and/or adoption requirements (as this https://github.com/slsa-framework/slsa/pull/1051#discussion_r1663188034 mentions at the end), and there are scenarios where both may be useful, and we wanted to leave the option open for either scenario.

2024-07-02 23:41 UTC, deeglaze commented on docs/spec/v1.1/requirements.md
> +        addition, the initial state of the build environment's disk image
There are reasons for the disk image to not be entirely measured, so this seems like it could be too coarse of a requirement. There are ways security-critical components of user space are measured. They go past the PCRs 0-7 in the TCG-compliant measured boot link.

This whole disk integrity would disallow content-addressed build caches that already have SLSA attestations, such as what Bazel.build uses for performance.

The fact of the matter is that we have bespoke ways of evaluating attestation evidence and specifying policy for their acceptance. There is no standard since OSes consider different things to be security-critical.

Perhaps, "every file read from disk must be integrity-protected by some means traceable to the build environment identity or build request"

2024-07-03 14:21 UTC, TomHennen commented
> As I describe above, I think the answer here should be no, because they aren't quite solving the same problem. In fact, we're intentionally vague about reproducible builds because we think there are scenarios where one approach may be enough depending on your threat model and/or adoption requirements (as this [#1051 (comment)](https://github.com/slsa-framework/slsa/pull/1051#discussion_r1663188034) mentions at the end), and there are scenarios where both may be useful, and we wanted to leave the option open for either scenario. How this is reflected in build levels I think is a separate question.

Ah, I guess how to reflect it in the build levels is what I'm most interested in at the moment. :)

The way I'd read defining L4 as requiring hardware attested builds is that it would preclude someone from achieving a similar goal via reproducibility.  While we could then define level 5 as reproducible that would seem to require hardware backed attestations when doing reproducible builds.  Is that desirable?  Is my reading too strict?

The way I think about levels generally is that they're additive and single tracked.  What we seem to have here is a branch of sorts?  I don't know how to handle that within the levels framework.

I could see handling it within a specific level "you have choices on how to can reduce trust in the build platform a) hardware backed attestations, b) reproducible builds, c) both a & b".

To be clear I _do_ see the distinction in how these two approaches reduce the need to trust the build platform; but I wonder how meaningful that distinction would be for downstream users?  Maybe it's a distinction that could be made in whatever attestations are used to communicate level 4-ness?

2024-07-22 16:33 UTC, bobbiec commented on docs/spec/v1.1/levels.md
> +        measurements of the entire initial state of the build environment
>Perhaps the right target is a broadened version of the same: a chain of hardware-rooted build attestations to what software was running on each node leveraged in the build process, with that software in turn attesting what environment it set up locally, etc?

@EricBurnett I agree with this target (and I think it's consistent with the spirit - the build environment is potentially distributed). It would be a small change in the next line to make it more explicit -

```diff
- (i.e., VM/container image, boot process and filesystem)
+ (i.e., VM/container image, boot process, and filesystem, for each host in the build environment)
```

2024-07-30 17:53 UTC, marcelamelara commented on docs/spec/v1.1/terminology.md
> +| Build request | The process of assigning a build to a pre-provisioned build environment on a hosted build process.
Fair point. This isn't really about the exchanged messages, but about the action of assigning and dispatching a tenant's build process to a pre-deployed build environment. More recently, I've been using the term "build environment dispatch" for this step in the build environment's lifecycle, which is hopefully a little clearer.

2024-08-06 19:18 UTC, marcelamelara commented on docs/spec/v1.1/requirements.md
> +-   When creating a new build environment:
Let's move this discussion to #1107

2024-08-06 19:19 UTC, marcelamelara commented on docs/spec/v1.1/requirements.md
> +        addition, the initial state of the build environment's disk image
I'll be closing this PR soon. Let's move this discussion to #1107 !

2024-08-15 22:10 UTC, marcelamelara commented
Per the [7/22 SLSA spec meeting](https://docs.google.com/document/d/1PwhekVB1iDpcgCQRNVN_aesoVdOiTruoebCs896aGxw/edit#heading=h.a7pe3nsqmnuj), these requirements are to be re-worked as a separate track. So, this PR is being superseded by #1115 .

2024-08-15 22:10 UTC, closed without merging

2024-08-26 23:34 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +    -   Each build image (i.e., VM or container) made available to software
@deeglaze Can you please clarify, when you say non-VM, do you mean that a build could be running inside a container (backed by a physical TPM), or a bare metal environment, or either?

2024-08-27 04:31 UTC, deeglaze commented on docs/spec/v1.1/levels.md
> +    -   Each build image (i.e., VM or container) made available to software
I mean a task that is launched by a trusted orchestration daemon that establishes some resource limitations and filesystem access restrictions as Linux allows, but not necessarily following an OCI container description. At Google we have build servers that only run builds but still run on Borg. All the node software is accounted for with Titan TPMs. There’s no strong reason for us to require builds to run in VMs since we have everything measured and can account for the machine access by the identity and access management system and (measured) software-enforced ACLs. The build environment is managed by this production identity system before getting to the build job that then measures the inputs for slsa L3 but without incorporating the measurement into pcrs.

The hardware attestation of prodID and software attestation by borg Id (BCID) protect our build environment integrity in an auditable manner, but without incorporating the entirety of our production ecosystem in the build attestation. The new slsa level should allow for ecosystem measurements to be held back if the operational security and physical security of the servers can ve attested to implicitly with the slsa signing key release mechanism.

Now if you’re saying that the build ecosystem integrity is only a means to an end of requiring the build to be run within confidential computing technologies, I’d say that is not the most important goal to reach. If you want the build ecosystem to satisfy holistic properties like “no humans may access the environment” then you have to talk about more security commitments of the software, not just its measurement.

2024-08-27 17:12 UTC, marcelamelara commented on docs/spec/v1.1/levels.md
> +    -   Each build image (i.e., VM or container) made available to software
Thanks for the detailed explanation!