source track: update objective to align with build track
slsa-framework/slsa pull request #1083
Opened 2024-06-28 17:26 UTC by zachariahcox

fixes https://github.com/slsa-framework/slsa/issues/1072

See [discussion here](https://docs.google.com/document/d/13Xt8mA_2b00McGX2vkyhu4GQdFAqtXPu7YXE8ZA6ISE/edit?resourcekey=0-EqfHF79tUWAKp4PzsE3z1A#heading=h.svjr333bawb). 

Copied from [draft proposal here](https://docs.google.com/document/d/13Xt8mA_2b00McGX2vkyhu4GQdFAqtXPu7YXE8ZA6ISE/edit?resourcekey=0-EqfHF79tUWAKp4PzsE3z1A#bookmark=id.4qr65cfy6ufj). 

Google document requires slsa-discussion@googlegroups.com membership.

2024-06-28 18:02 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> -## Outstanding TODOs
happy to add these back, it feels like this content should be (and is?) tracked in issues?

2024-06-28 18:05 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +The lowest level only requires the provenance to exist, while higher levels provide increasing protection against tampering of the version control system, the provenance, or the revision.
this PR doesn't actually address the leveling definitions further on in the document.

2024-07-01 12:48 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> -## Outstanding TODOs
I think the idea is that while the source track is still in draft form it's helpful to keep the TODOs here as an indication it's not quite ready yet.

2024-07-01 13:49 UTC, TomHennen requested changes

2024-07-01 13:49 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +The SLSA SOURCE track describes increasing levels of trustworthiness and completeness in a repository revision's provenance.
open question: should we call this 'provenance' (which is overloaded with the specific format used by SLSA to track _build_ information) or should we call it something else?

If we do continue to use the word 'provenance' here we'll need to update other documentation which only uses 'provenance' when talking about mapping build -> source (and not when talking about source itself).  E.g. https://slsa.dev/spec/v1.0/provenance

We may be able to work around this by eliding the word entirely?

> The SLSA SOURCE track describes increasing levels of trustworthiness and completeness in repository revisions. and their history.
>
> This history describes which Source Control Provider produced the revision, what process was used, and who were the contributors. 
> The lowest level only requires the provenance to exist, while higher levels provide increasing protection against tampering of the version control system, the provenance, or the revision.
> ...

2024-07-01 13:49 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each source revision's actual provenance to those expectations.
> The primary purpose of the source track is to enable verification that a revision followed the expected process. 
Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each source revision's actual provenance to those expectations. 

I wonder if we can cut this section?

IIUC it's modified from [the 'Build track' description](https://slsa.dev/spec/v1.0/levels#build-track:~:text=Consumers%20have%20some%20way%20of%20knowing%20what%20the%20expected%20provenance%20should%20look%20like%20for%20a%20given%20package%20and%20then%20compare%20each%20package%20artifact%E2%80%99s%20actual%20provenance%20to%20those%20expectations.%20Doing%20so%20prevents%20several%20classes%20of%20supply%20chain%20threats.), but the interesting thing about the build track is that there's much greater variability in the way a build process is done, so the 'expected' process needs to be defined and communicated somehow and that process may vary from project to project.

However, I think 'source' is different?  The 'expected process' should have much less variability and it's easier to introspect?  Instead of expected process I think we're looking for something like "the source was written or approved of by the project's maintainers" (or something like that)

2024-07-01 13:49 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Subject | The subject of the attestation is the immutable identifier of a repository revision. EG: https://github.com/slsa-framework/slsa/commit/306642f21dbdaca2eaafe2df8e98432b4d4f2f02
This seems like an interesting topic of conversation.  When I read 'subject' here I'm thinking of the subject field in [the in-toto statement layer](https://github.com/in-toto/attestation/blob/main/spec/v1/statement.md) and I'd imagine that to look a lot like [`resolvedDependencies` does](https://slsa.dev/spec/v1.0/provenance#:~:text=%22resolvedDependencies%22%3A%20%5B%7B%0A%20%20%20%20%22uri%22%3A%20%22git%2Bhttps%3A//github.com/octocat/hello%2Dworld%40refs/heads/main%22%2C%0A%20%20%20%20%22digest%22%3A%20%7B%22gitCommit%22%3A%20%227fd1a60b01f91b314f59955a4e4d4e80d8edf11d%22%7D%0A%7D%5D) so that the build provenance and source attestation can easily be matched.

So I suppose my question is: can we update the example or just remove it until we're more firm on what the attestation format actually is?

2024-07-01 13:49 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Source | An identifiable set of text and binary files and associated metadata.
Any particular reason to drop "usually used as input for the build system (see SLSA Build Track)."

2024-07-01 13:49 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Source Provenance Attestation | A signed document describing the security claims associated with a revision.
This is probably related to my question about naming above.  We might consider leaving this definition out until we actually have the attestation defined?

I also wouldn't be surprised if we wound up with multiple attestation types.  One for consumers to understand the claim of a given source level in a revision and one that is used as evidence to compute the source level for all revisions.

2024-07-01 14:07 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> -## Outstanding TODOs
how do we feel about 

```
status: draft
open issues: https://github.com/slsa-framework/slsa/issues?q=is%3Aissue%20state%3Aopen%20label%3Asource-track
```

or something else that keeps it dynamic?

2024-07-01 14:12 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> -## Outstanding TODOs
SGTM

2024-07-01 16:47 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each source revision's actual provenance to those expectations.
I was initially thinking that too but have kind of come around. 
While in practice SLSA may make a few specific recommendations (such as around code review process), virtually all consumers will be interested in whether their own policy CI jobs were run properly on the revision (github has _many_ of these). 

To phrase it differently, is the expected verification flow "ensure that all the configured rules passed?" or "ensure that the specific rules I care about passed?" 

From experience, it tends to be a mix: most of the time customers care that "the configured rules were followed" and sometimes they need to know that "definitely this revision passed a specific policy-related-ci."

I feel like this aligns pretty well to an "expectation matching" approach, similar to the build track.

2024-07-01 16:49 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Subject | The subject of the attestation is the immutable identifier of a repository revision. EG: https://github.com/slsa-framework/slsa/commit/306642f21dbdaca2eaafe2df8e98432b4d4f2f02
Yeah, we can remove the specific example for now. 
However, if we're basing this on revisions, that's just a url to a revision.

2024-07-01 16:52 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Source | An identifiable set of text and binary files and associated metadata.
In the other issue there was a comment thread about there being tons of uses for version control system revisions. 

We could continue to point out that repos could be consumed by other processes.

2024-07-01 16:54 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Source Provenance Attestation | A signed document describing the security claims associated with a revision.
I think this is a specific issue digging into this topic https://github.com/slsa-framework/slsa/issues/758

I would support cutting it for now if it's at all contentious.

2024-07-01 17:46 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Source | An identifiable set of text and binary files and associated metadata.
Yeah that SGTM

2024-07-01 17:48 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Source Provenance Attestation | A signed document describing the security claims associated with a revision.
Yeah my preference would be to cut and then add back in when we have the actual attestation proposals.

2024-07-01 18:02 UTC, adityasaky commented on docs/spec/v1.1/source-requirements.md
> +The SLSA SOURCE track describes increasing levels of trustworthiness and completeness in a repository revision's provenance.
I suggest we use a different word to avoid confusion.

2024-07-02 20:36 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +The SLSA SOURCE track describes increasing levels of trustworthiness and completeness in a repository revision's provenance.
@TomHennen @adityasaky I think the objective section of this doc should settle on the term for "the process that created a revision."

I think mechanically this thing would be a "revision creation process attestation" so generally the word provenance seems to work pretty well and carries the right semantics. 
If we choose a new term, it would need to make sense on its own too: You'd fetch the "provenance attestation" for a file artifact and the "<new term> attestation" for the repo artifact, etc. 

Potentially we could just use: "predicateType": "https://slsa.dev/source-provenance/v1" or something else to differentiate the schema. Conceptually, these schemas would hold very similar data, so it might be that most of the existing docs would hold up unless they were discussing specific data elements?

2024-07-03 13:26 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +The SLSA SOURCE track describes increasing levels of trustworthiness and completeness in a repository revision's provenance.
You've convinced me.  How does being deliberate about referring to it as "source provenance" in this track (and then updating the build docs to talk about "build provenance" in another PR) sound?

We can then see how it's received later.

2024-07-03 13:36 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each source revision's actual provenance to those expectations.
Oh hmm.  I think we have different ideas in mind here.

I was thinking the source track would identify rules that _must_ be enforced for each level and be silent on any others.  That we'd leave any other rules that might need to be checked to something else.  (But I definitely understand that use case).  The way I'd expect this to work is that downstream consumers of this source probably won't want to care about the specific rules but the repo owner may, and so I'd be inclined to leave this to some sort of policy evaluation that can happen on the repo (the same thing that makes the determination for downstream users).

Note that I _definitely_ see the value in this sort of thing, but given that I think it can be handled separately, and that it would make the source track more complicated (at least I expect it would) how would you feel about deferring some of that pluggability until later (or some orthogonal effort)?

Do you have any particular rules in mind?

2024-07-03 13:38 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Subject | The subject of the attestation is the immutable identifier of a repository revision. EG: https://github.com/slsa-framework/slsa/commit/306642f21dbdaca2eaafe2df8e98432b4d4f2f02
Ok, yeah let's remove for now and then discuss.  My biggest qualm about changing it from what's in resolvedDependencies is that to put it to use we'd have to change the build provenance spec which seems hard.

2024-07-03 14:36 UTC, adityasaky commented on docs/spec/v1.1/source-requirements.md
> +The lowest level only requires the provenance to exist, while higher levels provide increasing protection against tampering of the version control system, the provenance, or the revision.
is the idea to add more to this PR? I think it might be fine to handle them in separate PRs to keep diffs small and easier to reason about and discuss.

2024-07-03 14:36 UTC, adityasaky commented on docs/spec/v1.1/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each source revision's actual provenance to those expectations.
Given that this is specifically about the _provenance_ about the source changes, I lean towards just capturing what process was followed and leaving it to the verifier to set expectations. So, effectively "ensure that the specific rules I care about passed" in @zachariahcox's comment above.

Source track is indeed a bit different from the build track but IMO there's value in keeping the separation between recording what happened (the source provenance) and what the expectations are when verifying the source provenance. It allows for greater agility wrt which parties we trust for what data. We also don't have to reason about how different expectations measure up against each other. For example, the maintainers may have expectations set A and I may have expectations set B, where B is in fact a subset of A. Instead of reasoning about that for every individual security control making up A and B, we can independently verify A and B are met by inspecting the provenance rather than having this extra bit of indirection.

> Note that I definitely see the value in this sort of thing, but given that I think it can be handled separately, and that it would make the source track more complicated (at least I expect it would) how would you feel about deferring some of that pluggability until later (or some orthogonal effort)?

I know this question is for @zachariahcox but I'm not sure I fully understand this. Could you clarify, perhaps with an example, what you propose we defer? 😄

2024-07-03 14:36 UTC, adityasaky commented on docs/spec/v1.1/source-requirements.md
> +The SLSA SOURCE track describes increasing levels of trustworthiness and completeness in a repository revision's provenance.
I think settling on the term for the process is fine. I also agree that we could define a separate predicate type; I'm not too worried about confusion when this is implemented in attestors / verifiers, but rather in regular conversations where context may be muddier. But let's punt that!

2024-07-03 14:36 UTC, adityasaky commented on docs/spec/v1.1/source-requirements.md
> +| Subject | The subject of the attestation is the immutable identifier of a repository revision. EG: https://github.com/slsa-framework/slsa/commit/306642f21dbdaca2eaafe2df8e98432b4d4f2f02
I think this could be a resource descriptor, like resolvedDependencies, indeed. Note that the attestation framework supports `gitCommit`, `gitTree` etc as types of hashes, so this should be quite straightforward to represent.

2024-07-03 14:39 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +The lowest level only requires the provenance to exist, while higher levels provide increasing protection against tampering of the version control system, the provenance, or the revision.
I think the idea is to handle the level definitions in another PR.

2024-07-03 15:00 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> -## Outstanding TODOs
historically we've biased towards leaving todos in the doc so we don't have to context switch away from the editor to work through them, I think it would be useful to leave them/add them back.

2024-07-03 15:07 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +The SLSA SOURCE track describes increasing levels of trustworthiness and completeness in a repository revision's provenance.
+1 to using "source provenance" and "build provenance" as a starting point.

2024-07-03 16:25 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +The SLSA SOURCE track describes increasing levels of trustworthiness and completeness in a repository revision's provenance.
```suggestion
The SLSA source track describes increasing levels of trustworthiness and completeness in a repository revision's _provenance_. 
```

This matches the style in https://slsa.dev/spec/v1.0/levels

2024-07-03 16:25 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +Provenance describes which Source Control Provider produced the revision, what process was used, and who were the contributors.
```suggestion
Provenance describes which Source Control Platform (SCP) produced the revision, what process was used, and who were the contributors. 
```

2024-07-03 16:25 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +The lowest level only requires the provenance to exist, while higher levels provide increasing protection against tampering of the version control system, the provenance, or the revision.
```suggestion
The lowest level only requires the provenance to exist, while higher levels provide increasing protection against tampering with any parts of the Source Control Platform, the provenance, or the revision.
```

2024-07-03 16:25 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +| Repository | A uniquely identifiable instance of a VCS hosted on an SCP. The repository controls access to the Source in the version control system. The objective of a repository is to reflect the
We should move VCS and SCP definitions up so that we have defined terms before we use them.

2024-07-03 16:25 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +| Change | A set of modifications to one or more source files and associated metadata. A change is proposed by a “publisher,” and applied to specific revision to create a new revision.
Do we need to define publisher? 🤔

2024-07-03 18:31 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each source revision's actual provenance to those expectations.
Great discussion. I definitely meant @TomHennen 's point 3: how many tools will a customer need to use to verify something? Or baking in an assumption that the attestation format will at least be somewhat extensible.

For teams that need more, I expect the SCP will want to add the additional claims in there somewhere (maybe akin to how the [gh oidc token contains a bunch of useful, gh-specific info](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token)). 

Empirically, to satisfy at least some customers, the revision-creation-process-attestation would need to contain no less than all the info captured by [ruleset insights](https://youtu.be/BYajh38HhCs?t=1025), plus a qualitative assessment as to whether those configured rulesets _also_ combine to fulfill any SLSA levels. 

> how would you feel about deferring some of that pluggability until later (or some orthogonal effort)?

💯 👍 
Does that effectively mean that for the first pass, we're _only_ targeting summaries?
Even with that goal, the wording like "Consumers have some way of knowing what the expected provenance should look like ... and compare it to actual" is pretty accommodating.

2024-07-03 18:36 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Subject | The subject of the attestation is the immutable identifier of a repository revision. EG: https://github.com/slsa-framework/slsa/commit/306642f21dbdaca2eaafe2df8e98432b4d4f2f02
> to put it to use we'd have to change the build provenance spec which seems hard

I'd guess that you can resolve a dependency that comes with its own provenance attestation though, right? 
Would this case be different?

> I think this could be a resource descriptor, like resolvedDependencies

Nice! Wouldn't this source provenance attestation still have a revision as its subject though?
I'm probably missing some nuance here.

2024-07-03 18:54 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each source revision's actual provenance to those expectations.
Oh I see, thanks!  So I think I have a good idea on how to handle nicely.  Perhaps I should put together a proposal for the consumer side attestation that would do what you're looking for?

How do you feel about "Consumers have some way of knowing what security properties the revision meets and how they can trust that determination".

But now that I say that I also see that in the original wording "Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each source revision's actual provenance to those expectations. " I might have gotten confused with the two different mentions of "provenance" :).

I think what that is trying to say is "The primary purpose of the source track is to enable verification that _the process to create a revision meets the expected security properties_.  Consumers have some way of mapping the sources listed in the _build provenance_ to the various _source provenance_ attestations to determine if all sources used during the build meet their requirements."

2024-07-03 18:59 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Subject | The subject of the attestation is the immutable identifier of a repository revision. EG: https://github.com/slsa-framework/slsa/commit/306642f21dbdaca2eaafe2df8e98432b4d4f2f02
Yes I think it would.

It would look something like

```
...
    "subject": [
        {
            "uri": "git+https://github.com/octocat/hello-world@refs/heads/main",
            "digest": {"gitCommit": "7fd1a60b01f91b314f59955a4e4d4e80d8edf11d"}
        }
    ]
...
```

2024-07-08 13:35 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +The lowest level only requires the provenance to exist, while higher levels provide increasing protection against tampering of the version control system, the provenance, or the revision.
Probably we can cut this line altogether, but as written the "lowest level" wouldn't involve SCP yet.

2024-07-08 13:38 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> -## Outstanding TODOs
this PR will be rebased onto the results of : https://github.com/slsa-framework/slsa/pull/1088/files. 

I'm still not sure I see the utility of keeping these stale topics under VCS, I'll refresh the list when this is put back up for review.

2024-07-08 17:35 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Subject | The subject of the attestation is the immutable identifier of a repository revision. EG: https://github.com/slsa-framework/slsa/commit/306642f21dbdaca2eaafe2df8e98432b4d4f2f02
>  "uri": "git+https://github.com/octocat/hello-world@refs/heads/main",

this reminds me that we need to define "ref" or "branch" in the spec.

2024-07-08 19:56 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Subject | The subject of the attestation is the immutable identifier of a repository revision. EG: https://github.com/slsa-framework/slsa/commit/306642f21dbdaca2eaafe2df8e98432b4d4f2f02
And that reminds me that there are cases where the destination branch / release is often an important part of the context for a 'review'.  So it might not be enough to say commit 'abc123' was reviewed, it might be necessary to know "reviewed in what context".

2024-07-10 01:11 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each source revision's actual provenance to those expectations.
@TomHennen this comment got disconnected post rebase. 👀

2024-07-10 01:12 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +| Subject | The subject of the attestation is the immutable identifier of a repository revision. EG: https://github.com/slsa-framework/slsa/commit/306642f21dbdaca2eaafe2df8e98432b4d4f2f02
yeah 💯 , that should be part of the "situation" in the change definition I think.

2024-07-10 01:13 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +| Change | A set of modifications to the source, or the computed difference between two revisions. A change is proposed by a [publisher](#source-roles), and applied to a specific revision to create a
https://github.com/slsa-framework/slsa/pull/1083#discussion_r1669216998

update to talk about ref context

2024-07-10 01:17 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +| Change History | A record of the history of revisions that preceded a specific revision.
I updated the text here a bit to help it cover git repos too (which don't track change history, technically).

2024-07-10 01:18 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
>  | Untrusted person | A human who has limited access to the project. They MAY be able to read the source. They MAY be able to propose or review changes to the source. They MAY NOT approve changes to t
we might want to change all instances of "changes to the source" to "new revisions."

2024-07-10 12:56 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +| Branch | A named pointer to a revision. Branches may be modified by authorized actors.
added a section about branches / refs. needs to move above the "change" definition that will need to use it.

2024-07-10 13:13 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Doing so prevents several classes of supply chain threats.
```suggestion
The primary purpose of the source track is to enable verification that the process to create a revision meets the expected security properties. Consumers have some way of mapping the sources listed in the _build_ provenance to the various _source_ provenance attestations to determine if all sources used during the build meet their requirements.
```

2024-07-10 13:13 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given revision and compare a revision's actual provenance to those expectations.
```suggestion
The primary purpose of the source track is to enable verification that the process to create a revision meets the expected security properties.
Consumers have some way of mapping the sources listed in the _build_ provenance to the various _source_ provenance attestations to determine if all sources used during the build meet their requirements.
```

2024-07-10 13:15 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given package and then compare each source revision's actual provenance to those expectations.
Found it and made a suggestion...

2024-07-10 13:18 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +The SLSA source track describes increasing levels of trustworthiness and completeness in a repository revision's provenance.
```suggestion
The SLSA source track describes increasing levels of trustworthiness and completeness in a repository revision's provenance (e.g. how it was generated, who the contributors were, etc...).
```

2024-07-10 13:19 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Source provenance describes which Source Control Platform (SCP) produced the revision, when it was generated, what process was used, and who were the contributors.
This seems out of place here.  When I read it it sounds like it's describing the attestation format but we haven't even finished talking about the objective yet.

I think the reason it's here is to explain 'provenance' for source in the sentence above.  I added a suggestion to just make that a parenthetical to get the point across without sounding like we're describing a specific format yet.

2024-07-10 13:20 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Higher levels provide increasing protection against tampering with any parts of the Version Control System, Source Control Platform, or the source provenance.
```suggestion
Higher source levels provide increasing protection against tampering with any parts of the Version Control System, Source Control Platform, or the source provenance.
```

2024-07-10 13:20 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Higher levels provide increasing protection against tampering with any parts of the Version Control System, Source Control Platform, or the source provenance.
Could also sub 'attestations' for 'information'.

2024-07-10 13:26 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given revision and compare a revision's actual provenance to those expectations.
the build provenance hasn't been computed yet to be used for this right? When you check source provenance, you're either looking at the build instructions themselves or trying to build some other artifact. 

At least in some cases, I would not expect a build to continue if one of the inputs fails to meet its requirements. This seems true whether the dependency is a package or repository.

2024-07-10 13:27 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +| Source Provenance | Verifiable information about a source revision describing where, when and how it was produced.
```suggestion
| Source Provenance | Information  about which Source Control Platform (SCP) produced a revision, when it was generated, what process was used, who were the contributors, and what parent revisions it was based on.
```
I'm having second thoughts about cutting this.   In the objective section we seem to be using 'provenance' in the more generic sense (what is this code and what do we know about it).  Would it make sense to describe that concept here separate from whatever attestations carry that information?

It seems helpful to have the generic concept of provenance decoupled from the specific implementation (which would need to be verifiable).

Of course that might be at odds with [the 'provenance' definition here](https://slsa.dev/spec/v1.0/terminology#:~:text=by%20the%20build.-,Provenance,-Attestation%20(metadata)%20describing).

Seems like there should be some way to work it out.

2024-07-10 13:28 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +| Reviewer | The role that reviews a particular change to the source.
```suggestion
| Reviewer | A role that reviews a particular change to the source.
```

There can be multiple reviewers so I suggest 'a' instead of 'the'.

2024-07-10 13:30 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
>  | Untrusted person | A human who has limited access to the project. They MAY be able to read the source. They MAY be able to propose or review changes to the source. They MAY NOT approve changes to t
I see the benefit of changing some of those instances, but we probably want to keep some?

After all, quite a bit of the point is that actors _want_ to make "changes to the source" and one of the reasons we need the source track is to make that safe.  There can perhaps be a section that explains "Changes to the source are realized as new revisions within a repository" or something like that?

2024-07-10 13:35 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Consumers have some way of knowing what the expected provenance should look like for a given revision and compare a revision's actual provenance to those expectations.
Oh so I think this gets back to a conversation we were having someplace else.

Sometimes folks will want to examine the source attestations (VSAs?) _after_ the build with the build provenance (that's what we do).  Often the builder doesn't know what the policy for any given package should be so it's helpful to be able to defer until later.

However, I think the important point your making is that _sometimes_ (perhaps often) the builder will be checking these things and it doesn't need to compare it with the build provenance.

In that case we could either drop "Consumers have some way of mapping the sources listed in the _build_ provenance to the various _source_ provenance attestations to determine if all sources used during the build meet their requirements." or we could adjust it to "Consumers can examine the various _source_ provenance attestations to determine if all sources used during the build meet their requirements." (which is generic enough).

We'll probably need to come up with some model and options for "how & when to verify source provenance attestations" but that can happen later.

2024-07-10 17:30 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
>  | Untrusted person | A human who has limited access to the project. They MAY be able to read the source. They MAY be able to propose or review changes to the source. They MAY NOT approve changes to t
Let's track it and skip for now.

2024-07-10 18:27 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
>  | Untrusted person | A human who has limited access to the project. They MAY be able to read the source. They MAY be able to propose or review changes to the source. They MAY NOT approve changes to t
https://github.com/slsa-framework/slsa/issues/1095

2024-07-10 18:34 UTC, TomHennen requested changes

2024-07-10 18:34 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Doing so prevents several classes of supply chain threats.
We should probably enumerate those at some point.  Is this the time to do so?

2024-07-10 18:34 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +| Source Provenance | Information  about which Source Control Platform (SCP) produced a revision, when it was generated, what process was used, who were the contributors, and what parent revisions it
```suggestion
| Source Provenance | Information  about which Source Control Platform (SCP) produced a revision, when it was generated, what process was used, who the contributors were, and what parent revisions it was based on.
```

2024-07-10 18:35 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +| Change | A set of modifications to one or more source files and associated metadata. A change is proposed by a “publisher,” and applied to specific revision to create a new revision.
I think this is obsolete with the new wording?

2024-07-10 18:37 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +Doing so prevents several classes of supply chain threats.
yeah, this is the wording from the levels doc -- I think it's saying "these levels represent bundles of Good Ideas and are widely regarded by experts as effective at preventing classes of supply chain threats. Each increasing level is constructed to prevent specific threat vectors of increasing complexity."

2024-07-10 20:07 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +Doing so prevents several classes of supply chain threats.
```suggestion
```

2024-07-10 20:12 UTC, TomHennen approved these changes

2024-07-12 16:30 UTC, joshuagl reviewed
A few minor nits, but otherwise LGTM

2024-07-12 16:30 UTC, joshuagl commented on docs/spec/draft/source-requirements.md
> +Consumers can examine the various source provenance attestations to determine if all sources used during the build meet their requirements
```suggestion
Consumers can examine the various source provenance attestations to determine if all sources used during the build meet their requirements.
```

2024-07-12 16:30 UTC, joshuagl commented on docs/spec/draft/source-requirements.md
> +| Version Control System (VCS)| Software for tracking and managing changes to source. Git and Subversion are examples of version control systems.
Should git be capitalised here? it's not capitalised in the next entry

2024-07-12 16:30 UTC, joshuagl commented on docs/spec/draft/source-requirements.md
> +| Source Provenance | Information  about which Source Control Platform (SCP) produced a revision, when it was generated, what process was used, who the contributors were, and what parent revisions it
```suggestion
| Source Provenance | Information about which Source Control Platform (SCP) produced a revision, when it was generated, what process was used, who the contributors were, and what parent revisions it was based on.
```

2024-07-12 16:30 UTC, joshuagl commented on docs/spec/draft/source-requirements.md
> +| Source Control Platform (SCP) | A service or suite of services for hosting version-controlled software. GitHub and GitLab are examples of source control platforms, as are combinations of tools like
```suggestion
| Source Control Platform (SCP) | A service or suite of services (self-hosted or SaaS) for hosting version-controlled software. GitHub and GitLab are examples of source control platforms, as are combinations of tools like Gerrit code reviews with GitHub source control.
```
"Can we self host" is a frequent question, is it worth including in the definition?

2024-07-12 16:30 UTC, joshuagl commented on docs/spec/draft/source-requirements.md
>  | Administrator | A human who can perform privileged operations on one or more projects. Privileged actions include, but are not limited to, modifying the change history and modifying project- or org
Nit: projects is not defined.

2024-07-12 17:34 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +| Version Control System (VCS)| Software for tracking and managing changes to source. Git and Subversion are examples of version control systems.
In this case, I think it's just because it's the beginning of the sentence.

2024-07-12 17:38 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
>  | Administrator | A human who can perform privileged operations on one or more projects. Privileged actions include, but are not limited to, modifying the change history and modifying project- or org
Agree -- this PR only updates the objective (and required definitions). 
I think we're informally using "repository" instead of "project" for this concept, but we should discuss that in the next PR. 

To me, one of the reasons to use "project" is to encompass things like issues, actions, other stuff besides versioning. 
We're not finished, but I suspect this specification will need to focus entirely on source topics, ignoring everything else related to software development.

2024-07-15 09:17 UTC, joshuagl commented on docs/spec/draft/source-requirements.md
>  | Administrator | A human who can perform privileged operations on one or more projects. Privileged actions include, but are not limited to, modifying the change history and modifying project- or org
I agree with your suspicion, I think the other aspects of projects are out of scope for this track. I don't mind handling this in a future PR but we need a mechanism to track that the work still needs doing. I filed https://github.com/slsa-framework/slsa/issues/1099

2024-07-15 09:17 UTC, merged