content: source track v.next draft, address remainder of pre-merge issues
slsa-framework/slsa pull request #1088
Opened 2024-07-02 15:47 UTC by zachariahcox

closes out the remainder of the pre-merge [issues](https://docs.google.com/document/d/13Xt8mA_2b00McGX2vkyhu4GQdFAqtXPu7YXE8ZA6ISE/edit?resourcekey=0-EqfHF79tUWAKp4PzsE3z1A#heading=h.au8zjzii8lgw). 

## changes

1. adds high-level document status section. 
2. convert outstanding TODOs to a dynamic link to `label:source-track` issues in slsa repo
3. removes reference "time" in the definition of "revision."
4. adds source track links to what's new file.

2024-07-03 13:39 UTC, TomHennen approved these changes
LGTM thanks!

2024-07-03 16:35 UTC, joshuagl commented
> It looks like I technically have permission to merge this, but I don't think that's the right process.

Thanks for holding off! Per the CONTRIBUTING guide, content changes should have 3 approvers and allow a minimum of 72h for review: https://github.com/slsa-framework/slsa/blob/main/CONTRIBUTING.md#pull-request-types

2024-07-03 16:38 UTC, joshuagl requested changes
Thanks, this LGTM but please restore the TODO items within the file contents.

2024-07-03 16:38 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +## Status: DRAFT
```suggestion
```
Let's drop this line, the whole document is already heavily indicated as a draft
<img width="1033" alt="Screenshot 2024-07-03 at 17 36 17" src="https://github.com/slsa-framework/slsa/assets/13888612/24d2f273-3ff4-4e63-8ce9-00dc5ffe30a7">

2024-07-03 16:38 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +Open issues are tracked with the [source-track](https://github.com/slsa-framework/slsa/issues?q=is%3Aissue+is%3Aopen+label%3Asource-track) label in the [slsa-framework/slsa](https://github.com/slsa-f
Please leave todos within the doc, that better communicates to readers what's left to work on and makes it marginally easier to work through the todos when editing the file.

2024-07-03 16:59 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +Open issues are tracked with the [source-track](https://github.com/slsa-framework/slsa/issues?q=is%3Aissue+is%3Aopen+label%3Asource-track) label in the [slsa-framework/slsa](https://github.com/slsa-f
the problem we were having was the todos were growing faster than our ability to approve changes to the draft. At best wouldn't it always be a snapshot of the issues in that query captured every time a pr is merged?

2024-07-03 17:03 UTC, zachariahcox commented on docs/spec/v1.1/source-requirements.md
> +Open issues are tracked with the [source-track](https://github.com/slsa-framework/slsa/issues?q=is%3Aissue+is%3Aopen+label%3Asource-track) label in the [slsa-framework/slsa](https://github.com/slsa-f
or @joshuagl to put it differently, which TODOs should appear in version control? there were previously only three, and there are currently 23 open issues. 

I would strongly suggest making this doc more accurate by tracking the current set of blocking issues. 

Maybe to your deep point, not all of those issues are blocking this doc from moving out of "draft" status, but I think that's something we should track and solve by labeling any such blocking issues as they appear?

What do you think?

2024-07-03 17:25 UTC, TomHennen commented on docs/spec/v1.1/source-requirements.md
> +Open issues are tracked with the [source-track](https://github.com/slsa-framework/slsa/issues?q=is%3Aissue+is%3Aopen+label%3Asource-track) label in the [slsa-framework/slsa](https://github.com/slsa-f
IMO the 'easy' thing is just to list the TODOs from https://docs.google.com/document/d/13Xt8mA_2b00McGX2vkyhu4GQdFAqtXPu7YXE8ZA6ISE/edit?resourcekey=0-EqfHF79tUWAKp4PzsE3z1A&tab=t.0 and then maybe also link to that tag as a helpful pointer.

2024-07-08 11:19 UTC, joshuagl approved these changes

2024-07-08 11:19 UTC, joshuagl commented on docs/spec/v1.1/source-requirements.md
> +-   [] https://github.com/slsa-framework/slsa/issues/1080
```suggestion
-   [] [Structure & formatting don't match the build track](https://github.com/slsa-framework/slsa/issues/1069)
-   [] [Either identify the unique value of L1 or merge it with L2](https://github.com/slsa-framework/slsa/issues/1070)
-   [] [How to communicate SLSA source track metadata?](https://github.com/slsa-framework/slsa/issues/1071)
-   [] [Clarify source track objective](https://github.com/slsa-framework/slsa/issues/1072)
-   [] [Clarify the 'merger' identity in source track](https://github.com/slsa-framework/slsa/issues/1074)
-   [] [Flesh out the definition and bounds of 'identity', and why they're required](https://github.com/slsa-framework/slsa/issues/1075)
-   [] [VCS and SCP concerns are mixed or too prescriptive](https://github.com/slsa-framework/slsa/issues/1076)
-   [] [Clarify that self-hosted SCPs are allowed](https://github.com/slsa-framework/slsa/issues/1077)
-   [] [Create guidance for consumers on how to evaluate the source platform](https://github.com/slsa-framework/slsa/issues/1078)
-   [] [Clarify what must be retained during source migrations](https://github.com/slsa-framework/slsa/issues/1079)
-   [] [Refine requirements/guidance for trusted robots](https://github.com/slsa-framework/slsa/issues/1080)
```

2024-07-08 19:06 UTC, lehors approved these changes
LGTM

2024-07-08 19:06 UTC, merged