blog: Dependency Confusion and Typosquatting Attacks
slsa-framework/slsa pull request #1109
Opened 2024-08-13 04:25 UTC by meder

Blogpost that looks at dependency confusion and typosquatting attacks from defender's perspective and defines "managed ingestion" as an important capability for supply chain risk management.

2024-08-21 16:19 UTC, joshuagl approved these changes
Made a few minor suggestions for clarity, but otherwise this looks good to me. Thank you for writing this up.

2024-08-21 16:19 UTC, joshuagl commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +-   **Namespacing:** Some package registries support namespacing, sometimes called scoping or organization support. This feature enables organizations to claim a namespace in the public registry for
```suggestion
-   **Namespacing:** Some package registries support namespacing, sometimes called scoping or organization support. This feature enables organizations to claim a namespace in the public registry for their internal dependencies. This prevents attackers from registering internal names, as they are not authorized to publish to the organization's namespace. Confidentiality concerns would likely prevent large organizations, that are usually targeted by the dependency confusion attacks, from hosting internal dependencies in the public instance; claiming the namespace is, however, sufficient to prevent attackers from exploiting dependency confusion. Namespacing is not supported by all package registries, and moreover the solution is not very robust as trust is placed into another forgeable identifier outside of the organization's control.
```

2024-08-21 16:19 UTC, joshuagl commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +Dealing with _typosquatting_ attacks is trickier because at the time of the attack the developer is adding a new dependency, potentially interacting with it for the first time. Trust on first use (TO
```suggestion
Dealing with typosquatting attacks is trickier because at the time of the attack the developer is adding a new dependency, potentially interacting with it for the first time. Trust on first use (TOFU) is a common approach to bootstrapping trust and [forming expectations](https://slsa.dev/spec/v1.0/verifying-artifacts#forming-expectations), however, since it's impossible to know the developer's intent, all tooling can do is present them with the metadata about the package they are adding. Unfortunately that metadata could be for the attacker's impostor package.
```
italics here feels inconsistent

2024-08-22 15:47 UTC, mlieberman85 approved these changes
LGTM, I agree with @joshuagl 's suggestions.

2024-08-23 03:42 UTC, arewm requested changes
Thanks for this blog post. A couple questions to help drive better clarity.

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +Dependency confusion and typosquatting attacks are very similar in their nature. They both exploit the weakness in the way many package managers identify packages using only their names. This weak fo
Sentences 2 and 3 feel like they are largely repeating each other.

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +The convenience of package managers for dependency management has been recognized by developers and organizations worldwide. It enabled them to leverage existing tooling to effectively distribute int
```suggestion
The convenience of package managers for dependency management has been recognized by developers and organizations worldwide. It has enabled them to leverage existing tooling to effectively distribute internal dependencies. One common approach involves running an internal, private instance of a package registry to distribute internal dependencies and configuring **_all_** build processes to first look for a package in the private registry and only if it is not found there going to the public instance of the package registry to fetch it[^1].
```

What is the "it"? Are you saying that package managers have enabled developers and organizations worldwide to distribute internal dependencies? What are internal dependencies?

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +This works but is fragile. If someone in the organization attempts to build software that uses internal packages but doesn't correctly configure the build to use the private registry instance then th
```suggestion
This works but is fragile. If someone in the organization attempts to build software that uses internal packages but doesn't correctly configure the build to use the private registry instance first then the package installer will attempt to fetch internal packages from the public registry instance. Under normal circumstances this will return an error, as the internal package name would not be present in the public instance.
```

It it accurate that the proper configuration is using the internal package repository first? If it is not configured to be used first then the public registry may be accessed first causing the error?

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +The workflow for developers to add a new dependency most often involves modification of a manifest file to add a reference to the new package by its name and version. The package name is usually manu
Should we be more specific about what they are adding a new dependency to? Is it more than just adding a dependency to code/software?

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +In case of _typosquatting_ attacks the mitigation is not very straightforward and for the most part requires intervention at the point when developers are adding a new dependency. Effective mitigatio
What do you mean by "number of dependents" here?

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +2.  SLSA build provenance is [distributed along with the artifact](https://slsa.dev/spec/v1.0/distributing-provenance).
Not all artifact distribution repositories support distributing SLSA provenance alongside the other packages. Should selecting an appropriate repository be part of these steps?

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +4.  Upon installation of the internal packages their build provenance is verified to ensure they were built by the authorized build system and from the canonical source repository.
Who verifies the build provenance of the dependencies?

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +Attackers are unable to forge SLSA build provenance thus all dependency confusion attempts will be immediately detected due to a different canonical source repository or builder ID. Native support fo
I think that this should be qualified with >= build L2.

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +Dealing with typosquatting attacks is trickier because at the time of the attack the developer is adding a new dependency, potentially interacting with it for the first time. Trust on first use (TOFU
This is assuming that the dependency is not produced internally (i.e. the identity associated with the provenance is not known). It could be possible to partially defend against this if you know that you are consuming your own organizations' packages.

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +In this context a reasonable baseline for managed ingestion includes:
What is this section meant to convey? What do you mean by "a reasonable baseline" here? The items seem to fall across a couple different themes.

2024-08-23 03:42 UTC, arewm commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +The process of using OSS packages via registries presents a lot of risks beyond typosquatting and dependency confusion—and requires the same level of attention and control as the build process itself
What is "this fundamental capability" that you are referring to?

2024-08-26 23:05 UTC, marcelamelara requested changes
Thanks for submitting this blog post @meder ! My main high-level question is about the audience for this blog post. This is a relatively advanced topic, so if the intent is to reach a more general audience, my main suggestion is to make some revisions in the text that would help such an audience grapple with this topic. Either way, I left several comments that should help smooth out the flow and ease the transitions between sections to guide a more familiar reader as well.

2024-08-27 02:17 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +Dependency confusion and typosquatting attacks are very similar in their nature. They both exploit the weakness in the way many package managers identify packages using only their names. This weak fo
Great catch, thanks. Fixed.

@marcelamelara I believe this is already in place, but please let me know if you have concrete suggestions for changes.

2024-08-27 02:46 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +The convenience of package managers for dependency management has been recognized by developers and organizations worldwide. It enabled them to leverage existing tooling to effectively distribute int
Clarified this further in the text. PTAL.

2024-08-27 02:47 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +This works but is fragile. If someone in the organization attempts to build software that uses internal packages but doesn't correctly configure the build to use the private registry instance then th
Incorporated.

2024-08-27 02:57 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +The workflow for developers to add a new dependency most often involves modification of a manifest file to add a reference to the new package by its name and version. The package name is usually manu
Incorporated @marcelamelara's suggestion.

re: manifest example: I've considered this as I was writing and decided against to keep the post high level and ecosystem agnostic. Instead I believe this paragraph describes the mechanics well without getting into ecosystem specific details. Please reopen if you'd like to discuss this further.

2024-08-27 03:01 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +In case of _typosquatting_ attacks the mitigation is not very straightforward and for the most part requires intervention at the point when developers are adding a new dependency. Effective mitigatio
Correct, it is the number of packages directly depending on the package. (e.g. https://deps.dev/maven/com.google.guava%3Aguava/33.3.0-jre/dependents).

@marcelamelara Could you please say more on what you'd like to see? Current text is making the point that asking humans to verify things is prone to human errors.

2024-08-27 03:04 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +4.  Upon installation of the internal packages their build provenance is verified to ensure they were built by the authorized build system and from the canonical source repository.
Not sure I follow the question, could you please elaborate? This list outlines a general algorithm that will need to be followed to verify provenance in the context of dependency confusion.

2024-08-27 03:05 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +Attackers are unable to forge SLSA build provenance thus all dependency confusion attempts will be immediately detected due to a different canonical source repository or builder ID. Native support fo
Great call, done.

2024-08-27 03:24 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +The process of using OSS packages via registries presents a lot of risks beyond typosquatting and dependency confusion—and requires the same level of attention and control as the build process itself
Managed ingestion, tweaked the sentence.

2024-08-27 03:32 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +The convenience of package managers for dependency management has been recognized by developers and organizations worldwide. It enabled them to leverage existing tooling to effectively distribute int
I've updated section headings to be more explicit. PTAL. If you have other suggestions please reopen.

2024-08-27 03:34 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +The attacker begins by performing reconnaissance to acquire names of internal packages. This can be done using a number of techniques, e.g. trawling through organization's open source repositories, i
Thanks, incorporated.

2024-08-27 04:44 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +The workflow for developers to add a new dependency most often involves modification of a manifest file to add a reference to the new package by its name and version. The package name is usually manu
Incorporated, thanks.

2024-08-27 04:59 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +A much more robust way to address dependency confusion is to use SLSA. SLSA build provenance contains metadata about an artifact, which includes the URL of the source repository and identifies the bu
My assumption with dependency confusion is that the release location is known given that that's where organizations download / publish their packages and I worry that mentioning release attestations would cause confusion. However, if you do have a way to incorporate them into text in mind, please add it as suggestion. Thanks.

2024-08-27 06:10 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +
Added a short sentence, PTAL.

2024-08-27 06:24 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +### Managed Ingestion
Thanks, would love to improve the flow more, unfortunately the suggestion doesn't really match the narrative that follows. I'll ping you on Slack to chat more about this. Thank you.

2024-08-27 06:34 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +Dealing with typosquatting attacks is trickier because at the time of the attack the developer is adding a new dependency, potentially interacting with it for the first time. Trust on first use (TOFU
Yeah, I've left that scenario out for the sake of clarity/readability and in favor of the dependency confusion solution using SLSA provenance. Happy to chat more if you think this nuance is important here.

2024-08-27 06:38 UTC, meder commented
@arewm @marcelamelara thank you both for the review and feedback, PTAL.

2024-08-27 20:55 UTC, marcelamelara commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +In case of _typosquatting_ attacks the mitigation is not very straightforward and for the most part requires intervention at the point when developers are adding a new dependency. Effective mitigatio
I think what I would like to see is concrete examples of why asking humans to verify things in this context leads to mistakes. For example, I can imagine that people will just click "accept" when prompted to verify the package installation because they are on a deadline, lack expertise, they still mis-read the package name., etc. I'm not looking for a bunch of examples or elaborate explanations, but just some more intuition behind the problem you highlighted.

2024-08-27 21:06 UTC, marcelamelara commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +4.  Upon installation of the internal packages their build provenance is verified to ensure they were built by the authorized build system and from the canonical source repository.
Right, I think the question is about which party is responsible for the verification and setting that policy. In other words,  who decides what constitutes an "authorized" build system or "canonical" repo? Since this is about a local installation, I could imagine there would be some policy that is set by the organization in an enterprise setting. In other settings, it could be the individual developer who sets the policy. So what I, at least, would like to see here is just a little more detail about the responsible party. I think it'll also tie this recommendation back nicely to the earlier sections of the blog post that talk about enterprise software development.

2024-08-27 21:09 UTC, marcelamelara commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +In this context a reasonable baseline for managed ingestion includes:
Cool, yeah, I definitely agree on the goal here. I think it makes sense for the blog post to mention the purpose of the baseline and to call out explicitly that these recommendations originate from years of experience in this space. IMO this strengthens the case for managed ingestion.

2024-08-28 03:54 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +In case of _typosquatting_ attacks the mitigation is not very straightforward and for the most part requires intervention at the point when developers are adding a new dependency. Effective mitigatio
Thank you for the clarification. Expanded the sentence a bit. PTAL.

2024-08-28 05:35 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +4.  Upon installation of the internal packages their build provenance is verified to ensure they were built by the authorized build system and from the canonical source repository.
Thanks, @marcelamelara. This should now be reflected, PTAL.

2024-08-28 05:45 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +In this context a reasonable baseline for managed ingestion includes:
Thank you, done. PTAL.

2024-08-28 05:51 UTC, meder commented
Thank you for the clarifications, @marcelamelara. Feedback was addressed, PTAL.

2024-08-28 06:01 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +2.  SLSA build provenance is [distributed along with the artifact](https://slsa.dev/spec/v1.0/distributing-provenance).
(sorry, missed this earlier).

I wanted to highlight the "recommended" path here for provenance distribution, please LMK if you think adding this nuance will contribute to readability.

re: selecting repository: the text was tweaked and references internal registry instance as an example.

2024-08-28 22:20 UTC, meder commented on docs/_posts/2024-08-13-dep-confusion-and-typosquatting.md
> +The inadequacy of just using package names as the way to identify software packages is hopefully obvious by now. Let's first explore common recommendations to mitigate _dependency confusion_ attacks
Agree, changed to fragility and added links to a couple of examples.

2024-08-28 22:30 UTC, meder commented
@marcelamelara I believe all feedback was addressed, PTAL.

2024-09-01 23:26 UTC, meder commented
@marcelamelara @arewm I'd like to target publish this on Wed (Sep 4th), please let me know if you have any blocking feedback.

2024-09-04 15:24 UTC, mlieberman85 approved these changes
LGTM

2024-09-04 15:39 UTC, arewm approved these changes
Thanks for this blog post!

2024-09-04 17:08 UTC, marcelamelara approved these changes
Thanks for all of the updates @meder ! LGTM.

2024-09-04 18:41 UTC, merged