content: Attested build environment track
slsa-framework/slsa pull request #1115
Opened 2024-08-15 22:04 UTC by marcelamelara

This PR introduces the following spec changes associated with https://github.com/slsa-framework/slsa/issues/975. The spec enhancements are being proposed as the new "build Environment track".

Spec changes:

- [ ] Add new level to levels.md
- [ ] Add new requirements to requirements.md
- [ ] Add related terminology to terminology.md
- [ ] Add example of hardware-based build environment attestation
Part 1 of https://github.com/slsa-framework/slsa/issues/975 CC @paveliak

2024-08-16 18:03 UTC, TomHennen commented
FYI if you want to make the linter happy easily [this might help](https://github.com/slsa-framework/slsa/blob/main/CONTRIBUTING.md#markdown-style).  The linter caused me a ton of trouble until I figured this out.

2024-08-16 18:29 UTC, TomHennen reviewed
I like where this is heading :)

2024-08-16 18:29 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +The lowest level only requires SLSA Build L2 (or higher) Provenance to exist
nit: environment Level 1 seems to only require SLSA Build L1.

I can see the advantage of making L1 require SLSA Build L2 (but that might also be confusing. :)).

2024-08-16 18:29 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +-   MUST automatially generate and distribute SLSA [Build L1] or higher
Can you clarify what you mean by 'distribute'?  Provenance has a lot of metadata in it and some business might be nervous about publishing the actual build provenance.  However they'd likely be totally fine with publishing VSAs for those images that show they were verified.

2024-08-16 18:29 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +-   MUST execute builds on infrastructure that meets SLSA [Build L2].
What is the difference between the "supplied build images" and the infrastructure itself being Build L2?  I suppose it might be that "all the other software in the service is Build L2"?

2024-08-16 18:29 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +All of [Environment L1], plus:
nit: I think some of these requirements are duplicated from L1.  I can also see why we wouldn't focus on removing the duplication _now_ and would wait until it's closer to done.

2024-08-16 18:29 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +[future versions]: future-directions.md
```suggestion
[VSA]: verification_summary.md
[future versions]: future-directions.md
```

2024-08-16 22:19 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +-   MUST execute builds on infrastructure that meets SLSA [Build L2].
Yeah, this one has been tricky for us to articulate. Here's what we're trying to tease out. The build platform has some separate (internal) build process for the build images they supply to their users (e.g., GHA runner images), so the platform is essentially acting as a software producer. So for the VM images, we're saying that their SLSA Build Provenance needs to be at least Build L1. At the same time, since tenants will be running builds using these VM images on the hosted build platform, this implies that the build should produce at least Build L2 Provenance for any artifacts built on it.

So, put differently, we're trying to explicitly codify both the "hosted build platform" requirement as well as the need to collect SLSA Provenance for the VM/container images that that platform puts out there to run builds. 

A couple options I'm considering to address this confusion could be 1) SLSA Provenance for build images should also start at Build L2, so the VM images and artifacts built through the hosted platform have the same provenance level, or 2) we focus only on the "platform as a producer" aspect in this track, and say upfront that this track applies to Build L2 or L3 build platforms. I'm leaning towards option 2 because our intent is mainly to bolster the integrity guarantees for artifacts built in attested compute environments. WDYT?

2024-08-16 22:34 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +-   MUST automatially generate and distribute SLSA [Build L1] or higher
Fair point. Something that we haven't clearly expressed yet is that for higher levels, we have an expectation that the build platform will verify the Provenance and other attestations for the build images before taking certain actions. I'll amend L1 to support VSAs or full SLSA Provenance, as long as there's evidence about the build image provenance.

2024-08-16 22:37 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +All of [Environment L1], plus:
Yeah, we're mostly being extra explicit here. FWIW, I pretty much copied the build track levels file, which also has a lot of this duplication :)

2024-08-17 14:41 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +-   MUST execute builds on infrastructure that meets SLSA [Build L2].
Do you think it might help if we considered the producer of the build images as potentially distinct from the build platform itself?  Would that help make the language more clear?

Then a) "the components of build platform must be SLSA Build Level 2+" and b) "images used to run user provided build processes must be Build Level X+, regardless of who produced them".  'b' seems important because surely users will want to bring their own image sometimes?

I could also imagine removing 'b' entirely from the track, and instead handling that as some sort of extension of the build track itself or however [the transitivity problem](https://slsa.dev/spec/v1.0/faq#q-why-is-slsa-not-transitive) is solved.

2024-08-17 14:42 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +All of [Environment L1], plus:
Ha yeah.  Let me resolve this and we can leave it be for now.

2024-08-19 17:59 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +-   MUST execute builds on infrastructure that meets SLSA [Build L2].
That's an interesting suggestion, thanks! I think that's already sort of where I was heading with my option 2 above, but I think it makes sense to more cleanly separate the two roles. The only part that's still trickier in my mind is disentangling the build image from the broader build environment once it's running on the platform, e.g. waiting in a runner pool to be dispatched, but I'll give this framing a try.

2024-08-20 14:02 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +-   MUST execute builds on infrastructure that meets SLSA [Build L2].
Oh something else to consider is that "components of the build platform" might wind up being _very large_ in a SaaS environment.  So it might help to be quite explicit about what is and is not in scope.

2024-08-21 19:28 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +-   MUST execute builds on infrastructure that meets SLSA [Build L2].
I made some changes, PTAL!

2024-08-21 19:28 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +The lowest level only requires SLSA Build L2 (or higher) Provenance to exist
With the split of build image producer and build platform, this does actually become L1 :) Hopefully that's slightly less confusing.

2024-08-26 01:48 UTC, paveliak commented on docs/spec/draft/attested-build-env-levels.md
> +    -   Prior to deployment of a new build environment, a signed attestation
How this is different from L1 which states that `Prior to deployment of a new build environment, the SLSA Provenance for the selected build image MUST be automatically verified.` Does it add a "distribution" requirement or there is more to it?

2024-08-27 16:53 UTC, haydentherapper commented on docs/spec/draft/attested-build-env-levels.md
> +    -   MUST meet SLSA [Build L2] requirements.
Why did you choose to have build image producer and build platform requirements differ with respect to the SLSA Build level? If they differ, then the overall security of the system ultimately degrades to the lowest SLSA level in my opinion. Given the diff between Build L1 and Build L2 is primarily signed provenance, could we bump up the Build Image Producer requirement to Build L2? (And similarly, for BuildEnv L2 as well, could both be Build L3?)

2024-08-27 22:35 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    -   MUST meet SLSA [Build L2] requirements.
This is something we've gone back and forth on, and we originally had the requirement to start at Build L3, but got some pushback about how that could set the bar too high for BuildEnv L1. We've also heard some confusion/concerns around the dependency on the build track in the buildEnv track. So the current choice to lower the requirement down to Build L1 for BuildEnv L1 was mostly to make the barrier to entry for the build image producer lower. Ultimately, I agree with you that starting at Build L2 provenance for BuildEnv L1 images makes more sense from an integrity standpoint, but I also think you raise a broader question about the transitivity of SLSA levels.

2024-08-27 22:38 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    -   Prior to deployment of a new build environment, a signed attestation
At L2, the intent is to add the requirement to generate and distribute an attestation for the verification, while in L1, it's sufficient to have the verification, but it's not required to attest to this step. I agree the difference isn't clear enough right now. Maybe it makes more sense to remove the verification requirement from L1 since there's no evidence that the build platform perform it anyway?

2024-08-27 22:38 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +The build environment is measured and authenticated prior to dispatching
Thanks for catching this.

2024-08-29 07:18 UTC, kommendorkapten commented on docs/spec/draft/attested-build-env-levels.md
> +environment executes the tenant's build definition.
Nit but the indentation is missing on this line 😄

2024-08-29 16:57 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    -   MUST allow independent automatic verification of a build image's SLSA
Interesting, this is definitely a different scenario. I think the way to handle this is for the build image producer to separately put out an explicit attestation that hash X corresponds to a certain build image. We can then articulate this in the spec as an additional requirement like "The build image producer MUST distribute sufficient information about the build image artifact to allow for verification of its provenance, either in the form of the artifact itself or an immutable identifier (e.g., an attestation to its hash)." WDYT?

2024-08-29 17:25 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    -   MUST meet SLSA [Build L2] requirements.
I reconsidered this comment, and I actually think that the argument that the security (and therefore SLSA level) of the system degrades to the lowest level isn't really accurate in this case. This track intends to build upon the integrity of the Build track because all of the requirements stated here are needed in addition to the basic Build L2 requirements in the platform. The said, there's still a reason to bump the Provenance level at L1, but it's because the focus of L2 needs to be about attesting to the "deployment chain".

2024-08-29 22:59 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    -   MUST allow independent automatic verification of a build image's SLSA
I'd made some changes to explicitly incorporate this scenario. PTAL!

2024-09-18 09:31 UTC, TomHennen reviewed
Thanks for these changes!

This generally LGTM, I would also like to see what @deeglaze thinks about it too.

2024-09-18 18:19 UTC, deeglaze commented on docs/spec/draft/attested-build-env-levels.md
> +    -   Prior to dispatching a tenant's build to an instantiated environment,
You can verify a quote's signature without caring about the contents it measured. I think we need to say that the measurements in the quote are verified against the signed reference values provided by the build producer for the instantiated build image.

I'm interested in how you plan on identifying what a booted environment is as a whole to compare against its components. I don't think there is a commonly accepted mechanism for this.

2024-09-18 18:19 UTC, deeglaze commented on docs/spec/draft/attested-build-env-levels.md
> +        a signed attestation that binds its boot process quote to the
The binding should be to the boot, build job description and build job outputs, no?

If the build environment is meant to be from a clean slate every time, then the job description and outputs can be measured to integrity registers. I'm unclear about build ID. Is this not an in-toto signing key? If it is, I'd expect to see the key only released after the build is complete, following a quote binding to a challenge to get the key released to the build environment to sign the in-toto attestation.

2024-09-20 21:46 UTC, thirumalareddym commented on docs/spec/draft/attested-build-env-levels.md
> +| Build image | The template for a build environment, such as a VM or container image. Individual components of a build image include the bootable storage volume containing the build executor, a dedi
When a container image is used as build environment, in practice those container images are executed on a VM which gets created using a VM image. In that scenario, does the requirements documented here for build image would apply for both the host VM image and container image?

2024-09-23 18:16 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Build image | The template for a build environment, such as a VM or container image. Individual components of a build image include the bootable storage volume containing the build executor, a dedi
Yes, we're not currently covering builds that are distributed in any way, we have a big TODO for this. I opened #1150 to have the discussion specifically about multiple container images.

2024-09-23 18:18 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Build image | The template for a build environment, such as a VM or container image. Individual components of a build image include the bootable storage volume containing the build executor, a dedi
Good question. I've actually seen cases in which the containers may _not_ be run inside of VMs, hence the current wording. I agree the current spec is ambiguous about the case you describe. I'll open an issue to address the question of container-in-VMs in the spec.

2024-09-23 18:19 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Build image | The template for a build environment, such as a VM or container image. Individual components of a build image include the bootable storage volume containing the build executor, a dedi
See #1151

2024-09-29 22:34 UTC, deeglaze commented on docs/spec/draft/attested-build-env-levels.md
> +The deployed build environment is integrity measured and authenticated
```suggestion
The deployed build environment is integrity-measured and authenticated
```

2024-09-29 22:34 UTC, deeglaze commented on docs/spec/draft/attested-build-env-levels.md
> +Organizations wanting to ensure that a specific build is running
```suggestion
Organizations wanting to ensure that an attestation policy–approved build is running
```

2024-09-29 22:34 UTC, deeglaze commented on docs/spec/draft/attested-build-env-levels.md
> +    independent verification.
I don't think this part ought to be required. The boot is measured and authenticated before giving access to the tenant, so perhaps we need only for the build agent to use credentials that root back to the attestation server, and that the certificate binds the agent to an immutable label for the policy the environment was evaluated under. If the build image has a unique name (such as a CoBOM tag UUID), then that could be included as well.

2024-09-29 22:34 UTC, deeglaze commented on docs/spec/draft/attested-build-env-levels.md
> +-   MUST uniquely bind a build image to a build environment instance.
As in a build environment can only be identified as a uniquely identified single build image? What if there are two copies of the image with the same measurements but different endorsers? I'm not sure what "uniquely bind" means.

2024-09-29 22:34 UTC, deeglaze commented on docs/spec/draft/attested-build-env-levels.md
> +general [TODO: minimum requirements], this track does not dictate the
Whereas the track does not dictate the implementation-specific details, is there going to be a co-developed reference implementation of such formats/technologies to help folks build the analogy?

2024-09-30 15:25 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Build image | The template for a build environment, such as a VM or container image. Individual components of a build image include the bootable storage volume containing the build executor, a dedi
We've been going back and forth on what the best term is for the "storage volume" that covers both the container and VM use cases (there's an [open issue](#1107) for this discussion). For now, I _think_ we've landed on "root filesystem", as you noted we're using below, and it seems I missed to update this section. I'm going to make a note of your other comments in that issue.

You raise a very valid point re: the volume that contains the build executor and build agents. For now, at L2 we're requiring that those components be measured (and their measurements checked against their reference values ofc), but we aren't assuming that they be part of the bootable volume or even root fs.

2024-09-30 15:26 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    guest kernel, build agent, build executor, and root filesystem (e.g.,
The intent for "root filesystem" is to be the `/` mount point. I suppose for windows environments, that would typically be `C:` ?

2024-09-30 15:29 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    guest kernel, build agent, build executor, and root filesystem (e.g.,
Resolving the second part of this comment via #1164.

2024-09-30 15:40 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +        a signed attestation that binds its boot process quote to the
The build hasn't executed at this point, so there are no build outputs to bind yet. The build ID is typically a unique opaque identifier generated by the build platform's control plane (e.g., GitHub's job ID), and is assigned to a build environment at dispatch time. We anticipate the build environment and build outputs will be indirectly bound via this build ID, which is included both in this "dispatch" quote and also in the resulting SLSA Build Provenance when the build completes.

What do you mean by build job outputs here? The return status, or the actual built artifacts. The former could certainly be easily measured into the integrity registers, the latter is more challenging in the case of very large built artifacts.

2024-09-30 15:48 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    for the selected build image MUST be automatically verified.
For now, we're implicitly defining the following simple policy: "Does the build image (via its hash) match my expectations (via its Provenance)"? We have an outstanding TODO to describe the verification process for all of the attestation types generated through this track, that will be in a separate doc. 

Beyond that, we're being very careful not to be overly prescriptive in the verification policies that SLSA users will ultimately define. We're not actually precluding an implementer of this track from bundling the build image and artifact Provenance attestations together (this is something in-toto readily supports), but because the build image isn't fully representative of the _instantiated_ build environment (e.g., because more components may be loaded at startup time, and each environment is uniquely identified by the build platform, even if it comes from the same base image), we can't simply treat the build environment as an input into the build.

2024-09-30 15:57 UTC, deeglaze commented on docs/spec/draft/attested-build-env-levels.md
> +        a signed attestation that binds its boot process quote to the
Build job outputs I'm just talking about the in-toto ResourceDescriptions of the built artifacts. The build integrity gets bound to the build environment integrity before permitting the signing of the build attestation as meeting a certain level. 

I'm misunderstanding the build ID and treating it as synonymous with the credentials to sign the build. Is there no SLSA-defined role for the build attester? I'm guessing the build agent will take on that role, but I haven't seen specific wording about signing. The RATS architecture would assign the role of Attester, I believe.

Even if the key is not released to the build environment itself and the in-toto attestation is meant to be signed remotely, either the key release request or the signing request that uses the L2-rated key ought to have measurements of both the build job description (measured before starting the build) and the build results description (the output resource descriptors) to permit use of the key. This can be accomplished with an appropriate attestation appraisal policy.

Both inputs and outputs get bound to the request to remove the need for a challenge, since there's nothing left to do if you replay in an attack environment. I don't think it's reasonable to require that the whole of the attestation request to the verification server gets stored. You just need an immutable label for the state of the appraisal policy (including the appraisal implementation provenance itself) and knowledge base of approved reference values.

2024-09-30 16:32 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +general [TODO: minimum requirements], this track does not dictate the
Absolutely. We've been prototyping this here: https://github.com/chkimes/image-attestation

2024-09-30 16:59 UTC, zachariahcox commented on docs/spec/draft/attested-build-env-levels.md
> +    the *host interface's* boot process quote MUST be automatically verified.
for GHA, i guess this would be the runner verifying the host's boot attestation before downloading any customer-generated payload?

2024-09-30 21:12 UTC, paveliak commented on docs/spec/draft/attested-build-env-levels.md
> +| Build image | The template for a build environment, such as a VM or container image. Individual components of a build image include the bootable storage volume containing the build executor, a dedi
Great question. It depends on how we draw the boundaries of the build environment. Speaking about CloudBuild do we stop at the build executor and treat all individual steps (including the docker images) as a tenant context? Or we measure them as the part of Build environment?

Ultimately CloudBuild runs in an environment that uses different kind of builders for each step. We can say that this _is_ the build environment and individual steps are the payload that may use builders that run things inside a Docker container or in a separate virtual machine or elsewhere. And those builders may in turn spin up other builders. Where do we stop?

I think the scope of this track is to focus on the top level environment, i.e. effectively measure CloudBuild, because as it was said in the beginning of this document we measure the Build Platform. Technically individual builders can also be treated as build environment providers and hence this track could be applied to them as well.

Perhaps it could be summarize with this analogy of nested environments. Practically this track could be applied at any nested level, at least for L1. L2 and L3 get more complicated because  the more we go deeper into the nesting levels the larger "build platform" surface becomes.
```
[ top level environment [docker run [docker in docker run [...]]]]

```

2024-09-30 22:53 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    the *host interface's* boot process quote MUST be automatically verified.
The short answer is no, it's not the runner performing the verification, it's the control plane of the CI platform.

Here's the general flow we're envisioning: 
1) The hypervisor (i.e., the host interface) boots up a new VM with some measured boot mechanism (commonly something like Secure Boot). This will generate a vTPM-signed attestation for the VM's boot process (plus, some extensions we introduce in this track), which the control plane retains for later verification.
2) When a new build request comes in, the control plane performs an authentication handshake with the build agent (not runner) in the VM. As part of this handshake, the agent will quote the vTPM again, and send the new attestation to the control plane.
3) The control plane will only dispatch a tenant's build into the VM if the content of the new quote matches the expected boot-time quote. 

I will caveat this by saying the intended audience for this doc is software developers/CISOs who need the broad strokes of the requirements. A separate "requirements" doc will specify the properties and protocols in greater detail for actual build or CI platforms looking to implement the track.

2024-09-30 23:00 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +-   MUST uniquely bind a build image to a build environment instance.
This is an old requirement we took out in a more recent commit. The way GHA operates today is that each VM is assigned a authentication token/ID. So, the idea here was to bind that ID to the build image via an integrity measurement when the VM first starts up, so that you could validate later that a particular build job ran inside of the intended VM.

Again, we took out this specific piece, because it's strictly implementation-specific, and to simplify the requirements of L2. Now, we only require that the build _job_ ID be bound to the build image (as we were discussing above).

2024-09-30 23:01 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    independent verification.
I think you were looking at an older commit, we've revised this requirement so that it's no longer required.

2024-09-30 23:32 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +        a signed attestation that binds its boot process quote to the
Got it. The build ID is not the Provenance signing key. The build ID is a random identifier that the control plane assigns to the build process. On GHA, for example, this is the 11-digit job number, whose primary purpose is to denote different runs of the same build process. The attestation signing credential is also issued by the control plane, but is typically mapped to the individual _user_ that triggered a build process, at least in the typical OIDC token-based PKI used by Sigstore and GHA.

To your point, SLSA doesn't currently follow the RATS architecture, so there isn't an explicit build attester role. Part of the reason for that is that the Build track doesn't even have a notion of an attested build at every level. 

> Both inputs and outputs get bound to the request to remove the need for a challenge, since there's nothing left to do if you replay in an attack environment. I don't think it's reasonable to require that the whole of the attestation request to the verification server gets stored. You just need an immutable label for the state of the appraisal policy (including the appraisal implementation provenance itself) and knowledge base of approved reference values.

Two thoughts here. First, I think it's definitely possible to make build environments less susceptible to replay attacks. It's actually something I've started thinking about for a while, and I think replay prevention needs to eventually become part of this BuildEnv track. 

Second, I agree that the ideal realization of attested builds would cover provenance for the appraisal  implementation, track the state of the appraisal policy, etc. as you suggest. I'll also say that handling policy is outside of the current scope of SLSA overall. If it's something that interests you, we do have an ongoing policy WG through the in-toto project where we're starting to look at exactly these kinds of problems. Please let me know if you'd like to get connect with that group.

2024-09-30 23:52 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +        a signed attestation that binds its boot process quote to the
Tracking the various points raised in this thread in separate issues #1167 #1168 #1169

2024-10-01 00:05 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Build image | The template for a build environment, such as a VM or container image. Individual components of a build image include the bootable storage volume containing the build executor, a dedi
Tracking this in #1170.

2024-10-01 00:19 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    for the selected build image MUST be automatically verified.
Tracking in #1169

2024-10-01 00:20 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +The deployed build environment is integrity measured and authenticated
This was been revised in a later commit.

2024-10-01 00:22 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +Organizations wanting to ensure that a specific build is running
This was revised in a later commit.

2024-10-01 00:41 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    the *host interface's* boot process quote MUST be automatically verified.
Commit 209f139 should begin to address this. Tracking the greater details in #1169.

2024-10-01 19:02 UTC, TomHennen requested changes
This doesn't show up in the side bar on draft mode and I can't seem direct link to it either.  TBH I'm not entirely sure how all that works.

I'd expect to see it listed on the left here
https://deploy-preview-1115--slsa.netlify.app/spec/draft

And maybe to link to it here?

Other than these few things I think I'm ready to approve and iterate.

2024-10-01 19:02 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +[auditing] that a build was run in the expected execution context.
this link doesn't seem to work

2024-10-01 19:02 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +    instead (e.g., using [SCAI] or a [Release Attestation]). If the full
[Release attestation] link doesn't seem to work.

2024-10-01 21:29 UTC, marcelamelara commented
> This doesn't show up in the side bar on draft mode and I can't seem direct link to it either. TBH I'm not entirely sure how all that works.
> 
> I'd expect to see it listed on the left here
https://deploy-preview-1115--slsa.netlify.app/spec/draft

Thanks @TomHennen ! 

It's in a separate file at https://deploy-preview-1115--slsa.netlify.app/spec/draft/attested-build-env-levels. I'll add a link to it from the Build Track levels.md file, and fix the other links, too!

2024-10-02 00:02 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +[auditing] that a build was run in the expected execution context.
Thanks for catching this. I'll remove it since the page this is pointing to doesn't exist yet.

2024-10-02 00:02 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    instead (e.g., using [SCAI] or a [Release Attestation]). If the full
Good catch, thanks!

2024-10-07 15:37 UTC, arewm requested changes
Thanks for this PR! You have an immense amount of detail present in the change which can definitely be helpful in nuanced situations like these.

I feel like the page needs to be split up so that we can move information to locations that share the level of abstraction/detail, context, and overview. The build track, for example, has information split across:
* [Terminology](https://slsa.dev/spec/v1.0/terminology) documenting the models and definitions
* [Security levels](https://slsa.dev/spec/v1.0/levels) giving a high level overview of the levels, tracks, requirements, benefits, etc.
* [Producing artifacts](https://slsa.dev/spec/v1.0/requirements) giving a more detailed breakdown of the requirements with a discussion of the many nuances

Would it make sense to create a similar split of the information for the build environment track?

2024-10-07 15:37 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +exist for the build image, while higher levels provide increasing
I read this initially as build L2 for the artifacts being generated, not for the build image. I think that this is because I was looking for a connection/commentary on how the BuildEnv and Build tracks support each other. Should we explicitly state this somewhere?

2024-10-07 15:37 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +by the build platform provider, whether they are a commercial CI/CD service,
```suggestion
by the build platform provider, whether they are a commercial CI/CD service
```

2024-10-07 15:37 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +attestation formats, the type of technologies used to meet L3/4 requirements,
This is BuildEnv L3/L4? Should we include L4 here since there is no L4 yet?

2024-10-07 15:37 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +    image's SLSA Provenance MUST be distributed instead.
This makes a reference to a broader conversation that has been going on (i.e. claiming/proving/verifying SLSA for closed build environments). I feel like we should expose it in another location and just reference that here.

2024-10-07 15:37 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +    MUST be generated and distributed (e.g., via a [VSA]).
What is the subject for this attestation? The artifact produced? 

Does this mean that the build platform will need to:
1. Verify the provenance of the build image
2. Detect that an artifact has been produced
3. Produce an attestation on that artifact with the VSA (i.e. whether L2 is passed/failed)

Some questions that come up:
* Should this identity be different from that of the build platform or can it be the same?
* Why does the verification need to happen before instantiation? Can it instead be verified after the fact (i.e. using the image recorded in a Tekton Chains-generated provenance if an immutable reference is used)?

2024-10-07 15:37 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +### BuildEnv L2: Attested build environment instantiation
Starting with this level, it seems like the criteria are very different for VMs and containers. They were grouped previously for simplicity, but would it make sense to separate them here as the amount of mutually relevant information is smaller?

Containers do still have some infrastructure behind them (i.e. VMs/nodes running the containers/pods). How do those requirements apply to that infrastructure?

2024-10-07 15:37 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +    MUST be generated and distributed (e.g., via a [VSA]).
Are you saying that there must be an agent? This might not always be the case. 

If a workload is pushed to a VM via SSH (i.e. a build script), would the agent be the ssh daemon or some process invoked in the build script?

2024-10-07 15:37 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +and autenticated by trusted hardware, attesting to the integrity
```suggestion
and authenticated by trusted hardware, attesting to the integrity
```

2024-10-08 21:40 UTC, marcelamelara commented
> I feel like the page needs to be split up so that we can move information to locations that share the level of abstraction/detail, context, and overview. The build track, for example, has information split across: Terminology, security levels, producing artifacts _[truncated for brevity]_


>
> Would it make sense to create a similar split of the information for the build environment track?

This is somewhat what we're already doing (and we have an even more detailed requirements and verification docs in the works). But I agree that we could split things more than we currently are. That being said, we're following a similar approach to the source track right now, which also coalesces all of these pieces (terminology, levels, detailed requirements) into a single page while in draft. 

More generally, from a website navigation standpoint, I think we may need to rethink how we want to organize pages, because I do think that having terminology, levels and requirements for each track on separate pages will become quite difficult/unwieldy to navigate for consumers of SLSA. The split we have right now works well because we have a single track and all of these pages are placed under the "Core specification" section of the website (see [left navigation pane](https://slsa.dev/)). With multiple tracks, we'll probably want to reorganize what falls under core spec versus track-specific sections.

2024-10-08 21:47 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +producer secrets, provenance signing).
Good point! We started using the term "hosted" mostly to stay consistent with the current spec, but are certainly not beholden to it if we eventually decide to use a different term. My current take (given our work on this track) is that "hosted" probably _is_ the right term, but that the current definition needs more context, so I'm definitely fine with using this track to help resolve #947. Happy to chime in on that issue to move things along.

2024-10-08 22:00 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +> The Build Environment track currently requires a [hosted] build platform.
Should we just get rid of L0? It's a no-op level anyway.

2024-10-08 22:01 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +<p align="center"><img src="images/build-env-model.svg" alt="Model Build Environment"></p>
Yes, we're tracking figure creation in #1165.

2024-10-08 22:04 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +### Build environment model
I'd like to, I mostly was trying to leave all BuidEnv track related changes in one place until, but if we are relatively comfortable with these new definitions (though we may continue iterating over them), I'm happy to move them over in a dedicated PR.

2024-10-08 22:24 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +environment, and the compute platform they used.
We are (as is the source track), and the reason is that SLSA Build Provenance is really well suited for describing a build process (inputs, outputs, build ID), but not other aspects about the state of a running environment. That is, we're really expanding what constitutes the full provenance of an artifact: SLSA Build Provenance + build environment provenance 
 (+ source provenance) etc. There already exist other metadata formats that _can_ describe some of those build environment attributes we want to validate (e.g., SCAI), so we're proposing to use those rather than change the Build Provenance format. 

Perhaps what this track needs is an [added definition](https://github.com/slsa-framework/slsa/blob/main/docs/spec/draft/source-requirements.md#definitions) and a [more detailed description](https://github.com/slsa-framework/slsa/blob/main/docs/spec/draft/source-requirements.md#communicating-source-levels) of what build environment provenance is, like the source track currently does?

2024-10-08 22:26 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    the build image producer outputs provenance describing this process.
Yes, this is just stating that the build image should itself have SLSA Build Provenance. The additional provenance formats come in at higher levels of the BuildEnv track.

2024-10-08 22:28 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Build image | The template for a build environment, such as a VM or container image. Individual components of a build image include the root filesystem, pre-installed guest OS and packages, the bui
The build image is the VM/disk image used to actually spin up a VM.

2024-10-08 22:32 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Build agent | A program that interacts with the hosted build platform's control plane from within a running build environment. The build agent must be included in the build image's measurement.
I think because we're assuming for the entire track that the build environment is running on a hosted build platform (as opposed to a bare metal/local builds), we do expect all environments to have a build agent in them. I'm happy to open a discussion issue for this expectation though, because it's very possible we're missing some important common use case here.

2024-10-08 22:43 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +attestation formats, the type of technologies used to meet L3/4 requirements,
Oh, this is a typo. We had an L4, but took it out because its focus wasn't clear to us. I'll fix this, thanks for catching this.

2024-10-08 22:46 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Quote | (Virtual) hardware-signed data that contains one or more (virtual) hardware-generated measurements. Quotes may additionally include nonces for replay protection, firmware information, or ot
It is. The most "official" definition for "quote" I could think of is in section 9.5.3.1 in [this doc](https://trustedcomputinggroup.org/wp-content/uploads/TPM-2.0-1.83-Part-1-Architecture.pdf), which is TPM-specific, but the term is used by many other hardware-based approaches now as well.

2024-10-08 23:21 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +### Definitions
Agreed, it'd be a little more reader-friendly if you could at least link to the individual definitions. I do think that adding the figure at the top will help a ton because then the reader would at least be able to visually see how the components fit (as [in the current build model[(https://slsa.dev/spec/v1.0/terminology#build-model)). But there are different levels of to these definitions too: some are components, and some are security mechanisms. Maybe we could split those up?

And in general, the terminology page may benefit from some re-organization between what are standard components and what are security/integrity mechanisms.

2024-10-08 23:22 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    into the *host interface* to create a new instance of a build environment
big +1. I think I'll handle this in a separate PR just to keep this one about the content.

2024-10-08 23:27 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +### Build environment model
Actually, I changed my mind. I'll move the terms to the terminology page in this PR.

2024-10-08 23:29 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +### Definitions
I'll try to address this as part of #1177 .

2024-10-08 23:30 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    into the *host interface* to create a new instance of a build environment
Tracking this in #1177 .

2024-10-08 23:31 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Primary Term | Description
"Build environment" is already defined in the current build model, but this comment just enforces the need to move all of the terminology definitions in one place.

2024-10-08 23:32 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Build agent | A program that interacts with the hosted build platform's control plane from within a running build environment. The build agent must be included in the build image's measurement.
CC @paveliak : Thoughts?

2024-10-08 23:33 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    image's SLSA Provenance MUST be distributed instead.
I'm not sure I'm aware of this discussion, is there an issue tracking this?

2024-10-11 02:17 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +> The Build Environment track currently requires a [hosted] build platform.
In https://slsa.dev/spec/v1.0/levels, we have L0. In https://slsa.dev/spec/v1.0/requirements we do not. This table more closely resembles the former so it makes sense to keep it for consistency.

2024-10-11 02:19 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +    image's SLSA Provenance MUST be distributed instead.
#974 is at least one issue that I am aware of.

2024-10-11 02:24 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +| Build agent | A program that interacts with the hosted build platform's control plane from within a running build environment. The build agent must be included in the build image's measurement.
I duplicated this comment later: https://github.com/slsa-framework/slsa/pull/1115/files/4610a2c6f55458a35479c81c9e37bc1a2421d3c9#r1790448929

One use case that I am aware of is to provision a VM, copy scripts over, and then run them remotely (i.e. via ssh).

2024-10-11 02:30 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +environment, and the compute platform they used.
> That is, we're really expanding what constitutes the full provenance of an artifact: SLSA Build Provenance + build environment provenance (+ source provenance) etc

I like something along these lines. While this isn't the first time, it is the first time that the repetition occurred to me. I'll follow up with a comment in #1010 as I think that issue is related as well.

2024-10-11 02:46 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +    the build image producer outputs provenance describing this process.
I think that we are in agreement then?
> the build image producer outputs provenance describing this process.

This describes the fact that the build image should have a SLSA build provenance attestation generated.

2024-10-11 18:52 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +producer secrets, provenance signing).
We're using the definition of build platform according to our current [build model](https://slsa.dev/spec/v1.0/terminology#build-model), which includes the infrastructure, to my understanding. What is the distinction between infrastructure and build platform you're drawing? Do you mean the compute platform, per the definition in this doc?

But perhaps we're interpreting the L3 requirements differently? My understanding based on the [Unforgeable](https://slsa.dev/spec/v1.0/requirements#provenance-unforgeable) requirement at L3 is that the build platform is trusted to handle these sensitive operations, but it must not be the case that the _tenant_/build itself can access the secrets and provenance signing.

2024-10-11 19:15 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Build agent | A program that interacts with the hosted build platform's control plane from within a running build environment. The build agent must be included in the build image's measurement.
Tracking this in #1185 .

2024-10-12 00:30 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    MUST be generated and distributed (e.g., via a [VSA]).
Tracking this in #1185

2024-10-12 00:31 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    image's SLSA Provenance MUST be distributed instead.
I think the source track has started a pretty good discussion on this, we might want to eventually convert that section into its one page of the spec.

2024-10-14 12:59 UTC, TomHennen commented on docs/spec/draft/attested-build-env-levels.md
> +    image's SLSA Provenance MUST be distributed instead.
Added a note to https://github.com/slsa-framework/slsa/issues/1148#issuecomment-2411165979 to try and capture this.

2024-10-14 16:20 UTC, zachariahcox commented on docs/spec/draft/attested-build-env-levels.md
> +    Provenance for the selected build image MUST be automatically verified.
> MUST be automatically verified.
If it must be, do we have to say what about the image is verified? 
Just the VSA's "build level 2" claim about the build image?

2024-10-14 16:20 UTC, zachariahcox commented on docs/spec/draft/attested-build-env-levels.md
> +    MUST be generated and distributed (e.g., via a [VSA]).
> SLSA Provenance verification MUST be generated and distributed

This is a VSA'd VSA! 
Neat. 

In practice, I wonder if it would typically be a mega VSA that checks provenance on the entire SBOM and the build image.

2024-10-14 16:20 UTC, zachariahcox commented on docs/spec/draft/attested-build-env-levels.md
> +Provides evidence that a build image was built from the advertised
is it also the case that we're including this build image as one of the "components" or dependencies of any artifacts built using the image? 
It seems to me that the answer should be "yes", but just checking!

2024-10-15 15:21 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    MUST be generated and distributed (e.g., via a [VSA]).
It could be a VSA'd VSA :D Or a regular SLSA -> VSA step, depending on what's available from the build image producer. 

> What is the subject for this attestation? The artifact produced?

I'm expecting the subject for this attestation will be the same as the subject for the _verified_ SLSA Provenance, i.e., the build image that us being instantiated.

> Why does the verification need to happen before instantiation? 

We want to be able to ensure that a build _won't_ run in a problematic/unexpected/compromised environment before the build runs, rather than detect issues with the build image used to spin up the VM/container after the fact.

2024-10-15 15:41 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +### BuildEnv L2: Attested build environment instantiation
You raise a really valid point. I think we need to think more carefully about the different requirements for containers vs VMs. I'll open up an issue to track this.

2024-10-15 15:46 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +### BuildEnv L2: Attested build environment instantiation
Tracking this in #1192

2024-10-15 15:47 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    image's SLSA Provenance MUST be distributed instead.
I tagged #974 issue to associate it with this track, so we're going to use that to track any related to discussion to this.

2024-10-15 15:48 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +environment, and the compute platform they used.
I think we can use #974 to track this. @arewm please let me know if you disagree.

2024-10-15 15:55 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Quote | (Virtual) hardware-signed data that contains one or more (virtual) hardware-generated measurements. Quotes may additionally include nonces for replay protection, firmware information, or ot
Just so I know whether this is resolved, would you like to see anything additional here? Should I add a link to the specification doc?

2024-10-15 15:58 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +| Build image producer | The party that creates and distributes build images. In practice, the build image producer may be the hosted build platform or a third party in a bring-your-own (BYO) build i
Which "party" are you referring to here? The new role of build image producer or the third party in the BYO case?

2024-10-15 16:07 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +exist for the build image, while higher levels provide increasing
We're trying pretty hard not to introduce a circular dependency between the two tracks right now. So in the per-level requirements, we do state which Build track level the artifacts needs to be (via the build platform requirements), but the BuildEnv track doesn't currently support the Build track.

2024-10-15 21:41 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +Provides evidence that a build image was built from the advertised
Agreed, the answer should be yes. I'm tracking this in #1195

2024-10-15 21:49 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    Provenance for the selected build image MUST be automatically verified.
Currently we say that it's the SLSA Provenance what needs to be verified, i.e. it's signature + contents. You're right though, that it could be the VSA if the build image Provenance isn't published. I'm tracking this change in #1196

2024-10-15 22:01 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    guest kernel, build agent, build executor, and root filesystem (e.g.,
Tracking the windows environment question in #1198

2024-10-15 22:35 UTC, TomHennen approved these changes
This is an amazing start.

I think we can continue to iterate on this draft in other issues & PRs.

Thanks Marcela!

2024-10-15 22:36 UTC, TomHennen commented
FYI updated title to indicate this is draft!

2024-10-18 20:20 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +producer secrets, provenance signing).
Sounds good.

2024-10-18 20:22 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +producer secrets, provenance signing).
Ah, right. https://slsa.dev/spec/draft/terminology 

The build platform includes the control plane which is where this information resides.

2024-10-18 20:23 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +| Quote | (Virtual) hardware-signed data that contains one or more (virtual) hardware-generated measurements. Quotes may additionally include nonces for replay protection, firmware information, or ot
You can add a link. I went ahead and resolved the thread.

2024-10-19 03:24 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +| Build image producer | The party that creates and distributes build images. In practice, the build image producer may be the hosted build platform or a third party in a bring-your-own (BYO) build i
The party that creates and distributes the build images. When related to the build track, I would assume that this is the producer, but the working seems like it is a specific build platform.

2024-10-19 03:25 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +exist for the build image, while higher levels provide increasing
I don't think that we need to add a circular dependency. This track can depend on the build track, but the build track doesn't need to depend on the build environment track.

That doesn't mean that the build environment track cannot support increasing confidence in the isolation that the build platform claims.

2024-10-21 13:05 UTC, arewm commented on docs/spec/draft/attested-build-env-levels.md
> +    MUST be generated and distributed (e.g., via a [VSA]).
I don't see any need to have a VSA'd VSA. One could simply produce multiple VSAs as well.

> We want to be able to ensure that a build won't run in a problematic/unexpected/compromised environment before the build runs, rather than detect issues with the build image used to spin up the VM/container after the fact.

Is this not just an implementation detail? We want to know whether an artifact was built in an environment provisioned by a SLSA conformant build image. It doesn't matter whether this verification happens before instantiation or after as long as we can trust the post-verification to be able to determine the suitability of the build environment. 

This would, of course, likely be harder to do for verifying the environment of the trusted control plane. Are there any common tools/processes that can perform this verification AND generate the VSA before instantiation?

2024-10-21 16:41 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +exist for the build image, while higher levels provide increasing
Tracking this in #1210

2024-10-21 16:43 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +    MUST be generated and distributed (e.g., via a [VSA]).
I'm tracking this as part of #1169

2024-10-21 17:02 UTC, marcelamelara commented on docs/spec/draft/attested-build-env-levels.md
> +producer secrets, provenance signing).
Tracking this in #1211

2024-10-21 18:18 UTC, arewm approved these changes
Thanks for this draft content. Many of the topics that I have raised have moved to issues. Partially for my reference (because there were so many threads), I think the conversation has moved here:
* Potential clarification for hosted terminology: #947 
* Which parts of the build system should this apply to: #1211
* Clarifications of where/how to use provenance vs VSA: #974; #1148 
* Missing figure: #1165 
* Consistency of terminology/definitions: #1177 (additionally, build image producer should be explicit about the party/parties involved https://github.com/slsa-framework/slsa/pull/1115#discussion_r1790394534)
* Agent-less build environments: #1185 
* Connection between build and build environment track: #1210 
* Attestation flow including how/when to verify: #1169
* VM and container differentiation: #1192

2024-10-21 19:08 UTC, merged