slsa.dev v2.0 - Major overhaul
slsa-framework/slsa pull request #113
Opened 2021-07-27 17:44 UTC by devmoran

- Adds custom page template and styling
- Adds new documentation structure
- Creates updated project overview

|   Page|   Screenshot|
|---|---|
|  Overview | ![image](https://user-images.githubusercontent.com/4757853/127200260-bb1ac463-8798-4d27-866f-fdeeeb01930b.png)  |
| Security levels  |  ![image](https://user-images.githubusercontent.com/4757853/127200298-92c53d3d-1cee-40f3-a74f-4bacb477506a.png) |
|  Requirements |  ![image](https://user-images.githubusercontent.com/4757853/127200312-841279a6-6f9e-4282-ac6f-b4dddc1a17dd.png) |
| Example of use |![image](https://user-images.githubusercontent.com/4757853/127200347-ff505192-c024-4a3e-8466-a537233ae76e.png) |
| Get involved |![image](https://user-images.githubusercontent.com/4757853/127200359-cbea45b7-1e08-4901-82fc-07709e61b3ca.png) |

2021-07-27 20:02 UTC, MarkLodato requested changes
Thanks, @devmoran! The PR is difficult to review, so I think it makes sense to split into smaller ones.

I just sent out #114 to do the file renames. The directory must be named `docs/` since that is the only name supported by GitHub Pages. I also moved the CNAME and _config.yaml files into there as well, which again is required.

Could you base your changes off that? You might want to also squash all your changes into a single commit, but it's up to you.

Splitting it further, e.g. style changes vs content changes, is up to you. We can see how big the diff is.

2021-07-28 17:15 UTC, devmoran commented
No problem @MarkLodato, I'll get this split out once #114 is merged.

2021-07-29 14:07 UTC, MarkLodato requested changes
I think this looks really great! Thanks so much for your work!

I'll be OOO until Monday, so I wanted to leave some early feedback now. Feel free to merge if others approve.

2021-07-29 14:12 UTC, inferno-chromium commented on README.md
> +SLSA is currently in alpha. The framework is ready-to-use. It’s in use by Google and is constantly being improved.
yes should remove both and instead maybe something like "We encourage the community to try SLSA levels incrementally and share experience or problems they encounter" (feel free to improve wording).

2021-07-29 14:14 UTC, inferno-chromium commented on README.md
> +## Maintainers
I would prefer to not have this section, we should just keep the openssf wg and calendar invite info. We can add a contributors section if we want to show the list of people that made this happen. But maintainers sections makes it feel less included, so we want to encourage community contributions.

2021-07-29 14:15 UTC, inferno-chromium commented on SLSA/index.md
> +An open source security framework to describe and verify what integrity looks like, giving anyone working with software a common language and a way to work at scale.
This new definition has been slightly confusing to me, i really liked the old version we had ?

2021-07-29 14:54 UTC, devmoran commented
Thanks @MarkLodato and @inferno-chromium for the notes and feedback. I'll address them all individually (there's a couple I want to discuss with Steven next week once he's back from vacay), but otherwise I'll incorporate these changes into the new separated PRs.

2021-07-30 08:57 UTC, closed without merging