slsa.dev 2.0 (PR 1/x): Content and structure updates
slsa-framework/slsa pull request #118
Opened 2021-07-30 18:05 UTC by devmoran

- Adds subpages and content
- New docs/index.md
- Updates project README

To be followed by a PR for layout and styling updates

2021-07-30 18:16 UTC, inferno-chromium approved these changes

2021-07-30 18:16 UTC, inferno-chromium commented on README.md
> +SLSA is currently in alpha. The framework is ready-to-use. It’s in use by Google and is constantly being improved.
lets fix this "ready-to-use" as discussed in comment in another pr.

2021-07-30 18:16 UTC, inferno-chromium commented on README.md
> +[Kim Lewandowski](https://github.com/kimsterv), [Mark Lodato](https://github.com/MarkLodato), [Tom Hennen](https://github.com/TomHennen), and [many others](https://github.com/slsa-framework/slsa/grap
break into bullet points,
add https://github.com/joshuagl from vmware
and https://github.com/jchestershopify from shopify as well.

2021-07-30 18:16 UTC, inferno-chromium commented on README.md
> +### Joining the working group
I think @kimsterv created the biweekly slsa meetings - "Aug 11 at 9am PT. It's on the OpenSSF community calendar"
https://www.google.com/calendar/event?eid=NjIycXNoOHBtbDhuNTJiNjlmaWk5ZjU5ZWVfMjAyMTA4MTFUMTYwMDAwWiBzNjN2b2VmaHA1aTlwZmx0YjVxNjduZ3Blc0Bn

we should link to that.

2021-07-30 18:16 UTC, inferno-chromium commented on docs/getinvolved.md
> +-   SLSA is part of the [OpenSSF Digital Identity Working Group](https://github.com/ossf/wg-digital-identity-attestation). Join the [mailing list](https://groups.google.com/forum/#!forum/ossf-wg-deve
same comment as above.

2021-08-02 14:01 UTC, MarkLodato requested changes
Thanks, Dev! Sorry for so many comments - it's a big PR! :-D

2021-08-02 16:38 UTC, devmoran commented on README.md
> +# SLSA (salsa) is Supply-chain Levels for Software Artifacts
We added this as a. A pronunciation guide (it's not otherwise intuitive) and b. A search indexing hack for if people search for 'that salsa thing so and so was talking about'.
Happy to remove if you think it's confusing and misleading.

2021-08-02 16:57 UTC, devmoran commented on docs/example.md
> +[threats, risks, and mitigations in the open source ecosystem]: https://github.com/Open-Source-Security-Coalition/Open-Source-Security-Coalition/blob/master/publications/threats-risks-mitigations/v1.
Down a rabbit hole trying to work out why this is happening.
It's autoformatting on save. I've found [this](https://github.com/prettier/prettier/issues/3835) which suggests the issue might be to do with Commonmark but I don't understand why others are not experiencing the same problem. 
At this point not sure the best way to resolve (other than to turn them into `[Links](like this)`, but will keep trying.

2021-08-02 17:17 UTC, devmoran commented on docs/index.md
> +A security framework to describe and verify supply chain, giving anyone working with software a common language and a way to work at scale.
@peterkwells let's bring this back to the team

2021-08-02 17:40 UTC, MarkLodato commented on README.md
> +# SLSA (salsa) is Supply-chain Levels for Software Artifacts
OK. Maybe add in quotes `("salsa")` as a hint that it's a pronunciation guide? Might also be good to keep the "pronounced "salsa") in the paragraph, but either way is OK by me.

2021-08-02 17:43 UTC, MarkLodato commented
Regarding the link renaming, we're using [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) instead of prettier since the former is less opinionated.

2021-08-03 11:55 UTC, stevenif commented on docs/index.md
> +A security framework to describe and verify supply chain, giving anyone working with software a common language and a way to work at scale.
(should be "supply chain integrity", typo. @devmoran could you re-add?)

@MarkLodato @inferno-chromium rationale for the changes: 
we'd wanted to really use this top of page real estate to be a little more inclusive of the non-technical audiences while presenting SLSA's initial value proposition, reducing some of the complexity, being a little more accessible than the base version. and to use a tone/style that's a little more everyday, a bit of a lowered barrier to entry that might help more users adopt it.

it still has to hit certain keywords ("supply chain integrity"), but with the new design it also needs to be less 'explain everything precisely' and more a lead in to the rest of the page, which will follow up and do that job progressively. so, we'd thought to touch on the idea of consensus ("a common language"), the multiple audiences ("anyone working with software", but without risking being exclusive by naming roles), and incrementality ("a way to work at scale").

peter and i had worked on a couple of further variants for consideration, that attempt to bring in a little more of the _why_ behind SLSA into this value proposition - though these are pending at the mo, and could change following all the work you've been doing in the goals workshops:

**A security framework from source to service, giving anyone working with software a common language for increasing levels of software security and supply chain integrity.**

**A security framework to reduce the risk of using third party software, giving a common language for levels of security and supply chain integrity.**

2021-08-03 14:41 UTC, inferno-chromium commented on docs/index.md
> +A security framework to describe and verify supply chain, giving anyone working with software a common language and a way to work at scale.
I like this - "A security framework from source to service, giving anyone working with software a common language for increasing levels of software security and supply chain integrity.". @MarkLodato wdyt, this one is crisp and punchy!

2021-08-03 14:44 UTC, inferno-chromium commented
@devmoran - looks like linter is failing.
Can you please do that definition update (see comment above) and these minor lint fixes

```
docs/getinvolved.md:3 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h4]
docs/getinvolved.md:7 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h3; Actual: h4]
docs/levels.md:3 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h4]
docs/levels.md:53 MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "○ = required unless there is a..."]
docs/requirements.md:3 MD001/heading-increment/header-increment Heading levels should only increment by one level at a time [Expected: h2; Actual: h4]
use_cases.md:80:1 MD005/list-indent Inconsistent indentation for list items at the same level [Expected: 4; Actual: 6]
use_cases.md:81:1 MD005/list-indent Inconsistent indentation for list items at the same level [Expected: 4; Actual: 6]
Error: Process completed with exit code 1.
```

2021-08-03 14:46 UTC, MarkLodato commented on docs/index.md
> +A security framework to describe and verify supply chain, giving anyone working with software a common language and a way to work at scale.
Got it. Thanks for explaining! That helps a lot. I also like the variant @inferno-chromium mentioned.

I'll toss in one more option to consider (or to mix in):

_A security framework to prevent software tampering, giving the industry a common language for increasing levels of protection._

2021-08-03 18:21 UTC, MarkLodato commented
I pushed a few cleanup commits but otherwise LGTM. Thanks, Dev and company!

2021-08-03 18:21 UTC, MarkLodato approved these changes

2021-08-03 18:21 UTC, merged

2021-08-03 18:21 UTC, inferno-chromium commented
Thanks @devmoran and @MarkLodato !