content: draft: Harden 'safe-expunging-process'
slsa-framework/slsa pull request #1203
Opened 2024-10-16 15:18 UTC by TomHennen

fixes #1135

Hardens the 'safe-expunging-process' by:

1. Suggesting that SCSs should document and log changes when possible.
2. SCSs should use multi-party approval when possible

Also clarifies that some of these changes may need to be kept private to comply with local laws.

2024-10-16 15:18 UTC, TomHennen commented
@adityasaky I'd also like your input here.

2024-10-16 15:19 UTC, trishankatdatadog approved these changes
Don't see anything controversial

2024-10-16 23:43 UTC, adityasaky reviewed
I'm still a bit curious what this may end up looking like. In addition to the experiences @zachariahcox and others have had at GitHub, GitLab, etc., I wonder if something like this has ever come up within the LF for https://git.kernel.org/ or so? Is there a public guide for dealing with these scenarios that we can leverage for this?

2024-10-16 23:43 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +The Safe Expunging Process MUST be documented and describe how requests and actions are tracked and SHOULD log the fact that content was removed.
Should they log _privately_ the content that was removed as well? is there an expectation of being able to _prove_ that only the content they were legally supposed to remove was removed, even if they can only do so for internal parties / auditors?

2024-10-16 23:43 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +The Safe Expunging Process MUST be documented and describe how requests and actions are tracked and SHOULD log the fact that content was removed.
I guess this is hard to answer if the information that must be removed is something personal (say PII the person in question doesn't want a cloud SCP to hold on to even privately)...

2024-10-17 14:34 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +The Safe Expunging Process MUST be documented and describe how requests and actions are tracked and SHOULD log the fact that content was removed.
I think we're quite constrained here.  Different legal environments have different requirements.  If you think about [national security letters](https://en.wikipedia.org/wiki/National_security_letter) and their non-disclosure requirement, you could imagine a similar mechanism being used for a takedown request.  Of course, we need to think beyond just US law.  One could _imagine_ (I am not a lawyer!) [this Australian law](https://www.homeaffairs.gov.au/about-us/our-portfolios/national-security/lawful-access-telecommunications/assistance-and-access-overview) being used to require a change without logging it.

Additionally, requiring this logging mechanism would likely require a lot of new code and systems to be written, which would constrain implementers.  Maybe that's OK for SLSA L3, but it seems like a lot to ask for SLSA L2.  How readily do we want this to be adoptable?  How much do we want to delay the release and adoption of the source track while we get an answer to this question and implementations built?

2024-10-17 19:26 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +The Safe Expunging Process MUST be documented and describe how requests and actions are tracked and SHOULD log the fact that content was removed.
Good points! I agree on not blocking too much on this and on not being very specific about how this is implemented as we can't foresee all scenarios and their variables.

2024-10-17 19:26 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +Safe Expunging Scenarios:
Should we highlight this list isn't exhaustive?

2024-10-17 19:26 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +SCSs SHOULD make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
Thoughts on making this `SHOULD` a `MUST`? I understand why this can't be said for legal takedowns but this scenario (and others like it such as repo renames) seem to have no reason we can't require an announcement? If we can think of reasons, perhaps we list them as examples of when an announcement isn't made?

2024-10-17 20:49 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Safe Expunging Scenarios:
Done!

2024-10-17 20:50 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +SCSs SHOULD make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
Sure.  I also changed SCSs to 'Organizations' since it's likely not the system that will do this but rather the people involved in running it.

2024-10-17 21:11 UTC, adityasaky approved these changes

2024-10-17 21:11 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +SCSs SHOULD make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
Thanks!

2024-10-18 13:41 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +SCSs MAY allow _administrators_ to expunge (remove) content from a repository and its change history without leaving a public record of the removed content.
```suggestion
SCSs MAY allow the organization to expunge (remove) content from a repository and its change history without leaving a public record of the removed content.
```

I'm hoping we can remove this as a general capability of repo admins one day. It's logically going to be "the org" (not just the admins) that make decisions about which data is inappropriate for the repo and must be removed, because the org defines the "intent" of the code.

2024-10-18 13:46 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> -Scenarios that need to be addressed:
this was definitely "things to think about" more than scenarios we know we want to support.

2024-10-18 13:47 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
I've been struggling with this topic recently. 

I'm certainly leaning towards a position that "we wish commit metadata were different" should never be a good enough reason to rewrite history. 
Commit shas are the foreign keys of package registries. Changing them causes unknowable damage to an ecosystem's ability to trust itself.

2024-10-18 13:50 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
I think this would only be true for public oss repos. 

```suggestion
Organizations MUST inform all consumers of a repo of these changes when they occur.
Organizations SHOULD provide a means to resolve previous revision IDs to the new revision IDs.
```

2024-10-18 13:52 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
Great point.

2024-10-18 13:53 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +SCSs MAY allow _administrators_ to expunge (remove) content from a repository and its change history without leaving a public record of the removed content.
agreed

2024-10-18 13:54 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
>  ### Repository renames
probably the best case scenario here is to just archive/lock the previous repo name so the attestations stay hosted and available.

2024-10-18 13:55 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
I can add some language to that effect.  "Orgs should strive to avoid rewriting commit metadata and only do so as a last resort" ?

2024-10-18 13:58 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
>  ### Legal Takedowns
In git / merkle-tree-based-VCS, I think this is going to be the only legit reason to consider history rewrites due to the damage they cause to the trustworthiness of a repo. 

In these cases, we should probably build out a health mapping concept. 
These shas XYZ have been updated to ABC. 

We need to somehow say: provenance issued for XYZ is legitimate and still hosted but the revision is no longer available in the repo. 
It will depend on the situation whether packages built on XYZ are still legal.

2024-10-18 16:32 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
I was considering just cutting this "commit metadata rewrites" section. Essentially saying "This process is built for legal challenges. Other uses are hard to justify."

2024-10-18 16:37 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +SCSs MAY allow the organization to expunge (remove) content from a repository and its change history without leaving a public record of the removed content.
We could add a sentence here to help set the tone. 

```
Removing a revision from a repository is similar to deleting a package version from a registry: it's almost impossible to estimate the amount of downstream supply chain impact. 

In version control systems like git, removal of a revision changes the object id of all subsequent revisions that were built on top of it. 

Although there is no "safe" way to do it, it sometimes necessary and there are steps you can take to mitigate the damage.

2024-10-20 02:02 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
I like the idea of reducing the scope of use of safe expunging to legal challenges.

2024-10-21 13:42 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
That works for me.  Would I remove 'Repository renames' too?

2024-10-21 14:01 UTC, zachariahcox commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
good question -- maybe we could move that info into "how source provenance attestation subjects work?"

Essentially the take away should be "if you remove a sha or change the url of a repo, provenance attestations are voided. Also you may have broken the chain of custody for shipped packages."

2024-10-21 21:29 UTC, marcelamelara requested changes
Thanks for these revisions @TomHennen ! I agree with the other reviewers that the safe expunging process should be scoped to legal challenges.

2024-10-23 17:25 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +SCSs MAY allow the organization to expunge (remove) content from a repository and its change history without leaving a public record of the removed content.
Done.

2024-10-23 17:26 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> -Scenarios that need to be addressed:
I think we can resolve this since we've decided to only focus on legal requests for now.

2024-10-23 17:26 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
>  ### Legal Takedowns
Removed metadata/history rewrites entirely, so I think this comment is obsolete.

2024-10-23 17:27 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
Done

2024-10-23 17:27 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Organizations SHOULD provide a means to resolve previous revision IDs to the new revision IDs.
Removed this section entirely.

2024-10-23 17:28 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +changes within a repository (see below for more information on the various scenarios).
I think this is resolved now as we've removed this section?

2024-10-23 18:47 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +A legal takedown request will be addressed by following an agreed-upon process.
I suspect it could be too restrictive.  We've seen some examples in National Security Letters [that forbid disclosure](https://en.wikipedia.org/wiki/National_security_letter#:~:text=NSLs%20typically%20contain%20a%20nondisclosure%20requirement%20forbidding%20the%20recipient%20of%20an%20NSL%20from%20disclosing%20the%20FBI%20had%20requested%20the%20information).  I could see something like that happening here too.

I figure laws are written by governments which have their own agendas and may not care what SLSA says.

2024-10-24 15:29 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +In version control systems like git, removal of a revision changes the object id of all subsequent revisions that were built on top of it.
```suggestion
In version control systems like Git, removal of a revision changes the object IDs of all subsequent revisions that were built on top of it.
```

2024-10-24 15:29 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +Although there is no "safe" way to do it, it sometimes necessary and there are steps you can take to mitigate the damage.
```suggestion
Although there is no "safe" way to do it, it is sometimes necessary and there are steps you can take to mitigate the damage.
```

2024-10-24 15:29 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +Although there is no "safe" way to do it, it sometimes necessary and there are steps you can take to mitigate the damage.
I think it might flow better to swap this sentence with the previous one, especially since the "it" here is different from the "it" the last sentence ends with.

2024-10-24 15:29 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
>  When used as an attack, this is called “repo hijacking” (or “repo-jacking”) and is one of the primary threats source provenance attestations protect against.
Does this text still belong here? I always understood this to mean repo takeovers or name squatting if a popular repository is renamed, and I think we've taken out repo renames from this.

2024-10-24 15:29 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
>  ### Legal Takedowns
If we have only one scenario, I wonder about reframing the section to say it's for legal takedowns only. OTOH, if we foresee adding scenarios, that'd create more work then, so we can punt until we're ready to publish and see if we still only have one scenario?

2024-10-24 15:29 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +The takedown request MUST be addressed by following an agreed-upon process.
This agreed-upon process is the same as the documented safe expunging process mentioned above, right? If so, perhaps this could be combined or refer to it?

2024-10-24 15:29 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +This process and the resulting logs MAY be private to both prevent calling attention to potentially sensitive data (e.g. PII) or to comply with local laws
```suggestion
The application of the safe expunging process and the resulting logs MAY be private to both prevent calling attention to potentially sensitive data (e.g. PII) or to comply with local laws
```

Also, could this say something to the effect of "It must be as transparent / public as possible within the constraints of complying with local laws and regulations and protection of sensitive data (e.g. PII)." I think, as it's written, it's easy to default to making these actions fully private rather than a best effort at transparency?

2024-10-24 15:50 UTC, mlieberman85 commented on docs/spec/draft/source-requirements.md
> +Although there is no "safe" way to do it, it sometimes necessary and there are steps you can take to mitigate the damage.
I think we need to be clearer also with no "safe" way. I understand we're using quotation marks around safe to indicate irony but I think it is easy for it to get confused especially since above we call it safe expunging process.

Maybe switching to something like

> Although there is no completely safe way to do it

Or we if we think even that is confusing maybe we call it something other than safe expunging process. Given that this is part of a specification it will be potentially interpreted in ways we can't anticipate, so anything we can do to clarify would be great.

2024-10-24 17:08 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +This process and the resulting logs MAY be private to both prevent calling attention to potentially sensitive data (e.g. PII) or to comply with local laws
Honestly my preference is to accept your suggestion but leave it otherwise unchanged.  Setting up all the mechanisms for this will be very difficult.  If we say "must be as transparent/public as possible" we _will_ get questions like "how do we quantify that?", "what counts as transparent?", etc...

I'd prefer to err on the side of being less prescriptive here so that folks can more easily adopt.

2024-10-24 17:36 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +The takedown request MUST be addressed by following an agreed-upon process.
Yeah, there's lots of duplication.  I've re-written a bunch and should have addressed this.

2024-10-24 17:37 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
>  ### Legal Takedowns
I've reworked the whole thing and only cover legal takedowns.  There's now a section for 'Warning' where we tell folks the problems they're going to encounter and then a section for 'Process' where we talk a bit more about what to do.

2024-10-24 17:39 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +This process and the resulting logs MAY be private to both prevent calling attention to potentially sensitive data (e.g. PII) or to comply with local laws
I did add something that says they SHOULD disclose if possible, which is hopefully easy enough?

2024-10-24 17:47 UTC, adityasaky approved these changes
Some minor language suggestions but I think this looks good!

2024-10-24 17:47 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +this can break downstream consumers ability to refer to source they've already integrated into their products.
```suggestion
and this can break downstream consumers ability to refer to source they've already integrated into their products.
```

nit

2024-10-24 17:47 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +It may be the case that the specific set of commits targeted by the takedown can be expunged in ways that do not impact revisions which can mitigate these problems.
```suggestion
It may be the case that the specific set of changes targeted by the takedown can be expunged in ways that do not impact consumed revisions, which can mitigate these problems.
```

nit: making language a bit more generic and highlighting that "revisions" is the consumed ones from the previous sentence.

2024-10-24 17:54 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +this can break downstream consumers ability to refer to source they've already integrated into their products.
So I was really trying to explain why it's bad that the object ID changes.

So maybe something more like:
```suggestion
, breaking downstream consumers ability to refer to source they've already integrated into their products.
```

2024-10-24 18:41 UTC, adityasaky commented on docs/spec/draft/source-requirements.md
> +this can break downstream consumers ability to refer to source they've already integrated into their products.
Looks good. Follow up nit I just noticed: `breaking downstream consumers' ability to`, with the possessive apostrophe.

2024-10-24 20:51 UTC, marcelamelara commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
@TomHennen Is there an issue tracking the repo renaming discussion?

2024-10-24 20:55 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +Organizations MUST make the fact of these changes public when they occur (e.g. an issue, announcement, or other mechanism).
No, I didn't create one.  It sounded as though we could drop it until we needed to resolve it.  Should I create one anyways?

2024-10-24 20:59 UTC, marcelamelara reviewed
I think this process is much clearer now, thanks @TomHennen ! I have one remaining question about the multi-party approval.

2024-10-24 20:59 UTC, marcelamelara commented on docs/spec/draft/source-requirements.md
> +It may be the case that the specific set of changes targeted by the takedown can be expunged in ways that do not impact consumed revisions, which can mitigate these problems.
Nit: I don't think we've used the term takedown anywhere before, so adding this for clarity

```suggestion
It may be the case that the specific set of changes targeted by a legal takedown can be expunged in ways that do not impact consumed revisions, which can mitigate these problems.
```

2024-10-24 20:59 UTC, marcelamelara commented on docs/spec/draft/source-requirements.md
> +SCSs SHOULD require multi-party approval for any changes made under this process.
This requirement isn't entire clear. Who are these multiple parties? And how are they authorized to approve a legal takedown?

2024-10-24 21:33 UTC, TomHennen commented on docs/spec/draft/source-requirements.md
> +SCSs SHOULD require multi-party approval for any changes made under this process.
Reworded this.  Hopefully the new words are better?

2024-10-24 23:56 UTC, marcelamelara approved these changes
Thank you for these final wording changes @TomHennen ! LGTM

2024-10-25 01:21 UTC, zachariahcox approved these changes
This looks good to me and I recommend merging it. 

We will need to come back at some point to review a real life expungement and see what can actually be accomplished to here. How smooth a process can we make it in git? 

I'm also not sure the scs can be on the hook for enforcing that the data removals were for legal reasons. 
Generally I think "the owner of the intellectual property in the repo (the root repo owner, in gh terms) can remove data. They should only do this for legal or privacy reasons due to the risk of severe reputational consequences (damage to artifact chain of custody)." Ie: it's indistinguishable from a repo hijack so you should have a good reason.

2024-10-25 15:37 UTC, TomHennen commented
> This looks good to me and I recommend merging it.

Thanks!

> 
> We will need to come back at some point to review a real life expungement and see what can actually be accomplished to here. How smooth a process can we make it in git?

Agreed.  We'll probably want similar feedback for the entire build track.  Once we're in the RC phase (hopefully soon!) we can try to elicit that sort of feedback?

> 
> I'm also not sure the scs can be on the hook for enforcing that the data removals were for legal reasons. Generally I think "the owner of the intellectual property in the repo (the root repo owner, in gh terms) can remove data. They should only do this for legal or privacy reasons due to the risk of severe reputational consequences (damage to artifact chain of custody)." Ie: it's indistinguishable from a repo hijack so you should have a good reason.

Filed #1222 to track.

2024-10-25 15:37 UTC, merged