content: source track: address org threats
slsa-framework/slsa pull request #1236
Opened 2024-11-18 16:05 UTC by zachariahcox

fixes: https://github.com/slsa-framework/slsa/issues/1178

I'm not sure how much we need this threats.md section. 
We already have a generic blurb here that covers much the same topic: https://github.com/slsa-framework/slsa/blob/5fea409bc055bb0e593950b23a256422ee8b3ba5/docs/spec/draft/about.md#what-slsa-doesnt-cover

2024-11-19 13:46 UTC, TomHennen reviewed
Just the one comment, otherwise this looks great!

2024-11-19 13:46 UTC, TomHennen commented on docs/spec/draft/threats.md
> +<details><summary>The organization changes the intent of the repository and creates a malicious revision</summary>
What about this...

```suggestion
<details><summary>The organization intentionally creates a malicious revision</summary>
```

Rationale: the "changes the intent of the repository" may be a distraction.  Folks might think "this thing still does compression so the major intent of the repo is the same"

2024-11-22 15:42 UTC, adityasaky commented on docs/spec/draft/threats.md
> +<details><summary>The organization intentionally creates a malicious revision</summary>
Is there a reason to switch the terminology to "organization" from "producer"? Organization seems narrower to me, and the figure also uses producer.

2024-11-25 13:50 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +<details><summary>The organization intentionally creates a malicious revision</summary>
that's a good question. 
My idea was to align with the "entity that determines the intent of the source," because "sudden change of intent" is really the attack vector here.

2024-11-25 13:59 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +<details><summary>The organization intentionally creates a malicious revision</summary>
I started a conversation in slack. Copied here: 

https://openssf.slack.com/archives/C03NUSAPKC6/p1732542950838849?thread_ts=1732542830.795929&cid=C03NUSAPKC6

The threats diagram uses the term "producer" in the source threats section, but is not one of the [defined terms for the proposed source track](https://github.com/slsa-framework/slsa/blob/4a5c7e682c304f73a9d2501d3ec0c819648c346f/docs/spec/draft/source-requirements.md#definitions)

At least to me, "producer" doesn't capture what we mean here.
"producer" seems like it must be akin to "organization" in our source track terminology, but there are other actor-based threats against the source that do not require a compromised organization (IE: "contributors" and "reviewers" also "produce" source.) 

The source track needs to talk about several kinds of actors with roles [described here](https://github.com/slsa-framework/slsa/blob/4a5c7e682c304f73a9d2501d3ec0c819648c346f/docs/spec/draft/source-requirements.md#source-roles). The only entity that could be described as the sole "producer" would be the org, which defines the intent of the software and the rules to enforce it.

2024-11-25 15:51 UTC, arewm commented on docs/spec/draft/threats.md
> +<details><summary>The organization intentionally creates a malicious revision</summary>
A producer can be an individual or an organization. I think it makes sense to keep it general.

2024-12-03 22:26 UTC, TomHennen approved these changes

2024-12-03 22:39 UTC, adityasaky reviewed
this isn't a complete review because I wasn't sure if more changes are coming, so I'm submitting this for visibility for now.

2024-12-04 05:28 UTC, trishankatdatadog commented on docs/spec/draft/threats.md
> +Trustworthiness scales with transparency, and consumers SHOULD push their vendors to follow transparency best-practices.
"Transparency" is unfortunately an overloaded word in our world. WDYM specifically in this context?

2024-12-04 05:28 UTC, trishankatdatadog commented on docs/spec/draft/threats.md
> +*Mitigation:* The producer can require pre-approval for all changes.
This new language is actually more confusing than the last one. What's a "pre-approval"?

2024-12-04 05:28 UTC, trishankatdatadog commented on docs/spec/draft/threats.md
> +*Mitigation:* The produce must ensure that no actor is able to control or influence multiple accounts with review privileges.
```suggestion
*Mitigation:* The producer must ensure that no actor is able to control or influence multiple accounts with review privileges.
```

2024-12-04 05:28 UTC, trishankatdatadog commented on docs/spec/draft/threats.md
> +Control of the robot and an actors own legitimate account is enough to exploit this vulnerability.
Confusing. The solution goes into another problem, but does not prescribe a solution for that. Best to separate the latter out IMHO.

2024-12-04 05:28 UTC, trishankatdatadog commented on docs/spec/draft/threats.md
> +Solution: Do not allow such exceptions.
Who should not allow such exceptions? The SCS, the org, or someone else?

2024-12-04 05:28 UTC, trishankatdatadog commented on docs/spec/draft/threats.md
> +Solution: The producer can use higher-permission-level rulesets (such as organization-level) to prevent repository-level tampering.
Have we defined "rulesets" in our terminology?

2024-12-04 14:37 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Trustworthiness scales with transparency, and consumers SHOULD push their vendors to follow transparency best-practices.
oof, that's a good callout. 

I propose that I mean: 
* open source
* open build
* open policies
* published "definitions of correctness."

2024-12-04 14:40 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +*Mitigation:* The producer can require pre-approval for all changes.
```suggestion
*Mitigation:* The producer requires approval of all changes before they are accepted.
```

2024-12-04 14:41 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +*Mitigation:* The producer can require pre-approval for all changes.
is that a clearer? pre-approval does sound like you're applying for a car loan lol

2024-12-04 14:43 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Solution: The producer can configure branch protection rules on the `main` branch.
I think in many ways this section is duplicative of other sections. 

We could just say: 
```
*Threat*: source threats!
*Mitigation*: SLSA source track! <url>
```

2024-12-04 14:45 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +A best practice would be to required pre-approval of any changes via a change management tool (such a as GitHub pull request).
```suggestion
A best practice is to require approval of any changes via a change management tool before they are accepted into the source.
```

2024-12-04 14:46 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Control of the robot and an actors own legitimate account is enough to exploit this vulnerability.
I think we can just cut it. This is very duplicative of other sections in the source track.

2024-12-04 14:49 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Control of the robot and an actors own legitimate account is enough to exploit this vulnerability.
```suggestion
Solution: The producer must require strongly authenticated user accounts and ensure that all accounts map to unique persons. It must not be possible for one actor to exploit robot actors that possess review privileges. 
```

2024-12-04 14:51 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Solution: Do not allow such exceptions.
```suggestion
Solution: The producer adjusts the rules to prohibit such exceptions.
```

2024-12-04 14:55 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +If X is allowed to become reachable from the protected branch, the content may become available in secured contexts, such as developer machines and vulnerable to exploits.
```suggestion
If X is allowed to become reachable from the protected branch, the content may become available in secured environments such as developer machines.
```

2024-12-04 14:56 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Solution: The producer can use higher-permission-level rulesets (such as organization-level) to prevent repository-level tampering.
```suggestion
Solution: The producer can configure higher-permission-level rules (such as organization-level GitHub Rulesets) to prevent repository-level tampering.
```

2024-12-04 15:28 UTC, TomHennen commented on docs/spec/draft/threats.md
> +Solution: The producer can configure branch protection rules on the `main` branch.
Note that this page discusses lots of threats to the build and doesn't just defer to the SLSA Build Track.

The general purpose of this page, AIUI, was to centralize all the various threats in one place and direct folks elsewhere as needed.

2024-12-04 15:29 UTC, TomHennen commented
If we merge this before 1.1 goes out will that make it harder to remove this from the 1.1 release?  Have we decided we want to include this in the 1.1 release (fine with me at this point)?

2024-12-04 21:13 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +*Example:* The [libxz attack](https://access.redhat.com/security/cve/CVE-2024-3094) and the intentional sabotage of [colors.js and faker.js](https://fossa.com/blog/npm-packages-colors-faker-corrupted
@TomHennen I think we missed the suggestion here ☝️

2024-12-04 21:15 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Trustworthiness scales with transparency, and consumers SHOULD push their vendors to follow transparency best-practices.
@TomHennen I think SLSA tooling gives you a way to unilaterally improve trust when the source and builds are open source. This is possible independently of whether or not the producer has something to lose.

2024-12-04 21:23 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +*Threat:* A producer intentionally creates a malicious revision with the intent of harming their consumers.
@TomHennen what if we update this to cover both: 

```suggestion
*Threat:* A producer intentionally creates a malicious revision (or a VSA issuer intentionally creates a malicious attestation) with the intent of harming their consumers.
```

The mitigation for both is a clearer -- you cannot.

2024-12-04 21:27 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +For example, a consumer may choose to only consume source artifacts from repositories that have a high score on the OSSF Scorecard.
```suggestion
Ultimately, consumers must decide which producers are trusted to produce artifacts and which issuers are trusted to produce VSAs. 
```

We could redirect from here over to "verifying platforms".

2024-12-04 21:30 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +*Example:* The [libxz attack](https://access.redhat.com/security/cve/CVE-2024-3094) and the intentional sabotage of [colors.js and faker.js](https://fossa.com/blog/npm-packages-colors-faker-corrupted
```suggestion
*Example:* A producer with an otherwise good reputation decides suddenly to produce a malicious artifact with the intent to harm their consumers. 
```
This is simpler. wdyt @TomHennen ?

2024-12-04 21:32 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Trustworthiness scales with transparency, and consumers SHOULD push their vendors to follow transparency best-practices.
I left two suggestions. wdyt @trishankatdatadog @TomHennen ?

2024-12-04 21:33 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Solution: The producer can configure branch protection rules on the `main` branch.
Potentially then most of these examples should link to relevant sections of the relevant tracks. Maybe we'll take it as a todo.

2024-12-04 21:35 UTC, zachariahcox commented on docs/spec/draft/threats-overview.md
> +that source revisions are not modified as they pass between development stages.
this wording aligns better with the build integrity section below.

2024-12-04 21:38 UTC, zachariahcox commented on docs/spec/draft/threats.md
> --->
we could add another section here like 
```
*threat*: A member of the producer's organization acts against the intent of the producer.
```
We could say this is when "the producer UNintentially ships bad code."

2024-12-04 21:50 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Intermediate revisions don't count as being reviewed and are not added to the protected context (such as the `main` branch).
```suggestion
In this configuration, intermediate revisions are not considered to be approved and are not added to the protected context (e.g. the `main` branch).
With git version control systems this is called a "squash" merge strategy.
```

2024-12-04 21:53 UTC, zachariahcox commented on docs/spec/draft/threats.md
> -trusted persons" as a proxy for "intent of the software producer".
I do not think we should use "two trusted persons" as a proxy for producer intent. We should probably say "the documented change process for the source" if we must, but I prefer just "the intent".

2024-12-04 22:39 UTC, zachariahcox commented
> If we merge this before 1.1 goes out will that make it harder to remove this from the 1.1 release? Have we decided we want to include this in the 1.1 release (fine with me at this point)?
> 
> @lehors thoughts?

@TomHennen! Potentially I am off base -- is 1.1 going to be different from the /draft folder? 
I think this kind of change should go out with the most recent version of the source track, whichever that is 👍 
It was not my intention to add items to the 1.1 release if that is different than the drafts folder.

2024-12-05 07:59 UTC, lehors commented
> > If we merge this before 1.1 goes out will that make it harder to remove this from the 1.1 release? Have we decided we want to include this in the 1.1 release (fine with me at this point)?
> > @lehors thoughts?
> 
> @TomHennen! Potentially I am off base -- is 1.1 going to be different from the /draft folder? I think this kind of change should go out with the most recent version of the source track, whichever that is 👍 It was not my intention to add items to the 1.1 release if that is different than the drafts folder. In the meantime I'll update the title to talk about drafts spec instead of 1.1

I'm glad @TomHennen remembers that we need to get 1.1 finalized. I was going to bring that up myself looking at this PR. Unfortunately, we don't have a very clean way of working on several versions in parallel.

The plan was to only work in the draft folder and when all 1.1 issues have been addressed to create a new folder for 1.1 selecting (manually) from the draft what is relevant. Of course this is really only practical if the differences are fairly coarse (like whole files to be left out). If the content of some files start changing in ways that are only relevant for the next version this operation becomes quite impractical.

If we want to go ahead and merge this, I will need to create the 1.1 folder before, and from then on every change made for 1.1 will have to be made in both folders (1.1 and draft). Not ideal but doable.

2024-12-05 22:31 UTC, TomHennen commented
> > > If we merge this before 1.1 goes out will that make it harder to remove this from the 1.1 release? Have we decided we want to include this in the 1.1 release (fine with me at this point)?
> > > @lehors thoughts?
> > 
> > 
> > @TomHennen! Potentially I am off base -- is 1.1 going to be different from the /draft folder? I think this kind of change should go out with the most recent version of the source track, whichever that is 👍 It was not my intention to add items to the 1.1 release if that is different than the drafts folder. In the meantime I'll update the title to talk about drafts spec instead of 1.1
> 
> I'm glad @TomHennen remembers that we need to get 1.1 finalized. I was going to bring that up myself looking at this PR. Unfortunately, we don't have a very clean way of working on several versions in parallel.
> 
> The plan was to only work in the draft folder and when all 1.1 issues have been addressed to create a new folder for 1.1 selecting (manually) from the draft what is relevant. Of course this is really only practical if the differences are fairly coarse (like whole files to be left out). If the content of some files start changing in ways that are only relevant for the next version this operation becomes quite impractical.
> 
> If we want to go ahead and merge this, I will need to create the 1.1 folder before, and from then on every change made for 1.1 will have to be made in both folders (1.1 and draft). Not ideal but doable.

I wonder if at this point we can just wait and include the source track (and the build track if it's ready).  We've waited this long, and there don't seem to be that many outstanding issues elsewhere.  By trying to separate them now we'd probably just cause ourselves more work for less gain. WDYT?

2024-12-06 06:54 UTC, lehors commented
> I wonder if at this point we can just wait and include the source track (and the build track if it's ready). We've waited this long, and there don't seem to be that many outstanding issues elsewhere. By trying to separate them now we'd probably just cause ourselves more work for less gain. WDYT?

You mean to skip 1.1? That would solve the problem of course. It's true that the more time goes by the less relevant it is.

2024-12-09 15:07 UTC, TomHennen commented
> > I wonder if at this point we can just wait and include the source track (and the build track if it's ready). We've waited this long, and there don't seem to be that many outstanding issues elsewhere. By trying to separate them now we'd probably just cause ourselves more work for less gain. WDYT?
> 
> You mean to skip 1.1? That would solve the problem of course. It's true that the more time goes by the less relevant it is.

Not so much "skip" as _include_ the source track in 1.1.  New tracks [are supposed to go](https://github.com/slsa-framework/slsa/blob/main/docs/spec-stages.md#:~:text=MINOR%20version%20when,Versioning%20Rules.) in minor releases

2024-12-10 19:56 UTC, TomHennen commented
We had a long, _long_, chat about tracks, threats pages, etc... at yesterday's meeting.  Do we still like this PR or do we want to simplify it some?  I have no opinion at this time.

2024-12-18 07:21 UTC, trishankatdatadog commented on docs/spec/draft/threats.md
> +For example, a consumer may choose to only consume source artifacts from repositories that have a high score on the OSSF Scorecard.
Sorry for late reply. Why do consumers even need to know which producers are trusted to produce artifacts (source code, I imagine, in this case)? Couldn't they just get away with the Source Track VSA from the issuer, and call it a day so long as its subjects/outputs (e.g., source code) matches the inputs to the next step (e.g., build)?

2024-12-18 07:21 UTC, trishankatdatadog commented on docs/spec/draft/threats.md
> +Trustworthiness scales with transparency, and consumers SHOULD push their vendors to follow transparency best-practices.
Left a comment down there...

2025-03-03 18:05 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Trustworthiness scales with transparency, and consumers SHOULD push their vendors to follow transparency best-practices.
good ideas. I'll incorporate these.

2025-03-03 18:24 UTC, zachariahcox commented on docs/spec/draft/threats.md
> -[future version](current-activities.md#source-track). In the meantime, the
I think this was a broken link? I have added a section to future-directions to target.

2025-03-03 18:24 UTC, zachariahcox commented on docs/spec/draft/future-directions.md
> +## Source Track
added the "objective" section from source-requirements.md, updated the verbs to be future tense. 
this is to be the target of future-direction links.

2025-03-03 18:26 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Solution: The proposed change still requires two-person review in the upstream context even though it received two-person review in another context.
I updated the words to be a little more precise. 
In general, I'd expect reviews to be transitive for some situations. but yeah, if your org thinks this is a problem, then this is how you'd fix it.

2025-03-03 18:29 UTC, zachariahcox commented
Howdy friends! I have updated this PR to reference only 1.1 legal concepts. 
I also incorporated the most recent feedback from reviewers (thank you!)

There were a lot of structural changes to the repo and I ultimately rebased these smallish patches. 
Apologies if your comments fell off! I think I got to all of them but please let me know.

cc: @TomHennen @adityasaky @lehors @trishankatdatadog @arewm

2025-03-03 19:16 UTC, TomHennen commented on docs/spec/draft/threats.md
> -[future version](current-activities.md#source-track). In the meantime, the
agreed

2025-03-03 19:45 UTC, TomHennen requested changes
Looking good!

2025-03-03 19:45 UTC, TomHennen commented on docs/spec/draft/threats.md
> +*Threat:* A producer intentionally creates a malicious revision (or a VSA issuer intentionally creates a malicious attestation) with the intent of harming their consumers.
```suggestion
*Threat:* A producer intentionally creates a malicious revision with the intent of harming their consumers.
```

I think the VSA Issuer note should probably go in https://slsa.dev/spec/draft/threats#verification-threats (below) as it applies everywhere, and the 'producer' of the VSA isn't aligned with the producer being discussed here: https://slsa.dev/spec/draft/terminology#:~:text=Examples-,Producer,-A%20party%20who

2025-03-03 19:45 UTC, TomHennen commented on docs/spec/draft/threats.md
> +*Threat:* Submit code to the source repository without another person reviewing.
I think this leaves out that the code being submitted is malicious.

the vast majority of unreviewed changes aren't malicious.

Perhaps this can be rephrased as 

```suggestion
*Threat:* Malicious code submitted to the source repository.
```
And then the (partial) mitigation is "The producer requires approval of all changes before they are accepted".

2025-03-03 19:45 UTC, TomHennen commented on docs/spec/draft/threats.md
> +A common vector for this attack is to take over a robot account with the permission to contribute code.
optional: Robot accounts are discussed below so this seems somewhat redundant.  Suggest removing.

2025-03-03 19:45 UTC, TomHennen commented on docs/spec/draft/threats.md
> +Solution: The producer must require strongly authenticated user accounts and ensure that all accounts map to unique persons.
Trying to scope this down some for folks.  There's no way an org can ensure all GitHub accounts map to unique persons.  They really just need it to be the case for people that can approve code.

```suggestion
Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
```

2025-03-03 19:45 UTC, TomHennen commented on docs/spec/draft/threats.md
> +Solution: Require review for such changes.
Optional: 

```suggestion
Solution: Require review for such changes or ensure all changes relevant to the robot's behavior require review.
```

E.g. imagine if the Robot is a GHA that generates code.  If the workflow that runs that code is reviewed, and the generation tool is reviewed, then it could be safe?

2025-03-03 19:45 UTC, TomHennen commented on docs/spec/draft/threats.md
> +Adversary submits a malicious executable named `evil.md` and a code review is not required due to the exception.
On first reading it wasn't clear to me what the actual problem was here.

```suggestion
Adversary submits a malicious executable masquerading as a documentation file, `help.md`. A code review is not required due to the exception, and a user (or another workflow) is then induced to _execute_ `help.md` and are compromised.
```

2025-03-03 19:45 UTC, TomHennen commented on docs/spec/draft/threats-overview.md
> +that source revisions are not modified as they pass between development stages.
I think this is 'fine', but we do lose the introduction of the concept of 'intent' (which we reference later) which isn't quite the same as 'process'.  I'd argue the process is one of the ways the producer tries to ensure their intent is tracked, but it's not really what the end user cares about.

I'd also probably argue that the build process is somewhat different and they don't _need_ to mirror each other.  To some extent the source is the closest approximation of the org's intent, and then we just rely on the build system to mechanically transform that source faithfully.

2025-03-03 21:27 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +*Threat:* Submit code to the source repository without another person reviewing.
That's fine with me too. 
Generally, it's hard to say whether a commit is malicious, and "exploitable" ends up being just as bad.

2025-03-03 21:33 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +A common vector for this attack is to take over a robot account with the permission to contribute code.
That's probably fine. I _think_ these are different threat models, but not sure if the difference is worth calling out, or if these two blurbs are doing so. 
This one is about gaining access to two accounts with `write` and the robots one is about gaining access to an account with `bypass`. 

The mitigation for the first is _hard_ to execute and protect against. You'd have to somehow prevent account takeovers. 

The mitigation for the robots one is easier to execute (just run some kind of automation with a poisoned payload, usually) and protect against-- just do not allow any account to bypass code review requirements.

2025-03-03 21:33 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Solution: Require review for such changes.
(commented on the other thread)

2025-03-03 21:39 UTC, TomHennen commented on docs/spec/draft/threats.md
> +A common vector for this attack is to take over a robot account with the permission to contribute code.
Right.  I guess I'll leave it to you?

2025-03-03 21:40 UTC, TomHennen commented on docs/spec/draft/threats.md
> +Solution: Require review for such changes.
I suppose I think there are legitimate use cases for bypassing code review by robots, and I think it is possible to do safely?

I also don't think we have to address that here and now, especially if we don't have a fully fleshed out framework for doing so.

2025-03-03 21:47 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Solution: Require review for such changes.
I think eventually we'd need to say something like:
## autobypasses
for some security postures, this practice increases risk because due to threat of account takeover.
For others it's way to reduce risk because security patches are applied faster (or whatever the bot does)

2025-03-03 21:53 UTC, zachariahcox commented
I'm going to take another crack at the source threats overview. I mostly left it alone today from where it was in december.

2025-03-04 17:43 UTC, adityasaky commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
```suggestion
Solution: The producer must require all users trusted to write to the repository and approve changes to be strongly authenticated and ensure they map to unique persons.
```

I took a stab at generalizing this, WDYT?

2025-03-04 17:53 UTC, TomHennen commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
To be honest, I think 'credentials' obscures the meaning.

'credentials' can be interpreted as a specific thing (e.g. password, cryptographic key, badge, etc).  I have _many_ of those things, and I use multiple of them when interacting with systems like GitHub.  Further those systems rarely restrict use based on the way a user authenticated.

2025-03-04 18:08 UTC, adityasaky commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
That's a good point. Maybe:

```
The producer must require anyone trusted to write to the repository and approve changes to be strongly authenticated and ensure the credentials they use to authenticate themselves map to unique persons.
```

Perhaps an example as well after this?

2025-03-04 18:17 UTC, TomHennen commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
1. I think we need "write to the repository _or_ approve changes"
2. I think the use of credentials later in the sentence is still misplaced.

The ACLs systems implement are still based on accounts (users).  User auth to those accounts with their credentials, but the way you ensure they map to a single person is at the account level (since that's where the ACLs are).

Now I'm sure that in some systems account == credential, but those systems may have an even _harder_ (impossible) time enforcing this mapping.  What we really want is that no unique person can appear to be two or more people.

2025-03-04 18:41 UTC, adityasaky commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
> I think we need "write to the repository or approve changes"

you're right.

> The ACLs systems implement are still based on accounts (users). User auth to those accounts with their credentials, but the way you ensure they map to a single person is at the account level (since that's where the ACLs are).

I agree with this where the point of enforcement is a hosted platform that is part of the SCS. I worry this doesn't apply when we're considering other types of systems such as gittuf, that is also listed in the source spec. I do see your point about the word "credentials" not applying well, though.

2025-03-04 18:46 UTC, TomHennen commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
I guess when considering a system like gittuf the goal is still that "No unique person is able to take actions that would otherwise require two or more people."

I don't think talking about the credential actually helps in that case.  As written it's still possible to have two credentials that map to the same person (and in gittuf that probably has to happen in case folks lose a key, are using multiple hardware backed keys, etc?).  Alternatively the advise to implementors is "don't allow a unique person to have more than one credential in the ACL"

2025-03-04 18:50 UTC, TomHennen commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
Oh, but also!  This is _not_ the source requirements doc, this is just _an example_ of a solution for how this can be addressed.

In the future this will link the source reqs doc.

(maybe that needs to be more clear)

2025-03-04 22:43 UTC, adityasaky commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
>Oh, but also! This is not the source requirements doc, this is just an example of a solution for how this can be addressed.

Oh wow, I'd missed that when I paged things in for this PR!

> I guess when considering a system like gittuf the goal is still that "No unique person is able to take actions that would otherwise require two or more people."
>
> I don't think talking about the credential actually helps in that case. As written it's still possible to have two credentials that map to the same person (and in gittuf that probably has to happen in case folks lose a key, are using multiple hardware backed keys, etc?). Alternatively the advise to implementors is "don't allow a unique person to have more than one credential in the ACL"

You're right in that "credentials" doesn't necessarily address it for the gittuf case, which was also my concern for "account". But, given this isn't actually part of the source track, I think we can close this thread. :)

2025-03-07 17:44 UTC, adityasaky approved these changes

2025-03-07 17:44 UTC, adityasaky commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
If two accounts under consideration must map to unique persons, don't we have also have the case that each person is mapped to at most one account?

That said, I think it is better to put the emphasis on the persons involved being distinct rather than the accounts, it would partially address the concern I had in the other thread I think.

2025-03-07 20:02 UTC, arewm commented on docs/spec/draft/threats.md
> +With git version control systems this is called a "squash" merge strategy.
While it is likely harder to detect/enforce, another reasonable mitigation is just to review all commits. There could even be automation which flags content from earlier commits that have been removed/overwritten in order to try to detect this type of attack.

2025-03-07 20:27 UTC, TomHennen commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
I think the trick is that it should still be possible for anonymous folks to send PRs.  _They_ don't need to be unique.  But you'd want to unique and trusted people to be involved.

I also wonder how much of this nuance is actually needed.  These are just example solutions, they're not really meant to be completely bulletproof (I don't think?).

Another alternative is we just punt and say "SLSA doesn't address this yet".  But that seems annoying. :p

2025-03-08 02:15 UTC, arewm commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
If an anonymous person sends a PR then this can be protected against by _requiring_ 2-party reviews. I don't know how to word that though.

You are probably right that this much nuance isn't needed here. This might even be addressing a separate threat?

2025-03-08 02:18 UTC, arewm commented on docs/spec/draft/future-directions.md
> +The organization determines the intent of the software in the repository, what Source level should apply to the repository, and administers technical controls to enforce that level.
It is okay for it to not be _precise_ here, but I don't think it should be confusing. I interpret this blurb as an indication of the identities that might be involved in the source track. If that is the case, we should clarify that it relates to the organization hosting the version control system?

2025-03-10 14:38 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +-   The code is open source and has a sufficiently large user-base that malicious changes are likely to be detected.
I guess both to some extent. 
Expert code review may be "required" to approve something 
into the main branch, but prs are often reviewed by non-authorized (but maybe informed) reviewers too. 
Those extra eyes help.

Maybe this should be a time-to-mitigation claim. 
`With more sets of eyes, the length of time that a vulnerability exists in the repo is reduced.`

2025-03-10 14:48 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +-   The code is open source and has a sufficiently large user-base that malicious changes are likely to be detected.
or maybe 

```The repo is open source with an active user-base. High numbers of engaged users increase the likelihood that bad code is detected during code review and reduce the time-to-detection when bad code makes it in.

2025-03-10 15:03 UTC, arewm commented on docs/spec/draft/threats.md
> +-   The code is open source and has a sufficiently large user-base that malicious changes are likely to be detected.
I think commenting about a reduced time to detection feels right. We can also make an additional comment about an "expert" review as a potential additional mitigation.

How about 
```suggestion
-   The code is open source and has a large engaged user-base. Time to detect and remediate malicious changes to the code base are reduced.
-   The organization requires that all code is vetted by expert reviewers before revisions are accepted.
```

2025-03-10 15:13 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
> An account that creates a revision request doesn't necessarily need to have write permissions. 

Not to get tooooooo in the weeds, but in most implementations an open requires write permissions to created the proposed merge commits for CI.

2025-03-10 15:15 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
I'm not sure how to tighten this one up. 
I feel like the threat, mitigation and example are all good, but the solution needs work.

2025-03-10 15:15 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +Solution: The producer must require all accounts with 'write' and 'approval' permissions to be strongly authenticated and ensure they map to unique persons.
I could just adjust it -- "the producer much prevent this kind of thing from happening somehow"

2025-03-10 15:48 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +A common vector for this attack is to take over a robot account with the permission to contribute code.
yeah, I don't like the word mapping here. let me try to remove it.

2025-03-10 15:57 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +With git version control systems this is called a "squash" merge strategy.
that's technically possible, but I would say that getting that right requires multiple squash merge PRs -- you cannot really do it in one shot.

2025-03-10 17:37 UTC, zachariahcox commented on docs/spec/draft/threats.md
> +<details><summary>Commit graph attacks</summary>
@arewm @TomHennen 

I rewrote this section based on y'all's feedback. 

My goal was to remove the wonky git stuff about squashes and focus on reachable revisions following process.

2025-03-11 16:38 UTC, mlieberman85 commented on docs/spec/draft/threats.md
> +<details><summary>Commit graph attacks</summary>
Oh, so one of the things I've done in a previous life was the attestation is actually an attestation of a particular ordering of the commits. so you are attesting to the change not each individual commit so if you roll back a commit it would no longer be valid since you're just attesting to HEAD. with the assumption you're just attesting to old HEAD -> PR/New HEAD

2025-03-11 17:55 UTC, arewm commented on docs/spec/draft/threats.md
> +-   The repo is open source with an active user-base. High numbers of engaged users may increase the likelihood that bad code is detected during code review and reduce the time-to-detection when bad
nit:
```suggestion
-   The repo is open source with an active user-base. High numbers of engaged users may increase the likelihood that bad code is detected during code review and reduce the time-to-detection when bad revisions are accepted.
```

2025-03-11 17:56 UTC, arewm approved these changes
Thanks! I left one nit comment outside of the review.

2025-03-11 18:03 UTC, arewm commented on docs/spec/draft/threats.md
> +<details><summary>Commit graph attacks</summary>
I know some folks that hold this to be a hotly debated and contentious topic. It feels right for it to be required at a higher SLSA level because of the higher protections that it guarantees. Some communities preferences may still prefer to not use this approach preventing the SLSA source level that can be achieved.

2025-03-11 20:49 UTC, zachariahcox commented
Ok! thanks everyone for your input and patience on this one!
I'm going to merge it -- and we'll focus on any followups in the next pr 👍

2025-03-11 20:49 UTC, merged