content: Add 'principle' protecting anonymous contribution in SLSA
slsa-framework/slsa pull request #1249
Opened 2024-12-02 20:25 UTC by TomHennen

As work on the source track progresses the topic of 'identity' comes up quite a bit. There has been some confusion about what this means, that it could be that SLSA intends to require legal identities for all contributors.  That isn't the case.

Many in the open source world prefer to contribute without revealing their 'real' identities as has been practiced for many years. SLSA does not intend to change that.

This PR tries to make it clear that SLSA does not require real identities.

refs #1133

2024-12-02 20:31 UTC, hepwori requested changes
lgtm apart from the one change suggested.

2024-12-02 20:59 UTC, adityasaky commented on docs/spec/draft/principles.md
> +## Support anonymous and pseudonymous contribution
```suggestion
## Support anonymous and pseudonymous contributions
```

2024-12-02 20:59 UTC, adityasaky commented on docs/spec/draft/principles.md
> +While organizations that implement SLSA may chose otherwise, SLSA itself does not require,
```suggestion
While organizations that implement SLSA may choose otherwise, SLSA itself does not require,
```

2024-12-02 20:59 UTC, adityasaky commented on docs/spec/draft/principles.md
> +The legal identity of actor is largely not relevant from a supply chain security perspective.  Further,
I support this. Is it possible to set expectations on how identities are meant to be used across SLSA tracks? I'm reading this entire change like so, but perhaps it could be made explicit here?

> **Reasoning**: Some SLSA tracks (e.g., the source track) use identities to attribute supply chain actions to the actor performing them. These identities need to be *strongly authenticated* and *consistent* (i.e., a developer uses the same unique identity for successive supply chain actions) within the context of the supply chain execution and artifact verification. These properties do not require the identities to be mapped to legal identities.

This is a bit hand wavy (can we define strongly authenticated and consistent etc. better? probably), but this might a) clarify why identities don't need to be legal identities, and b) provide grounding for new track authors on how to think about identities.

2024-12-03 16:29 UTC, TomHennen commented on docs/spec/draft/principles.md
> +The legal identity of actor is largely not relevant from a supply chain security perspective.  Further,
I'm somewhat worried about having the requirements from different tracks seep into the principles (that seems wrong??).

But maybe we can get at it more broadly...

> **Reasoning:** SLSA uses identities for multiple purposes: as a trust anchor for attestations (i.e. who or what is making this claim and do I trust them to do so) or for attributing actions to the actor which took them within the context of the system they're taking them in (e.g. a username, cryptographic signing key, etc...).
> 
> When identities are strongly authenticated and used consistently they can be used for both of these purposes without requiring them to be mapped to legal identities.
> This reflects how identities are often used in open source.  A legal name means much less to projects than the history and behavior of a given handle over time does.

2024-12-03 16:35 UTC, adityasaky commented on docs/spec/draft/principles.md
> +The legal identity of actor is largely not relevant from a supply chain security perspective.  Further,
This looks good to me!

2024-12-03 16:47 UTC, TomHennen commented on docs/spec/draft/principles.md
> +The legal identity of actor is largely not relevant from a supply chain security perspective.  Further,
Updated.

2024-12-03 16:52 UTC, adityasaky approved these changes
LGTM!

2024-12-03 17:08 UTC, hepwori approved these changes
lgtm, thank you!

2024-12-03 19:13 UTC, trishankatdatadog approved these changes

2024-12-04 04:15 UTC, arewm approved these changes
nit:

2024-12-04 04:15 UTC, arewm commented on docs/spec/draft/principles.md
> +When identities are strongly authenticated and used consistently they can be used for both of
What do you mean by "used consistently"? I feel like trying to deduplicate "used" in one sentence and the first seems like a more likely candidate.

Or how about 
```suggestion
When identities are strongly authenticated and used consistently they can be leveraged for both of
```

2024-12-04 04:15 UTC, arewm commented on docs/spec/draft/principles.md
> +username, cryptographic signing key, etc...).
```suggestion
username, cryptographic signing key, etc.).
```
No need to have etc and elipses.

2024-12-04 04:15 UTC, arewm commented on docs/spec/draft/principles.md
> +When identities are strongly authenticated and used consistently they can be used for both of
Is there a common definition for "strongly authenticated" here? I assume that private signing keys are a form of this strong authentication?

2024-12-04 14:23 UTC, zachariahcox commented on docs/spec/draft/principles.md
> +username, cryptographic signing key, etc...).
> attributing actions
to the actor which took them within the context of the system they're taking them in (e.g. a
username, cryptographic signing key, etc...).

This sentence is a lot!

maybe it would read more simply as: 

```
... or for attributing actions to an actor. Choice of identification technology is left to the platform that provides the action (e.g. username, cryptographic signing key, etc.).
```

2024-12-04 14:26 UTC, zachariahcox commented on docs/spec/draft/principles.md
> +history and behavior of a given handle over time does.
```suggestion
these purposes without requiring them to be mapped to legal identities.  This reflects how
identities are often used in open source. A legal name means much less to projects than the
history and behavior of a given handle over time does.
```
```suggestion
these purposes without requiring them to be mapped to legal identities.  
This reflects how identities are often used in open source and supports behavior tracking of specific actors over time.
```

2024-12-04 14:26 UTC, zachariahcox commented on docs/spec/draft/principles.md
> +history and behavior of a given handle over time does.
I think the key idea is that a system must have a way for actors to be uniquely identified and have track records.

2024-12-04 14:27 UTC, zachariahcox approved these changes
I left some minor comments, but overall looks good! Thank you!

2024-12-04 14:28 UTC, TomHennen commented on docs/spec/draft/principles.md
> +history and behavior of a given handle over time does.
I don't love "behavior tracking".  Sounds nefarious and like something folks would object to.

2024-12-04 15:36 UTC, TomHennen commented on docs/spec/draft/principles.md
> +When identities are strongly authenticated and used consistently they can be used for both of
There isn't.  Does there need to be?  This principles page isn't setting any specific requirements.

FWIW "Strongly authenticated" is used here: https://slsa.dev/spec/v1.0/threats#:~:text=Mitigation%3A%20Source%20control%20platform%20strongly%20authenticates%20actor%20identity%2C%20timestamp%2C%20and%20parent%20revisions.

We do talk about strong authentication in the source track (where it is a requirement) but it applies to people not services accounts and here we're also talking about services accounts to some extent.

2024-12-04 15:37 UTC, TomHennen commented on docs/spec/draft/principles.md
> +username, cryptographic signing key, etc...).
> > attributing actions
> > to the actor which took them within the context of the system they're taking them in (e.g. a
> > username, cryptographic signing key, etc...).
> 
> This sentence is a lot!
> 
> maybe it would read more simply as:
> 
> ```
> ... or for attributing actions to an actor. Choice of identification technology is left to the platform that provides the action (e.g. username, cryptographic signing key, etc.).
> ```

I like this

2024-12-04 21:53 UTC, mlieberman85 commented on docs/spec/draft/principles.md
> +history and behavior of a given handle over time does.
I think this is where we might want to leave it up to the consumer. I might be OK with using software from completely anonymous contributors but a bank might not be comfortable. There's nothing they can do about it but not use the software. What SLSA does a good job at is helping all end users be able to make the decisions for themselves whereas previously there might not be a good set of data around this.

Also, I agree that behavior can sound a bit bad but maybe "activity tracking" is better? I think the idea though here is nothing in SLSA itself cares whether or not you're anonymous, pseudonymous, or using a government issued legal identity. However, tracking that is important and both maintainers and end users might care whether or not a project all of a sudden has 10 people with all pseudonymous identities with no known activity history start contributing to a project.

2024-12-05 22:29 UTC, TomHennen commented on docs/spec/draft/principles.md
> +history and behavior of a given handle over time does.
I've added a bit to make it clear organizations can impose additional requirements on identities if they wish.

Since this isn't a requirements doc but just trying to emphasize that SLSA does allow anonymous and pseudonymous contributions I think the ability to track those identities over time is best left to the tracks that need it?

2024-12-06 03:50 UTC, arewm commented on docs/spec/draft/principles.md
> +When identities are strongly authenticated and used consistently they can be used for both of
Maybe it doesn't. The previous paragraph seemed more generic and easier to apply to multiple tracks. This paragraph feels more specifically tailored to the source track.

I'll still approve the PR even with this feedback.

2024-12-06 18:14 UTC, adityasaky commented on docs/spec/draft/principles.md
> +to an actor. Choice of identification technology is left to the platform that provides the
```suggestion
to an actor. Choice of identification technology (e.g. username, cryptographic signing key, etc.) is left to the specific instantiation of the SLSA specification.
```

I don't know if this is the right phrasing but I was if we want something other than "platform" as the identity provider.

2024-12-09 14:51 UTC, TomHennen commented on docs/spec/draft/principles.md
> +When identities are strongly authenticated and used consistently they can be used for both of
Honestly, I cannot manage to navigate GitHub's history to find the version you did like. :/

Do you happen to have a suggestion for what to change here?  Which parts seem specific to the source track?

2024-12-09 15:15 UTC, mlieberman85 commented on docs/spec/draft/principles.md
> +history and behavior of a given handle over time does.
Sure, seems reasonable.

2024-12-09 15:15 UTC, adityasaky commented on docs/spec/draft/principles.md
> +to an actor. Choice of identification technology is left to the platform that provides the
This looks good to me!

2024-12-09 15:15 UTC, mlieberman85 approved these changes
LGTM

2024-12-11 15:15 UTC, arewm commented on docs/spec/draft/principles.md
> +When identities are strongly authenticated and used consistently they can be used for both of
I think the current form looks great. Resolving the thread.

2024-12-11 15:16 UTC, TomHennen commented
Alright, everyone seems happy, merging. :)

2024-12-11 15:16 UTC, merged