Set page title to "Overview"; avoid custom header.
slsa-framework/slsa pull request #125
Opened 2021-08-06 13:44 UTC by MarkLodato

For index.md, manually set the page title to "Overview" rather than relying on the h1 ("Improving artifact integrity..."). This has two
effects:
1. The title in the titlebar is now "Overview", which reads better.
2. We no longer need a custom header.html template, and instead can  include the page in _config.yml.

Otherwise, there is no impact on how the page looks.

@devmoran Could you please review this change? In particular, is it OK to change the page title, or is there some SEO reason why we wanted it to be what it was before? Thanks!

2021-08-06 14:00 UTC, TomHennen requested changes

2021-08-06 14:00 UTC, TomHennen commented on docs/_layouts/home.html
> +We cut out all feature of the minima "home":
nit: 'minimal' ?

2021-08-06 14:00 UTC, TomHennen commented on docs/index.md
> +title: Overview
Does this just wind up rendering as 'Overview' in a tab?

Would 'SLSA Overview' be preferred?

2021-08-09 12:40 UTC, MarkLodato commented on docs/index.md
> +title: Overview
It renders as "Overview | SLSA".

2021-08-09 12:41 UTC, MarkLodato commented on docs/_layouts/home.html
> +We cut out all feature of the minima "home":
The theme name is "minima".

2021-08-09 12:42 UTC, MarkLodato commented
Setting to draft so we don't accidentally submit without @devmoran's approval.

2021-08-09 12:58 UTC, devmoran approved these changes
LGTM!

2021-08-09 13:10 UTC, TomHennen approved these changes

2021-08-09 13:12 UTC, MarkLodato commented
Thanks for the reviews!

2021-08-09 13:12 UTC, merged