Adds use cases to website documentation
slsa-framework/slsa pull request #137
Opened 2021-08-20 11:29 UTC by devmoran

### Preview here
https://devmoran.github.io/slsa/use-cases/

- Breaks each use case out into its own subpage for clarity and focus
- Adds preamble and goals to each use case
- Revises some of the #99 content

2021-08-20 19:06 UTC, TomHennen requested changes

2021-08-20 19:06 UTC, TomHennen commented on docs/use-cases/publishing-a-software-package.md
> +A software development organisation (e.g. BarInc) wants to protect consumers of their software from malicious changes to the BarImage container image they publish. They also want to prevent any negat
optional: These two things seem rather different.  Would it make sense to split them into two separate sentences?  I think goals here are all independent.

2021-08-20 19:06 UTC, TomHennen commented on docs/use-cases/publishing-a-software-package.md
> +This approach doesn’t protect their users from a published BarImage being tampered with after production. There may be other ways to address these concerns such as code signing after verification, ti
Should "being tampered with after production" be "being tampered with after publication" ?

2021-08-20 19:06 UTC, TomHennen commented on docs/use-cases/publishing-a-software-package.md
> +This approach doesn’t protect their users from a published BarImage being tampered with after production. There may be other ways to address these concerns such as code signing after verification, ti
"time-of-use verification" it occurs to me that we haven't really defined this elsewhere.  I wonder if it should just link to 'consuming third party software' ?

2021-08-20 19:06 UTC, TomHennen commented on docs/use-cases/package-repository-accepting-a-software-package.md
> +[Determine how to convey these keys]: https://github.com/slsa-framework/slsa/issues/101
I think we lost the links to these three things

2021-08-20 19:16 UTC, TomHennen commented on docs/use-cases/publishing-a-software-package.md
> +| **Users** | Developers                               |
I think 'Developers' may not be specific enough?  Maybe 'Developers publishing a software package' ?

2021-08-23 16:01 UTC, peterkwells commented on docs/use-cases/consuming-third-party-software.md
> +-   Only importing the siftware artifact if all the above checks pass
1. agh, typo. Sorry!
2. Checking back to the original the intent here is everything in the bulleted list so reading it that way is what we want

2021-08-23 16:01 UTC, peterkwells commented on docs/use-cases/consuming-third-party-software.md
> +A software development organisation developer (e.g. FooCo) using third party software (e.g. HowDo developed by HowInc) wants to ensure it hasn’t been tampered with before using it. They could take th
1. This also relates to the comment below about "organisation" <> "developer". We're going to switch to "developer" so that both individuals and individuals-in-organisations feel included. 
2. Will change "They could take the following steps to check, protecting the organisation from the software.." to "They could take these next steps to protect the organisation from the software..." to improve the second sentence

2021-08-23 16:01 UTC, peterkwells commented on docs/use-cases/consuming-third-party-software.md
> +    -   Determine how to convey these keys
We're trying to keep the main text of the use cases without open action items as we believe that will work for more users. That can mean putting the open action items into the limitations section, as they're important to know. I'll move the <determine how to convey these keys> bit to the limitation section and link to the related issue: https://github.com/slsa-framework/slsa/issues/101

2021-08-23 16:01 UTC, peterkwells commented on docs/use-cases/consuming-third-party-software.md
> +-   Establishing a secure control-point that any HowDo users must pass through to be used
will change  "Establishing a secure control-point that any HowDo users must pass through to be used" to "Establishing a secure control-point that any HowDo versions/artifacts must pass through to be used"

2021-08-23 16:01 UTC, peterkwells commented on docs/use-cases/consuming-third-party-software.md
> +-   Having the control-point check the candidate HowDo against its provenance, checking it -   against the policy mentioned above
Another typo that we've let snuck in, sorry, will delete

2021-08-23 16:01 UTC, peterkwells commented on docs/use-cases/index.md
> +How an organisation can protect their users from malicious damage to the software they publish
that rephrasing is very nice, we will use that

2021-08-23 16:01 UTC, peterkwells commented on docs/use-cases/index.md
> +How an organisation can work with third party software suppliers to reduce risk in a supply chain
as ^, we'll switch to "developer"

2021-08-23 16:01 UTC, peterkwells commented on docs/use-cases/index.md
> +How a repository can protect their users from malicious changes to uploaded software artifacts
we like that :)

2021-08-23 16:01 UTC, peterkwells commented on docs/use-cases/publishing-a-software-package.md
> +A software development organisation (e.g. BarInc) wants to protect consumers of their software from malicious changes to the BarImage container image they publish. They also want to prevent any negat
happy to split sentences

2021-08-23 16:01 UTC, peterkwells commented on docs/use-cases/publishing-a-software-package.md
> +This approach doesn’t protect their users from a published BarImage being tampered with after production. There may be other ways to address these concerns such as code signing after verification, ti
1. Yep
2. Nice spot on an undefined term, will change to that

2021-08-23 16:02 UTC, peterkwells commented on docs/use-cases/package-repository-accepting-a-software-package.md
> +[Determine how to convey these keys]: https://github.com/slsa-framework/slsa/issues/101
will fix

2021-08-23 16:02 UTC, peterkwells commented on docs/use-cases/publishing-a-software-package.md
> +| **Users** | Developers                               |
we think just keeping "developers" here is best, it feels _right_ to have at least one example that feels like it's for everyone while the title indicates the action they're taking

2021-08-24 09:01 UTC, 06kellyjac commented on README.md
> +## Steering committee
If the steering committee is going to be copied to several different documents I think there should probably be a comment just to remind people to update them all when changing one of them.

2021-08-24 12:47 UTC, TomHennen commented on README.md
> +## Steering committee
Update all the docs they're copied on?

2021-08-24 12:48 UTC, TomHennen commented on README.md
> +## Steering committee
Oh, I'm sorry, I see what you mean.  The steering committee is listed here, in getinvolved.md, etc...

Perhaps we should just have them listed in a single place and then link to that place from elsewhere?

2021-08-24 12:53 UTC, 06kellyjac commented on README.md
> +## Steering committee
Yeah, that would be a good option

Also I'm a bit confused why it looks like the steering committee is being added to `docs/getinvolved.md` in this PR when it seems to be there already...

https://github.com/slsa-framework/slsa/commit/d1180a04b39d60d19369dd1ddd1fd7283e2f7c4d

I must be missing something :thinking:

2021-08-24 12:55 UTC, TomHennen requested changes

2021-08-24 12:55 UTC, TomHennen commented on docs/use-cases/consuming-third-party-software.md
> +-   Requesting HowInc publish the [in-toto SLSA Provenance](https://slsa.dev/provenance) and any additional attestations (such as [source control attestations-(https://github.com/in-toto/attestation/
nit: the source control attestations link is broken.  I think you need to replace the - with [

2021-08-24 12:55 UTC, TomHennen commented on docs/use-cases/publishing-a-software-package.md
> +This approach doesn’t protect their users from a published BarImage being tampered with after publication. There may be other ways to address these concerns such as code signing after verification, [
It occurs to me that 'encouraging use of the SLSA framework by their software consumers.' is basically the same as 'time-of-use verification'.  Maybe we don't need both?  (We should still link to 'consuming-third-party-software')

2021-08-24 13:18 UTC, 06kellyjac commented on docs/requirements.md
> +</table>
Can use markdown tables instead since it's a simple table

```suggestion
| On this page                                        |
| :-------------------------------------------------- |
| [What is SLSA?](#what-is-slsa)                      |
| [Definitions](#definitions)                         |
| [Source requirements](#source-requirements)         |
| [Build requirements](#build-requirements)           |
| [Provenance requirements](#provenance-requirements) |
| [Common requirements](#common-requirements)         |

| Further reading |
| :-------------- |
| [FAQs](/faq.md) |
```

2021-08-25 10:35 UTC, joshuagl commented on docs/requirements.md
> +</table>
Yes please, a Markdown table is much easier to maintain.

2021-08-25 11:56 UTC, joshuagl reviewed
This looks good, thanks @devmoran. I made a few minor suggestions where I think we could use clearer language.

2021-08-25 11:56 UTC, joshuagl commented on docs/getinvolved.md
> +-   [Joshua Lock](https://github.com/joshuagl) - VMWare
```suggestion
-   [Joshua Lock](https://github.com/joshuagl) - VMware
```

2021-08-25 11:56 UTC, joshuagl commented on docs/use-cases/consuming-third-party-software.md
> +-   Requesting HowInc publish the [in-toto SLSA Provenance](https://slsa.dev/provenance) and any additional attestations (such as [source control attestations-(https://github.com/in-toto/attestation/
```suggestion
-   Requesting HowInc publish the [in-toto SLSA Provenance](https://slsa.dev/provenance) and any additional attestations (such as [source control attestations](https://github.com/in-toto/attestation/issues/47)) for HowDo each time it’s released
```

2021-08-25 11:56 UTC, joshuagl commented on README.md
> +-   [Joshua Lock](https://github.com/joshuagl) - VMWare
```suggestion
-   [Joshua Lock](https://github.com/joshuagl) - VMware
```

2021-08-25 11:56 UTC, joshuagl commented on README.md
> +## Steering committee
Agreed, it would be good to have an includes file for the steering committee, if they will be listed in multiple places. Or just list them once and link the the single location.

2021-08-25 11:56 UTC, joshuagl commented on docs/use-cases/consuming-third-party-software.md
> +    -   e.g. on import to a local Docker registory
```suggestion
    -   e.g. on import to a local Docker registry
```

2021-08-25 11:56 UTC, joshuagl commented on docs/use-cases/index.md
> +The following are some typical cases to explore how SLSA compliance can provide protection. In each, we’ve detailed goals that users need to meet, how organisations can use the SLSA framework to help
We should pick en_GB or en_US spellings and try to be consistent, here it's organisation vs. organization.

2021-08-25 11:56 UTC, joshuagl commented on docs/use-cases/package-repository-accepting-a-software-package.md
> +-   Checking new artifacts against the policy above
```suggestion
-   Checking new artifacts and their provenance (as well as any other attestations) against the policy above, ensuring any attestations evaluated by the policy are signed by the publisher's public key
```
I've expanded this to:
a) indicate that artifacts and their provenance are evaluated (as we do in other use-cases)
b) remind folks to verify signed data

2021-08-25 11:56 UTC, joshuagl commented on docs/use-cases/publishing-a-software-package.md
> +-   Having the control-point check the candidate BarImage against its provenance, checking that:
```suggestion
-   Having the control-point check the candidate BarImage against its provenance, checking that – for example:
```
We don't go into much detail of what a policy might look like in the other use-cases. Adding some explicit recommendations here is good, but I wanted to soften the language to better indicate it's a non-exhaustive(?) suggestion.

2021-08-25 11:56 UTC, joshuagl commented on docs/use-cases/consuming-third-party-software.md
> +-   Having the control-point check the candidate HowDo against its provenance, checking it against the policy mentioned above
```suggestion
-   Having the control-point check the candidate HowDo and its provenance (as well as any other published attestations) against the policy mentioned above, ensuring any attestations evaluated by the policy are signed by HowInc's public key(s)
```
Expanded to:
a) indicate that artifacts and their provenance (as well as other attestations) are evaluated
b) remind folks to verify signed data

2021-08-25 15:13 UTC, devmoran commented on docs/requirements.md
> +</table>
Definitely agree on maintainability. 
However, this was a deliberate UI compromise to allow the table to be styled for small, neat yet prominent inline links on the frontend.
This is something we worked up after a conversation with @MarkLodato and @TomHennen about how to link to new sub-pages when they arise. I.e. a pattern that can be used elsewhere.

**Example**
In the future, the 'Further reading' block on this page could take you to 5 or 6 new sub-pages that are not top-level menu items. 

**Happy to accept this suggestion if maintainability/code readability is considered more important by the group,** but would recommend using standard md list styles rather than a table.
Also happy for someone to suggest a different way to style the markdown table!

| State | Img |
|------|-----|
| With html/css table | ![image](https://user-images.githubusercontent.com/4757853/130815171-3f66ee49-7c54-4896-a312-80115757694c.png) |
| md table | ![image](https://user-images.githubusercontent.com/4757853/130815128-30f3c9c6-0875-4c73-9fc9-3672d140fc9b.png) |
| With standard md list styles | ![image](https://user-images.githubusercontent.com/4757853/130816861-27a02e93-64d9-46d6-9598-9d7a1878c8b4.png) |

2021-08-25 15:21 UTC, devmoran commented on docs/use-cases/index.md
> +The following are some typical cases to explore how SLSA compliance can provide protection. In each, we’ve detailed goals that users need to meet, how organisations can use the SLSA framework to help
👍 we'll go for en_US as the language of the internet

2021-08-25 15:33 UTC, devmoran commented on README.md
> +## Steering committee
Agree in principle but sadly the duplication is due to both being md files (Only html files can use includes), and [one of these files](https://github.com/slsa-framework/slsa/blob/89d660d380ca01247592b276db3c18f18ccd42fc/README.md) being outside of the gh-pages published `/docs` folder and [one being inside](https://github.com/slsa-framework/slsa/blob/main/docs/getinvolved.md).

Also yes not sure how it popped up as part of this PR, but rebased and now these changes are excluded.

2021-08-25 15:33 UTC, devmoran commented on docs/use-cases/publishing-a-software-package.md
> +This approach doesn’t protect their users from a published BarImage being tampered with after publication. There may be other ways to address these concerns such as code signing after verification, [
cc @peterkwells

2021-09-01 09:29 UTC, peterkwells commented
@TomHennen do you think this is good to go now, or do we need a steering committee member to review/approve?

2021-09-01 10:35 UTC, joshuagl approved these changes
This LGTM, but as @TomHennen requested changes I'd like his re-review before we merge.

2021-09-01 13:41 UTC, TomHennen commented
Sorry, didn't realize I was blocking this.  LGTM

2021-09-01 13:41 UTC, TomHennen approved these changes

2021-09-01 13:41 UTC, merged