Require config as code at levels L3+
slsa-framework/slsa pull request #141
Opened 2021-08-27 19:26 UTC by TomHennen

* Require build instructions to be tracked at **all** levels.
  * Lets people know how a build was produced.
  * Should support all build methods without requiring architectural changes.
  * If we adopt [this document](https://docs.google.com/document/d/1fLtR5-AfauKlgTvQ1yRrupIZVnX3YqBhAjO_2X3d4qE/edit#heading=h.q2vn2vj1ydg5) as level motivation (#111) then we may only need to require build instructions at level 2+ or 3+.  We can easily relax this requirement later, while making the requirement more strict would be more difficult.
* Require config-as-code at L3+.
  * Allows people to review the details of how builds are performed.
  * Can require changes to how builds are performed to be reviewed by additional parties.
  * Tracks changes to how builds are produced over time.
  * Provides an easier method of writing policy to make sure an artifact followed the build steps you expect (just point at the build config in source control)
  * May require architectural changes in some builders or changes to how users interface with their build service (e.g. Tekton, LUCI, Cloud Build)
* Combine "identifies source" with "identifies entry point".
  * The 'identifies source' requirement was _already_ specific to the top-level build script which was the 'entry point'.
    So there doesn't seem to be a reason to have these as separate requirements.
  * 'Identifies source' might have had an overly broad name since it was only talking about where the top-level build script was, but could have been interpreted to mean "identifies **all** source" (which it did not!).
* Only require "identifies entry point" at L3+.
  * As discussed with 'config-as-code' above, not all build architectures support  singular entry-points that are defined in a script.
  * Requiring 'identifies build instructions' at all levels should cover cases where folks aren't using config-as-code.
* Small updates to provenance examples to make linking easier.

This PR _does not_ take a position on how/if requiring all sources or dependencies be recorded in the provenance. That should
be handled in a different PR addressing  a different issue.

Note #115 suggested the language "require that the provenance identify the independent inputs", but I found "independent inputs" to be fairly broad.  The rest of the text of #115 indicated that this was really about tracking what the build did, so "build instructions" seems to cover the spirit of #115.

fixes #115

2021-08-30 15:26 UTC, msuozzo requested changes

2021-08-30 15:26 UTC, msuozzo commented on docs/requirements.md
> +The build service configuration is defined in source control and drives the build automatically.
> "drives the build automatically"

I'm a little hesitant about requiring there to be automation triggering the build. I think it'd be fine to just limit build configuration to "use this workflow" regardless of how/when it's triggered.

2021-08-30 15:26 UTC, msuozzo commented on docs/requirements.md
> +build config.  If the build does not use config-as-code it MAY list details of the
I feel like this MAY indicates we may not want to require it at lower levels, especially L1. One option would be to make a SHOULD at L1 as it may be more onerous to meet in some situations (e.g. inside build systems that don't expose the workflow to all steps). I think this might even mean our github actions demo wouldn't qualify since it's not always possible to access to correct workflow defintion in actions.

2021-08-30 15:26 UTC, msuozzo commented on docs/requirements.md
> +            "environment": {
not thrilled with advocating for this syntax inside the spec. This was mainly just a way to get build steps encoded in the existing schema but I don't think the intent was for `environment` to permanently host this metadata.

I don't have great alternatives, though.

2021-08-30 15:26 UTC, msuozzo commented on docs/requirements.md
> +              "image": "gcr.io/tekton-releases/..."
not really sure what the `...` is doing here. do you want to give a literal image name?

2021-08-30 15:26 UTC, msuozzo commented on docs/requirements.md
>  <td>✓<td>✓<td>✓<td>✓
as noted above, this might be loosened to suggested at lower levels (maybe just L1)

2021-08-30 15:47 UTC, TomHennen commented on docs/requirements.md
> +build config.  If the build does not use config-as-code it MAY list details of the
What information _do_ we have available about what the builder actually did?

2021-08-30 15:48 UTC, TomHennen commented on docs/requirements.md
> +              "image": "gcr.io/tekton-releases/..."
This was borrowed from https://github.com/tektoncd/chains/blob/main/PROVENANCE_SPEC.md and the actual images are _quite_ long.  I could include the whole thing?

2021-08-30 15:48 UTC, TomHennen commented on docs/requirements.md
> +            "environment": {
Can you expand on what you're worried about?  Maybe I could address that?

2021-08-30 15:54 UTC, msuozzo commented on docs/requirements.md
> +The build service configuration is defined in source control and drives the build automatically.
Is there an alternative phrasing that avoids the implication of automation?

2021-08-30 15:56 UTC, msuozzo commented on docs/requirements.md
> +            "environment": {
afaiu `environment` is really meant to be "env variables" (as can be provided by gha or gcb) but this field was overloaded to provide the container/image by grafeas. advocating for this use in the spec doesn't feel ideal...

2021-08-30 15:57 UTC, msuozzo commented on docs/requirements.md
> +              "image": "gcr.io/tekton-releases/..."
I wasn't clear whether `...` was intentional or meant as an abbreviation. I'd probably include the full names and then `...` the hash values.

2021-08-30 15:59 UTC, msuozzo commented on docs/requirements.md
> +build config.  If the build does not use config-as-code it MAY list details of the
In GCB, effectively nothing. In GHA, a pointer to the *file* that contains the workflow but IIUC no metadata on which workflow from that file.

2021-08-30 16:02 UTC, msuozzo commented on docs/requirements.md
> +              "image": "gcr.io/tekton-releases/..."
I also didn't understand the `container` field (and honestly I'm still not sure I have the right idea). Maybe rename to `name`? (and since this is shadowing the tekton doc, I guess suggest the same upstream?)

2021-08-30 17:12 UTC, TomHennen commented on docs/requirements.md
> +build config.  If the build does not use config-as-code it MAY list details of the
I thought GCB had some API that could give you all sorts of data?  Or is that only available if you're using cloudbuild.yaml?  Does GCB provide _any_ of the things used in the build?  Source repos fetched?  Deps?

In GHA what if we were to just list the file?

In #115 Mark suggested that we should require this information at L1.

What if that were weakened to 'all the details the builder has available'?  That's fine with me, but I get the impression other folks want a lot more detail.

2021-08-30 17:14 UTC, TomHennen commented on docs/requirements.md
> +            "environment": {
So, I didn't mean to say "use this format" I meant this to be an example of how _a_ builder could include these details.  Builders could use whatever format they want, they'd just specify their own type (like how here we're showing 'https://tekton.dev/chains/recipe/buildSteps@v1').

How could I change this to make it clear the level of detail that's being requested without being prescriptive about format (since I _don't_ want to be prescriptive about format).

2021-08-30 17:19 UTC, msuozzo commented on docs/requirements.md
> +            "environment": {
maybe move the `image` up to the top level and remove `container`? Feels like the most concise way to put it.

2021-08-30 17:28 UTC, msuozzo commented on docs/requirements.md
> +build config.  If the build does not use config-as-code it MAY list details of the
> I thought GCB had some API that could give you all sorts of data?

It has some env variables which provide some information but no step metadata.

> Does GCB provide any of the things used in the build? Source repos fetched? Deps?

https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#using_default_substitutions

All metadata is made available after the build is complete via their API.

> In #115 Mark suggested that we should require this information at L1.

That's not my reading of #115 . His wording feels a lot more like a SHOULD, not a MUST.

AFAIK, this sort of requirement was never discussed and imo shouldn't be given how it would prevent the in-build mechanism for L1 we've intended to support.

> What if that were weakened to 'all the details the builder has available'?

imo that's the same as SHOULD and I don't see a compelling reason to portray it as a requirement if it's going to be purposefully incomplete. For example, we handle all other cases of "best effort" here by leaving them blank.

> That's fine with me, but I get the impression other folks want a lot more detail.

At L1? I don't know of anyone who's advocated for this as a requirement at L1.

2021-08-30 19:50 UTC, TomHennen commented on docs/requirements.md
> +build config.  If the build does not use config-as-code it MAY list details of the
It does say 

"At SLSA 1+, **require** that the provenance identify the independent inputs"

In this PR "independent inputs" -> "build instructions" (as explained in the PR description that seems to make the most sense).

Now, we don't have to stick with what the issue suggests, but we should note a departure and why.

If we didn't change "independent inputs" to "build instructions" would GHA and GCB be able to specify their 'independent inputs'?  What would those inputs be?

2021-08-30 19:52 UTC, TomHennen commented on docs/requirements.md
> +The build service configuration is defined in source control and drives the build automatically.
"The build service configuration is defined in source control and drives the build automatically."  -->

"The build service configuration is defined in source control and is executed by the build service."

?

2021-08-30 20:01 UTC, msuozzo commented on docs/requirements.md
> +The build service configuration is defined in source control and drives the build automatically.
maybe "and is used as the build entrypoint"?

2021-08-31 16:48 UTC, msuozzo commented on docs/requirements.md
> +build config.  If the build does not use config-as-code it MAY list details of the
Okay so I'm going to walk back my previous position. I think going from the previous config-as-code requirement to this one does make some sense and ensures we have an accounting of the build process at all levels.

I still think a recommendation could work instead of this requirement but, versioning-wise, I think it'd be safer to leave the more restrictive requirement for now and potentially relax it later than having to do the reverse.

2021-09-01 14:47 UTC, TomHennen commented on docs/requirements.md
> +build config.  If the build does not use config-as-code it MAY list details of the
Gotcha.  Updated PR comment to reflect that.

2021-09-01 15:00 UTC, TomHennen commented on docs/requirements.md
> +            "environment": {
I've simplified the example a bit and made it refer to a _fake_ builder.

I definitely _don't_ want this to dictate the structure that various builders use to record this information.  So if you have some suggestions as to how I can make it clear this will vary from builder to builder that might be best.

2021-09-01 15:01 UTC, TomHennen commented on docs/requirements.md
> +              "image": "gcr.io/tekton-releases/..."
Followed you suggestion regarding ...

As mentioned above I've simplified this.

2021-09-01 15:03 UTC, TomHennen commented on docs/requirements.md
> +The build service configuration is defined in source control and drives the build automatically.
I'm not that hot on using 'entrypoint' here because later we distinguish between 'entrypoint' (a singular field to reference) and 'steps' (details about how the build progressed) as being two different things.  Yet here _both_ of them count as the build instructions.

I think I'll go with "The build service configuration is defined in source control and is executed by the build service." and we can see what others think.

2021-09-01 15:33 UTC, msuozzo commented on docs/requirements.md
> +The identified instructions SHOULD be at the highest level available to the build.
"highest level" is giving me problems. what do you mean by it?

2021-09-01 15:33 UTC, msuozzo commented on docs/requirements.md
> +            "#!/usr/bin/env bash\nset -x\n\ncd src\n\nbuild.sh",
i think entry point has to be just as single executable. maybe just bash since the args look like a bash invocation?

2021-09-01 15:33 UTC, msuozzo commented on docs/requirements.md
> +            "gcr.io/foo-releases/github.com/foobuilder/pipeline/cmd/git-init@sha256:b963...",
nit: maybe "git-checkout" instead of "git-init"

2021-09-01 15:33 UTC, msuozzo commented on docs/requirements.md
>  <td>Identifies entry point
I think this section name needs to change. "Entry point" is used to describe both config as code and in-Providence build instructions so using it to exclusively refer to the former is confusing.

2021-09-01 19:32 UTC, TomHennen commented on docs/requirements.md
> +The identified instructions SHOULD be at the highest level available to the build.
Clarified.

2021-09-01 19:32 UTC, TomHennen commented on docs/requirements.md
> +            "gcr.io/foo-releases/github.com/foobuilder/pipeline/cmd/git-init@sha256:b963...",
Obsolete.  Removed inline examples.

2021-09-01 19:33 UTC, TomHennen commented on docs/requirements.md
>  <td>Identifies entry point
Obsolete.  Removed inline examples which conflicted with this 'entry point'.

2021-09-01 19:36 UTC, msuozzo approved these changes
Looks good!

2021-09-01 19:45 UTC, inferno-chromium commented
@trishankatdatadog @joshuagl @brunodom @david-a-wheeler @mlieberman85 @zakgreant - thoughts on this. we would definitely benefit from 1-2 additional eyes on this requirement review.

2021-09-01 20:03 UTC, joshuagl approved these changes
I made a couple of minor suggestions, but am happy to approve as is. This clarifies a common source of confusion for folks reading SLSA.

2021-09-01 20:10 UTC, TomHennen commented on docs/requirements.md
> +Identifies the top-level instructions used to execute the build.
Done.

2021-09-01 20:10 UTC, TomHennen commented on docs/requirements.md
> +(e.g. if the build it told to run build.sh it should list build.sh and NOT the
Good catch, thanks!

2021-09-02 00:01 UTC, merged

2021-09-27 18:02 UTC, squee1945 commented on docs/requirements.md
> +The build service configuration is defined in source control and is executed by the build service.
I'm trying to understand what this means for something like GCF where the build definition is entirely specified by the service itself (GCF), but is not part of the user's source control at all.

(I realize there are source provenance questions for GCF, but set those aside for the moment.)

2021-09-27 18:15 UTC, TomHennen commented on docs/requirements.md
> +The build service configuration is defined in source control and is executed by the build service.
GCF just builds/runs whatever is in a specific repo right?

My suggestion:

1. Have a recipe.type specific to GCF 'http://google.com/cloud/gcf_recipe/v1' (or whatever)
2. Set recipe.entrypoint to 'gcf_implicit' (or whatever)
3. Put the repo that GCF actually built in materials (should be doing this anyways)
4. Set recipe.definedInMaterial to the index of the repo in #3.

Thoughts?

2021-09-27 18:32 UTC, squee1945 commented on docs/requirements.md
> +The build service configuration is defined in source control and is executed by the build service.
GCF can build a repo, or an arbitrary zip file.

I'm not familiar with the `recipe.*` things - can you point me to a reference?

2021-09-27 18:40 UTC, TomHennen commented on docs/requirements.md
> +The build service configuration is defined in source control and is executed by the build service.
https://slsa.dev/provenance/v0.1#recipe.type

If GCF is building from a zip file it wouldn't qualify at SLSA Level 3 as SLSA Level 2 requires the use of source control https://github.com/slsa-framework/slsa/blob/main/docs/requirements.md#version-controlled

_but_

The way I'd represent building a zip file in the provenance for GCF would probably be very similar:

1. Have a recipe.type specific to GCF 'http://google.com/cloud/gcf_recipe/v1' (or whatever)
2. Set recipe.entrypoint to 'gcf_implicit' (or whatever)
3. Put the path of the zip file and it's hash that GCF actually built in materials (should be doing this anyways)
4. Set recipe.definedInMaterial to the index of the zip file in 3.


So the provenance would basically look the same, but the artifacts built from zip files shouldn't qualify for anything higher than SLSA L1.

2021-09-27 18:45 UTC, squee1945 commented on docs/requirements.md
> +The build service configuration is defined in source control and is executed by the build service.
Okay, so the `recipe.*` parts are within the provenance.

My question is more specifically about the phrase "build service configuration is defined in source control" - in GCF, the build configuration is *not* defined in source control - even in the case of the source being in version control.

2021-09-27 18:49 UTC, TomHennen commented on docs/requirements.md
> +The build service configuration is defined in source control and is executed by the build service.
Right.  I think since GCF is basically a fixed function in that regard (you can think of the build configuration as being as simple as 'gcf <repo>') that it would be completely fine to take the approach I outlined in https://github.com/slsa-framework/slsa/pull/141#discussion_r716932691

2021-09-27 18:53 UTC, TomHennen commented on docs/requirements.md
> +The build service configuration is defined in source control and is executed by the build service.
I think the way to think about it is "With GCF the configuration is defined in the source repo being built."  So all you have to do is point to that repo and say "GCF built this".