Add detailed source requirements.
slsa-framework/slsa pull request #17
Opened 2021-04-07 20:56 UTC by MarkLodato

This PR provides a starting point for discussions of detailed requirements for source systems. It likely does not get everything right, but hopefully it shows the level of detail we're expecting.

2021-04-07 20:58 UTC, MarkLodato commented
One question for @kimsterv and @TomHennen: are we ready to submit such detailed requirements now, or do we still want to hold off?

2021-04-07 21:11 UTC, TomHennen requested changes

2021-04-07 21:11 UTC, TomHennen commented on source-requirements.md
> +SLSA 3, but very old historical revisions before the cutoff were not reviewed
Are we imagining that when the repo adopts SLSA 3 controls that the entire state of the repo will be reviewed?

If not then it's still true that many files in the most recent revision won't have been reviewed.

2021-04-07 21:11 UTC, TomHennen commented on source-requirements.md
> +        -   TBD: Is it acceptable to have a policy on check-in that ensures SLSA
It seems like this will be the only way to say that a repo meets the requirements?  Or do we know of a method that could be used to analyze the content of a repo looking for generated or binary content?

2021-04-07 21:11 UTC, TomHennen commented on source-requirements.md
> +    -   **[Vendoring]** Bulk import of third-party code, such that the change is
I'm wondering how we'd implement this technically.  Would we have to start including paths in the provenance?  foo/bar -> SLSA 3, foo/baz -> SLSA 2 (bulk import of third party code)

2021-04-07 21:11 UTC, TomHennen commented on source-requirements.md
> +    -   **[Multiple Commits]** A "change" may be more than one commit. If
So this suggests that the first commit after adopting SLSA 3 requires reviewing all content in the repo?

That's a pretty high bar...

Maybe we need to have a bootstrapping story too or else people may wind up getting concerned about how they could possibly meet these requirements.

2021-04-07 21:11 UTC, TomHennen commented on source-requirements.md
> +-   **[Two-Person Review]** All changes in the revision's history were agreed to
I think talking about trusted robots might be very helpful here.  E.g. if a trusted robot does a copy of previously reviewed code then maybe it _doesn't_ need review?

2021-04-07 21:11 UTC, TomHennen commented on source-requirements.md
> +## SLSA 2
FWIW I've found this formulation of our internal requirements to be pretty difficult to read.  Could we go with the [L2,L3] tags or something like that?

2021-06-09 20:15 UTC, MarkLodato commented on source-requirements.md
> +SLSA 3, but very old historical revisions before the cutoff were not reviewed
Removed "was reviewed."

2021-06-10 01:01 UTC, MarkLodato commented on source-requirements.md
> +        -   TBD: Is it acceptable to have a policy on check-in that ensures SLSA
Removed this entirely. It's certainly an open question, but for now let's omit it.

2021-06-10 01:02 UTC, MarkLodato commented on source-requirements.md
> +## SLSA 2
Reworded to be the traditional L1, L2 = L1 + ..., L3 = L2 + ....

2021-06-10 01:42 UTC, MarkLodato commented on source-requirements.md
> +-   **[Two-Person Review]** All changes in the revision's history were agreed to
If it's OK with you, I'd like to omit it for now since we're running out of time and this is already taking a long time. We will likely need to add it in a future revision.

2021-06-10 01:42 UTC, MarkLodato commented on source-requirements.md
> +    -   **[Multiple Commits]** A "change" may be more than one commit. If
Agreed. PTAL at the current exception to see if it seems OK.

2021-06-10 01:46 UTC, MarkLodato commented
OK, I think this is now ready for review. It's not perfect, but I think it is hopefully good enough to commit and iterate.

2021-06-10 02:22 UTC, inferno-chromium approved these changes
Nice!

2021-06-10 02:22 UTC, inferno-chromium commented on source-requirements.md
> +Almost any popular version control system meets this requirement, such as git,
nit: s/Almost any popular version control system meets/Most popular version control systems meet

2021-06-10 02:22 UTC, inferno-chromium commented on source-requirements.md
> +    -   **[Immutable Reference]** There exists a way to indefinitely reference
nit: is indent wrong, this one appears slightly right.

2021-06-10 02:22 UTC, inferno-chromium commented on source-requirements.md
> +        acceptable to only display "path X was updated from hash abcd to hash
nit: instead of path, is dependency a slightly more realistic word here.

2021-06-10 02:22 UTC, inferno-chromium commented on source-requirements.md
> +        presented with a diff between the proposed revision and the previous
nit: expand on diff, maybe "full code diff"

2021-06-10 14:23 UTC, MarkLodato commented on source-requirements.md
> +    -   **[Vendoring]** Bulk import of third-party code, such that the change is
I removed this section entirely for now. It's certainly an issue, but I'd like to gloss over it since it's not really relevant until SLSA 3 and SLSA 3 isn't fully defined yet.

2021-06-10 15:16 UTC, MarkLodato commented on source-requirements.md
> +    -   **[Immutable Reference]** There exists a way to indefinitely reference
This was intentional because it was intended to be a sub-bullet for "Version Controlled". The idea (perhaps misguided) was that the only top-level entries correspond to the ones in the main table, and sub-bullets are clarifications of the main one. Basically, there are a bunch of smaller items that are necessary but (I thought) would be too cluttered to add to the main table.

Is that too confusing? Would it be better to remove this two-level system? Or perhaps only add exceptions as sub-bullets rather than additional requirements?

2021-06-10 15:19 UTC, MarkLodato commented on source-requirements.md
> +        acceptable to only display "path X was updated from hash abcd to hash
What about just "file" instead of "path X"? The point of this is that it's not sufficient for a "code review" to just indicate that a file changes, without showing the reviewer the contents of the change. Is there a way to make that more clear?

Updating a dependency, say in a package-lock.json file, actually would be fine IMO. There, it's perfectly normal for the content _of the package-lock.json_ to in turn contain a hash. Rather, it wouldn't be OK to just say "package-lock.json was updated" without explaining how.

WDYT?

2021-06-10 15:22 UTC, MarkLodato commented on source-requirements.md
> +        presented with a diff between the proposed revision and the previous
Done.

2021-06-10 15:22 UTC, MarkLodato commented on source-requirements.md
> +        acceptable to only display "path X was updated from hash abcd to hash
Reworded this entirely. PTAL.

2021-06-10 15:22 UTC, MarkLodato commented on source-requirements.md
> +Almost any popular version control system meets this requirement, such as git,
Done.

2021-06-10 15:28 UTC, inferno-chromium commented on source-requirements.md
> +    -   **[Immutable Reference]** There exists a way to indefinitely reference
slightly confused on the transition from main to sub-point. don't need to add to table, but can connect them by saying
**[Version Controlled]** Each revision has:
      -- **[Recorded History]
      -- **[Immutable Reference]

Not a big deal either way, either as-is or use this suggestion.

2021-06-10 15:29 UTC, inferno-chromium commented on source-requirements.md
> +        acceptable to only display "path X was updated from hash abcd to hash
LGTM

2021-06-10 15:39 UTC, MarkLodato commented on source-requirements.md
> +    -   **[Immutable Reference]** There exists a way to indefinitely reference
Good idea. Done.

2021-06-10 15:39 UTC, MarkLodato commented on source-requirements.md
> +-   **[Two-Person Review]** All changes in the revision's history were agreed to
Resolving but we can always have a follow-up to fix.

2021-06-10 15:40 UTC, MarkLodato commented
Thanks Abhishek. I'll submit now. We can always add further refinements down the road (which we will almost definitely need.) This is a good start.

2021-06-10 15:40 UTC, merged