Add Reproducible as a recommendation at SLSA 3
slsa-framework/slsa pull request #18
Opened 2021-04-09 20:30 UTC by MarkLodato

At SLSA 3, we now recommend reproducible builds. This is not a strict requirement because not all builds can become reproducible, as explained in the text. Once we write the detailed requirements, we will likely want to somehow explain that reproducible should be the default, while still allowing individual projects to opt-out.

The reason for adding this recommendation is to move the industry towards reproducibility, which is a generally useful property. By having it as the "default" path, most software will just go with the past of least resistance rather than opting out.

Note that this does not require *verifying* the reproduction for security (#5). Instead, the builder just claims that it was reproducible, presumably by building it twice and making sure that the output is identical.

2021-04-09 20:31 UTC, MarkLodato commented
@david-a-wheeler Could you please review?

(Ignore the first two commits - GitHub doesn't have a way of marking one PR a dependency of another. ☹

2021-04-14 18:08 UTC, david-a-wheeler approved these changes
This makes sense to me, and it's what we discussed.

2021-04-14 18:09 UTC, david-a-wheeler approved these changes
This makes sense to me, it's what we agreed on.

2021-04-15 18:29 UTC, TomHennen requested changes

2021-04-15 18:29 UTC, TomHennen commented on README.md
> +reasons, we require reproducibility and hermeticity at SLSA 3 by default.
"we require reproducibility" seems to be in conflict with "we only _recommend_ reproducibility" below.

2021-04-19 18:59 UTC, MarkLodato commented on README.md
> +reasons, we require reproducibility and hermeticity at SLSA 3 by default.
I rewrote most of this section to hopefully better explain. (With the old wording it was hard to make a small tweak.) PTAL

2021-04-19 19:03 UTC, TomHennen approved these changes

2021-04-19 19:04 UTC, merged