[WIP] slsa.dev design overhaul
slsa-framework/slsa pull request #251
Opened 2021-12-14 18:42 UTC by devmoran

This is a (huge) PR with wide ranging changes across all parts of the site and is the result of the SC and projectsbyIF collaboration in Nov/Dec 2021.

To view the extent of the changes visit https://devmoran.github.io/slsa/
This deploy reflects the `main` branch of https://github.com/devmoran/slsa.

At mo this is a DRAFT PR. Feel free to request clarification or changes on anything, with the goal of getting it merged by 16 Dec.

2021-12-15 13:28 UTC, inferno-chromium commented
I don't think it is easy to review a large website overhaul change. We all liked the design in the meeting, so I think we should move forward with merge, and then iterate on it as we notify minor issues. @slsa-framework/teams/slsa-steering-committee - thoughts ?

2021-12-15 17:00 UTC, MarkLodato requested changes
There are a bunch of small nitpicks that I'd like to address before merging, e.g. preserving old links. I imagine the best use of IF's time would be to address the higher level design issues in this PR, while I can cleanup the mechanical issues myself in a fork.

Questions:

* Could you provide sources for the images so that we can edit them in the future, particularly the supply chain ones?
* Can the images all be moved to the images/ folder?
* Can we delete the assets/js/*.js? They seem unused.
* I filed issues in devmoran/slsa, e.g. the 404 issue.

2021-12-15 17:20 UTC, devmoran commented
> * Could you provide sources for the images so that we can edit them in the future, particularly the supply chain ones?
Yes, working on it as we write!

> * Can the images all be moved to the images/ folder?
> * Can we delete the assets/js/*.js? They seem unused.
> * I filed issues in devmoran/slsa, e.g. the 404 issue.
Yup to all 💪 thanks Mark

2021-12-15 17:51 UTC, devmoran commented on docs/_includes/footer.html
> +      <p><strong>Privacy statement</strong><br>
If it was larger than a short paragraph I'd agree, but I'd prefer to keep things transparent on the top level (without additional clicks) since it's a small chunk. (Very few people read privacy policies in practise)

2021-12-16 13:48 UTC, inferno-chromium commented
Thank you Mark for review. Dev, looks like you addressed Mark's comments, any other work remaining here, small things can be fixed later, but want to check this in before holidays.

2021-12-16 14:46 UTC, devmoran commented
@inferno-chromium @MarkLodato Yes, IMO it's ready! 
I'll be raising some separate PRs today to add editable images, terminology page etc.

2021-12-16 17:30 UTC, MarkLodato commented
Dev, could you fix the following remaining issues?
- https://github.com/devmoran/slsa/issues/2
- Moving the icons to images/icons/ or similar (to avoid clutter in the top level).
- Addressing the font issues below? (monospaced code font, spacing issues between paragraphs and between lists)
- Add redirects from the existing URLs so nothing breaks. Examples: threats -> specifications/v0.1/threats, requirements -> specifications/v0.1/requirements, etc.

![image](https://user-images.githubusercontent.com/58860/146419565-7d882014-10f1-4313-8c6d-4f8e86b09bec.png)
![image](https://user-images.githubusercontent.com/58860/146419804-8fe1aba8-b332-43ca-a65b-3d582ad7d1c6.png)

Thanks!

2021-12-16 18:42 UTC, devmoran commented
@MarkLodato I've taken care of those CSS bits. I'm afraid that creating redirects is not something I'm familiar with, i've reached the extend of my 'product person pretending to be a developer' skills.
Do you have any idea the right way to go about this? I've had a google around for some ideas but wouldn't know the best approach.

2021-12-17 02:27 UTC, MarkLodato commented
Looking great!

I just pushed a few fixes to your branch. I hope you don't mind. I thought that would be easier than providing comments.

A few final minor things before merging:

- Bug: In the dropdown, "Introduction" should come first. Currently it's listed second, after "Security levels".
- Nit: Instead of having a spec page called "v0.1/overview.md", should we instead call it "index.md" so that the URL is just "v0.1"? My inclination is for shorter, simpler URLs, but perhaps this was intentional?
- Q: Shall we rename the directory "specifications" to "spec" to make the URL shorter and easier to read?

By the way, once this is ready, I think we should do a squash merge instead of merging in the huge intermediate comments.

2021-12-17 14:48 UTC, MarkLodato approved these changes
From my perspective this is good to go. Nice work, Dev and team!

@inferno-chromium, I'd like to get at least one more SC member to approve before merging, as per our contributing guide. But hopefully any requested changes could be fixed by me without IF's help.

@devmoran, if there is any spare time, have you thought about making the font size bigger on the threat diagram to match the main text? That might increase legibility. No worries if there's no time or it doesn't work.

Also, I pushed a fix for broken links on the mirror (namely the devmoran mirror). It didn't affect prod but still nice to fix. Again, hope it doesn't cause issues.

2021-12-17 14:59 UTC, inferno-chromium commented
> From my perspective this is good to go. Nice work, Dev and team!

+1. Great work Dev and ProjectsByIF team! 

> 
> @inferno-chromium, I'd like to get at least one more SC member to approve before merging, as per our contributing guide. But hopefully any requested changes could be fixed by me without IF's help.

Yes, @joshuagl @mlieberman85 @trishankatdatadog @zakgreant @brunodom @david-a-wheeler, can one of you please review this before holidays (just design/cosmetic changes, so should be simple), it will be nice to have this new site up!

> 
> @devmoran, if there is any spare time, have you thought about making the font size bigger on the threat diagram to match the main text? That might increase legibility. No worries if there's no time or it doesn't work.
> 
> Also, I pushed a fix for broken links on the mirror (namely the devmoran mirror). It didn't affect prod but still nice to fix. Again, hope it doesn't cause issues.

2021-12-17 16:11 UTC, david-a-wheeler approved these changes
This is so huge that it's hard to give a meaningful review! I hope future changes will be more "bite-sized" :-).

That said, I approve. Overall it makes sense, and it'd be ridiculous to throw away all this work.

2021-12-17 16:26 UTC, merged