terminology: define build [platform|service|step]
slsa-framework/slsa pull request #290
Opened 2022-02-02 22:04 UTC by joshuagl

Although Build platform is implicitly defined as part of the Build, there is still confusion around the term. 
Additionally what makes a build step is not explicitly defined. 

Expand the new terminology page to include:
* Build platform: runs builds/build processes
* Build service: typically a managed/hosted build platform
* Build step: a task in the build process

2022-02-02 22:12 UTC, trishankatdatadog commented
Thanks! Are these terms used anywhere else?

2022-02-03 11:20 UTC, joshuagl commented
Thanks for the quick feedback @trishankatdatadog. I don't think these terms are used in this way elsewhere, which is why they seem to be a frequent cause of confusion in my discussions of SLSA.

I think there's an open question around whether we want to define these, as SLSA aims to be versatile to fit multiple artefact production pipelines.

I infer through reading the SLSA docs that build platform and build service are used interchangeable and generally assumed to be some kind of CI/CD service.

* Should we be consistent in use of build platform OR build service (but not both)?
* Should we be explicit that the build platform is typically some kind of CI/CD service (particularly for small projects), or does my definition work:
   > An automation and scheduling platform for running build processes.
  (Admittedly, it all feels a bit circular)

2022-02-03 13:58 UTC, TomHennen requested changes
Thanks!  I like this direction.  I think it's definitely been confusing.

Would it be fair to say that the Build Service is responsible for meeting SLSA's requirements but that the Build Platform can help it to do so?  E.g. it's not enough to use Tekton by itself (even if it produces provenance and all that) you still need to manage the platform securely?

2022-02-03 13:58 UTC, TomHennen commented on docs/_spec/v0.1/terminology.md
> +| Build platform | An automation and scheduling platform for running build processes. Better defined by what it is not: the most desirable attribute of a build platform is that builds do not happen o
Should 'build process' be defined?  Is it just the same as 'build' above?

2022-02-03 13:58 UTC, TomHennen commented on docs/_spec/v0.1/terminology.md
> +| Build step | A single task in the build process | a `step` in a GitHub Action Workflow. |
Do you have any plans to use 'build step' anywhere?  Is it primarily here to distinguish itself from the entire build process?

2022-02-03 14:04 UTC, TomHennen commented on docs/_spec/v0.1/terminology.md
> +| Build platform | An automation and scheduling platform for running build processes. Better defined by what it is not: the most desirable attribute of a build platform is that builds do not happen o
@AdamZWu pointed out that since the Build Platform is just code it _could_ run on a developer's workstation.  But it makes it possible to easily run it elsewhere, like in a build service.

2022-02-03 17:02 UTC, MarkLodato commented
Thanks for starting this discussion! We certainly need more clarity here and this is a good start. I'm not sure that defining these two terms is sufficient, and I also think we should probably stick to either platform or service rather than using both.

I put together a skeleton of how we could expand this a bit. See #294. I threw that together, but maybe we can form that into a proper model?

@joshuagl Are you available to meet to discuss? I suspect we need a higher bandwidth channel than PR comments. I chatted with @TomHennen for a half hour and we didn't even come to a conclusion. :smiley:

2022-02-08 14:18 UTC, joshuagl commented on docs/_spec/v0.1/terminology.md
> +| Build step | A single task in the build process | a `step` in a GitHub Action Workflow. |
I defined build step here because the term is used multiple times in the [Build requirements](https://slsa.dev/spec/v0.1/requirements#build-requirements) in [scripted build](https://slsa.dev/spec/v0.1/requirements#scripted-build), [build service](https://slsa.dev/spec/v0.1/requirements#build-service), [ephemeral environment](https://slsa.dev/spec/v0.1/requirements#ephemeral-environment), [isolated](https://slsa.dev/spec/v0.1/requirements#isolated), [hermetic](https://slsa.dev/spec/v0.1/requirements#hermetic), and [reproducible](https://slsa.dev/spec/v0.1/requirements#reproducible) and to at least one reader it was not obvious what the term refers to.

2022-02-08 14:19 UTC, joshuagl commented on docs/_spec/v0.1/terminology.md
> +| Build platform | An automation and scheduling platform for running build processes. Better defined by what it is not: the most desirable attribute of a build platform is that builds do not happen o
That's a fair point.

2022-02-08 14:20 UTC, joshuagl commented
> Thanks for starting this discussion! We certainly need more clarity here and this is a good start. I'm not sure that defining these two terms is sufficient, and I also think we should probably stick to either platform or service rather than using both.

Agreed, the two definitions are not sufficient. I had intended to _start_ a discussion, so I probably should have started with an issue or draft PR.

> I put together a skeleton of how we could expand this a bit. See #294. I threw that together, but maybe we can form that into a proper model?

This looks like a great start, thanks for building on the vague ideas here and fleshing it out. We should close this PR in favour of #294.

> @joshuagl Are you available to meet to discuss? I suspect we need a higher bandwidth channel than PR comments. I chatted with @TomHennen for a half hour and we didn't even come to a conclusion. 😃

💯

2022-02-08 14:21 UTC, joshuagl commented on docs/_spec/v0.1/terminology.md
> +| Build platform | An automation and scheduling platform for running build processes. Better defined by what it is not: the most desirable attribute of a build platform is that builds do not happen o
Or alternatively, this definition is "an automation and scheduling platform for running builds".

2022-02-17 13:38 UTC, joshuagl commented
Closing in favour of the WIP model in #294

2022-02-17 13:38 UTC, closed without merging