threats: replace link to event-stream incident
slsa-framework/slsa pull request #318
Opened 2022-03-08 16:45 UTC by joshuagl

schneider.dev is down and, sadly, unlikely to come back. This patch
replaces the link to Zach Schneider's explanation with a link to the
official npm analysis of the incident.

Fixes #314

2022-03-08 21:00 UTC, MarkLodato requested changes
I personally find the npmjs writeup to be very sparse, not really explaining how the attack took place. Should we use the wayback version  of schneider instead?

2022-03-08 21:05 UTC, joshuagl commented
I'm more than happy to use the way back version. I'll update the PR tomorrow.

2022-03-09 11:27 UTC, MarkLodato approved these changes
Thanks for the fix!

2022-03-10 11:40 UTC, joshuagl commented
Merging with a single approval as the change doesn't affect the meaning of the spec.

2022-03-10 11:40 UTC, merged