✨ Recommend the slsa-github-generator for SLSA3
slsa-framework/slsa pull request #399
Opened 2022-06-20 19:55 UTC by laurentsimon

See title

2022-06-20 20:04 UTC, asraa commented on docs/get-started.md
> +                        <li>You’re now generating non-forgeable [SLSA provenance](https://slsa.dev/) on GitHub that meets the [build](https://slsa.dev/spec/v0.1/requirements#build-requirements) and [
nit: these links are markdown refs, not html so they don't render

2022-06-20 20:04 UTC, asraa commented on docs/get-started.md
> +                        This guide will help you achieve Level 3 on GitHub, and it should take less than a couple of hours for an individual project. The goals is to:
Is it worth direction to the generic or Golang ones?

2022-06-20 20:11 UTC, laurentsimon commented on docs/get-started.md
> +                        <li>You’re now generating non-forgeable [SLSA provenance](https://slsa.dev/) on GitHub that meets the [build](https://slsa.dev/spec/v0.1/requirements#build-requirements) and [
ouch, i copied without reading. Thanks. Addressed

2022-06-20 21:13 UTC, laurentsimon commented on docs/get-started.md
> +                        This guide will help you achieve Level 3 on GitHub, and it should take less than a couple of hours for an individual project. The goals is to:
The generic projects have `This is a pre-release only and we will have the official release in July 2022.`, so I suppose we could keep the link as-is? (Simplifies maintenance)

Let's see if others have an opinion

2022-06-20 21:20 UTC, mlieberman85 commented on docs/get-started.md
> +                        <li>You’re now generating non-forgeable <a href="https://slsa.dev/">SLSA provenance</a> on GitHub that meets the <a href="https://slsa.dev/spec/v0.1/requirements#build-require
Does this only support v0.1 of the spec?

2022-06-20 21:39 UTC, laurentsimon commented on docs/get-started.md
> +                        <li>You’re now generating non-forgeable <a href="https://slsa.dev/">SLSA provenance</a> on GitHub that meets the <a href="https://slsa.dev/spec/v0.1/requirements#build-require
good catch. We actually use v0.2 for our provenance, but I'm unable to get a link: https://slsa.dev/spec/v0.1 gives 404. Do you know the link?

2022-06-20 21:48 UTC, mlieberman85 commented on docs/get-started.md
> +                        <li>You’re now generating non-forgeable <a href="https://slsa.dev/">SLSA provenance</a> on GitHub that meets the <a href="https://slsa.dev/spec/v0.1/requirements#build-require
Oh, this is my mistake. The requirements spec might still be 0.1, but the in-toto predicate format spec for provenance might be 0.2? That's actually kind of confusing.

2022-06-20 21:58 UTC, laurentsimon commented on docs/get-started.md
> +                        <li>You’re now generating non-forgeable <a href="https://slsa.dev/">SLSA provenance</a> on GitHub that meets the <a href="https://slsa.dev/spec/v0.1/requirements#build-require
You're correct. Sorry I was confused too :-). So we're good then. Resolving the issue.

2022-06-21 03:19 UTC, ianlewis commented on docs/get-started.md
> +                        <li>Follow the steps in <a href="https://github.com/slsa-framework/slsa-framework">slsa-framework/slsa-verifier</a> to learn how to verify provenance for your release</li>
```suggestion
                        <li>Follow the steps in <a href="https://github.com/slsa-framework/slsa-verifier">slsa-framework/slsa-verifier</a> to learn how to verify provenance for your release.</li>
```

2022-06-21 03:19 UTC, ianlewis commented on docs/get-started.md
> +                        <li>You’re now generating non-forgeable <a href="https://slsa.dev/">SLSA provenance</a> on GitHub that meets the <a href="https://slsa.dev/spec/v0.1/requirements#build-require
Maybe add a step to evaluate other SLSA 3 requirements since using `slsa-github-generator` is not necessarily sufficient for SLSA 3.

2022-06-21 03:19 UTC, ianlewis commented on docs/get-started.md
> +## Reaching SLSA Level 3
Maybe we don't need to for this PR but I think it would be helpful to have different sections that cover different requirements.

For example, `slsa-github-generator` could fall under a "Build & Provenance requirements" section. While something like [gitsign](https://github.com/sigstore/gitsign) and/or GitHub commit verification could fall under "Source requirements".

2022-06-21 12:09 UTC, MarkLodato requested changes
Let's get review from @slsa-framework/slsa-steering-committee. In particular, how do you think it best to suggest the various tools while being impartial as to vendor?

2022-06-21 12:09 UTC, MarkLodato commented on docs/get-started.md
> +                        <li>Verify the generate provenance</li>
Let's remove this for now. Verification/policy is a big hole in SLSA today. I don't think we should just tell people to "verify" without further explanation of what they are trying to achieve or how to do so securely. Or if we do, add a caveat that it is not properly documented.

2022-06-21 12:09 UTC, MarkLodato commented on docs/get-started.md
> +                        <li>Use a GitHub trusted builder</li>
This makes it sound like GitHub is required to reach SLSA 3, which is not true. Instead, this section needs to be more generic (similar to above) to say that the goal is to have a tamper-proof build process that generates trustworthy provenance, and suggest various ways to achieve that.

2022-06-21 12:09 UTC, MarkLodato commented on docs/get-started.md
> +## Reaching SLSA Level 3
IMO this page needs a complete rewrite. It needs to be more focused on who the audience is, what they're trying to accomplish, and how they can do so.

2022-06-24 15:00 UTC, laurentsimon commented on docs/get-started.md
> +## Reaching SLSA Level 3
I was not sure whether you meant we need to re-write the entire get-started.md page or just the SLSA3 section of this PR. I've assumed the latter and updated this PR to address all other comments. PTAL

2022-06-24 15:00 UTC, laurentsimon commented on docs/get-started.md
> +                        <li>Verify the generate provenance</li>
Done, thanks

2022-06-24 15:00 UTC, laurentsimon commented on docs/get-started.md
> +                        <li>Use a GitHub trusted builder</li>
Done, PTAL

2022-06-24 15:24 UTC, MarkLodato approved these changes

2022-06-24 15:24 UTC, MarkLodato commented on docs/get-started.md
> +## Reaching SLSA Level 3
Not for this PR. I was just agreeing with Ian that this page needs work.

2022-06-24 15:28 UTC, laurentsimon commented on docs/get-started.md
> +## Reaching SLSA Level 3
SG. I've created an issue for tracking https://github.com/slsa-framework/slsa/issues/407. Resolving this comment.

2022-06-24 15:33 UTC, laurentsimon commented
friendly ping https://github.com/orgs/slsa-framework/teams/slsa-steering-committee, can we get an additional LGTM?

2022-06-27 13:11 UTC, kimsterv approved these changes

2022-06-27 14:35 UTC, merged