Add blog post Foundational-Framework-guidance
slsa-framework/slsa pull request #426
Opened 2022-07-15 20:31 UTC by emmy-ID

Add Blog post to SLSA.dev website

Signed-off-by: Emmy Eide <91090554+emmy-ID@users.noreply.github.com>

2022-07-20 18:49 UTC, melba-lopez commented
@slsa-framework/slsa-steering-committee

2022-07-20 18:53 UTC, lumjjb commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +In coordination with Aaron Bacchi, Emmy Eide, Melba Lopez, and Brandon Lum
nit: The metadata should follow the format so that it shows on the site properly: https://github.com/slsa-framework/slsa/blob/main/docs/_posts/2022-06-15-slsa-ssdf.md?plain=1#L1-L5, and also probably renamed to `.md` and follow lower case.

Can test locally to verify with https://github.com/slsa-framework/slsa/tree/main/docs#developing-and-testing-locally

2022-07-20 18:53 UTC, lumjjb commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +                Establish a governance capability for managing and monitoring components of embedded software to manage risk across the enterprise (e.g. SBOMs paired with criticality, vulnerability,
Probably can run [markdownlint](https://github.com/DavidAnson/markdownlint) to fix the formating. I believe there are images here as well right?

2022-07-21 00:09 UTC, trishankatdatadog commented
The blog post doesn't seem to be available in the Deploy Preview?

2022-07-21 03:00 UTC, melba-lopez requested changes

2022-07-21 07:39 UTC, moshe-apiiro commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +## The Cybersecurity Framework: 2.0 and Beyond
I am thinking maybe we should address SBOM at this stage at final words as another factor and thread of discussion that is constituting a big part of conversation on 'future and beyond'.
wdyt?

2022-07-21 13:10 UTC, lumjjb commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +## The Cybersecurity Framework: 2.0 and Beyond
I think SBOM should be kept as a separate topic. There is a lot of conflation and confusion between the two and I think we need to be careful on we present them to the broader audience.

2022-07-21 13:15 UTC, moshe-apiiro commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +## The Cybersecurity Framework: 2.0 and Beyond
i see your point, and agree that if we veer towards SBOM too much we might lose the audience and add to the confusion. That said (a) we already mentioned SBOM twice on the blog we no expansion (b) imho we shouldn't discourage the discourse for that - it is a very important distinction that we would like to promote the understanding of it for the crowd of readers

2022-07-21 13:19 UTC, lumjjb commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +## The Cybersecurity Framework: 2.0 and Beyond
I have a planned blog to follow that to cover some of the work that SPDX is doing with build profiles and how it relates to SLSA, I will talk about this if there's time on today's SLSA call.

2022-07-21 13:23 UTC, moshe-apiiro commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +Although the first two are ultimately written for US federal agencies, they are available for everyone to use and include both the criteria to evaluate software security itself as well as developer a
we might want to emphasize the extensive effect of NIST beyond their own jurisdiction
Suggestion:
`Although the first two are ultimately written for US federal agencies, they are available for everyone to use and include both the criteria to evaluate software security itself as well as developer and supplier security practices. Acquirers and end users of software, products, and services use these publications in tandem to understand what risks to look for and what actions to consider taking in response. SP800-53r5 is the “rock”, the “foundation” and prerequisite reading to the SP800-161r1, which is considered the framework and is mandatory for all US federal agencies. NIST standards are known to be transposed and translated by other entities, global and local, so by extension the standards have a much larger practical effect globally, by other regulatory entities and governments alike.`

2022-07-21 14:44 UTC, moshe-apiiro commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +## The Cybersecurity Framework: 2.0 and Beyond
sounds good, let's follow up on the call and I'd be happy to contribute on the follow up blog

2022-07-21 16:52 UTC, kimsterv commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +Flexible +  Simple + Foundational Guidance = A recipe for a useful framework, whether that is the Cybersecurity Framework, SLSA, or some other framework—customers are expecting this help from NIST, f
```suggestion
Flexible +  Simple + Foundational Guidance = A recipe for a useful framework, whether that is the Cybersecurity Framework, SLSA, or some other framework—organizations are expecting this help from NIST, from their vendors, from their partners, from all of us. 
```

2022-07-21 16:53 UTC, kimsterv commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +The addition of foundational guidance in the US government’s NIST material is quite welcome, and similar clarifications could follow later this year in the NIST Cybersecurity Framework as it relates
```suggestion
The addition of foundational guidance in the US government’s NIST material is quite welcome, and similar clarifications could follow later this year in the NIST Cybersecurity Framework as it relates to both the EO and organization expectations. 
```

2022-07-21 16:54 UTC, kimsterv requested changes
Great post! Approved after a few suggestions.

2022-07-21 18:39 UTC, lumjjb commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +is_guest_post: false
```suggestion
is_guest_post: true
```
This is considered a guest post.

2022-07-21 18:39 UTC, lumjjb commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +Post Location: slsa.dev
```suggestion
```

Date is encoded in the file name, it needs to be renamed to `<filename>.md` to be picked up

2022-07-22 13:12 UTC, joshuagl reviewed
This is a nice blog post, thank you for working on it!

I made some minor suggestions to provide some additional context for folks not as familiar with the US federal government and which departments are behind standardisation efforts.

Let's fix the metadata, include the images, and lint the Markdown before posting.

2022-07-22 13:12 UTC, joshuagl commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +The NIST Cybersecurity Framework was last updated in 2018 and is currently planning a more significant revision to the Framework: CSF 2.0. The Summary Analysis of requests for information was publish
```suggestion
The NIST Cybersecurity Framework (CSF) was last updated in 2018 and is currently planning a more significant revision to the Framework: CSF 2.0. The Summary Analysis of requests for information was published in June of this year. 
```

2022-07-22 13:13 UTC, joshuagl commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +
Where are the images used in the blog currently hosted? Should we include them in the SLSA repo (we might create a `_blog/assets` directory, or similar).

2022-07-22 14:58 UTC, MarkLodato commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +In coordination with Aaron Bacchi, Emmy Eide, Melba Lopez, and Brandon Lum
And once you push, you can view it on the Netlify preview:
https://deploy-preview-426--slsa.netlify.app/blog

Note that the entry does not show up.

2022-07-25 19:20 UTC, emmy-ID commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +
@melba-lopez I was able to make the change using that code. thank you!

2022-07-25 19:20 UTC, emmy-ID commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +## The Cybersecurity Framework: 2.0 and Beyond
@moshe-apiiro did this get resolved? are we adding more SBOM context here or keeping it separate?

2022-07-25 19:23 UTC, emmy-ID commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +Although the first two are ultimately written for US federal agencies, they are available for everyone to use and include both the criteria to evaluate software security itself as well as developer a
added. thank you for the suggestion

2022-07-25 19:30 UTC, emmy-ID commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +                Next steps to enhance C-SCRM. Use confidence building mechanisms such as third-party assessment surveys, on-site visits, and formal certifications such as the ISO 27000 family.
thanks, I made the change. resolving the conversation since its not letting me "sign off and commit". But I did make the change :)

2022-07-25 19:39 UTC, emmy-ID commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +In coordination with Aaron Bacchi, Emmy Eide, Melba Lopez, and Brandon Lum
Cool. thanks for helping!

2022-07-25 20:15 UTC, moshe-apiiro commented on docs/_posts/2022-07-15-Foundational-Framework-guidance
> +## The Cybersecurity Framework: 2.0 and Beyond
afaiu @lumjjb have another blog planned on the topic, we haven't discussed it on the latest call eventually. I agree that fundamentally, if we have another blog dedicated we don't want to mix the two parties.

2022-07-25 20:17 UTC, moshe-apiiro commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +*In coordination with Aaron Bacchi, Emmy Eide, Melba Lopez, and Brandon Lum*
```suggestion
*In coordination with Aaron Bacchi, Emmy Eide, Melba Lopez, Brandon Lum, and Moshe ZIoni*
```

2022-07-25 22:18 UTC, moshe-apiiro commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +*In coordination with Aaron Bacchi, Emmy Eide, Melba Lopez, Brandon Lum, and Moshe ZIoni*
```suggestion
*In coordination with Aaron Bacchi, Emmy Eide, Melba Lopez, Brandon Lum, and Moshe Zioni*
```

2022-07-26 16:28 UTC, emmy-ID reviewed
made adjustments as suggested

2022-07-27 15:36 UTC, emmy-ID commented
@kimsterv can you help me with removing you as a blocker? I added your changes but its still saying it needs your approval.

2022-07-27 17:20 UTC, kimsterv approved these changes

2022-07-27 18:08 UTC, inferno-chromium commented
@slsa-framework/slsa-steering-committee - can you please take a final look, we can one more approval before merging this.

2022-07-27 20:40 UTC, MarkLodato requested changes

2022-07-27 20:40 UTC, MarkLodato commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +Few frameworks are like SLSA. Many, including the National Institute of Standards and Technology (NIST) frameworks historically, can be overlapping, and sometimes overwhelming. It can be difficult to
nit: use a relative link to the markdown file to simplify maintenance: `[guest blog post](2022-06-15-slsa-ssdf.md)`

2022-07-27 20:40 UTC, MarkLodato commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +The ([attached](https://docs.google.com/spreadsheets/d/1P_xxMlyF5iPV51CqIk8_EhI57aR6wf1Gkrg8sRHBMMQ/edit#gid=0)) mapping document, created by members of the SLSA working group,  loosely illustrates t
Is this an important point of this blog post? If so, I suggest restructuring the post to make it more prominent. As-is, it appears to be a side note and is easily overlooked.

2022-07-27 20:40 UTC, MarkLodato commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +title: "All about that Base(line): How Cybersecurity Frameworks are Evolving with Foundational Guidance"
I'm having understanding what this blog post is trying to say. What is the purpose of this post and what are the main points you're trying to get across? It doesn't come across clearly right now, but perhaps I can give editing advice.

2022-07-28 02:22 UTC, emmy-ID commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +The ([attached](https://docs.google.com/spreadsheets/d/1P_xxMlyF5iPV51CqIk8_EhI57aR6wf1Gkrg8sRHBMMQ/edit#gid=0)) mapping document, created by members of the SLSA working group,  loosely illustrates t
its not the biggest point but its not unimportant. Not sure its worth restructuring the whole post for

2022-07-28 02:32 UTC, melba-lopez commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +The ([attached](https://docs.google.com/spreadsheets/d/1P_xxMlyF5iPV51CqIk8_EhI57aR6wf1Gkrg8sRHBMMQ/edit#gid=0)) mapping document, created by members of the SLSA working group,  loosely illustrates t
we reiterate that doc at the end (call to action).  If we want to make it more prominent, instead of rewriting (which i'm not a fan of) can we potentially have a visual of it embedded?

2022-07-28 02:32 UTC, emmy-ID commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +title: "All about that Base(line): How Cybersecurity Frameworks are Evolving with Foundational Guidance"
Talking about how SLSA fits in with the other relevant cybersecurity frameworks and the value it brings. "frameworks historically, can be overlapping, and sometimes overwhelming". And how to view SLSA amongst the other frameworks "The foundational guidance that begins with the basics and helps you get better over time is a key ingredient in SLSA."

2022-07-28 02:33 UTC, melba-lopez commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +title: "All about that Base(line): How Cybersecurity Frameworks are Evolving with Foundational Guidance"
Hi Mark, trying to figure out how best to help you out.  I myself do not like reading this in git (gives me a headache).  So perhaps the original would help?? https://docs.google.com/document/d/1Vn-ppR7eOFc1DMyczjsmpN3tz-jsiFOfzwnSNti-Sbg/edit#heading=h.xuz67jyns3n6

So far, we've gotten positive feedback from several community members.  Unless the core author Jennifer  and other contributors (emmy, brandon, aaron) disagree, i would say the intent is for positioning slsa with regards to the EO/NIST Frameworks.

2022-07-28 02:37 UTC, melba-lopez commented
@emmy-ID before you commit anymore changes, make sure you put signed off (with consistent email)

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/101211710/181408139-61cc5c4f-b19f-4331-a308-f40e0b4d0add.png">

2022-07-28 19:18 UTC, melba-lopez commented
@slsa-framework/slsa-steering-committee I just noticed in the preview it says "this is a guest post", but we would consider this a community post as it was created by multiple organizations in the community, which appears to have good consesus and is related to the "slsa-positioning" SIG.  

per the guidelines "Guest Blog Post are considered to be from **a single person/organization that is sharing how they are implementing/applying SLSA in their respective project/organization**."

2022-07-28 20:34 UTC, MarkLodato commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +title: "All about that Base(line): How Cybersecurity Frameworks are Evolving with Foundational Guidance"
To be clear, you don't need to follow my advice here. I have no objections to this post from a correctness or consensus point of view, and my approval is not required.

I'm happy to give editing advice if you're interested in revising it to better communicating your ideas. As a reader, I couldn't tell what the purpose of the post was. Was it informing me that these other frameworks exist? Informing me how SLSA relates to them (which I didn't really follow)? A request for me to review the spreadsheet (which wasn't obvious)? I suspect other readers may have the same confusion.

One suggestion is to make that purpose clear in the first paragraph so that readers know what to expect.

2022-07-28 23:59 UTC, emmy-ID commented
> @slsa-framework/slsa-steering-committee I just noticed in the preview it says "this is a guest post", but we would consider this a community post as it was created by multiple organizations in the community, which appears to have good consesus and is related to the "slsa-positioning" SIG.
> 
> per the guidelines "Guest Blog Post are considered to be from **a single person/organization that is sharing how they are implementing/applying SLSA in their respective project/organization**."

I agree with this. Any disagreement?

2022-07-29 00:02 UTC, emmy-ID commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +The ([attached](https://docs.google.com/spreadsheets/d/1P_xxMlyF5iPV51CqIk8_EhI57aR6wf1Gkrg8sRHBMMQ/edit#gid=0)) mapping document, created by members of the SLSA working group,  loosely illustrates t
if anyone knows how to do this id be happy to embed it.

2022-07-29 00:02 UTC, emmy-ID commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +Few frameworks are like SLSA. Many, including the National Institute of Standards and Technology (NIST) frameworks historically, can be overlapping, and sometimes overwhelming. It can be difficult to
done

2022-07-29 13:44 UTC, JenniferPrivette commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +title: "All about that Base(line): How Cybersecurity Frameworks are Evolving with Foundational Guidance"
Thank you for that feedback Mark, I agree. Perhaps a short summary up front would be beneficial? Something like: 

SUMMARY: Software security frameworks are beginning to give organizations foundational guidance they can build on so that they can start small with easily achievable tasks, and then increase to the highest assurances of integrity. SLSA does this in four levels of maturity. NIST also recently updated one of its main cybersecurity frameworks with foundational guidance. This blog shows examples of foundational guidance from both SLSA and NIST and introduces a mapping document that illustrates the correlation among SLSA and other existing frameworks.

2022-07-29 14:48 UTC, JenniferPrivette requested changes

2022-07-29 14:48 UTC, JenniferPrivette commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +
SUMMARY: Software security frameworks are beginning to give organizations foundational guidance they can build on so that they can start small with easily achievable tasks, and then increase to the highest assurances of integrity. SLSA does this in four levels of maturity. NIST also recently updated one of its main cybersecurity frameworks with foundational guidance. This blog shows examples of foundational guidance from both SLSA and NIST and introduces a mapping document that illustrates the correlation among SLSA and other existing frameworks.

2022-07-29 15:17 UTC, emmy-ID commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +title: "All about that Base(line): How Cybersecurity Frameworks are Evolving with Foundational Guidance"
added the summary section

2022-08-01 21:34 UTC, MarkLodato commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +title: "All about that Base(line): How Cybersecurity Frameworks are Evolving with Foundational Guidance"
That summary helps a lot. Thanks!

2022-08-01 21:35 UTC, MarkLodato approved these changes

2022-08-01 21:35 UTC, MarkLodato commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +*In coordination with Aaron Bacchi, Emmy Eide, Melba Lopez, Brandon Lum, and Moshe Zioni*
Would it be OK to just list these on the author line? Right now the first paragraph is shown as a preview, which means that only this shows up on https://deploy-preview-426--slsa.netlify.app/blog.

2022-08-01 21:35 UTC, MarkLodato commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +
Much better. Thanks.

2022-08-02 16:17 UTC, emmy-ID commented on docs/_posts/2022-07-25-slsa-foundational-framework.md
> +*In coordination with Aaron Bacchi, Emmy Eide, Melba Lopez, Brandon Lum, and Moshe Zioni*
I think thats okay @MarkLodato. Jennifer wrote 99% of this document. If we are calling it a guest post then its okay if her name stays as the only name. But if we are going to change it to a "community post", then I agree that we should add all of the names to the author line.

2022-08-02 16:19 UTC, emmy-ID commented
I would like to move this post forward if possible. Is there anyone that can help get this pushed out? Im not sure what else needs to be done.

2022-08-02 16:22 UTC, inferno-chromium commented
> I would like to move this post forward if possible. Is there anyone that can help get this pushed out? Im not sure what else needs to be done.

Can you please fix the DCO and Lint failures, then this seems ready to merge in.

2022-08-02 18:55 UTC, emmy-ID commented
To fix the Lint failures, I have to rebase which I believe will remove all of the comment history...is there a better way to do this that I don't know about? Ive been trying to troubleshoot it for a week. I was making updates on the github desktop client and it didn't automatically sign the commit like it does on the web GUI so I didn't realize it was happening until 5 commits too late.

2022-08-02 19:01 UTC, MarkLodato commented
Yup, need to rebase. And might as well squash into a single commit while you're at it.

The review comments won't disappear completely. They're just harder to follow. Sadly that's the only option as long as we're using GitHub for code reviews. We just have to live with it.

2022-08-02 21:45 UTC, emmy-ID commented
Okay I give up. Can I please just open a new pull request with the content as it stands now and close this one? The amount of time I've spent trying to rebase is just insane for a blog post.

2022-08-02 22:18 UTC, emmy-ID commented
Looks like it is passing the checks now. Can someone merge the request?

2022-08-02 23:18 UTC, merged