Move attestation model into the site
slsa-framework/slsa pull request #438
Opened 2022-07-22 15:41 UTC by joshuagl

This moves the attestation model, referenced from the Provenance and VSA pages, into the main site so we are not bouncing readers who follow the link to the GitHub repository.

I've not yet convinced myself that this should be part of the specification, so I'm open to moving it. 
I apologise for the hack in 0282b9fc3a9fdca2a204c6ae6a23992ebbb720a3. I'm very much open to alternative ways of displaying this and trying to improve the way the indentation is implemented.

Fixes #323

2022-07-22 16:03 UTC, joshuagl commented
Link to the new page on the preview site: https://deploy-preview-438--slsa.netlify.app/spec/attestation-model

2022-07-22 16:19 UTC, MarkLodato requested changes
This is great, thanks! Not only is the new location is helpful, but the wording and formatting changes are also a big readability improvement.

I do have a few small suggestions, but overall LGTM.

2022-07-22 16:19 UTC, MarkLodato commented on controls/attestations.md
> -Content moved to [../docs/attestation-model.md](../docs/attestation-model.md).
Let's leave this here until we update all old references, notably in the in-toto/attestation and in-toto/ITE repositories.

2022-07-22 16:19 UTC, MarkLodato commented on docs/spec/attestation-model.md
>  ---
What is the motivation from moving it into the specification? Isn't it independent from the level specification? Your original location (top-level docs/) better aligned with my expectations, but I may be missing something.

2022-07-22 16:19 UTC, MarkLodato commented on docs/_includes/nav.html
> +                  <a class="text-white md:text-black {% if subitem.nudge %}pl-5{% endif %} " href="{{ subitem.url | relative_url }}">
As an alternative, you could do something like this, adding an unlinked "Attestations:" heading and then link to the model as a sub-page of that:

![image](https://user-images.githubusercontent.com/58860/180481271-bafbf8d7-d621-4913-9a94-dca90629a1db.png)

2022-07-22 16:21 UTC, joshuagl commented on controls/attestations.md
> -Content moved to [../docs/attestation-model.md](../docs/attestation-model.md).
Yes, that makes sense. I ended up `rm`ing it because the linter complained, but I can add it back and placate the linter.

2022-07-22 16:22 UTC, joshuagl commented on docs/spec/attestation-model.md
>  ---
Simply that it felt odd linking to it from the specification menu when it wasn't tracked as part of the spec, but I was not convinced. As you aren't convinced either, I will move it back.

2022-07-22 16:23 UTC, joshuagl commented on docs/_includes/nav.html
> +                  <a class="text-white md:text-black {% if subitem.nudge %}pl-5{% endif %} " href="{{ subitem.url | relative_url }}">
That's less hacky, let me do that.

2022-07-22 16:30 UTC, MarkLodato commented on docs/_includes/nav.html
> +                  <a class="text-white md:text-black {% if subitem.nudge %}pl-5{% endif %} " href="{{ subitem.url | relative_url }}">
In my screenshot I also added a `margin: 13px 0` to the `<li>` containing the horizontal rule so that it's not so smushed.

2022-07-22 16:43 UTC, joshuagl commented
Thanks for the quick review Mark. I've addressed your comments as follow-on commits. I can clean up the git history before merging, or squash and merge – I don't have a preference but thought follow-on commits would be easier to review.

2022-07-22 17:12 UTC, MarkLodato commented on docs/attestation-model.md
> +version: 0.1
Is there any way to easily get rid of the version dropdown? It doesn't make sense for this page. (See [preview](https://deploy-preview-438--slsa.netlify.app/attestation-model)))

2022-07-22 17:12 UTC, MarkLodato commented on docs/attestation-model.md
> +![Attestation model diagram](/images/attestation_layers.svg)
nit: can you use relative paths to the images so that it renders correctly on the GitHub preview?

Optionally you can do the same for Markdown links (but not HTML links) since the Jekyll plugin convers links to .md files to the proper URL. But the value is much lower. Example: docs/roadmap.md, line 11

2022-07-22 18:39 UTC, joshuagl commented on controls/attestations.md
> +[the website](https://slsa.dev/attestation_model).
One day I'll stop pushing last minute changes on a Friday, but today is not that day. Apologies and thanks for the diligent review. I'll fix this, and the rest of the PR, on Monday.

2022-07-22 18:40 UTC, joshuagl commented on docs/attestation-model.md
> +version: 0.1
I will play around with this, perhaps changing the layout back to `standard`.

2022-07-22 18:42 UTC, joshuagl commented on docs/attestation-model.md
> +![Attestation model diagram](/images/attestation_layers.svg)
I will fix the images to use relative paths and try to improve the non-image links too.

2022-07-25 11:12 UTC, joshuagl commented on docs/attestation-model.md
> +version: 0.1
If I switch back to standard layout I get the large green header section for the hero text. Formatting text within that section is... awkward. So I've ended up changing the specification layout to _not_ show the version selector for the "Software attestations" page, as has already been done for the FAQ and use-cases pages.

2022-07-25 13:08 UTC, MarkLodato approved these changes
LGTM. Thanks!

2022-07-25 13:08 UTC, MarkLodato commented on controls/attestations.md
> +[../docs/attestation_model.md](../docs/attestation-model.md) and on
Oops! Shouldn't it always be a hyphen?

2022-07-25 13:57 UTC, joshuagl commented on controls/attestations.md
> +[../docs/attestation_model.md](../docs/attestation-model.md) and on
It should 🤦 . Fixed in 9b52b49

(this took an embarrassing number of attempts to get right 😆 )

2022-07-25 13:58 UTC, joshuagl commented
Any opinions on rebase vs. squash vs. leave as-is with messy PRs like this?

2022-07-25 14:29 UTC, MarkLodato commented
> Any opinions on rebase vs. squash vs. leave as-is with messy PRs like this?

I'd say rebase if you're up for it, or merge as-is if you don't care. Other PRs are much messier and I've learned to live with an ugly git history (GitHub's model seems to encourage that.)

I don't particularly like the squash option since (IIRC) GitHub provides a barebones commit message and it's too much work for me to recreate a nice commit message. But I'm not opposed to it.

2022-07-25 15:52 UTC, joshuagl commented
I've rebased to clean up commit history, the original (unclean) set of changes is still visible at https://github.com/joshuagl/slsa/commits/joshuagl/attestation-model-unclean

2022-07-26 09:20 UTC, joshuagl commented
I'll leave this for another day for folks to comment, then merge if there aren't any objections or major changes requested.

2022-07-27 09:50 UTC, merged