Create verification summary specification v0.2
slsa-framework/slsa pull request #446
Opened 2022-07-25 21:31 UTC by AdamZWu

Introduces `resource_uri` field in predicate to hold the resource URI used for verification, instead of the statement field `subject.name`.

2022-07-26 10:32 UTC, joshuagl requested changes
I fully support the idea of an explicit field rather than overloading the `name` field in the `subject`. Do you think it's possible to provide more concrete guidance on what the `resource_uri` field should reference? Or is there ambiguity in what this might resolve to, depending on the type of artifact?

2022-07-26 10:32 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +> URI that identifies the resource associated with the artifact being verified.
It would be great if this was a little clearer, we might do that by being more terse, i.e.
```suggestion
> URI that identifies the artifact being verified.
```
or perhaps by being more verbose, maybe even including some design rationale?

2022-07-26 13:15 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +the [materials](https://slsa.dev/provenance/v0.2#materials) of the artifact
Thanks, change applied.

2022-07-26 13:15 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +"_type": "https://in-toto.io/Statement/v0.2",
Sorry, my bad. :P

2022-07-26 13:31 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> URI that identifies the resource associated with the artifact being verified.
IMO the concept of "resource" is a bit different from that of the "artifact", from the supply-chain *internal* perspective.

- A resource identifies a SLSA protected "perimeter", e.g. a storage location, a well-known package name, a cryptographic key material, etc.;
- An artifact is a piece of data that wants to interact with a resource, e.g. stored in a location, claim a package name, signed by a key, etc., but may or may not qualify that interaction.

SLSA verification plays the role of checking the qualification of an artifact *before* it is allowed to interact with a resource. 

After the interaction took place, however, from the supply-chain *consumer's* perspective, "resource" and "artifact" are effectively the same thing, because the interaction above has established bindings between the two.

2022-07-26 13:33 UTC, AdamZWu commented
> Do you think it's possible to provide more concrete guidance on what the resource_uri field should reference? Or is there ambiguity in what this might resolve to, depending on the type of artifact?

Please see my above comments on "resource" vs. "artifact".

IMO the concept of resource is very much wide-open, so `resource_uri` really can be anything, depending on the scenario and needs of supply-chain protections.

2022-07-26 15:59 UTC, MarkLodato commented
Q: Do we need a new version for this, or can/should this be a backwards compatible change to v0.1? I know that old clients can just ignore the new field without chaning any information, but I guess the question is what to do if they were relying on the old `subject.name` field.

2022-07-26 17:18 UTC, AdamZWu commented
> Q: Do we need a new version for this, or can/should this be a backwards compatible change to v0.1?

Since it is not a pure addition of new fields, maybe it is appropriate to bump up the version?

2022-07-27 13:37 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +Attestations](https://github.com/slsa-framework/slsa/blob/main/controls/attestations.md),
Pulled upstream and applied link changes.

2022-07-27 13:50 UTC, AdamZWu commented
Rebased from the latest head and squashed previous revisions.

2022-07-29 17:53 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> URI that identifies the resource associated with the artifact being verified.
Hi @joshuagl, I wonder whether this address your concern on "resource"?

Compared with VSA, I think the "resource" concept is more relevant to the topic of policy, maybe we can leave the more verbose explanations in there, and link to that doc when it becomes available?

2022-08-03 16:54 UTC, joshuagl commented
> Q: Do we need a new version for this, or can/should this be a backwards compatible change to v0.1? I know that old clients can just ignore the new field without chaning any information, but I guess the question is what to do if they were relying on the old `subject.name` field.

Somewhat related to this question, should we mark v0.2 as a draft? We did this with the core spec in the past so that we could collect several changes together before making a new release.

2022-08-04 15:26 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> URI that identifies the resource associated with the artifact being verified.
Sounds good. Resolving for now.

2022-08-04 15:27 UTC, AdamZWu commented
> should we mark v0.2 as a draft?

Sounds good to me, will revise.

2022-08-04 21:56 UTC, AdamZWu commented
- Renamed to v0.2-draft
- Pulled the latest changes from master

2022-08-05 10:42 UTC, joshuagl requested changes
Overall, this looks good to me as a draft. Thanks for the iterations! 

I don't think we should be redirecting to VSA v0.2 until it's no longer a draft, though.
I'd like to see a review from @TomHennen, as he's proposed as code owner for the VSA in #449.

I think we should file a follow-on issue to ensure we do provide more guidance around `resource_uri`.

2022-08-05 10:42 UTC, joshuagl commented on docs/verification_summary/index.html
> +  <link rel="canonical" href="v0.2-draft">
I think we should continue to redirect to 1.0 until this is non-draft, WDYT?

2022-08-05 10:42 UTC, joshuagl commented on docs/verification_summary/index.md
> +redirect_to_url: v0.2-draft
Same comment here, I think this change is premature.

2022-08-05 10:42 UTC, joshuagl commented on docs/verification_summary/v0.1.md
> +"predicateType": "https://slsa.dev/verification_summary/v0.1",
Whoops! Thanks for fixing this.

2022-08-05 13:30 UTC, TomHennen commented
> I'd like to see a review from @TomHennen, as he's proposed as code owner for the VSA in #449.

Oh yes, I probably should have mentioned at the outset that I've been working pretty closely with Adam on this and suggested he submit this PR.  So I thought my review would be a conflict of interest in a way.  Next time I'll comment initially saying that I support it but that I'd like another review as well.

So yes, I approve of this change.  Keeping it as draft for perhaps the couple weeks makes sense to me.  We're starting to use this more internally and may identify some other helpful changes.

2022-08-08 17:00 UTC, AdamZWu commented on docs/verification_summary/index.html
> +  <link rel="canonical" href="v0.2-draft">
Ah sure, reverted.

2022-08-08 17:00 UTC, AdamZWu commented on docs/verification_summary/index.md
> +redirect_to_url: v0.2-draft
Reverted.

2022-08-08 17:01 UTC, AdamZWu commented on docs/verification_summary/v0.1.md
> +"predicateType": "https://slsa.dev/verification_summary/v0.1",
:D

2022-08-08 17:01 UTC, AdamZWu commented
Revised and rebased.

2022-08-11 09:42 UTC, joshuagl requested changes
Apologies for so much seemingly trivial back and forth on this, but I'd like to be very clear that this is not the final v0.2 so I've suggested an extra warning in the spec text itself and removing the redirect.

2022-08-11 09:42 UTC, joshuagl commented on docs/verification_summary/v0.2-draft.md
> +---
Let's try and ensure any readers are very aware that this is not yet final, we had text similar to this in the v0.2-draft provenance spec:
```suggestion
---

**IMPORTANT:** This is a DRAFT version of the VSA spec that is **subject to
change.** Once this version is finalized, the "-draft" suffix will be removed.
For the latest stable version, see [v0.1][0.1].

```

2022-08-11 09:42 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +sitemap: false
I'm not convinced it makes sense to redirect from a seeming final versioned url to a draft 🤔

2022-08-11 12:26 UTC, AdamZWu commented on docs/verification_summary/v0.2-draft.md
> +---
Sounds good. Thanks~

2022-08-11 12:29 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +sitemap: false
This is for coherency to the "predicateType" URI, i.e. make it point to something that has meaningful content, instead of 404. I think with the latest additional disclaimer banner there should not be misunderstandings. WDYT?

2022-08-11 15:09 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +sitemap: false
For the 2.0-alpha of the provenance spec we had an alpha-specific TypeURI, i.e. https://github.com/slsa-framework/slsa/commit/a2786e93540d8ec5db20a19b96aad9886a843c3e. I think we should do the same here and have added some suggestions in-line in the PR, WDYT?

2022-08-11 15:24 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +sitemap: false
Sure, sounds good.

2022-08-11 15:25 UTC, AdamZWu commented
Adopted suggestions and rebased.

2022-08-11 15:32 UTC, TomHennen approved these changes

2022-08-11 15:33 UTC, joshuagl approved these changes
Thanks for working through this!

2022-08-11 15:41 UTC, merged