Update Mike Lieberman's affiliation
slsa-framework/slsa pull request #450
Opened 2022-07-27 18:50 UTC by mlieberman85

2022-07-27 19:14 UTC, joshuagl approved these changes

2022-07-27 19:16 UTC, joshuagl commented
DCO check failed because the patch is missing a signed-off-by.

Could you please `git commit --amend -s` and force push?

2022-07-27 19:16 UTC, joshuagl requested changes
DCO check needs addressing

2022-07-27 19:26 UTC, 06kellyjac approved these changes

2022-08-03 15:02 UTC, mlieberman85 commented
Woops, I somehow missed the notification here. Will update.

2022-08-03 20:41 UTC, inferno-chromium approved these changes

2022-08-03 20:59 UTC, trishankatdatadog approved these changes

2022-08-03 22:19 UTC, joshuagl approved these changes

2022-08-03 22:20 UTC, merged