Add `input_attestations` to VSA and bump up to v0.2
slsa-framework/slsa pull request #468
Opened 2022-08-17 17:38 UTC by AdamZWu

2022-08-18 02:06 UTC, TomHennen requested changes
Thanks for doing this Adam!

Can you update the PR description to reference the issues this PR addresses and maybe describe it a bit more?

I'd also like to get @joshuagl's thoughts.

2022-08-18 02:06 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +> The collection of attestation bundles that are used to perform verification.
I wonder if instead of "The collection of attestation _bundles_" this should be the collection of "_attestations_"?

2022-08-18 02:06 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +> The URI of the attestation bundle used to perform verification.
Can you indicate what it means if this field is unset?  Probably just that the verifier doesn't know of a URI where the attestation is available?

2022-08-18 02:06 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +`input_attestations[*].digest` _object ([DigestSet]), optional_
Should the digest be required?  It should always be available if inputs_attestations is non-empty.  It seems like it would be odd to have attestations listed here without digests, What would be the point?

2022-08-18 02:06 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +      "uri": "https://example.com/provenances/example-1.2.3.tar.gz.intoto.jsonl",
I'm not sure if we want to address this here, but it's possible that example-1.2.3.tar.gz could be rebuilt with new attestations at some point.  If so the referenced digest below might not match.

We could:
1. Indicate that this is a possibility in the docs for the URI field.
2. Use the digest of the attestation in the URI to make it unambigious.
3. Something else?

2022-08-18 13:32 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +      "uri": "https://example.com/provenances/example-1.2.3.tar.gz.intoto.jsonl",
Since we don't dictate how the supply chain must provide attestation bundles, I think the best we can do is to provide sufficient mechanism to *allow* unambiguous identification of the data?

That is, in the current specs, we consider "a URI + a digest" should be sufficient for the systems that adopt this specs to resolve and locate any attestation bundles. How or whether they use them, we don't care.

If we get feedback that these two fields are insufficient, we can add more.

2022-08-18 13:50 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +`input_attestations[*].digest` _object ([DigestSet]), optional_
Since all attestations are individually signed, having another checksum around them doesn't provide protection for their integrity or correctness of verification.

So, to me, the digests here seem only serve the purpose of providing a locator.

And if that is the case, if a URI already provides sufficient information (e.g. content addressable URI), digests are not necessary.

2022-08-18 14:04 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> The collection of attestation bundles that are used to perform verification.
This is a potential clarification point.

I think we are running into a limitation of current SLSA specs.
Since here we are dealing with data retrieval, it involves storage and transportation, which is not well defined yet: https://slsa.dev/attestation-model#recommended-suite

The furthest I can go is Bundle, and I feel this *may be* OK -- but I think if we go further up, e.g. use attestations, we'd run into more ambiguities and potentially could exert unnecessary practical restrictions.

For example, if each `input_attestations` entry is one attestation, would that mean every attestation should have its own URI? Would that pose toil for systems that store all attestations in a single place?

Let's say we allow multiple attestations to share a URI, I think this creates another toil -- in order to identify each attestation, they have to be individually digested and put into a separate entries, but who would use this information? The verifier already has its own internal logic to determine what attestation to use; And each attestation is already signed, so re-digest them won't have any security benefit either...

2022-08-18 14:13 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> The collection of attestation bundles that are used to perform verification.
Fixed.

2022-08-18 14:16 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> A verifier MAY utilize this field to record information for facilitating location of the attestations,
Good point. Adopted except the following:

> It SHOULD omit any attestations that were not relevant to making the verification decision.

There may be practical difficulties for attestations that come in bundles. We know that not all attestations in a bundle wre used during a verification. So unless a verifier reconstructs bundles after every verification to only contain attestations used (which probably has no security benefit), this may not be achievable.

2022-08-18 14:16 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> The URI of the attestation bundle used to perform verification.
Good point. Done.

2022-08-18 14:16 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> The URI of the attestation bundle used to perform verification.
Done.

2022-08-18 14:20 UTC, AdamZWu commented
Applies some suggested changes, squashed and rebased.

2022-08-18 16:11 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +> The collection of attestation bundles that are used to perform verification.
I'm fine with leaving it as referring to the bundle (but I'd like @MarkLodato and @joshuagl's thoughts).

If we do leave it as bundle can you be even more explicit about what the digest is of?  E.g. "the contents of the bundle as provided to the verifier" or something like that?  Not sure if that helps.  Perhaps it's clear enough as is?

2022-08-18 16:15 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +`input_attestations[*].digest` _object ([DigestSet]), optional_
Even though the URI could be content addressable that's no guarantee that it is and since we always have the ability to compute the digest of the thing we may as well require it.  That would allow users to verify if the bundle they got from the URI is the same one the verifier used.

Also, by requiring it we make it easier on people that want to use it.  They can always depend on the digest, even if URI isn't always present.

2022-08-18 18:42 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +`input_attestations[*].digest` _object ([DigestSet]), optional_
I think your points are valid.

However, I am a bit concerned whether they may be unnecessarily restrictive -- the attestation bundle specs does not have requirements on the order of the items, but by requiring digest verification on all attestation bundle here, we implicitly added a restriction that is not part of the attestation bundle spec.

2022-08-23 12:57 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +`input_attestations[*].digest` _object ([DigestSet]), optional_
Let's chat when you're free. I think we can work this out.

2022-08-23 13:18 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +`input_attestations[*].digest` _object ([DigestSet]), optional_
Look forward to reading the outcome of that discussion here.

2022-08-23 13:21 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +`input_attestations[*].digest` _object ([DigestSet]), optional_
Perhaps it's more in the spirit of distributed development to try to do it all on GitHub?  We'd certainly document the result of the discussion here.  Also, FYI it will probably be a week before @AdamZWu is free.

2022-08-23 13:53 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +> and the decision may or may not be based on any attestations.
What is the expected value/presence of this field for this use-case as described in the purpose section?
> allows software publishers to keep the details of their build pipeline confidential while still communicating that some verification has taken place. 

In that scenario a decision is made with attestations but the attestations are not publicly available to users of the VSA.

2022-08-23 13:53 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +> A present but empty field indicates the decision was made with no attestation.
Having three ways to define the `input_attestation` field feels prone to error in verifiers and generators. I wonder whether this option, that the decision was made with no attestation, should be an explicit field?

2022-08-23 13:56 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +`input_attestations[*].digest` _object ([DigestSet]), optional_
It's perhaps unreasonable to expect all discussion to happen here, but having any decision or results documented here would be most useful. Thanks.

2022-09-01 15:28 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> A verifier MAY utilize this field to record information for facilitating location of the attestations,
Discussed separately and agreed that we can leave out the "should omit" specification as implicit.

2022-09-01 15:32 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> The collection of attestation bundles that are used to perform verification.
Discussed with @TomHennen and agreed that we keep the specification at attestation level, and do not mention bundle -- practically attestations may be stored in a bundles, or in other forms, we don't need to be prescriptive.

The URI is simply associated with the data fetching, so if we have multiple attestations in a bundle, then there could be multiple entries with the same URI, and the digests are used as identifier to tell apart different attestations.

2022-09-01 15:38 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +      "uri": "https://example.com/provenances/example-1.2.3.tar.gz.intoto.jsonl",
Per discussion with @TomHennen, we took option 2.

2022-09-01 15:47 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> A present but empty field indicates the decision was made with no attestation.
I think my writing made it feel more complicated. :P Rephrased the description and PTAL~

2022-09-01 15:48 UTC, TomHennen requested changes

2022-09-01 15:48 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +> (An empty collection indicates the decision was made without attestation.)
nit: ... made without attestations

2022-09-01 15:48 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +> an attestation.
nit: the attestation

2022-09-01 15:48 UTC, TomHennen commented on docs/verification_summary/v0.2.md
> +> An absent field indicates the verifier does not know how the attestation was fetched
nit: does not know where to fetch the attestation

2022-09-01 15:52 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> and the decision may or may not be based on any attestations.
I feel it is an orthogonal matter.

VSA could always refer to the attestation used if the verifier supports this feature; As to whether those attestations are available to which group of users:

Option 1: The vendor can control attestation access via ACLs on the URI serving side;
Option 2: The vendor can choose to not disclose the URI (which is optional).

2022-09-01 15:54 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> (An empty collection indicates the decision was made without attestation.)
Done.

2022-09-01 15:54 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> an attestation.
Done.

2022-09-01 15:54 UTC, AdamZWu commented on docs/verification_summary/v0.2.md
> +> An absent field indicates the verifier does not know how the attestation was fetched
Done.

2022-09-01 15:56 UTC, TomHennen commented
Thanks Adam!  This addresses all my issues.  We should still make sure @joshuagl is happy with this change before merging.

2022-09-06 10:09 UTC, joshuagl approved these changes
I pointed out a couple of minor nits, but this looks good to me. Thanks for working through the review with me!

2022-09-06 10:09 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +    -   Added optional `input_attestations` field;
Nit: let's use periods at the end of these lines to better match the change history of the provenance spec.
```suggestion
    -   Added `resource_uri` field.
    -   Added optional `input_attestations` field.
```

2022-09-06 10:09 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +> A present but empty field indicates the decision was made with no attestation.
Thanks, that does make it less complicated. My mental model of what use-cases these different scenarios satisfy has also improved, LGTM.

2022-09-06 10:09 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +> and the decision may or may not be based on any attestations.
Understood and I agree. Thanks.

2022-09-06 10:09 UTC, joshuagl commented on docs/verification_summary/v0.2.md
> +> (An empty collection indicates the decision was made without attestations.)
Nit: let's not make this a parenthetical?
```suggestion
> An empty collection indicates the decision was made without attestations.
```

2022-09-06 13:23 UTC, AdamZWu commented
> I pointed out a couple of minor nits, but this looks good to me. Thanks for working through the review with me!

Thanks, Joshua! Accepted suggestions and squashed commits.

2022-09-09 08:51 UTC, joshuagl commented
@TomHennen I think we're waiting for your review on this one.

2022-09-11 16:46 UTC, TomHennen approved these changes
Looks good, thanks everyone!

2022-09-11 17:41 UTC, merged