Blog post for slsa-github-generator generic GA
slsa-framework/slsa pull request #471
Opened 2022-08-22 03:09 UTC by ianlewis

Adds a blog post about the slsa-github-generator generic workflow and
it's general availability. This is a follow on to the previous blog post
on slsa-github-generator's Go functionality published on Jun 20.

2022-08-22 14:38 UTC, laurentsimon commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +         # The expected release tag of the artifact
nit: indentation

2022-08-22 14:38 UTC, laurentsimon approved these changes
Thanks!

2022-08-22 22:48 UTC, mlieberman85 commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +Provenance is then created, signed by the workflow, and attached to your build. The generic generator workflow will also optionally upload the provenance to a GitHub release. You can read more about
Can you clarify that the jsonl file will be needed for verification?

2022-08-22 23:41 UTC, ianlewis commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +Provenance is then created, signed by the workflow, and attached to your build. The generic generator workflow will also optionally upload the provenance to a GitHub release. You can read more about
Updated to clarify that the jsonl file is what's generated and used in verification. Let me know if it needs to be updated further.

2022-08-22 23:51 UTC, mlieberman85 approved these changes
LGTM

2022-08-23 00:30 UTC, sethmlarson commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +Popular projects like [urllib](https://github.com/urllib3/urllib3), [ko](http://github.com/google/ko), [jib](https://github.com/GoogleContainerTools/jib), [grpc-gateway](https://github.com/grpc-ecosy
urllib3*, not urllib

2022-08-23 00:32 UTC, ianlewis commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +Popular projects like [urllib](https://github.com/urllib3/urllib3), [ko](http://github.com/google/ko), [jib](https://github.com/GoogleContainerTools/jib), [grpc-gateway](https://github.com/grpc-ecosy
Oops! thanks!

2022-08-23 00:35 UTC, varunsh-coder commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +Tools like this are becoming necessary as we see a rise in malicious actors taking advantage of the open source community's trust. Some [recent attacks](https://www.bleepingcomputer.com/news/security
I am not sure if using the recent news about cloned repos is a good context for this blog post. The owner of cloned repo can also generate and store provenance in the `release` for the cloned repo. If one validates provenance, it will come out fo be fine. Moreover, there is no evidence anyone even used the cloned repos. 

Would it be better to use an actual attack as context?

2022-08-23 00:41 UTC, ianlewis commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +Tools like this are becoming necessary as we see a rise in malicious actors taking advantage of the open source community's trust. Some [recent attacks](https://www.bleepingcomputer.com/news/security
Yes, in this case catching the issue would require verifying the provenance against the correct repo. Your point is taken and I will rewrite using a better example.

2022-08-23 11:35 UTC, sethmlarson requested changes

2022-08-23 11:35 UTC, sethmlarson commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +    contents: read # Needed for API access
I believe `contents: write` is required for the generic builder: https://github.com/slsa-framework/slsa-github-generator/pull/758

cc @laurentsimon

2022-08-23 23:59 UTC, ianlewis commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +    contents: read # Needed for API access
I tested it at the time I wrote the docs but I'll test it again. I can't think of what it is needed for off the top of my head.

2022-08-24 02:10 UTC, laurentsimon commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +    contents: read # Needed for API access
It's needed to push releases https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/generator_generic_slsa3.yml#L32
There's currently no permission to upload release assets. (we have this in a wish list for GH).
The permissions are computed statically, not at runtime.

2022-08-24 02:13 UTC, ianlewis commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +    contents: read # Needed for API access
Yeah, I figured out that it became necessary after we added support for uploading to releases. I'm in the process up updating the post now.

2022-08-24 02:54 UTC, ianlewis commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +    contents: read # Needed for API access
Updated.

2022-08-24 02:55 UTC, ianlewis commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +Tools like this are becoming necessary as we see a rise in malicious actors taking advantage of the open source community's trust. Some [recent attacks](https://www.bleepingcomputer.com/news/security
I updated this paragraph. Let me know if it needs any further changes.

2022-08-24 03:14 UTC, laurentsimon commented
@MarkLodato is OOO. Any additional feedback? @joshuagl @kimsterv?

2022-08-24 03:14 UTC, ianlewis commented
Also would like approval from @asraa as well as her name is in the author line.

2022-08-24 05:11 UTC, varunsh-coder commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +Tools like this are becoming necessary as we see a rise in malicious actors taking advantage of the open source community's trust. Some [recent attacks](https://www.bleepingcomputer.com/news/security
Looks much better now!

2022-08-26 14:52 UTC, laurentsimon commented
Any further comments before we can merge this PR?

2022-08-26 14:58 UTC, varunsh-coder commented
> Thanks everyone for the thorough reviews. Any further comments before we can merge this PR?

Do you want to mention the recent pypi phishing and related unauthorized publishing of packages in the examples? Just a suggestion. no other comments from my side.

2022-08-26 15:01 UTC, laurentsimon commented
> > Thanks everyone for the thorough reviews. Any further comments before we can merge this PR?
> 
> Do you want to mention the recent pypi phishing and related unauthorized publishing of packages in the examples? Just a suggestion. no other comments from my side.

We already have examples in the text, but we can add one more. Do you have a link in mind you think we should add?

2022-08-26 15:13 UTC, varunsh-coder commented
> > > Thanks everyone for the thorough reviews. Any further comments before we can merge this PR?
> > 
> > 
> > Do you want to mention the recent pypi phishing and related unauthorized publishing of packages in the examples? Just a suggestion. no other comments from my side.
> 
> We already have examples in the text, but we can add one more. Do you have a link in mind you think we should add?

This one https://www.bleepingcomputer.com/news/security/pypi-packages-hijacked-after-developers-fall-for-phishing-emails/? I know there are already examples, which is why this might not be needed. At the same time, this is more recent and top of mind.

2022-08-26 16:07 UTC, inferno-chromium commented
Thank you @mlieberman85 for your review. I think this only needs one reviewer, but leaving for any other final comments from steering committee for another day (it was shared earlier in the week).

2022-08-29 03:32 UTC, ianlewis commented
> > > > Thanks everyone for the thorough reviews. Any further comments before we can merge this PR?
> > > 
> > > 
> > > Do you want to mention the recent pypi phishing and related unauthorized publishing of packages in the examples? Just a suggestion. no other comments from my side.
> > 
> > 
> > We already have examples in the text, but we can add one more. Do you have a link in mind you think we should add?
> 
> This one https://www.bleepingcomputer.com/news/security/pypi-packages-hijacked-after-developers-fall-for-phishing-emails/? I know there are already examples, which is why this might not be needed. At the same time, this is more recent and top of mind.

I thought the same thing when this came out. I added a note referencing this most recent incident.

2022-08-29 14:49 UTC, melba-lopez commented
> Thank you @mlieberman85 for your review. I think this only needs one reviewer, but leaving for any other final comments from steering committee for another day (it was shared earlier in the week).

@inferno-chromium where was this blog draft shared? I don't believe there was a SLSA meeting last week, so trying to understand if it was in a different medium that I did not see.

2022-08-29 15:20 UTC, inferno-chromium commented
> > Thank you @mlieberman85 for your review. I think this only needs one reviewer, but leaving for any other final comments from steering committee for another day (it was shared earlier in the week).
> 
> @inferno-chromium where was this blog draft shared? I don't believe there was a SLSA meeting last week, so trying to understand if it was in a different medium that I did not see.

This was shared on both slsa and tac openssf slack and here in the repo. We haven't needed discussions in SLSA meetings before. Feel free to take a look and let us know how would like to proceed.

2022-08-29 15:23 UTC, asraa approved these changes
LGTM!

2022-08-29 15:23 UTC, asraa commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +In order to enable the greatest number of OSS projects to make use of SLSA, we are announcing General Availability of the generic generator workflow. The generic generator workflow allows OSS project
```suggestion
In order to enable the greatest number of OSS projects to make use of SLSA, we are announcing General Availability of the [generic generator workflow](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/generic). The generic generator workflow allows OSS projects to build artifacts using their own custom GitHub Actions workflows that support seamless provenance generation. SLSA provenance for those artifacts can be generated by simply adding a new job step. We think this is the easiest way for projects using any language or build tools to add provenance generation to their build pipeline.
```

2022-08-29 15:23 UTC, asraa commented on docs/_posts/2022-08-29-slsa-github-workflows-generic-ga.md
> +go install github.com/slsa-framework/slsa-verifier@v1.2.0
```suggestion
go install github.com/slsa-framework/slsa-verifier/cli/slsa-verifier@v1.3.0
```

2022-08-30 00:06 UTC, merged