Blog post for EO and the recent OMB memo
slsa-framework/slsa pull request #489
Opened 2022-09-26 21:03 UTC by hepwori

Adds a blog post with an educational plain-english summary of the implications of the recent OMB memo following the Executive Order on Improving the Nation’s Cybersecurity. 

Signed-off-by: Isaac Hepworth <isaac.hepworth@gmail.com>

2022-09-26 22:18 UTC, kimsterv commented
lgtm

2022-09-27 13:53 UTC, joshuagl approved these changes
Nice work.

2022-09-27 13:53 UTC, joshuagl commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +5. See how SLSA can help! Read the previous posts [SBOM + SLSA: Accelerating SBOM success with the help of SLSA](https://slsa.dev/blog/2022/05/slsa-sbom) and [SLSA for Success: Using SLSA to help ach
```suggestion
5. See how SLSA can help! Read the previous posts [SBOM + SLSA: Accelerating SBOM success with the help of SLSA](https://slsa.dev/blog/2022/05/slsa-sbom) and [SLSA for Success: Using SLSA to help achieve NIST’s SSDF](https://slsa.dev/blog/2022/06/slsa-ssdf).
```

this list item was the only one that didn't use a period.

2022-09-27 13:53 UTC, joshuagl commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +Last week the White House Office of Management and Budget (OMB) issued [a memorandum](https://www.whitehouse.gov/wp-content/uploads/2022/09/M-22-18.pdf) requiring every Federal agency to comply with
Perhaps better to use a date, rather than "last week" – who knows when folks are reading.

2022-09-27 17:24 UTC, hepwori commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +Last week the White House Office of Management and Budget (OMB) issued [a memorandum](https://www.whitehouse.gov/wp-content/uploads/2022/09/M-22-18.pdf) requiring every Federal agency to comply with
Ack, good catch thanks. Updated.

2022-09-27 17:34 UTC, MarkLodato requested changes
Nice! A few style nits but overall content is good.

2022-09-27 17:34 UTC, MarkLodato commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +Last week the White House Office of Management and Budget (OMB) issued a memorandum setting firm and aggressive timelines for implementation of guidelines stemming from the EO, and you might reasonab
nit: link to the memorandum here?

2022-09-27 17:34 UTC, MarkLodato commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +You probably heard about [EO 14028](https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/), the “Executive Order on Improvin
suggestion: "You probably heard about" may put off readers who have not heard in fact heard about it or who don't know the details. Instead, consider using "You may have" and then adding a brief explanation of what it is, e.g.:

"You may have heard about ..., which sets minimum supply chain security standards for all software consumed by the US government."

2022-09-27 17:34 UTC, MarkLodato commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +After a [request for comments](https://www.ntia.gov/files/ntia/publications/frn-sbom-rfc-06022021.pdf) in **June 2021**, the US Department of Commerce [issued in July 2021](https://www.ntia.gov/blog/
nit: use relative links to blog posts throughout the article, e.g. `[blog post on SLSA and SBOMs](2022-05-02-slsa-sbom.md)`.

2022-09-27 17:34 UTC, MarkLodato commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +---
Please run `npm run format` (or `npm run lint`) and fix any issues identified. For example, extra blank lines.

2022-09-27 17:34 UTC, MarkLodato commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +If your software is sold to, or used by, the US Federal government then your ears should be pricking up about now. Starting next year you will be expected, for each major version of each software pro
optional: You might want to add a second paragraph noting that even if this doesn't apply to you now, there's a decent chance your customers will start demanding the same thing within the next few years, so you may want to get ahead of the game.

2022-09-27 17:35 UTC, MarkLodato commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +---
Or just see the [failing check](https://github.com/slsa-framework/slsa/actions/runs/3137676841/jobs/5096147744) if you don't feel like running npm.

2022-09-27 17:35 UTC, hepwori commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +Last week the White House Office of Management and Budget (OMB) issued a memorandum setting firm and aggressive timelines for implementation of guidelines stemming from the EO, and you might reasonab
Done!

2022-09-27 17:48 UTC, hepwori commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +After a [request for comments](https://www.ntia.gov/files/ntia/publications/frn-sbom-rfc-06022021.pdf) in **June 2021**, the US Department of Commerce [issued in July 2021](https://www.ntia.gov/blog/
👍

2022-09-27 17:48 UTC, hepwori commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +If your software is sold to, or used by, the US Federal government then your ears should be pricking up about now. Starting next year you will be expected, for each major version of each software pro
👍

2022-09-27 17:52 UTC, MarkLodato approved these changes

2022-09-27 17:52 UTC, hepwori commented on docs/_posts/2022-09-26-eo-in-plain-english.md
> +---
Ack! Passes the linter now. Thanks :)

2022-09-28 11:38 UTC, merged