adding sigstore to survey
slsa-framework/slsa pull request #501
Opened 2022-10-07 15:28 UTC by johnfosborneiii

Signed-off-by: John Osborne <johnfosborneiii@gmail.com>

2022-10-13 17:37 UTC, MarkLodato commented on controls/survey.md
> +[sigstore]             |          |           |           |  ✓      | ✓          | ✓      | Stable (keyless in development)
Need to define `[sigstore]` in the list of links above.

Also what is the policy component of sigstore?

2022-11-11 14:27 UTC, abacchi commented
https://blog.sigstore.dev/sigstore-ga-ddd6ba67894d
Rekor and Fulcio are GA now so this could also be updated.
Would want to link to the Sigstore website in the MD file

2023-01-30 16:38 UTC, lehors commented on controls/survey.md
> +[sigstore]             |          |           |           |  ✓      | ✓          | ✓      | Stable (keyless in development)
@johnfosborneiii do you care to follow up on this? This is awaiting your input.
Thanks.

2023-02-02 18:06 UTC, johnfosborneiii commented on controls/survey.md
> +[sigstore]             |          |           |           |  ✓      | ✓          | ✓      | Stable (keyless in development)
I updated the pr, for the policy component, you can pass CUE files on the cosign CLI that do data validation of the attestations

2023-02-02 19:40 UTC, developer-guy commented
Another great blog posts about the GA announcement of the sigstore 🥇 
* https://openssf.org/press-release/2022/10/25/sigstore-announces-general-availability-at-sigstorecon/
* https://github.blog/2022-10-25-why-were-excited-about-the-sigstore-general-availability/

2023-02-08 12:53 UTC, lehors commented on controls/survey.md
> +[sigstore]             |          |           |           |  ✓      | ✓          | ✓      | Stable (keyless in development)
@johnfosborneiii but your update doesn't address Mark's point. You need to define the corresponding link line #32 similar to what is done for the other rows:
`[in-toto v2]: https://github.com/in-toto/attestation`
The name simply needs to match and the link will be added automatically.

2023-02-15 17:58 UTC, di requested changes
Two things:

* There's currently a TODO at the bottom of this page that should be removed as part of this PR: https://github.com/slsa-framework/slsa/blame/9e992400619cd81bdbae7768a4fb65bd21997fd4/controls/survey.md#L179
* Each of the following sections go into more detail about how/why a given project does or does not have the quality listed. We should also add "sigstore" to each of them.

2023-02-15 17:58 UTC, di commented on controls/survey.md
> +[sigstore - cosign]    |          |           |           |  ✓      | ✓          | ✓      | Stable
I think this should probably just be "sigstore" -- cosign is just one of many sigstore clients that have the same features.

Also, can you add a link above the table for this? Like this:

```
[sigstore]: sigstore.dev

2023-02-27 03:25 UTC, johnfosborneiii commented on controls/survey.md
> +[sigstore - cosign]    |          |           |           |  ✓      | ✓          | ✓      | Stable
I cleaned up the table, links, etc, but left it as sigstore/cosign because some of the sub projects are still in development (gitsign, sigstore-js) or otherwise impose their own constraints and don't fully support everything that cosign does

2023-03-01 15:03 UTC, lehors commented on controls/survey.md
> +[sigstore]: https://docs.sigstore.dev/
This needs to match the anchor name you are using in the table for the link to work.
```suggestion
[sigstore/cosign]: https://docs.sigstore.dev/
```

2023-03-01 15:03 UTC, lehors requested changes
The link is still broken.

2023-03-27 14:47 UTC, MarkLodato commented
Closing stale PR since this has been open for months with no activity.

2023-03-27 14:47 UTC, closed without merging