SLSA v1.0 levels - depict differences in authentication L2 vs L3
slsa-framework/slsa pull request #509
Opened 2022-10-17 19:38 UTC by abacchi

Signed-off-by: Aaron Bacchi <aaron.bacchi@gmail.com>

Based on this conversation- https://github.com/slsa-framework/slsa/pull/502#discussion_r995886785

My intention for this change is to outline the difference between the weak guarantee in L2 vs the strong guarantee in L3.

I am basing this off of my interpretation of the Authenticated and non-falsifiable requirements today.

Authenticated:
> The provenance’s authenticity and integrity can be verified by the consumer. This SHOULD be through a digital signature from a private key accessible only to the service generating the provenance.

Non-falsifiable: 
> Provenance cannot be falsified by the build service’s users.
> Any secret material used to demonstrate the non-falsifiable nature of the provenance, for example the signing key used to generate a digital signature, MUST be stored in a secure management system appropriate for such material and accessible only to the build service account.
> Such secret material MUST NOT be accessible to the environment running the user-defined build steps.

I like Mark's thoughts here:

> L1 - no authenticity requirement
> L2 - weak guarantee that the provenance came from a service and not a person, but exploitation may be easy
> L3 - strong guarantee that the provenance came from a service, and exploitation is difficult

2022-10-17 19:38 UTC, abacchi commented on docs/spec/v1.0/levels.md
> -    provenance itself, outside the control of the users of the build service.
L3 requirement: _Such secret material MUST NOT be accessible to the environment running the user-defined build steps._

2022-10-18 13:33 UTC, MarkLodato requested changes
Thanks! This is a definite improvement IMO.

/cc @awwad @pkmooreanaconda since this relates to #494.

2022-10-18 13:33 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +SLSA levels are split into *tracks*. Each track has it's own set of levels that
typo: its

```suggestion
SLSA levels are split into *tracks*. Each track has its own set of levels that
```

2022-10-18 13:33 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +-   Secret material used to sign the provenance must not be accessable to the user-defined build steps.
nit/suggestion: merge this with the bullet above since both are implemented by the build service. (Also fix a typo and use consistent phrasing.)

```suggestion
-   Build service implements strong controls to:
    -   prevent runs from influencing one another, even within the same project.
    -   prevent secret material used to signed the provenance from being
        accessible to the user-defined build steps.
```

2022-10-18 14:45 UTC, MarkLodato approved these changes

2022-10-19 20:42 UTC, MarkLodato commented
In the interest of speeding up development, I will merge this now. As always, we can address further comments in subsequent PRs.

2022-10-19 20:42 UTC, merged