SLSA v1.0: update requirements.md for new tracks
slsa-framework/slsa pull request #512
Opened 2022-10-18 21:09 UTC by MarkLodato

- Rename levels Build L1/2/3.
- Delete L4 and associated requirements.
- Delete Source requirements.
- Delete Definitions, which were only needed for L4 and Source.
- Add an indication of a future Build L4 and Source track, linking to the v0.1 requirements. This serves as both insight as to where we might go as well as a hint for readers accustomed to v0.1.

2022-10-25 15:49 UTC, shaunmlowry requested changes

2022-10-25 17:40 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> -interpreted as described in [RFC 2119](https://www.rfc-editor.org/rfc/rfc2119).
I think we still need the RFC 2119 key words? We're still using MUST in the updated 1.0 requirements

2022-10-25 17:40 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +The [prior version](../v0.1/requirements.md) of SLSA defined a "SLSA 4" that
I like "A draft version of SLSA defined a "SLSA L4" that ..."

2022-10-25 21:35 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> -| Source - [Two-person reviewed]       |        |        |        | ✓      |
I think it would be useful to keep the draft Source requirements somewhere, especially for the Go ecosystem that is more source-based than package-based. Maybe we could put them behind a click like the Build L4 requirements.

2022-10-31 18:52 UTC, MarkLodato commented
Friendly ping for reviewers. 😄

2022-11-03 12:11 UTC, joshuagl approved these changes
LGTM (apologies for the delay on review).

2022-11-04 14:30 UTC, MarkLodato commented
Submitting now to move on with the process, but as always, I'm happy to address post-merge comments in another PR.

2022-11-04 14:30 UTC, merged