Clarify SLSA terms and fill in 2/3.
slsa-framework/slsa pull request #52
Opened 2021-06-07 20:49 UTC by dlorenc

This PR makes a few (hopefully) clarifying tweaks to the level and
term definitions:

* Split isolation into two rows, one called "Ephemeral Environments".
  I think we could roll all of this into isolation, but this makes it
  easier to understand and incrementally adopt IMO.
* Define Source Integrity, and leave it as a requirement at L2.
* Define Dependencies, and add it as a requirement at L2.
* Add one new requirement to Common for separate system identities. This
  is important for ephemeral/hermetic builds and system-generated
  provenance to be meaningful at lower levels.
* Move the "Security" requirement to be purely L3. I like having this
  reference a thorough existing compliance standard. We should decide
  which one(s), but that's fine to do later.
* Make Access and SuperUsers a requirement at L2.
* Define Verified History, including examples.
* Clarify the definition of Hermetic, authenticated and Dependencies.

Signed-off-by: Dan Lorenc <dlorenc@google.com>

2021-06-07 21:29 UTC, inferno-chromium approved these changes
LGTM. @MarkLodato @msuozzo - thoughts?

2021-06-07 21:29 UTC, inferno-chromium commented on README.md
> +    strongly authenticated unless they are signed, however Pull Requests are.
Pull requests is common workflow in Github, nice that subsitutes for this.

2021-06-07 21:29 UTC, inferno-chromium commented on README.md
> +    immutable identifiers (specific commit vs. branch/tag, or a tarball along
nit: "instead of" reads slightly better than "vs. "

2021-06-07 21:29 UTC, inferno-chromium commented on README.md
> +*   **[Dependencies]** Provenance records all build dependencies via immutable
Should we call this [Build Dependencies], just dependencies is slightly confusing.

2021-06-07 21:40 UTC, MarkLodato requested changes

2021-06-07 21:40 UTC, MarkLodato commented on README.md
> +  <tr><td>Dependencies              <td>  <td>✓ <td>✓     <td>✓     </tr>
This change (Requiring Deps at 1.5 instead of 3) seems impratical. Doesn't this require hermeticity? For example, how does the GitHub Actions framework know that your Dockerfile did a `apt-get install`?

2021-06-07 21:40 UTC, MarkLodato commented on README.md
> +    strongly authenticated unless they are signed, however Pull Requests are.
Do you mean automatic merge commits generated by GitHub pull requests? (Pull Requests themselves are not part of the version history.)

Also, I assume MFA = multi-factor auth? If so, do those automatic merge commits satisfy that? In other words, how can one know that the signature was from an MFA-enabled account?

2021-06-07 21:40 UTC, MarkLodato commented on README.md
>    <tr><td rowspan="6">Build
this is now 7

2021-06-07 21:40 UTC, MarkLodato commented on README.md
> +    **[Ephemeral]** The build steps ran in an ephemeral environment, such as a
nit: [Ephemeral Environment] and move it above Isolated to match table.

2021-06-07 21:40 UTC, MarkLodato commented on README.md
> +  <tr><td>Ephemeral Environments    <td>  <td>✓ <td>✓     <td>✓     </tr>
nit: Environment (singular)

2021-06-07 21:40 UTC, MarkLodato commented on README.md
> +    influence from other concurrent build instances. Build caches should not
nit: The following wording would be more to the point:
"Build caches, if used, are purely content-addressable."
I think we can leave the hash algorithm bit to the details.

2021-06-07 21:40 UTC, MarkLodato commented on README.md
> -    influence from other build instances, whether prior or concurrent.
I'm a bit confused by the removal of "prior." It sounds to me like build caches could be the result of a prior build, not a concurrent one?

2021-06-07 21:40 UTC, MarkLodato commented on README.md
> +    immutable identifiers (specific commit vs. branch/tag, or a tarball along
How is this clause different from "hermetic"? They sound the same to me.

I interpreted this item as "in the absence of hermeticity, you at least fetch the mutable references over TLS."

2021-06-07 21:40 UTC, MarkLodato commented on README.md
> +*   **[Dependencies]** Provenance records all build dependencies via immutable
I suggest [Dependencies Complete]. The main point of this bullet is that the list of dependencies is complete. This new change makes it seem like the immutability is the important bit, which is misleading. I suggest moving this to an additional sentence at the end.

2021-06-07 21:40 UTC, MarkLodato commented on README.md
> +*   **[System Identity]** Any platform components run as a separate identity
Isn't this (a) build-specific and (b) part of non-falsifiable?

2021-06-07 21:40 UTC, MarkLodato commented on README.md
> +  <tr><td>Access                    <td>  <td>  <td>✓     <td>✓     </tr>
I'm not sure this is practical at SLSA 2. Let's discuss.

2021-06-07 23:49 UTC, msuozzo requested changes

2021-06-07 23:49 UTC, msuozzo commented on README.md
> +  <tr><td>Dependencies              <td>  <td>✓ <td>✓     <td>✓     </tr>
Yeah +1. In general, I'd be fine with some lesser, more informational accounting of dependencies at these lower levels but I agree that this requirement would end up either being a) too difficult to meet or b) not meaningful without additional constraints.

Also, given that we've punted on even discussing dependencies in any sort of depth, I don't think we should include this in the initial set of requirements. I still have a lot of questions and concerns.

2021-06-07 23:49 UTC, msuozzo commented on README.md
> +  <tr><td>Access                    <td>  <td>  <td>✓     <td>✓     </tr>
@MarkLodato This is in reference to just Access or to System Identity, as well?

For Access, the MPA requirement in particular seems tricky. Would that refer to the Build Service? The build workers? (and not to over-complicate this but...) The VCS server?

If we walk back the MPA into a suggestion, I'm fine requiring logged access and locked-down ACLs at L2.

2021-06-07 23:49 UTC, msuozzo commented on README.md
> +*   **[System Identity]** Any platform components run as a separate identity
+1 to point b). I think one implies the other and they're now required at different levels.

2021-06-07 23:49 UTC, msuozzo commented on README.md
> +    immutable identifiers (specific commit vs. branch/tag, or a tarball along
I had assumed this would only apply to the top-level source. "All input artifacts" would be too broad if that's the intent here.

2021-06-07 23:57 UTC, dlorenc commented on README.md
>    <tr><td rowspan="6">Build
Fixed.

2021-06-08 00:01 UTC, dlorenc commented on README.md
> +    strongly authenticated unless they are signed, however Pull Requests are.
Tried to clarify here. Is that more clear?

2021-06-08 00:02 UTC, dlorenc commented on README.md
> -    influence from other build instances, whether prior or concurrent.
Fixed.

2021-06-08 00:03 UTC, dlorenc commented on README.md
> +  <tr><td>Access                    <td>  <td>  <td>✓     <td>✓     </tr>
I thought Common applied to everything - source, build, artifact storage, etc.

2021-06-08 00:05 UTC, dlorenc commented on README.md
> +*   **[Dependencies]** Provenance records all build dependencies via immutable
Completeness and accuracy are orthogonal IMO. The immutability is the important part here. I'll try to clarify in the text: the difference is: what is specified is accurate, vs everything is specified. Both are useful, and accuracy is both important and feasible and lower levels.

2021-06-08 00:07 UTC, dlorenc commented on README.md
> +  <tr><td>Dependencies              <td>  <td>✓ <td>✓     <td>✓     </tr>
Replied above, this is intentional and will aid in the generation of SBOMs, which are likely to be required WAY before hermeticity:

> Completeness and accuracy are orthogonal IMO. The immutability is the important part here. I'll try to clarify in the text: the difference is: what is specified is accurate, vs everything is specified. Both are useful, and accuracy is both important and feasible and lower levels.

2021-06-08 00:13 UTC, dlorenc commented on README.md
> +    immutable identifiers (specific commit vs. branch/tag, or a tarball along
Fixed!

2021-06-08 00:13 UTC, dlorenc commented on README.md
> +    immutable identifiers (specific commit vs. branch/tag, or a tarball along
Yes, anything declared as input artifacts. Basically, no curl | bash.

2021-06-08 00:14 UTC, dlorenc commented on README.md
> +*   **[System Identity]** Any platform components run as a separate identity
Happy to drop - the intention was to cover other parts of the system beyond simply provenance capture, but maybe I'm reading too much into what "Common" is for.

2021-06-08 00:35 UTC, dlorenc commented on README.md
> +    strongly authenticated unless they are signed, however Pull Requests are.
Exactly! Requiring pull requests and 2FA is actually **stronger** than signing with random GPG keys and not using 2FA.

2021-06-08 00:41 UTC, msuozzo commented on README.md
> +  <tr><td>Dependencies              <td>  <td>✓ <td>✓     <td>✓     </tr>
Gotcha. Can we make the ladder a bit more nuanced then? I like the idea of describing completeness on a scale. Maybe "best-effort" or "partial" -> "source and data inputs" -> "all inputs and build tools".

2021-06-08 00:41 UTC, msuozzo commented on README.md
> +*   **[System Identity]** Any platform components run as a separate identity
Maybe this could be moved to the Build header and expressed as something like "Isolated Identity" and have a similar intent: The builder identity doesn't have sensitive access in the system.

I'm not exactly sure where GCB would sit with these constraints, though, at least with the current architecture.

2021-06-08 01:53 UTC, inferno-chromium approved these changes
LGTM with some minor changes below and:

1) I think we need to drop the policy,logging part from table (i thought we discussed dropping it from now, but still see in table)
2) Common table needs concensus, so fine to commit now, but please discuss in meeting/chatroom.

2021-06-08 01:53 UTC, inferno-chromium commented on README.md
> +*   **[System Identity]** Any platform components run as a separate identity
Lets drop this then.

2021-06-08 01:53 UTC, inferno-chromium commented on README.md
> +  <tr><td>Access                    <td>  <td>  <td>✓     <td>✓     </tr>
Can you please note this one down and discuss with @MarkLodato in next meeting. For now, fine to commit.

2021-06-08 01:53 UTC, inferno-chromium commented on README.md
> +  <tr><td>Dependencies              <td>  <td>✓ <td>✓     <td>✓     </tr>
Sure, can add a "*" that this will be on best-effort basis for 1.5 ? And complete for 2 and 3?

2021-06-08 12:54 UTC, dlorenc commented on README.md
> +  <tr><td>Dependencies              <td>  <td>✓ <td>✓     <td>✓     </tr>
Clarified that it is not "complete" until hermeticity.

2021-06-08 12:55 UTC, dlorenc commented on README.md
> +  <tr><td>Access                    <td>  <td>  <td>✓     <td>✓     </tr>
I think we're good now, I dropped this one.

2021-06-08 13:20 UTC, MarkLodato requested changes
I think all of the new 1.5 requirements should be reverted, but if we ultimately agree on adding them, the commit title needs to be updated to reflect that. (Right now it just sounds like it's clarifying, not adding any new requirements.)

2021-06-08 13:20 UTC, MarkLodato commented on README.md
> +  <tr><td>Dependencies              <td> <td>✓<td>✓     <td>✓</tr>
This row should be called "Dependencies Complete" and should only be required only at SLSA 3. It can't be required earlier because it depends on hermeticity.

If you want another "best effort" requirement earlier, (a) that should be another row, (b) that should not be required at 1.5, and (c) how would that work?Let's use GitHub Actions as an example. Since GHA is the one generating provenance, how would it know what the dependencies were if there is no hermeticity? Until that is worked out, I don't think it should be added.

2021-06-08 13:20 UTC, MarkLodato commented on README.md
> +*   **[Ephemeral Environment]** The build steps ran in an ephemeral environment,
We lost the other thread (man, GitHub is a terrible review system). In another thread, @msuozzo brought up that this seems intertwined with Isolated. I'm also not sure we can require it at 1.5. What is the motivation for breaking it up?

2021-06-08 13:20 UTC, MarkLodato commented on README.md
> +    prevents tampering (such as TLS), and these artifacts were referenced using
Lost the original thread. I don't agree with this change. It doesn't make any sense to me. What is "referenced"? Why is it related to TLS?

Overall, I think we should drop this requirement. I don't see how it can be implemented except with hermeticity, and in that case, we can just make that a line-item under hermeticity.

@msuozzo who also commented on this.

2021-06-08 13:21 UTC, MarkLodato commented on README.md
> +*   **[Dependencies]** Provenance records build dependencies via immutable
Whoops, for this this one. Please revert this change. It completely changes the meaning of the requirement.

2021-06-08 13:36 UTC, dlorenc commented on README.md
> +    prevents tampering (such as TLS), and these artifacts were referenced using
> I think all of the new 1.5 requirements should be reverted, but if we ultimately agree on adding them, the commit title needs to be updated to reflect that. (Right now it just sounds like it's clarifying, not adding any new requirements.)

I'm happy to delete requirements completely, but we need to move this forward. Reverting to an undefined state is the wrong direction. If you can suggest clarifications that improve, that works too.

2021-06-08 13:42 UTC, MarkLodato commented on README.md
> +    prevents tampering (such as TLS), and these artifacts were referenced using
Sorry, I thought all of my suggestions were very concrete. Is there something that is confusing?

2021-06-08 13:46 UTC, dlorenc commented
> * I think we need to drop the policy,logging part from table (i thought we discussed dropping it from now, but still see in table)

Also dropped this one for now too.

2021-06-08 14:35 UTC, dlorenc commented
Closing this one for now.

2021-06-08 14:35 UTC, closed without merging