Add definition of specification development stages
slsa-framework/slsa pull request #543
Opened 2022-12-02 14:04 UTC by lehors

To address issue #541 this PR adds a page defining the different stages a specification can be in, setting the expectation that every specification being published will display a "Status of this document" section that communicates to the reader what stage of the development the spec is in and what they can expect from it.

Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>

2022-12-02 15:18 UTC, joshuagl requested changes
Thanks for working on this @lehors! The four stages you've defined here seem prudent and LGTM.

I've left some minor comments inline about how we describe documents/pages/sections of the cohesive SLSA specification.

2022-12-02 15:18 UTC, joshuagl commented on docs/_data/nav.yml
> +
I'm not convinced it makes sense to include this in the navigation menu. Can we just link it from the stage declarations in the spec documents? Is there a reason we should list it here?

2022-12-02 15:18 UTC, joshuagl commented on docs/spec-stages.md
> +layout: specifications
Should this document be part of the spec folder? Should it be versioned along with the rest of the spec (so that we can change it in newer spec versions, if we need to)?

2022-12-02 15:18 UTC, joshuagl commented on docs/spec-stages.md
> +different stages and their meaning.
```suggestion
Specifications go through various stages of development from which you
should have different expectations. This document defines the different
stages the SLSA project uses and their meaning for readers and
contributors.
```

2022-12-02 15:18 UTC, joshuagl commented on docs/spec-stages.md
> +looking at is in.
I think SLSA is a specification, not multiple specifications. Let's refer to individual pages (documents? sections?) of the spec and not individual specs.
```suggestion
Every page of the specification should prominently display a *Status of this
document* section stating which stage the specification page is in.
```

2022-12-02 15:18 UTC, joshuagl commented on docs/spec-stages.md
> +implementation beyond experimentation.
specification --> specification page
```suggestion
This is the first stage of development a page of the specification goes
through. At this point, not much should be expected of it. The page may
be very incomplete and may change at any time and even be abandoned. It is
therefore not suitable for reference or for implementation beyond
experimentation.
```

2022-12-02 15:18 UTC, joshuagl commented on docs/spec-stages.md
> +reviews and feedback are welcome.
```suggestion
A specification page may be published several times during this stage as
work progresses. The status section of the document may provide
additional information as to its development status and whether
reviews and feedback are welcome.
```

2022-12-02 16:32 UTC, lehors commented on docs/_data/nav.yml
> +
Happy to take it out if others feel the same but I see this as akin to some process related document that we should make easy to find.

2022-12-02 16:56 UTC, lehors commented on docs/spec-stages.md
> +layout: specifications
I have to admit that I wasn't sure about that but I think it should apply to all specifications, including the Provenance spec for instance. So it makes sense to have it in a central place.
And as far as versioning is concerned I don't know that we would need to have the different versions available concurrently so until the need arise I wouldn't bother.

2022-12-02 17:01 UTC, lehors commented on docs/spec-stages.md
> +looking at is in.
I was thinking of other specifications like Provenance. Isn't that a specification too?
Besides, I think we're better off not getting too much into the details of how this gets implemented so we keep more freedom on that front: whether to add a link, a popup, an actual section, etc.

2022-12-02 17:03 UTC, joshuagl commented on docs/spec-stages.md
> +looking at is in.
That's a good point, we do imply that provenance and vsa are separate specifications.

2022-12-02 17:04 UTC, lehors commented on docs/spec-stages.md
> +implementation beyond experimentation.
ok, so we seem to have a different mental model here. You're thinking of allowing each page to have its own stage?
I was think of the specification as a whole.

2022-12-02 17:05 UTC, lehors commented on docs/spec-stages.md
> +reviews and feedback are welcome.
same here (mental model/granularity)

2022-12-02 17:48 UTC, MarkLodato requested changes
Thanks, Arnaud!

2022-12-02 17:48 UTC, MarkLodato commented on docs/_data/nav.yml
> +
FWIW I could go either way. Both seem OK to me.

2022-12-02 17:48 UTC, MarkLodato commented on docs/spec-stages.md
> +layout: specifications
I think it makes sense where it is, since it applies to all versions of all specifications.

2022-12-02 17:48 UTC, MarkLodato commented on docs/spec-stages.md
> +looking at is in.
I prefer Joshua's suggestion - every page should display the status. But I suggest that it's just "Status" rather than "Status of this document" since every page within the spec shares the same status (Arnuad's interpretation, below). Maybe also append "linking to the relevant section here"?

2022-12-02 17:48 UTC, MarkLodato commented on docs/spec-stages.md
> +implementation beyond experimentation.
I agree with @lehors and prefer the original wording.

2022-12-02 17:48 UTC, MarkLodato commented on docs/spec-stages.md
> +reviews and feedback are welcome.
same (agree with @lehors)

2022-12-02 17:48 UTC, MarkLodato commented on docs/spec-stages.md
> +## Proposed Specification
nit: I find "Specification" in the status to be awkward. (I realize that this matches the W3C and IETF usage, but it doesn't seem to fit well here.)

Any thoughts on any of the following alternatives?

- "Proposed" or "In Review"
- "Published", "Accepted", or "Stable"

2022-12-02 17:48 UTC, MarkLodato commented on docs/spec-stages.md
> +possible if they might adversely impact implementations.
I think "final" and the restrictions on changes are a bit too restrictive. We may continue to clarify the specification without version bumps, but we won't change the meaning.

2022-12-02 17:48 UTC, MarkLodato commented on docs/spec-stages.md
> +## Retired
Should we split "Outdated" from "Abandoned"? The former is still a perfectly valid specification that people can continue to rely on (just not the latest version) while the latter should not be used.

2022-12-03 11:04 UTC, lehors commented on docs/spec-stages.md
> +looking at is in.
I'm happy to change to just "Status" and I agree with having it on every page with a link to the definition. I wouldn't get that level of details on how we implement this here though but I will add it since you guys prefer it.

2022-12-03 11:10 UTC, lehors commented on docs/spec-stages.md
> +## Proposed Specification
For what it's worth that's not how W3C and IETF call them but we're not bound to them anyway so no problem there. Plus I have to admit I wasn't sure about using "Specification" in the status either so I'm good with dropping it.
I don't really feel strongly about those but I quite like "In Review" and "Stable".

2022-12-03 11:10 UTC, lehors commented on docs/spec-stages.md
> +possible if they might adversely impact implementations.
Ok, I dropped final.

2022-12-03 11:12 UTC, lehors commented on docs/spec-stages.md
> +## Retired
It really depends on whether we are actually fine with people keeping on using an old version or whether we'd rather try to get them moving to the newer version. I was assuming the latter but it's worth some discussion.

2022-12-05 11:44 UTC, joshuagl commented on docs/_data/nav.yml
> +
OK, let's leave it as is.

2022-12-05 11:45 UTC, joshuagl commented on docs/spec-stages.md
> +reviews and feedback are welcome.
WFM

2022-12-05 17:19 UTC, sudo-bmitch commented on docs/spec-stages.md
> +used. It has been either rendered obsolete by a newer version or
Consider softening the language here:

```suggestion
This stage indicates that the specification is no longer maintained.
It has been either rendered obsolete by a newer version or
```

2022-12-05 17:31 UTC, MarkLodato commented on docs/spec-stages.md
> +## Proposed Specification
👍

2022-12-05 17:32 UTC, MarkLodato commented on docs/spec-stages.md
> +## Retired
From the meeting today:

- Keeping "Retired" is OK with me. Others may have an opinion, but I defer to Arnaud to make the decision.
- Let's soften the wording in the paragraph. Instead of "should not be used", rather something like "is no longer maintained" and something about new uses should prefer the newer version?

2022-12-12 14:40 UTC, lehors commented on docs/spec-stages.md
> +## Retired
Ok, I applied the change to "is no longer maintained". I think that should do.

2022-12-12 16:51 UTC, MarkLodato approved these changes

2022-12-15 20:58 UTC, MarkLodato commented
Looks like this needs a merge conflict resolution. @lehors would you mind doing that? @joshuagl is on vacation now so we can submit without his approval.

2022-12-16 12:13 UTC, lehors commented
> Looks like this needs a merge conflict resolution. @lehors would you mind doing that? @joshuagl is on vacation now so we can submit without his approval.

Done.

2022-12-16 14:16 UTC, abacchi approved these changes
I like it- the four stages are very appropriate.

2022-12-16 14:17 UTC, mlieberman85 approved these changes
lgtm

2022-12-16 15:40 UTC, MarkLodato approved these changes

2022-12-16 15:41 UTC, merged