docs: add blog post on GCB slsa provenance verification
slsa-framework/slsa pull request #544
Opened 2022-12-02 16:48 UTC by asraa

@laurentsimon @ianlewis @sanastos @r2wend2 @olivekl 

This year, GCB announced reaching SLSA level 3 requirements for provenance, which included generating non-falsifiable provenance. We integrated support for verification for cloud builders in slsa-verifier, and created a blog post announcing it. Please let me know if you have any comments!

Signed-off-by: Asra Ali <asraa@google.com>

2022-12-02 18:15 UTC, laurentsimon approved these changes
Thanks!

2022-12-02 18:15 UTC, laurentsimon commented
@slsa-framework/slsa-steering-committee PTAL

2022-12-02 20:02 UTC, MarkLodato requested changes
Overall LGTM, just some nitpicks.

2022-12-02 21:36 UTC, asraa commented on docs/_posts/2022-12-02-gcb-slsa-verification.md
> +provenance_summary:
Ah, yes. That makes sense. This is the YAML human readable summary that GCB outputs, but it would be confusing to the SLSA reader who's familiar with the JSON statements.

2022-12-02 21:38 UTC, asraa commented on docs/_posts/2022-12-02-gcb-slsa-verification.md
> +IMMUTABLE_IMAGE="${UNVERIFIED_IMAGE%:*}@"$(crane digest "${UNVERIFIED_IMAGE}")
For some reason the linter dislikes putting $'s where there is no output, but let me see if I can finagle it. I also agree, the `$` are more readable

```
docs/_posts/2022-12-02-gcb-slsa-verification.md:62:1 MD014/commands-show-output Dollar signs used before commands without showing output [Context: "$ UNVERIFIED_IMAGE="us-central..."]
```

2022-12-02 22:03 UTC, asraa commented on docs/_posts/2022-12-02-gcb-slsa-verification.md
> +IMMUTABLE_IMAGE="${UNVERIFIED_IMAGE%:*}@"$(crane digest "${UNVERIFIED_IMAGE}")
I resolved to remove all, and followed suggestions to display outputs through comments per https://arcticicestudio.github.io/styleguide-markdown/rules/code.html#no-shell-code-dollar-sign

2022-12-05 05:22 UTC, mlieberman85 approved these changes
LGTM!

2022-12-05 11:44 UTC, joshuagl requested changes
LGTM, I left a few minor suggestions and a question – should this be a guest post as it's mostly about GCB?

2022-12-05 11:44 UTC, joshuagl commented on docs/_posts/2022-12-02-gcb-slsa-verification.md
> +is_guest_post: false
Should this be a guest post? According to the [contribution guidelines](https://github.com/slsa-framework/governance/blob/ff056c911c70670f867c2dc6cdf2307175c4296a/6._Contributing.md?plain=1#L93) in our governance docs:
> Guest Blog Post are considered to be from a single person/organization that is sharing how they are implementing/applying SLSA in their respective project/organization.

2022-12-05 11:44 UTC, joshuagl commented on docs/_posts/2022-12-02-gcb-slsa-verification.md
> +At SLSA Level 3, users have assurance that the metadata content is authentic, tamper-proof, and not altered by the project maintainers. The build definition and configuration is verifiably derived fr
Nit: add backticks around `recipe` field name to match the use of code formatting in other mentions of provenance fields.
```suggestion
At SLSA Level 3, users have assurance that the metadata content is authentic, tamper-proof, and not altered by the project maintainers. The build definition and configuration is verifiably derived from definitions stored in versioned source control systems (known as “[build-as-code](https://slsa.dev/spec/v0.1/requirements#build-as-code)”). So in order to describe the full top-level build instructions, GCB now identifies the build configuration stored in git, the `entrypoint`, often named [cloudbuild.yaml](https://cloud.google.com/build/docs/configuring-builds/create-basic-configuration).  A record of all user-controlled parameters ([substitutions](https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values)) to the build is also provided in the provenance’s `recipe`.
```

2022-12-05 11:44 UTC, joshuagl commented on docs/_posts/2022-12-02-gcb-slsa-verification.md
> +  "slsaProvenance": {
```suggestion
  "predicate": {
```
This should be "predicate" to fit the in-toto attestation spec: https://github.com/in-toto/attestation/blob/3b9f1a206317c015986b5ba9c96196303d24053c/spec/README.md#statement

2022-12-05 11:44 UTC, joshuagl commented on docs/_posts/2022-12-02-gcb-slsa-verification.md
> +      "arguments": {...},
```suggestion
      "arguments": {
```
the braces in your JSON don't match up, I assume that's because the following lines are part of the arguments dictionary and thus this line should not include a closing brace?

2022-12-05 16:19 UTC, asraa commented on docs/_posts/2022-12-02-gcb-slsa-verification.md
> +  "slsaProvenance": {
Ohhhh thank you, this makes a lot of sense now. GCB prints 3 versions of the provenance in their artifact provenance, and I finally realize why. (1) is the human-readable summary. Then inside the base64-encoded `envelope.payload`, there are two versions of the predicate: https://gist.github.com/asraa/ff2f4c59d3df55941bf2f39f0518535f. (2) is inlined inside `slsaProvenance`, which must have been kept for compatibility, and the (3) is the `predicate`. I should have copied the 3rd.

2022-12-05 16:21 UTC, asraa commented on docs/_posts/2022-12-02-gcb-slsa-verification.md
> +is_guest_post: false
Hmmm yeah, I was thinking that this was showcasing slsa-verifiers support extended support, but I actually think the focus is on GCB's SLSA implementation, and that we can use a SLSA tool to verify it. I'm happy with that change.

2022-12-05 17:04 UTC, joshuagl approved these changes
LGTM, thanks!

2022-12-06 00:05 UTC, laurentsimon commented
@MarkLodato any further comments?
We'd like to have you LGTM before merging. Thanks!

2022-12-06 02:40 UTC, MarkLodato approved these changes

2022-12-06 03:04 UTC, laurentsimon commented on docs/_posts/2022-12-05-gcb-slsa-verification.md
> +IMMUTABLE_IMAGE="${UNVERIFIED_IMAGE%:*}@"$(crane digest "${UNVERIFIED_IMAGE}")"
fixed the double quote. Thanks.

2022-12-06 03:04 UTC, laurentsimon commented
Thanks everyone for the review. Merging it it.

2022-12-06 03:05 UTC, merged