Add information about in-toto to the SLSA website
slsa-framework/slsa pull request #551
Opened 2022-12-12 20:22 UTC by adityasaky

This PR adds some information about in-toto and its relationship to SLSA.

2022-12-12 20:24 UTC, adityasaky commented
Just noticed a rendering issue because of the link in the FAQ title. Fix incoming.
![image](https://user-images.githubusercontent.com/8928778/207147104-b92c471b-a0a6-4a38-99c0-7aa518b85b39.png)

2022-12-12 20:27 UTC, adityasaky commented
Fixed!

2022-12-12 22:09 UTC, MarkLodato requested changes
Thanks!

2022-12-12 22:09 UTC, MarkLodato commented on docs/spec/v0.1/faq.md
> +Provenance and other attributes are expressed. Thus, in-toto can be thought of
in-toto is a recommendation, not a requirement

(same in the v1.0 page)

```suggestion
Provenance and other attributes are recommended to be expressed. Thus, in-toto can be thought of
```

2022-12-12 22:09 UTC, MarkLodato commented on docs/index.md
> +                These look at the builds, sources and dependencies in open source or commercial software. Starting with easy, basic steps at the lower levels to build up and protect against advanced
nit: I'm not sure this makes sense here. This front page, and this paragraph in paragraph in particular, is very abstract, so it seems odd to mention a particular technology ehre. Maybe revert this one particular change?

2022-12-12 23:59 UTC, adityasaky commented on docs/index.md
> +                These look at the builds, sources and dependencies in open source or commercial software. Starting with easy, basic steps at the lower levels to build up and protect against advanced
Reverted.

2022-12-13 00:00 UTC, adityasaky commented on docs/spec/v0.1/faq.md
> +Provenance and other attributes are expressed. Thus, in-toto can be thought of
Took a second pass because the original sentence sounded odd when I looked at it again. WDYT?

2022-12-13 14:10 UTC, MarkLodato approved these changes

2022-12-13 14:10 UTC, merged