SLSA v1.0: Add "Verifying Build Systems"
slsa-framework/slsa pull request #568
Opened 2023-01-10 23:15 UTC by kpk47

Addresses #508 .

2023-01-10 23:58 UTC, mlieberman85 commented on docs/spec/v1.0/output.md
> +    -  What controls are in place to detect or prevent the employee from abusing such access? Examples: two-person approvals, audit logging
We might want to call out "workload identities" also as an example as it's a common pattern now to use things like SPIFFE identities to enforce that a workload can't be tampered with, without invalidating the workload.

2023-01-11 17:50 UTC, kpk47 commented on docs/spec/v1.0/output.md
> +    -  What controls are in place to detect or prevent the employee from abusing such access? Examples: two-person approvals, audit logging
Done

2023-01-12 17:24 UTC, JoshuaMulliken requested changes
Overall I think this is great! There are only a few typos that need to be fixed and I think there are some areas that we can improve, especially when it comes to cryptographic secret security

2023-01-12 17:24 UTC, JoshuaMulliken commented on docs/spec/v1.0/verifying_systems.md
> +    -   How does the control plane prevent executors from accessing its cryptographic secrets? Examples: dedicated secret storage, not mounting its own file system partitions on executors
We may want to also mention hardware security modules here

2023-01-12 17:24 UTC, JoshuaMulliken commented on docs/spec/v1.0/verifying_systems.md
> +    -   How do you store the  control plane's cryptographic secrets?
two spaces inbetween "the" and "control"

2023-01-12 17:24 UTC, JoshuaMulliken commented on docs/spec/v1.0/verifying_systems.md
> +-   Managing cryptographic secrets
We may also want to include hardware security modules here. Ideally, it should not be possible to extract secrets from a running environment.

One example question could be:

```
   -   How are secrets protected in memory? Examples: secrets are stored in hardware security modules and backed up in secure cold storage
```

2023-01-12 20:31 UTC, MarkLodato requested changes
This looks great to me! I just have some minor suggestions

2023-01-12 20:31 UTC, MarkLodato commented on docs/spec/v1.0/verifying_systems.md
> +-   How do you defend against cache poisoning attacks? Example: content-addressable storage
nit: CAS might be misleading here - I'm not sure it's sufficient to defend against attacks, and listing it here might encourage the reader to just say "we use a CAS" rather than spelling out what a possible attack is. Maybe just omit it for now?

2023-01-12 20:31 UTC, MarkLodato commented on docs/spec/v1.0/index.md
> +| [Verifying Build Systems](verifying_systems.md) | Guidelines for securing SLSA Build L3+ builders, intended for system implementers. |
nit: other titles use sentence case

```suggestion
| [Verifying build systems](verifying_systems.md) | Guidelines for securing SLSA Build L3+ builders, intended for system implementers. |
```

2023-01-12 22:59 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +Parameters are the external interface to the builder. They must include references to the source to be built and the build definition/script to be executed. They may include instructions to the build
Your interpretation is correct, but I reworded your suggestion to remove the 'must' imperative and avoid referencing Medium Privilege attackers. I don't think we gain much from the reference here, and it breaks the reader's flow by encouraging them to scroll back up the page.

2023-01-12 22:59 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +### Control Plane
Done.

2023-01-12 22:59 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +    -   What are they ways an employee can use privileged access to influence a build or provenance generation? Examples: physical access, terminal access, access to cryptographic secrets
Done.

2023-01-12 22:59 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +    -   How does the control plane prevent executors from accessing its cryptographic secrets? Examples: dedicated secret storage, not mounting its own file system partitions on executors
Done.

2023-01-12 22:59 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +-   Managing cryptographic secrets
Done.

2023-01-12 22:59 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +    -   How do you store the  control plane's cryptographic secrets?
Done.

2023-01-12 22:59 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +-   How do you defend against cache poisoning attacks? Example: content-addressable storage
Done.

2023-01-12 22:59 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +![image](slsa_attack.png)
Done.

2023-01-13 14:30 UTC, abacchi commented on docs/spec/v1.0/verifying_systems.md
> +TODO: Redraw diagrams in the style used by the rest of the site.
@MarkLodato who has created the diagrams before?

2023-01-13 14:32 UTC, abacchi commented on docs/spec/v1.0/verifying_systems.md
> +    -   Build servec insiders without administrative access
Should be "Build service"

2023-01-13 14:51 UTC, abacchi commented
Great work! Thinking about the user experience for someone wanting to fill out the assessment- 
I could see a next step once this is finalized to create some sort of consolidated questionnaire with just the questions for folks to use. That way they wouldn't have to copy and paste different sections from the page.
**Con to this:** now we would need to keep this page and the pure questionnaire in sync any time there is a change.

2023-01-13 17:13 UTC, MarkLodato commented on docs/spec/v1.0/verifying_systems.md
> +#### Prompts for Assessing External Parameters
also: What gives us confidence that there are no additional external parameters that are missing from the provenance, and that a future design change will not violate SLSA assumptions?

(I ask because the new [GHA Variables](https://docs.github.com/en/actions/learn-github-actions/variables) is exactly this type of design change.)

2023-01-13 17:13 UTC, MarkLodato commented on docs/spec/v1.0/verifying_systems.md
> +-   How frequently are cryptographic secrets rotated? Describe the rotation process.
Looks like an accidental de-indent.

```suggestion
    -   How are secrets protected in memory? Examples: secrets are stored in hardware security modules and 
    -     backed up in secure cold storage
-   How frequently are cryptographic secrets rotated? Describe the rotation process.
```

2023-01-13 17:13 UTC, MarkLodato commented on docs/spec/v1.0/verifying_systems.md
>  -   Isolation technologies
suggestion: Add something about isolation between builds of the same tenant or project. Virtually every build system will be protected against cross-tenant compromise, but fewer isolate between individual builds within a project.

2023-01-13 17:13 UTC, MarkLodato commented on docs/spec/v1.0/verifying_systems.md
>  -   Isolation technologies
suggestion: Maybe it's worth calling out explicitly "persistence" explicitly, e.g. "What prevents a malicious build from gaining persistence and influencing subsequent runs of the same build or other builds?"

2023-01-13 17:28 UTC, joshuagl reviewed
Really nice work on this Kris. It looks great overall, I made a few minor comments on clarity and would like to see other's feedback addressed too.

Should we be adding a requirement that all build systems provide this information? My reading of the "Builder Evaluation" section suggests yes. If so, is that follow-on work?

2023-01-13 17:28 UTC, joshuagl commented on docs/spec/v1.0/verifying_systems.md
> +The control plane is the build system component that orchestrates each independent build execution. It is responsible for setting up each build and cleaning up afterwards. The control plane generates
```suggestion
The control plane is the build system component that orchestrates each independent build execution. It is responsible for setting up each build and cleaning up afterwards. At SLSA Build L3+ the control plane generates and signs provenance for each build performed on the system. The control plane is operated by one or more administrators, who have privileges to modify the control plane.
```
I'm worried that folks could read the original phrasing as only L3+ builds are signed, but maybe I'm being overly pessimistic here. My suggestion may not actually help either. :-D

2023-01-13 17:28 UTC, joshuagl commented on docs/spec/v1.0/verifying_systems.md
> +-   How do you defend against cache poisoning attacks?
Might re-phrase this as "How are cache contents validated before use?"

2023-01-13 17:28 UTC, joshuagl commented on docs/spec/v1.0/verifying_systems.md
> +Organizations can either self-attest to their answers or seek an audit/certification from a third party. Questionnaires for self-attestation should be published on the internet. Questionnaires for th
We should probably expand on " All provenance generated by L3+ builders must contain a non-forgeable attestation of the builder's L3+ capabilities with a limited validity period." – what attestation? Why? What period?

This AI could be a TODO

2023-01-13 17:28 UTC, joshuagl commented on docs/spec/v1.0/verifying_systems.md
>  #### Low privilege
+1 to the alternatives

2023-01-13 18:18 UTC, abacchi commented on docs/spec/v1.0/verifying_systems.md
>  #### Low privilege
Considering private projects, I'd recommend to not use "Everyone else" rather something like "Developer" or "Contributor". I feel this could help apply for both public and private projects.
+ 1 for alternatives though.

2023-01-13 18:21 UTC, abacchi commented
> Should we be adding a requirement that all build systems provide this information?

It would make the maintainers' lives easier if the build system vendors were able to provide this to the best of their ability (maintainer may need to fill in some gaps)

2023-01-13 18:23 UTC, abacchi commented on docs/spec/v1.0/verifying_systems.md
> +Organizations can either self-attest to their answers or seek an audit/certification from a third party. Questionnaires for self-attestation should be published on the internet. Questionnaires for th
I like the idea of this - maybe for SLSA 1.1 we could create a verified build system attestation spec :)

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +TODO: Redraw diagrams in the style used by the rest of the site.
Done

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
>  #### Low privilege
Done

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +    -   Build servec insiders without administrative access
Done

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +    -   Access builder maintainers' intranet or other internal communications (e.g. email, design documents).
I was also thinking of this privilege as a way to escalate privileges either through finding and exploiting design flaws or phishing using a build service-internal identity. I agree that it doesn't fit with the rest of the attacker profile, but I'm not sure where best to move it or whether we need it at all.

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +The control plane is the build system component that orchestrates each independent build execution. It is responsible for setting up each build and cleaning up afterwards. The control plane generates
Done, though I used L2+ since that's when the service starts signing provenance.

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +-   How frequently are cryptographic secrets rotated? Describe the rotation process.
Done

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
>  -   Isolation technologies
Done

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
>  -   Isolation technologies
Done

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +    -   What environment is available in executors on creation? How were the elements of this environment chosen?
Done.

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +-   How do you defend against cache poisoning attacks?
Done

2023-01-13 19:47 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +Organizations can either self-attest to their answers or seek an audit/certification from a third party. Questionnaires for self-attestation should be published on the internet. Questionnaires for th
Added as a TODO. I'm hoping to squeeze it into 1.0 if possible.

2023-01-13 20:31 UTC, MarkLodato commented on docs/spec/v1.0/verifying_systems.md
>  #### Low privilege
New wording is "Project contributors". (But it should be singular.)

But that seems overly narrow. An attacker could be someone who is not a contributor at all, no?

2023-01-13 20:36 UTC, MarkLodato approved these changes

2023-01-13 20:36 UTC, MarkLodato commented on docs/spec/v1.0/verifying_systems.md
> +# Verifying Build Systems
nit: use hyphens to separate words, not underscores (e.g. use-cases.md, get-started.md, also that's [Google's style guide](https://developers.google.com/search/docs/crawling-indexing/url-structure)). I suggest waiting until right before merging so that we don't lose comments.

2023-01-13 20:36 UTC, MarkLodato commented on docs/spec/v1.0/verifying_systems.md
> +    -   Remotely access build executors (e.g. via SSH).
suggestion: de-indent, making "Capabilities:" a regular paragraph

```suggestion
#### Project contributors

Capabilities:

-   Create builds on the build service. These are the attacker's controlled builds.
-   Modify one or more controlled builds' external parameters.
-   Modify one or more controlled builds' environments and run arbitrary code inside those environments.
-   Read the target build's source repo.
-   Fork the target build's source repo.
-   Modify a fork of the target build's source repo and build from it.

#### Project maintainer

Capabilities:

-   All listed under "low privilege".
-   Create new builds under the target build's project or identity.
-   Modify the target build's source repo and build from it.
-   Modify the target build's configuration.

#### Build service admin

Capabilities:

-   All listed under "low privilege" and "medium privilege".
-   Run arbitrary code on the build service.
-   Read and modify network traffic.
-   Access the control plane's cryptographic secrets.
-   Remotely access build executors (e.g. via SSH).
```

2023-01-13 20:55 UTC, abacchi commented on docs/spec/v1.0/verifying_systems.md
>  #### Low privilege
Fair point, we are talking about someone who is able to execute the capabilities:

> Capabilities:
> -   Create builds on the build service. These are the attacker's controlled builds.
> -   Modify one or more controlled builds' external parameters.
> -   Modify one or more controlled builds' environments and run arbitrary code inside those environments.
> -   Read the target build's source repo.
> -   Fork the target build's source repo.
> -   Modify a fork of the target build's source repo and build from it.

I suppose they are an "Authenticated User" with those abilities. That would satisfy my concern about private / public projects.

2023-01-13 22:14 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +#### Prompts for Assessing External Parameters
Done

2023-01-13 22:14 UTC, kpk47 commented on docs/spec/v1.0/verifying_systems.md
> +# Verifying Build Systems
Done

2023-01-14 16:17 UTC, abacchi approved these changes

2023-01-15 19:31 UTC, merged