Introduce setting and verifying expectations
slsa-framework/slsa pull request #571
Opened 2023-01-17 17:40 UTC by joshuagl

Introduce to the specification the so far implicit notion that artefacts are automatically verified against a set of expectations (constraints) before use.

* Updates the terminology page to discuss a verification model which includes manual verification, expectations, and automatic verification.
* Starts to flesh out requirements for automatic verification of a package's provenance against known expectations.

This PR is very much a starting point which I hope we can continue to develop in tree on the road to SLSA 1.0.

Fixes: #46

2023-01-18 21:07 UTC, kpk47 commented on docs/spec/v1.0/terminology.md
> +| Automatic Verification | Artifacts are automatically verified by the package ecosystem to ensure that the package's expectations are met before the package is used. |
I would suggest against defining verification in terms of automatic and manual since those are implementation details of _how_ provenance and systems are verified (respectively). I would suggest "Provenance verification" and "Build system verification". Or, if we want the terms to be more distinct, maybe "verification" for provenance and "conformance" for build systems.

2023-01-19 14:31 UTC, lehors commented on docs/spec/v1.0/requirements.md
> +Verifying expectations COULD happen in multiple places within a package ecosystem:
Is the list exhaustive? It seems that you could just not capitalize COULD in this case. Each item in the list has its own MUST, SHOULD or MAY that is sufficient.

2023-01-19 14:31 UTC, lehors commented on docs/spec/v1.0/terminology.md
> +| Automatic Verification | Artifacts are automatically verified by the package ecosystem to ensure that the package's expectations are met before the package is used. |
Maybe instead of Automatic vs Manual this should be something like Systematic vs Occasional?
Systematic verification would generally be automatic and Occasional manual but not necessarily.

2023-01-20 11:19 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +There are several approaches a package ecosystem could take to setting expectations, for example:
Good feedback, thanks. I am trying to say there are several approaches, here are two possibilities. I will remove the use of implicit and explicit.

2023-01-20 11:20 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +The package ecosystem MUST ensure that expectations are non-falsifiable, that is secure against attacks which would enable use of a package which was:
I was purposefully trying not to be too prescriptive here.

2023-01-20 11:24 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +Verifying expectations COULD happen in multiple places within a package ecosystem:
Great feedback, thanks both! The list is not exhaustive, it's some example places that expectations can be verified. The only hard requirement is that expectations are verified (where they exist). I will lowercase COULD hear, remove all of the RFC 2119 capitalised keywords from the list, and add a more explicit statement that expectations MUST be verified.

2023-01-20 11:28 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +-   during package upload the registry SHOULD verify that the package's provenance matches any known expectations for the package before accepting the package into the registry.
agreed, I am removing the use of SHOULD here. It was intended to indicate that a package ecosystem might not verify during upload, not that it should accept packages with provenance that doesn't match.

2023-01-20 11:29 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +The package ecosystem SHOULD default to denying use of packages, only allowing packages if there exists provenance for the package which matches the known expectations.
Yeah, I fully support this pattern and I think the text allows for it implicitly (SHOULD default to deny, not MUST). I'm happy to call it out explicitly, if that's preferred.

2023-01-20 11:44 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +There are several approaches a package ecosystem could take to setting expectations, for example:
I've rephrased the examples in the list in 6c7884567ce530e9a4a73e8844f6cbabbdfe248c.

2023-01-20 11:54 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +The package ecosystem SHOULD default to denying use of packages, only allowing packages if there exists provenance for the package which matches the known expectations.
I've updated earlier sections in a way that I think makes it clear that the npm approach is fully supported by the spec, do you think we need to add something more explicit?

2023-01-20 12:11 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +| Automatic Verification | Artifacts are automatically verified by the package ecosystem to ensure that the package's expectations are met before the package is used. |
I like systematic vs occasional, but I think the explicit "build system verification" and "provenance verification" terms are clearer so I've made edits to use those. WDYT?

2023-01-20 14:08 UTC, lehors reviewed
Added a few comments and suggestions for improvement.
Hope this helps.

2023-01-20 14:08 UTC, lehors commented on docs/spec/v1.0/requirements.md
> +Verifying expectations COULD happen in multiple places within a package ecosystem:
LGTM.

2023-01-20 14:08 UTC, lehors commented on docs/spec/v1.0/terminology.md
> +| Automatic Verification | Artifacts are automatically verified by the package ecosystem to ensure that the package's expectations are met before the package is used. |
I think your edits address the problem.

2023-01-20 14:15 UTC, lehors commented
One more thing: is the use of "known" in "known expectations" intended to convey that there may be cases where expectations defined by the producer are not known and requirements related to the consumption of packages only apply in cases where these are known?

Otherwise I suggest changing from "known expectations" to "specified expectations", or "defined expectations".

2023-01-20 14:50 UTC, lehors commented on docs/spec/v1.0/requirements.md
> +Verification MUST ensure that the `BuildType` and `ExternalParameters` in the provenance match the known expectations. The package ecosystem MAY allow an approved list of `ExternalParameters` to be i
By the way, I realize  "unrecognized" isn't wrong per se but the rest of the spec uses the American spelling so I think we should be consistent.

2023-01-20 15:24 UTC, MarkLodato requested changes
Thanks! Sorry for the delay in reviewing. I think this is a great start!

2023-01-20 15:24 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +The package ecosystem SHOULD default to denying use of packages, only allowing packages if there exists provenance for the package which matches the known expectations.
I think there is confusion over what "default" means, since there are two defaults at play:

- Opt-in vs opt-out on a per-package-name basis: how do you handle packages that have no explicit SLSA configuration? I think that is up to the ecosystem. I'm guessing SLSA would not recommend one vs the other. IIUC this is what Kris was talking about.

- If a package *is* opted in, then effectively the implementation MUST be implemented such that it only considers the package [version?] as meeting a SLSA level if there exists some provenance that meets the expectations. In other words: (1) omitting provenance results in a deny; (2) if there are multiple provenance attestations, the system accepts any combination that satisfy the expectations. I believe that's what this sentence was trying to explain?

2023-01-20 15:24 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +Verification MUST ensure that the `BuildType` and `ExternalParameters` in the provenance match the known expectations. The package ecosystem MAY allow an approved list of `ExternalParameters` to be i
Also need to add something about having a pre-configured map from builder ID to SLSA level. OK to leave as a TODO.

2023-01-20 15:36 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +Verification MUST ensure that the `BuildType` and `ExternalParameters` in the provenance match the known expectations. The package ecosystem MAY allow an approved list of `ExternalParameters` to be i
Absolutely right, I try to stick to en_US when working on SLSA but failed here. Thanks for catching it.

2023-01-23 13:00 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +#### Expectations
Yes, great point. I'll add a paragraph here and may even mention this in the terminology page too.

2023-01-24 21:48 UTC, joshuagl commented
Thank you all for the excellent review and suggestions. I have made several changes to try and address feedback from each of you. Please take another look.

I plan to rebase on `main` once the review is done, so that comments/discussion are not lost.

2023-01-24 23:48 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +    do not match the known expectations. **TODO:** shoul we expand to emphase
```suggestion
    do not match the known expectations. **TODO:** should we expand to emphasize
```

2023-01-24 23:48 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +trusted builder id's to SLSA level, and that the `BuildType` and
Should we also require that the provenance's level is one of levels the builder ID is trusted to produce?

2023-01-24 23:48 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +All package ecosystem verifiers will require a pre-configured map from
In this context does "pre-configured" mean "configured prior to verification"? If so, maybe we should make that explicit.  Or maybe it's simpler to drop "pre-configured" and say "require a mapping".

2023-01-24 23:48 UTC, kpk47 commented on docs/spec/v1.0/terminology.md
> +| Provenance verification | Performed automatically on cluster nodes before execution by querying the expectations database. |
Verifying provenance in this way doesn't seem to match the verification model diagram above, but it does match the text description here and in requirements.md. Maybe we need two diagrams: one for the workflow where verification prevents downloading bad packages (the diagram we already have), and one for the workflow where verification prevents executing bad packages (this scenario).

2023-01-25 10:37 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +    do not match the known expectations. **TODO:** shoul we expand to emphase
well, that's embarrassing. thanks for catching.

2023-01-25 10:43 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +All package ecosystem verifiers will require a pre-configured map from
I agree that it's simpler to drop, I will do so.

2023-01-25 10:45 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +| Provenance verification | Performed automatically on cluster nodes before execution by querying the expectations database. |
Good observation. Mark suggested (in https://github.com/slsa-framework/slsa/pull/571#discussion_r1082586444) that we replace the diagram with "the diagram at the bottom of [What is the purpose of SLSA policy](https://docs.google.com/document/d/1X30O8jlxNP-_n0oTQo_b-c-VwmGeX8y7cHhmw075D04/edit#)" – WDYT?

Can we do that as a follow-on PR?

2023-01-25 11:49 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +trusted builder id's to SLSA level, and that the `BuildType` and
Do you mean to explicitly require that a verifier ensures that the provenance meets provenance [generation requirements](https://slsa.dev/spec/v1.0/requirements#provenance-generation) and that the provenance includes the fields required to satisfy the stated level in the mapping?

2023-01-25 16:16 UTC, MarkLodato reviewed
Looking good!

2023-01-25 16:16 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> +Verification in SLSA is performed in two ways. Firstly, the build system is
Q: Should we use different terms to avoid confusion? Perhaps "certification" of the build system and "verification" of the artifact? @lehors FYI

2023-01-25 16:16 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +Expectations SHOULD be set for all packages in a package ecosystem. Where expectations are set, the package ecosystem MUST verify the package's provenance meets the expectations before the package is
Good enough for me.

2023-01-25 16:16 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +The package ecosystem MUST ensure that expectations are non-falsifiable, that is secure against attacks which would enable use of a package which was:
LGTM.

2023-01-25 20:44 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +SLSA level.
This definitely felt lacking, thanks for the suggestions. I've expanded this a bit to include them and also added a TODO to link to more concrete guidance.

2023-01-25 20:44 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +name, whereas provenance is tied to an <dfn>artifact</dfn>. Package ecosystem's
Done

2023-01-25 20:44 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +exists for the artifact, this should result in verification failure.
Agree, this is a MUST for verification. Updated the text.

2023-01-25 20:44 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +    emphasize that the value of monitoring without enforcement is lower?
Thank you!

2023-01-25 20:44 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +All package ecosystem verifiers will require a mapping from `builder` `id` to
Apologies, I had intended to tidy that up before submitting. I've changed to "builder identity" so that we're not relying on the recommended provenance format too much in our requirements.

2023-01-25 20:44 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +Verification MUST ensure that the `builder` `id` is one of those in the map of
Great suggestions, done.

2023-01-25 20:44 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +NOTE: The term <dfn>package ecosystem</dfn> may be interpreted loosely. For
Done.

2023-01-25 20:44 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +
Agreed. TODO added to the list.

2023-01-25 20:44 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
>  **TODO:** Update the requirements to provide guidelines for how to implement,
Done.

2023-01-25 20:44 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +Verification in SLSA is performed in two ways. Firstly, the build system is
I think that would clear things up a lot. Perhaps we should only describe automatic verification of artifacts in this section of the terminology?

2023-01-25 21:11 UTC, joshuagl reviewed
I think I've address all comments except what to do with the model in terminology, thanks again for the rigorous review everyone.

2023-01-25 21:50 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> +Verification in SLSA is performed in two ways. Firstly, the build system is
No, I think talking about both is valuable here because it resolves a source of confusion. I was just thinking of not using the term "verify" to mean both concepts.

2023-01-25 21:50 UTC, MarkLodato approved these changes

2023-01-26 12:05 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +Verification in SLSA is performed in two ways. Firstly, the build system is
I pushed a minor change to the terminology page to start moving towards using certification and verification.

2023-01-26 12:07 UTC, joshuagl commented
@kpk47 I would appreciate you taking a look to ensure your comments are addressed, or at least captured as TODO items, before I squash and merge. Thanks.

2023-01-26 17:55 UTC, kpk47 approved these changes

2023-01-26 17:55 UTC, kpk47 commented on docs/spec/v1.0/terminology.md
> +| Provenance verification | Performed automatically on cluster nodes before execution by querying the expectations database. |
A follow-on PR SGTM

2023-01-26 18:05 UTC, MarkLodato approved these changes

2023-01-26 18:12 UTC, merged