Add SLSA conformance to requirements page
slsa-framework/slsa pull request #572
Opened 2023-01-18 22:52 UTC by kpk47

#515

Signed-off-by: kpk47 <1079282+kpk47@users.noreply.github.com>

2023-01-19 02:26 UTC, laurentsimon commented on docs/spec/v1.0/requirements.md
> +-   the expiration date is strictly later than the time of validation
I don't think this works with for systems that supports key rotation, e.g. SIgstore.

2023-01-19 12:56 UTC, lehors commented on docs/spec/v1.0/requirements.md
> +An auditor SHOULD periodically reassess build systes for conformance.
```suggestion
An auditor SHOULD periodically reassess build systems for conformance.
```

2023-01-19 16:30 UTC, JoshuaMulliken requested changes
I'm thrilled with the progress we've made so far. There are a few areas we can refine to make things even better.

Thanks @kpk47!

2023-01-19 16:30 UTC, JoshuaMulliken commented on docs/spec/v1.0/requirements.md
> +the build system to embed provenance it generates.
small grammar issue. I think it should read as follows:

```
the build system to embed in the provenance it generates.
```

2023-01-19 17:33 UTC, JoshuaMulliken approved these changes

2023-01-19 18:40 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +  non-forgability to belong to the auditor named in the attestation
Done.

2023-01-20 19:25 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +consumer MAY delegate their trust to an auditor.
I wonder if we should be a bit less prescriptive here. Ideally, consumers wouldn't have to do anything to get some amount of protection by default. I imagine most would use whatever trust roots (build system) come by default, or maybe whatever their organization has configured. In some cases consumers might opt-in for higher protection, e.g. only allow SLSA Build L3 unless granted an exception, or configure custom trust roots.

For example, imagine a system that only does verification at publication time. As long as you trust the packaging ecosystem, this would protect all users automatically without any client-side validation. This could be particularly valuable for closed-source applications, where provenance is less meaningful. In this case, I think this should still be considered SLSA even though the consumer does nothing at all.

Maybe this part really should go to the packaging ecosystem section after #571 is implemented? And in that case, I'm not sure "explicitly trusted" is the right word, but more that someone made a security decision that a particular build system (as identified by the provenance) is trusted at a particular level?

2023-01-20 19:39 UTC, laurentsimon commented on docs/spec/v1.0/requirements.md
> +-   the expiration date is strictly later than the time of validation
first question: does "attestation" refers to the auditor's attestation or the "SLSA provenance" attestation?

2023-01-24 19:14 UTC, laurentsimon commented on docs/spec/v1.0/requirements.md
> +-   the expiration date is strictly later than the time of validation
I would say something  to the effect of: "the validity period of the enclosing provenance is within the validity period of the auditor's attestation". Then maybe iterate on what this means for static keys vs ephemeral / rotated keys and leaked keys.

2023-01-24 22:03 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +### SLSA conformance attestations
I've stashed this subheading and will reintroduce it on the 'certification' page when it's ready.

2023-01-24 22:04 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +-   the expiration date is strictly later than the time of validation
Done

2023-01-24 22:07 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
Done.

It's just a link to the verifying systems page for now, but I don't mind expanding if you don't think it would be duplicative.

2023-01-25 19:53 UTC, MarkLodato approved these changes
I'd like to hear @lehors's opinion as well.

2023-01-25 19:53 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +The SLSA Build level describes the minimum bar for isolation strength. For more information on assessing a build system's isolation strength, see [Verifying build systems](verifying-systems.md).
nit: wrap at 80 columns

2023-01-25 19:53 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +An <dfn>auditor</dfn> is an organization or individual that assesses build
optional: should we use "certifies" here? Perhaps we want to rename this role to "certifier" to avoid proliferation of terms?

```suggestion
An <dfn>auditor</dfn> is an organization or individual that certifies build
```

2023-01-26 10:07 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +An <dfn>auditor</dfn> is an organization or individual that assesses build
Certifier is a great suggestion. I anticipate that in many cases the auditor/certifier is the same organisation that produces the build system. Self-certification seems much more reasonable than self-auditing.

2023-01-26 12:57 UTC, lehors reviewed
I must admit that I don't see much value in the AUDITOR section. It merely contains a MAY and a couple of SHOULDs that don't buy us much.

I would much prefer that we scrap this off and instead add that consumers MUST ensure that the build systems they depend on are conformant and that to do so they can either do their own audit leveraging the prompts in the verifying systems or leverage the certification program which lists conformant systems.

We can leave it to the certification program to get into the details of what certifiers are required to do.

2023-01-26 12:57 UTC, lehors commented on docs/spec/v1.0/requirements.md
> +An <dfn>auditor</dfn> is an organization or individual that assesses build
Actually, although I support the goal of limiting the number of different terms being used, I don't think certifier is the right term here because certification is for the benefit of someone else. Self-certification is about telling others that based on your own audit you claim that your implementation is conformant. It is not about telling yourself that someone else's implementation is conformant. It doesn't really make sense to say that a consumer may act as their own certifier.

2023-01-30 22:38 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +The SLSA Build level describes the minimum bar for isolation strength. For more information on assessing a build system's isolation strength, see [Verifying build systems](verifying-systems.md).
Done

2023-01-30 23:19 UTC, merged

2023-01-31 06:58 UTC, lehors commented
@kpk47 I think it was premature to merge this. I said that I thought the AUDITOR section should be deleted and @MarkLodato agreed.

2023-01-31 18:37 UTC, kpk47 commented
I'm so sorry. I'm still not used to tracking code reviews in GitHub and thought that I'd addressed all the open comments. I'll send another PR.