Split 'Requirements' page into 'Producing artifacts' and 'Verifying a…
slsa-framework/slsa pull request #619
Opened 2023-02-16 00:31 UTC by kpk47

…rtifacts'

2023-02-16 00:32 UTC, kpk47 commented
@olivekl I'm doing some restructuring here and would like your review if you have time.

2023-02-16 19:01 UTC, lehors requested changes
I think this is going in the right direction. Thanks!

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/requirements.md
> +> **TODO:** Do we still need this content?
I don't think so? Or, if needed, does it belong on this page? I think it would do better under "Getting Started."

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +Although there is no formal requirement that consumers verify SLSA provenance,
Multiple points:

- The previous section said "the intended audience is system implementers" but this first sentence is about consumers, which is confusing. 
- Is bringing up the idea of "formal requirement" even necessary? 
-  "Third-party verification" is introduced but not included in the table below. 
- The table says the consumer should opt in to verification, but it's not clear from the text what that means or how they'd do it. 

Overall, this section could be clearer about who is actually responsible for what.

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +
+1, are three column needed if all three columns have check marks for all rows?

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +The package ecosystem is responsible for ensuring that consumers only use
A package ecosystem is defined as a set of conventions and tooling. But here a package ecosystem is being given a responsibility. That seems to assume humans behind the ecosystem have the responsibility, not the tooling and conventions.

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +for a given package (assuming the SLSA provenance format) in order to address
assuming it uses the SLSA provenance format?

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +provenance is tied to an *artifact*. Package ecosystem's using the
```suggestion
provenance is tied to an *artifact*. Package ecosystems using the
```

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +It is important to note that expectations are tied to a *package name*, whereas
Will the reader understand the distinction being made here? My best guess is that it means that the expectations for the same artifact can be different in different ecosystems (i.e., with different package names)?

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +Although there is no formal requirement that consumers verify SLSA provenance,
Having read to the end, I think this section could also be more useful if it introduced at a high level the "pipeline" of verification that's in the table below (explaining that the process involves provenance distribution, setting expectations, verifying, and optionally opt-ing in (for consumers).

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +### Setting Expectations
Why is "Provenance distribution" not included as a section?

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +<dfn>Expectations</dfn> define the allowed values for
I'm having a hard time grasping this section. Would it be possible to add a high-level summary of what "setting expectations" means in more general terms, either here or at the start?

2023-02-16 22:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +insider access to any trusted systems. Expectations MUST be sufficient to detect
`Expectations MUST be sufficient to detect
or prevent this adversary from injecting unofficial behavior into the package.
Example threats in this category include building from an unofficial fork or
abusing a build parameter to modify the build. Usually expectations identify
the canonical source repository (which is the main external parameter) and
any other security-relevant external parameters.`

This seems more relevant to the "Setting Expectations" section?

2023-02-17 18:43 UTC, MarkLodato reviewed
I think this split is a good start, but the verifying-artifacts page needs much more work. Hopefully we can align it with https://slsa.dev/provenance/v1#verification?

I'm fine merging something that is a work in progress - just let us know what the bar is for merging and i think we can review to that standard.

2023-02-17 23:55 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +The producer MUST set expectations on how the package ought to be built and then
I've reworded this to take implicit vs explicit expectations into account. I'm not sure we can get around the fact that the verifier controls the expectations format. Maybe we should create an expectations format for v2.0.

2023-02-17 23:55 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +The package ecosystem is responsible for ensuring that consumers only use
Done

2023-02-17 23:55 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +### Setting Expectations
Done

2023-02-17 23:55 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +for a given package (assuming the SLSA provenance format) in order to address
Done

2023-02-17 23:55 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +It is important to note that expectations are tied to a *package name*, whereas
I added some elaboration. Do you think it makes more sense now?

2023-02-17 23:55 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +insider access to any trusted systems. Expectations MUST be sufficient to detect
Done

2023-02-17 23:55 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +rely on the [SLSA certification program](certification.md).
Done

2023-02-17 23:55 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +
I removed the table in favor of more detailed text.

2023-02-17 23:55 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +Although there is no formal requirement that consumers verify SLSA provenance,
I rewrote this section as a high-level overview of process. Thanks for the suggestion!

2023-02-21 12:11 UTC, lehors approved these changes

2023-02-21 20:12 UTC, olivekl commented on docs/spec/v1.0/index.md
> +Using SLSA is a bit like using nutrition labels. It is the software producer's
Yeah, a more universal analogy would be ideal, but the art provenance maps so much more cleanly. I think the way Mark explains it makes it clear even to someone who doesn't interact with the art world. The idea of Sotheby's = package ecosystem, for example, clarifies things more than the grocery store. +1 to moving the Provenance analogy to the Overview.

2023-02-21 21:12 UTC, MarkLodato approved these changes
I'm good with merging this and iterating. More work is needed, but this seems like a good first step.

2023-02-21 21:16 UTC, di commented
I have a review incoming!

2023-02-21 21:19 UTC, di commented on docs/spec/v1.0/requirements.md
> +an authentic artifact. The verifier can set those expectations either implicitly (e.g.
```suggestion
an authentic artifact. The producer can set those expectations either implicitly (e.g.
```

I think? Since we're talking about setting expectations in the "producing artifacts" page, and later we say "the producer MUST meet any expectations they provided to the artifact verifier"

2023-02-21 21:19 UTC, di commented on docs/spec/v1.0/verifying-artifacts.md
> +may also be responsible for providing provenance to consumers.
Not sure I agree with this. I think the responsibility of the ecosystem is to a) reliably redistribute artifacts/provenance, b) make the producers expectations known c) provide tooling that makes safe consumption possible. Other than that, I don't think the ecosystem has any responsibility (or ability) to ensure users only consumer artifacts that meet their expectations.

We might want to soften this to something like the above.

2023-02-21 21:19 UTC, di commented on docs/spec/v1.0/verifying-artifacts.md
> +The package ecosystems MUST distribute provenance for the packages they distribute.
I think the language here is probably too strong -- ecosystem's won't be able to distribute provenance for everything. Should this say something like "must support distribution of provenance if provided", or something simlar?

2023-02-21 21:22 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +It is important to note that expectations are tied to a *package name*, whereas
Much clearer!

2023-02-21 21:41 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +title: Producing artifacts
Done

2023-02-21 21:41 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +The package ecosystems MUST distribute provenance for the packages they distribute.
Done

2023-02-21 21:41 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +may also be responsible for providing provenance to consumers.
Done

2023-02-21 21:41 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +<dfn>Expectations</dfn> define the allowed values for
Done

2023-02-21 21:42 UTC, di approved these changes

2023-02-22 02:10 UTC, merged