Update get-started.md
slsa-framework/slsa pull request #621
Opened 2023-02-16 19:58 UTC by jonvnadelberg

Changing scope of document from achieving SLSA 1 to various SLSA levels depending on build system.

Removed Google Cloud Build as a recommended build system

Added table to end containing known build systems and levels they can obtain.

Reformatted document so it is in simple markdown with extra HTML removed.

2023-02-21 13:35 UTC, lehors requested changes
Thanks, this is better than the previous version but still needs some work. Please, consider the various suggestions I made.

2023-02-21 13:35 UTC, lehors commented on docs/get-started.md
> +These options work with your build system to produce unsigned, formatted provenance. They do not qualify for SLSA 2 because they are unsigned and not run by the hosted server:
```suggestion
The following options work with your build system to produce unsigned, formatted provenance. They do not qualify for SLSA 2 because they are unsigned and not run by the hosted server:
```

2023-02-21 13:35 UTC, lehors commented on docs/get-started.md
> +These options are user-configured inside a hosted service. They observe the build process and produce signed, formatted provenance. These options do not qualify for SLSA 2 because they are configured
```suggestion
The following options are user-configured inside a hosted service. They observe the build process and produce signed, formatted provenance. These options do not qualify for SLSA 2 because they are configured by users, not the hosted service.
```

2023-02-21 13:35 UTC, lehors commented on docs/get-started.md
> +The builders suggested in this guide meet SLSA expectations. If you believe a build option is missing or misclassified, please [open an issue](https://github.com/slsa-framework/slsa/pull/589).
We need to soften this because there is no way to test it yet and no certification program and we should point out that the reason we are discussing specific tools is because they are freely available. Besides, the link is wrong. I suggest something like:
```suggestion
The tools discussed in this guide are freely available and believed to meet SLSA expectations. The [Builder SLSA levels section](#builder-slsa-levels) provides a more complete list. If you think a build option is misclassified or want to add one, please [open an issue](https://github.com/slsa-framework/slsa/issues) or [submit a PR](https://github.com/slsa-framework/slsa/pulls) against this page.
```

2023-02-21 13:35 UTC, lehors commented on docs/get-started.md
> +The following table shows known build software packages and the potential SLSA level they qualify for.  Potential levels are reached with proper provenance.
We really need to be careful here because this may involve some legal liability.
```suggestion
The following table shows known build software packages and the potential SLSA level they are believed to qualify for.  Potential levels are reached with proper provenance. Again, if you think a build option is misclassified or want to add one, please [open an issue](https://github.com/slsa-framework/slsa/issues) or [submit a PR](https://github.com/slsa-framework/slsa/pulls) against this page.

Note that this list is provided "as is". OpenSSF makes no claim as to the reliability of this information. A certification program is under development to provide a more definitive list.
```

2023-02-21 20:51 UTC, olivekl commented on docs/get-started.md
> +SLSA levels are progressive: SLSA 3 includes all the guarantees of SLSA 2, and SLSA 2 includes all the guarantees of SLSA 1. Currently, though, the work required to achieve lower SLSA levels will not
I don't think this is talking about the guarantees of lower levels, but rather the work involved. The current problem is that SLSA 1 requires quite a bit of effort and then you hit a dead end. To move on to SLSA 2, none of the effort from SLSA 1 carries over. And the same for SLSA 3 --- if you adopt FRSCA to achieve SLSA 2, then to meet SLSA 3 you (currently) have to leave FRSCA and adopt GitHub Actions. There's no path from 2 to 3 that would be easier than just starting at 3. 

There's the possibility that users will misunderstand the SLSA levels as steps, and assume that you must start at SLSA 1. Yet in actuality, the easiest option currently is to jump directly to SLSA 3, which gives all the benefits of SLSA 1 and 2, and requires adoption effort only once. It's good to include instructions that warn against that misunderstanding. 

Instead of "future implementations," what about: "will not necessarily accrue toward the work needed for higher levels, since they currently involve adopting different build systems."

2023-02-22 20:25 UTC, lehors commented on docs/get-started.md
> +SLSA levels are progressive: SLSA 3 includes all the guarantees of SLSA 2, and SLSA 2 includes all the guarantees of SLSA 1. Currently, though, the work required to achieve lower SLSA levels will not
All right, now I understand what you're trying to say. Thanks @olivekl 

I agree that this change would make it clearer but I would go a bit further and try to make it a bit less time sensitive by saying something like:

"will not necessarily accrue toward the work needed for higher levels, because achieving a higher level may require migrating to a different build system altogether."

2023-02-22 23:31 UTC, jonvnadelberg commented on docs/get-started.md
> +SLSA levels are progressive: SLSA 3 includes all the guarantees of SLSA 2, and SLSA 2 includes all the guarantees of SLSA 1. Currently, though, the work required to achieve lower SLSA levels will not
Hi @lehors 

I've made the requested changes.  Please check.

2023-02-23 17:11 UTC, lehors requested changes
Thank you, much better!
I just have a final nit - sorry I didn't see it earlier.

2023-02-23 17:11 UTC, lehors commented on docs/get-started.md
> +Containers have a standard place to put the provenance in the OCI container registry. With time, the SLSA community hopes to create standard ecosystem-based repositories for provenance. For now, the
I don't really know what it means to say that "the sigstore bundle that's used currently is semi-standard".
Used by whom? What's a semi-standard? Old standards geezers like myself will wonder. :-)
I suggest avoiding making any claims related to standards which would be hard to backup. And I think it would make sense to capitalized Sigstore and put a link to sigstore.dev:

`Containers have a standard place to put the provenance in the OCI container registry. With time, the SLSA community hopes to create standard ecosystem-based repositories for provenance. For now, the convention is to keep the provenance attestation with your artifact. Though [Sigstore](https://www.sigstore.dev/) is becoming more and more popular, the format of the provenance is currently tool-specific.`

2023-02-23 18:15 UTC, jonvnadelberg commented on docs/get-started.md
> +Containers have a standard place to put the provenance in the OCI container registry. With time, the SLSA community hopes to create standard ecosystem-based repositories for provenance. For now, the
@lehors ok, i changed the sentence.   Would that be all?

2023-02-23 18:17 UTC, lehors commented on docs/get-started.md
> +Containers have a standard place to put the provenance in the OCI container registry. With time, the SLSA community hopes to create standard ecosystem-based repositories for provenance. For now, the
Yes, that's it for me. Thank you!

2023-02-23 18:18 UTC, lehors approved these changes

2023-02-23 18:18 UTC, di commented on docs/get-started.md
> +What differs for each level is the robustness of the build and provenance. For more information about provenance see [https://slsa.dev/provenance/v0.2](https://slsa.dev/provenance/v0.2).
```suggestion
What differs for each level is the robustness of the build and provenance. For more information about provenance see [https://slsa.dev/provenance/](https://slsa.dev/provenance/).
```

I think this should probably just link to the latest version of the spec?

2023-02-23 18:33 UTC, lehors commented on docs/get-started.md
> +What differs for each level is the robustness of the build and provenance. For more information about provenance see [https://slsa.dev/provenance/v0.2](https://slsa.dev/provenance/v0.2).
Good catch.

2023-02-23 19:05 UTC, di approved these changes

2023-03-09 19:16 UTC, merged