Add draft "gcb-triggered-build" buildType.
slsa-framework/slsa pull request #623
Opened 2023-02-17 20:40 UTC by MarkLodato

This buildType is for Google Cloud Build. It only supports "triggers" because those are the ones that are config-as-code, roughly corresponding to the existing "github-actions-workflow" buildType. (Config as code is not strictly required by SLSA v1.0, but without it setting expectations is not practical.)

/cc @prabenzom @bobcatfish @chitrangpatel @khalkie to review from GCB side.

2023-02-23 23:14 UTC, prabenzom commented on docs/gcb-triggered-build/v1.md
> +In BuildTrigger, this corresponds to `gitFileSource` if set, else
For Triggered builds from SCM events (e.g. github push), this is usually set by inferring the repo from the trigger type and the [filename](https://source.corp.google.com/piper///depot/google3/google/devtools/cloudbuild/v1/cloudbuild.proto;rcl=510514760;l=3917) field. From other events (webhook, pubsub, manually run triggers),  we use `gitFileSource`.  I didn't think we fell back to sourceToBuild if gitFileSource isn't set, but is this what you observed during testing?

2023-02-23 23:14 UTC, prabenzom commented on docs/gcb-triggered-build/v1.md
> +commit that triggered the build, for repo-based triggers).
I think this sentence confuses me a bit. I think most of our customers use triggered builds, which means they never set sourceToBuild explicitly in the BuildTrigger. Should we mention repo-based triggers first?

2023-02-23 23:14 UTC, prabenzom commented on docs/gcb-triggered-build/v1.md
> +The `resolvedDependencies` SHOULD contain entries identifying the resolved git
Just curious, for GitHub Actions, was there any additional data (system parameters or resolved dependencies) they thought was worth mentioning if the action was done on a GitHub Enterprise instance?

2023-02-23 23:16 UTC, khalkie commented on docs/gcb-triggered-build/v1.md
> +> **TODO:** Is there a URI we can use for `invocationId`?
I assume this would be the full resource name of the build? (contains project, region and build ID, can be used to view the build logs etc.)

projects/argo-local-khalk/locations/us-west1/builds/d8108272-2655-4c6d-abd1-edeb7a28a601

2023-02-24 17:51 UTC, MarkLodato reviewed
Thanks for the reviews! I tried to address your comments but I'm not 100% confident I fully addressed everything.

2023-02-24 17:51 UTC, MarkLodato commented on docs/gcb-triggered-build/v1.md
> +This field SHOULD be omitted if all subfields are empty, i.e. if the commit is
Reworded. Does that help?

2023-02-24 17:51 UTC, MarkLodato commented on docs/gcb-triggered-build/v1.md
> +commit that triggered the build, for repo-based triggers).
Reworded to be less specific. Does that help?

2023-02-24 17:51 UTC, MarkLodato commented on docs/gcb-triggered-build/v1.md
> +The `resolvedDependencies` SHOULD contain entries identifying the resolved git
Sorry, this is in the context of https://slsa.dev/provenance/v1, which defines `resolvedDependencies` as any artifacts fetched. So we consider the repo URL and ref the parameters, while the actual git commit it resolved to is in `resolvedDependencies`. Does that help?

In terms of SHOULD vs MUST, I was thinking it's a recommendation but that the provenance is still valid if not recorded. MUST seems overly strong. But maybe I'm using MUST and SHOULD incorrectly.

2023-02-24 17:51 UTC, MarkLodato commented on docs/gcb-triggered-build/v1.md
> +The `resolvedDependencies` MAY contain additional artifacts known to be input
See other comment - does https://slsa.dev/provenance/v1 help explain the model?

2023-02-28 03:46 UTC, khalkie commented on docs/gcb-triggered-build/v1.md
> +This field SHOULD be omitted if all subfields are empty, i.e. if the commit is
Yes that makes sense thanks!

2023-02-28 03:46 UTC, khalkie commented on docs/gcb-triggered-build/v1.md
> +Map of (string -> string) containing the substitutions to perform on the Build
Ah I understand now, thanks!

2023-02-28 03:46 UTC, khalkie commented on docs/gcb-triggered-build/v1.md
> +Git reference within `repository` from which the configuration was read, as
Yes I think that does help, also the Resolved Dependencies section does contain the actual commit SHA (which wouldn't match if it was a different underlying repo)

2023-02-28 03:46 UTC, khalkie commented on docs/gcb-triggered-build/v1.md
> +The `resolvedDependencies` MAY contain additional artifacts known to be input
Yes sorry, didn't realize it was already defined elsewhere. Thanks!

2023-02-28 03:46 UTC, khalkie commented on docs/gcb-triggered-build/v1.md
> +The `resolvedDependencies` SHOULD contain entries identifying the resolved git
> In terms of SHOULD vs MUST, I was thinking it's a recommendation but that the provenance is still valid if not recorded. MUST seems overly strong. But maybe I'm using MUST and SHOULD incorrectly.

Thanks, I understand this field now. What would be the case where the provenance would still be valid if it does not have a resolved SHA/commit for the source? I thought this was one of the most important parts. If there is no source? (i.e. it just tags and uploads an image?)

2023-02-28 03:46 UTC, khalkie commented on docs/gcb-triggered-build/v1.md
> +| `repositoryId` | string | The immutable (numeric) ID of `repository` provided by the source control host, if known. |
@prabenzom Are we currently recording (or have access to repositoryId and repositoryOwnerId?

2023-02-28 03:46 UTC, khalkie commented on docs/gcb-triggered-build/v1.md
> +> **TODO:** Is there a URI we can use for `invocationId`?
Yes we could convert the full resource name to a URL as described here (https://cloud.google.com/apis/design/resource_names#resource_name_vs_url)

i.e.

//cloudbuild.googleapis.com/projects/argo-local-khalk/locations/us-west1/builds/d8108272-2655-4c6d-abd1-edeb7a28a601

would become

https://cloudbuild.googleapis.com/v1/projects/argo-local-khalk/locations/us-west1/builds/d8108272-2655-4c6d-abd1-edeb7a28a601

however it requires auth credentials and permissions to the build

2023-03-02 21:45 UTC, MarkLodato commented on docs/gcb-triggered-build/v1.md
> +The `resolvedDependencies` SHOULD contain entries identifying the resolved git
The use case is where an organization wants to verify that the sources came from the official source repository. For example, the FooBrowser software is expected to be built from FooBrowser's official source code repository. To [verify](https://slsa.dev/provenance/v1-rc1#verification), one would check that the `externalParameters.configSource.repository == "https://git.foobrowser.org/browser.git"`. This doesn't require knowing the commit ID.

Recording the commit ID is a good idea for several reasons (debugging, reproducibility, enabling other checks, etc.) but not required for that use case, which is why I thought SHOULD was more appropriate.

2023-03-02 21:45 UTC, MarkLodato commented on docs/gcb-triggered-build/v1.md
> +> **TODO:** Is there a URI we can use for `invocationId`?
Thanks! I added that to the doc but may have made a mistake. PTAL.

2023-03-02 21:45 UTC, MarkLodato commented on docs/gcb-triggered-build/v1.md
> +> project (and/or service account)?
@khalkie @prabenzom Any recommendation here? Or should I omit it for now?

2023-03-06 07:33 UTC, lehors requested changes
Proprietary product specific information does not belong here. This should be published on some Google documentation site instead.

2023-03-06 13:01 UTC, MarkLodato commented
> Proprietary product specific information does not belong here. This should be published on some Google documentation site instead.

We need a place to put community-developed build types to describe proprietary build systems, like this GCB one and the GitHub Actions one we have already submitted. For one, any community plugins that describe the build need a common type even if the builder doesn't official support it, e.g. [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator). Also, there's a chicken-and-egg problem where we need good examples of how to properly write a buildType definition; we can't wait until proprietary build system develop it.

Do you have an alternative recommendation?

2023-03-06 14:28 UTC, lehors commented
Ok, I undertand. I think we need to adopt a distributed system so that we provide people with useful information and yet don't end up having to store every build system documentation on the OpenSSF website. A simple list with a link to the related information would achieve that.

For that matter I don't think the URI used for the build type should be slsa.dev based. It would make more sense to have it specific to each build system. For the GitHub action we should use something that is based on https://github.com/slsa-framework/slsa-github-generator for instance. This way, if/when GitHub ends up creating its own build type there is no ambiguity. They can have it prefixed with some other URI that's under their control without any conflict.

A simple list also makes it very simple for anyone to make a PR to get their build type added to the list and for us to accept it. This is far better than if they have to submit a whole page of documentation that we then have the responsibility to manage.

2023-03-06 16:03 UTC, MarkLodato commented
I just filed #662. Let's discuss there and then update this PR with whatever we decide.

2023-03-06 16:16 UTC, lehors commented
> I just filed #662. Let's discuss there and then update this PR with whatever we decide.

Sounds good. Thanks.

2023-03-20 20:33 UTC, MarkLodato commented
As per #662, I have moved this content to https://github.com/slsa-framework/gcb-buildtypes/tree/main/triggered-build/v1 and sent out #711 to link to it. Closing this PR since it is now obsolete.

2023-03-20 20:33 UTC, closed without merging