SLSA v1 terminology: add Package Model
slsa-framework/slsa pull request #664
Opened 2023-03-06 20:33 UTC by MarkLodato

This defines the minimal terminology needed for Verifying Artifacts. It is based on the [draft proposal](https://docs.google.com/document/d/1yHc3Bcq8fV5sthCcOhhQBd5UC6xfH9UV-NTry56ocD0/edit) that several people contributed to, with some updated wording and a new introduction.

Fixes #520.

2023-03-06 20:44 UTC, TomHennen requested changes
The "Example: Open source language distribution" could use some cleaning up.  It looks like it currently using some ambiguous terms ('package') and some terms to avoid ('package manager').

Otherwise this looks good!

2023-03-06 20:59 UTC, MarkLodato commented
Good point on "package manager". We do need a term for the client-side tooling. Since I can't come up with a better name, I used "package manager client" to avoid ambiguity, but a shorter name would be preferred.

We'll leave cleanup of existing usage to a separate PR.

2023-03-06 21:01 UTC, TomHennen approved these changes

2023-03-07 14:58 UTC, joshuagl approved these changes
This looks good to me. I'm curious for wider feedback.

2023-03-07 14:58 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +informal ecosystems include a linking to a file on a website or distributing
```suggestion
informal ecosystems include linking to a file on a website or distributing
```
"a linking to ..." reads a bit awkwardly

2023-03-07 14:58 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +    <td><a href="https://www.npmjs.com/">npm</a> (Javascript)
```suggestion
    <td><a href="https://www.npmjs.com/">npm</a> (JavaScript)
```

2023-03-07 14:58 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +    <td>Repositry
```suggestion
    <td>Repository
```

2023-03-07 14:58 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +    <td><a href="https://go.dev/ref/mod">go</a>
```suggestion
    <td><a href="https://go.dev/ref/mod">Go</a>
```

2023-03-07 18:14 UTC, olivekl approved these changes
A few minor comments, but LGTM.

2023-03-07 18:14 UTC, olivekl commented on docs/spec/v1.0/terminology.md
> +| Package name | <p>A mutable collection of artifacts that all represent different versions of the same software. This is the primary identifier that consumers use to obtain the software. Therefore,
`Therefore, it is the thing being protected by SLSA.`

Seems like one of the most useful points to emphasize. Is there anything to say that could spell this out a bit more? Or is here not the place?

2023-03-07 18:14 UTC, olivekl commented on docs/spec/v1.0/terminology.md
> +| Publish [a package] | Make an artifact available for use by registering it with the package registry. In technical terms, this means associating an artifact to a package name. This does not necessa
```suggestion
| Publish [a package] | Make an artifact available for use by registering it with the package registry. In technical terms, this means associating an artifact to a package name. This does not necessarily mean making the artifact fully public; an artifact may be published for only a subset of users, such as internal testing or a closed beta. |
```

2023-03-07 19:31 UTC, kpk47 approved these changes

2023-03-07 19:31 UTC, kpk47 commented on docs/spec/v1.0/terminology.md
> +informal ecosystems include a linking to a file on a website or distributing
I'd suggest "a link".

2023-03-07 19:31 UTC, kpk47 commented on docs/spec/v1.0/terminology.md
> +| Package name | <p>A mutable collection of artifacts that all represent different versions of the same software. This is the primary identifier that consumers use to obtain the software. Therefore,
```suggestion
| Package name | <p>The primary identifier referring to a mutable collection of artifacts that all represent different versions of the same software. SLSA protects this identifier from [impersonation? squatting? reuse?].
<p>A package name is specific to an ecosystem + registry and has an official owner/maintainer. It is more general than a specific hash or version and is associated with a “correct” source location. A package ecosystem may group package names into some sort of hierarchy, such as the Group ID in Maven, though SLSA does not have a special term for this. |
```

2023-03-07 19:31 UTC, kpk47 commented on docs/spec/v1.0/terminology.md
> +    <td><a href="https://doc.rust-lang.org/cargo/appendix/glossary.html#crate">Crate</a> (or <a href="https://doc.rust-lang.org/cargo/appendix/glossary.html#artifact">Artifact</a>?)
If I understand your definitions correctly, then this entry should be Artifact. Artifact refers specifically to the compiled binary, whereas Crate is ambiguous and may refer to either the compiled binary or its (bundled?) source code.

2023-03-07 19:31 UTC, kpk47 commented on docs/spec/v1.0/terminology.md
> +    not yet clear which of these constitute the "registry", if either.
How will we clarify which is the registry? Do we lack information about Go, or is the problem that we need to form an opinion on our definitions or model?

2023-03-07 22:34 UTC, di commented on docs/spec/v1.0/terminology.md
> +    not yet clear which of these constitute the "registry", if either.
I think in this case, the registry would be the (one or more) git repositories, because they are the ones that permit/refuse changes to a given package namespace (in this case, the repo itself) based on ownership/access.

2023-03-07 22:34 UTC, di commented on docs/spec/v1.0/terminology.md
> +    <td><a href="https://packaging.python.org/en/latest/glossary/#term-Project">Project</a>
```suggestion
    <td><a href="https://packaging.python.org/en/latest/glossary/#term-Project">Project Name</a>
```
The "project" is really the entire thing. The "project name" is just the mutable name.

2023-03-07 22:34 UTC, di commented on docs/spec/v1.0/terminology.md
> +    <td><em>n/a</em>
```suggestion
    <td><em><a href="https://cloud.google.com/storage/docs/buckets">Bucket</a>.</em>
```
Maybe? Seems to fit to me.

2023-03-07 22:34 UTC, di commented on docs/spec/v1.0/terminology.md
> +    <td><a href="https://doc.rust-lang.org/cargo/appendix/glossary.html#crate">Crate</a> (or <a href="https://doc.rust-lang.org/cargo/appendix/glossary.html#artifact">Artifact</a>?)
I agree, I think this is `Artifact`.

2023-03-14 19:39 UTC, MarkLodato reviewed
Addressed comments. PTAL.

2023-03-14 19:39 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> +| Package name | <p>A mutable collection of artifacts that all represent different versions of the same software. This is the primary identifier that consumers use to obtain the software. Therefore,
Reworded the first half and removed the second half (see other comment).

2023-03-14 19:39 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> +    <td><em>n/a</em>
I don't think so? I think Google (or "GCS") might be the registry here, since it is the entity with control. A bucket is just a unit of the package name, isn't it?

2023-03-14 19:39 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> +    not yet clear which of these constitute the "registry", if either.
After more thought, I argue that it's the module proxy. I updated the text accordingly. PTAL.

2023-03-14 20:30 UTC, kpk47 approved these changes

2023-03-16 00:14 UTC, MarkLodato commented
I'll merge this now since I already got several approvals, but if you have further comments, please let me know and I'm happy to fix in a future PR.

2023-03-16 00:14 UTC, merged

2023-03-22 14:54 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> -
Oh, thanks for spotting this! Sent out #718 to fix.