Edit guiding principles
slsa-framework/slsa pull request #671
Opened 2023-03-07 21:28 UTC by olivekl

Copyedit to make the important principles, reasoning behind them, and benefits stand out more for readers

2023-03-07 21:50 UTC, hayleycd commented on docs/spec/v1.0/principles.md
> +bespoke build systems.
```suggestion
bespoke build systems.
```

2023-03-07 21:50 UTC, hayleycd commented on docs/spec/v1.0/principles.md
> +ensuring that they were produced by trusted systems**.
```suggestion
ensuring that they were produced by trusted systems**.
```

2023-03-07 21:50 UTC, hayleycd commented on docs/spec/v1.0/principles.md
> +amount of central work.
```suggestion
amount of central work.
```

2023-03-07 21:51 UTC, hayleycd commented on docs/spec/v1.0/principles.md
> +credential compromise, and sometimes malicious action.
```suggestion
credential compromise, and sometimes malicious action.
```

2023-03-07 21:51 UTC, hayleycd commented on docs/spec/v1.0/principles.md
> +based on the system's configuration.
```suggestion
based on the system's configuration.
```

2023-03-07 21:51 UTC, hayleycd commented on docs/spec/v1.0/principles.md
> +the form of attestations that the package was built correctly**.
```suggestion
the form of attestations that the package was built correctly**.
```

2023-03-08 17:42 UTC, MarkLodato requested changes

2023-03-08 17:42 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +the form of attestations that the package was built correctly**.
Can we keep the term "defense in depth"? This is a widely used security term that many readers will instantly understand.

2023-03-08 17:42 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +individuals do not have sufficient permission to tamper with the package.
The original said "individuals that are accidentally granted access" because the intent of "configured so that the only path from source to release is through the official channels" is not to grant individuals such access. I think it's probably still valuable to keep that.

2023-03-08 17:42 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +Securely trace all software back to source code.
This drops an important concept:

> rather than individual maintainers who have write access to package registries

Without SLSA, we solely trust the individual maintainers (or their credentials) that the binary we receive matches the source code that we expect and review. SLSA addresses this by removing (or reducing) the need to trust these maintainers.

Could we add this back somehow?

2023-03-08 17:42 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +Establish trust in a small number of systems (such as change management, build, and packaging systems) and then automatically verify the many artifacts produced by those systems.
```suggestion
Establish trust in a small number of systems---such as change management, build,
and packaging systems---and then automatically verify the many artifacts
produced by those systems.
```

2023-03-08 17:42 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +ensuring that they were produced by trusted systems**.
nit: Could we be a bit more verbose here? I find this new version a bit harder to read because it's so terse.

In my mind, the gist of this principle is:

- We have no choice but to trust some number systems.
- It is hard, manual work to harden and verify each such system. (Plus, each system we trust increases attack surface == increases the chance of compromise.)
- It is easy, automatic work to verify that an artifact was produced by such as system.
- Therefore, to scale and to "reduce attack surface", we want to trust a small, limited number of systems and then verify arbitrarily many artifacts (or packages?) produced by those systems. This gives us a near-constant amount of central work (and have a near-constant amount of attack surface) regardless of how many packages we support.
- Contrast this to the alternative, where each package uses its own trusted systems. This would result in a roughly linear scaling of work and attack surface.

Technically all that is there, but I am not sure if it comes across super clearly. Though maybe my worry is unfounded. Might be valuable to get other opinions here.

2023-03-08 17:42 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +decisions.
nit: "the three" makes it sound like there are exactly three, official principles, especially when they're numbered 1-3. I don't think this list is necessarily complete or immutable. Any thoughts on softening this to remove "three" and the numbering below?

2023-03-08 17:42 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +Reason: Trusted computing bases are unavoidable, but analysis to establish that trust is
suggestion: make "Reason:" and "Benefit:" bold so that it stands out more, and maybe consider renaming to "Reasoning" to emphasize it's more about the thinking than an iron-clad argument?

2023-03-08 18:15 UTC, olivekl commented on docs/spec/v1.0/principles.md
> +decisions.
I'll take out the numbers if they're not immutable/complete. I was actually trying to draw attention to the "finalness" by numbering them that way.

2023-03-08 18:18 UTC, olivekl commented on docs/spec/v1.0/principles.md
> +Reason: Trusted computing bases are unavoidable, but analysis to establish that trust is
Done

2023-03-08 19:22 UTC, olivekl commented on docs/spec/v1.0/principles.md
> +the form of attestations that the package was built correctly**.
done

2023-03-08 19:22 UTC, olivekl commented on docs/spec/v1.0/principles.md
> +Securely trace all software back to source code.
added back

2023-03-08 19:25 UTC, olivekl commented on docs/spec/v1.0/principles.md
> +individuals do not have sufficient permission to tamper with the package.
added back

2023-03-08 19:35 UTC, olivekl commented on docs/spec/v1.0/principles.md
> +ensuring that they were produced by trusted systems**.
Your explanation is clearer -- I added text along these lines.

2023-03-09 16:14 UTC, MarkLodato requested changes
Looks good, just a few more suggestions

2023-03-09 16:14 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +trusted system, though, is easy to automate.
Second and third sentence repeat each other. Here's a suggestion to clean up wording (and wrap to 80 columns while we're at it):

```suggestion
**Reasoning**: Trusted computing bases are unavoidable---there's no choice but
to trust some systems. Hardening and verifying systems is difficult and
expensive manual work, and each trusted system expands the attack surface of the
supply chain. Verifying that an artifact is produced by a trusted system,
though, is easy to automate.
```

2023-03-09 16:14 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +The attack surfaces and work to estalish trust does not scale with the number of artifacts produced,
```suggestion
The attack surface and work to establish trust does not scale with the number of artifacts produced,
```

2023-03-09 16:14 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
>  after it has been committed.
suggestion: call out compromised maintainer creds since this is a major risk and also more palatable to people on a team. No one wants to think their colleague is malicious, while credential compromise is widely recognized as a problem.

```suggestion
**Benefits**: Removes the possibility for an individual maintainer---or an
attacker abusing a compromised maintainer's credentials---to tamper with source
code after it has been committed.
```

2023-03-09 16:24 UTC, olivekl commented on docs/spec/v1.0/principles.md
>  after it has been committed.
Done, thanks!

2023-03-09 20:11 UTC, MarkLodato approved these changes

2023-03-09 20:51 UTC, merged