fix: Update links to in-toto attestation spec
slsa-framework/slsa pull request #679
Opened 2023-03-10 01:11 UTC by ianlewis

Signed-off-by: Ian Lewis <ianlewis@google.com>

2023-03-10 01:40 UTC, ianlewis commented on docs/provenance/v1-rc1.md
> +<td>string (<a href="https://github.com/in-toto/attestation/blob/main/spec/v1.0-draft/scalar_field_types.md#typeuri">TypeURI</a>)<td>
Not sure if SLSA v1 should be pointing to the v1.0-draft for in-toto attestations but I assumed so.

2023-03-10 14:47 UTC, MarkLodato approved these changes
LGTM but it would be good to have another reviewer as well

2023-03-10 14:53 UTC, TomHennen commented
I think all the various _type fields in 1.0 should be updated to point to `"_type": "https://in-toto.io/Statement/v1"`

It looks like there are a number of these in various files?

2023-03-13 01:07 UTC, ianlewis commented
> I think all the various _type fields in 1.0 should be updated to point to `"_type": "https://in-toto.io/Statement/v1"`
> 
> It looks like there are a number of these in various files?

I updated this in the doc files related to SLSA v1 (and v1-rc1) (including cue files).

2023-03-14 15:02 UTC, marcelamelara commented on docs/provenance/v1-rc1.md
> +<td>string (<a href="https://github.com/in-toto/attestation/blob/main/spec/v1.0-draft/scalar_field_types.md#typeuri">TypeURI</a>)<td>
Thanks for these updates! We're about to do a tagged release of v1 in-toto attestations (by EOW), so the SLSA docs can probably be updated to point to those instead.

2023-03-15 15:47 UTC, joshuagl commented
Thanks for working on this! there's a mixture of v0.1.0 and v1.0-draft links, per @marcelamelara's comment https://github.com/slsa-framework/slsa/pull/679/files#r1135698487 can we update this PR to only link to v1 once the release is made (some time this week)?

2023-03-16 00:32 UTC, ianlewis commented
> Thanks for working on this! there's a mixture of v0.1.0 and v1.0-draft links, per @marcelamelara's comment https://github.com/slsa-framework/slsa/pull/679/files#r1135698487 can we update this PR to only link to v1 once the release is made (some time this week)?

The mixture was intentional as I believe that SLSA v0.2 (i.e. prior to 1.0) would be technically be using the v0.1.0 versions of the in-toto attestation spec.

I can wait on the PR until the v1 is finalized and update the v1 links then.

2023-03-17 10:32 UTC, joshuagl commented
> > Thanks for working on this! there's a mixture of v0.1.0 and v1.0-draft links, per @marcelamelara's comment https://github.com/slsa-framework/slsa/pull/679/files#r1135698487 can we update this PR to only link to v1 once the release is made (some time this week)?
> 
> The mixture was intentional as I believe that SLSA v0.2 (i.e. prior to 1.0) would be technically be using the v0.1.0 versions of the in-toto attestation spec.

Excellent point, that sounds right to me.

> I can wait on the PR until the v1 is finalized and update the v1 links then.

Thank you!

2023-03-23 03:24 UTC, ianlewis commented
v1 for the in-toto spec was finalized so I hope to clean this up by EOW

2023-03-31 05:54 UTC, ianlewis commented
@MarkLodato @TomHennen Updated and merged with HEAD. PTAL

2023-03-31 14:21 UTC, MarkLodato requested changes
Thanks, Ian! Just two small fixes

2023-03-31 14:21 UTC, MarkLodato commented on docs/provenance/schema/v1/provenance.cue
> +    "predicateType": "https://slsa.dev/provenance/v1",
Let's hold off for now - we'll do this when we mark v1.0 as final

2023-03-31 14:21 UTC, MarkLodato commented on docs/attestation-model.md
> +[attestation bundle]: https://github.com/in-toto/attestation/blob/main/spec/v0.1.0/bundle.md
why not v1?

2023-03-31 18:04 UTC, MarkLodato commented on docs/attestation-model.md
> +[attestation bundle]: https://github.com/in-toto/attestation/blob/main/spec/v0.1.0/bundle.md
pushed a change to fix

2023-03-31 18:04 UTC, MarkLodato commented on docs/provenance/schema/v1/provenance.cue
> +    "predicateType": "https://slsa.dev/provenance/v1",
pushed a fix

2023-03-31 18:04 UTC, MarkLodato approved these changes

2023-03-31 22:15 UTC, marcelamelara approved these changes
Thanks!

2023-03-31 23:19 UTC, ianlewis commented
Thanks for fixing those.

2023-03-31 23:19 UTC, merged