Update docs structure 1
slsa-framework/slsa pull request #683
Opened 2023-03-14 15:26 UTC by olivekl

First in a series of PRs to update docs; see [Issue 672](https://github.com/slsa-framework/slsa/issues/672)

- Move content and create pages according to [Issue 672](https://github.com/slsa-framework/slsa/issues/672)
- No changes to the moved content (content updates are forthcoming in another PR)
- Add descriptive material to pages/sections for clarity about what’s moved
- Add or update Previous/Next nav buttons
Note: some nav buttons are missing because not all files are in the Spec directory yet (will move and add in later PR)

2023-03-14 20:28 UTC, kpk47 approved these changes

2023-03-14 20:28 UTC, kpk47 commented on docs/spec/v1.0/levels.md
> +This page is a descriptiove overview of the SLSA levels and tracks, describing their intent. For the prescriptive requirements for each level, see
```suggestion
This page is a descriptive overview of the SLSA levels and tracks, describing their intent. For the prescriptive requirements for each level, see
```

2023-03-16 12:21 UTC, olivekl commented on docs/spec/v1.0/levels.md
> +This page is a descriptiove overview of the SLSA levels and tracks, describing their intent. For the prescriptive requirements for each level, see
done, thanks!

2023-03-16 13:23 UTC, MarkLodato requested changes

2023-03-16 13:23 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +# Security Levels
nit: seems like capitalization is inconsistent. For example, this one was changed to title case, while index and whats-new were changed to sentence case.

2023-03-16 13:23 UTC, MarkLodato commented on docs/use-cases.md
> +
revert this change (wait until we move the use-cases page)

2023-03-16 13:23 UTC, MarkLodato commented on docs/spec/v1.0/threats.md
>    url: faq
Remove - this is the last page now

2023-03-16 13:23 UTC, MarkLodato commented on docs/spec/v1.0/threats.md
>    url: verifying-systems
should be verifying artifacts

2023-03-16 13:23 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> +  url: future-directions
Need to update future-directions.md to have terminology as the next_page

2023-03-16 13:23 UTC, MarkLodato commented on docs/spec/v1.0/threats-overview.md
> +environment. [TODO: add link to Threats in detail here and bottom]
did you mean to do this now?

2023-03-16 13:40 UTC, MarkLodato commented on docs/spec/v1.0/index.md
> +| [VSA](/verification_summary/v1) | Suggested VSA format and explanation |
```suggestion
| [Provenance](/provenance/v1) | Recommended format for provenance |
| [VSA](/verification_summary/v1) | Recommended format for summarizing verification results |
```

2023-03-16 14:04 UTC, olivekl commented on docs/spec/v1.0/levels.md
> +# Security Levels
thanks for catching -- aiming for sentence case even for titles, right?

2023-03-16 21:39 UTC, MarkLodato approved these changes

2023-03-16 21:40 UTC, merged