Clarify actions between producer and build system
slsa-framework/slsa pull request #685
Opened 2023-03-14 20:00 UTC by arewm

Part of the confusion mentioned in https://github.com/slsa-framework/slsa/issues/657 was related to the separation between producer actions and build system actions for achieving a desired SLSA build level. While there is likely additional clarification needed, this is at least a step to get there.

2023-03-14 20:12 UTC, mlieberman85 approved these changes
LGTM

2023-03-14 20:13 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +level.
The producer must also adopt the builder's security controls.

2023-03-14 20:18 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +-   The build system SHOULD NOT open services that allow for remote influence.
And we removed the hermetic requirement from 1.0.

2023-03-15 11:10 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +-   The build system SHOULD NOT open services that allow for remote influence.
My read of these requirements is about ensuring that the build system is properly isolated from other actors outside of the trust boundary. This includes be able to be acted upon from outside the trust boundary or from having any explicit dependencies outside the trust boundary. I personally think that the remote execution terminology here is misleading and that it can be removed. 

I see this as being different from a hermetic-like complete (or semi-complete) revocation of network access as _any_ access within the trust boundary is perfectly fine. We need to ensure that a build is not going to be changed based on anything outside of the trust boundary so that we can have confidence that the configuration (i.e. configuration as code) input to the system fully defines the actions carried out by the system.

Yes, the hermetic requirement was removed from 1.0. General restriction of network access (except for any required access to/by the build system) will hopefully fall in some future SLSA specification release.

2023-03-15 11:10 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +Build system</a>. The requirement is on the build system to strengthen the
Thanks, adjusted the wording.

2023-03-15 11:10 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +level.
Thanks, adjusted the wording.

2023-03-15 15:10 UTC, arewm commented
@dlorenc, FYI as my recent commit is backing out the change you proposed to separate ephemeral from isolated.

2023-03-15 20:26 UTC, kpk47 approved these changes

2023-03-17 13:13 UTC, joshuagl approved these changes
This looks like a nice refinement, thanks @arewm !

2023-03-17 13:13 UTC, joshuagl commented on docs/spec/v1.0/requirements.md
> +initial [draft version (v0.1)](../v0.1/requirements.md#hermetic),
```suggestion
initial [draft version (v0.1)](../v0.1/requirements.md#hermetic).
```

2023-03-17 16:32 UTC, MarkLodato requested changes
Thanks, this is a big improvement!

2023-03-17 17:17 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +initial [draft version (v0.1)](../v0.1/requirements.md#hermetic).
Sure, we can move this to another PR. One point of reference that I have been struggling with is how to differentiate the producer's build process with the build system's build process. The requirement in v1.0 is about enforcing build system isolation. I saw the removed hermetic requirement as enforcing isolation of the producer's build (i.e. the build event -- docker/podman/buildah/etc command).

2023-03-17 17:28 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +-   The build system SHOULD NOT open services that allow for remote influence.
I can open another PR to discuss this as its scope is different from that originally indicated in the PR.

Ah, splitting like that would be much clearer if that was your intention. At a level 4, that SHOULD NOT would become a MUST NOT.

I still believe that these are valid statements for the build system as well. 

> -   The build system SHOULD NOT call out to remote execution unless it's
>    considered part of the "builder" within the trust boundary.

There might be situations where this is done (i.e. `ntp`), but any situations should be weighed and considered to ensure that the build system doesn't introduce an additional attack vector. For as much as is reasonably possible, all build system execution should happen within the trust boundary.

> -   The build system SHOULD NOT open services that allow for remote influence.

Again, this is important to ensure that the configuration passed to the build system is an accurate representation of the state of the build to enable proper attestation. We do not want a running build to be influenced by some remote actor outside of the trust boundary. This may even be better suited as MUST NOT.

2023-03-17 17:34 UTC, arewm commented on docs/spec/v1.0/threats.md
>  <details><summary>Compromise parallel build <span>(Build L3)</span></summary>
I see benefit in continuing to have them lumped together as they are closely related. I will change the title from `parallel` to `other` and leave `in parallel or subsequent` for the threat.

2023-03-17 18:07 UTC, arewm commented
With 869044a1857fe246ff11b0f88c51914ea84976c4, I removed all references to ephemeral and isolated. I will open a new PR for those changes to allow for more focused changes and conversations. I will post here with that PR once it is open.

2023-03-17 18:09 UTC, MarkLodato approved these changes

2023-03-17 18:11 UTC, merged

2023-03-17 18:37 UTC, arewm commented
#700 was created to follow up on the ephemeral and isolated change.