Add description across SLSA pages.
slsa-framework/slsa pull request #695
Opened 2023-03-16 14:52 UTC by arewm

Link unfurling and SEO currently only uses the default description for the entire webpage. In order to provide more clarity to this, I unified pages' frontmatter to specify the title and provide a description.

Resolves: #693

Blog posts don't need to have descriptions added as they seem to be handled differently. Their description is populated by the initial content in the post.

I added basic one-liner content to each of the pages, but the HTML tag (and unfurling) can handle longer descriptions. Feel free to offer suggestions about what the description should be.

I also modified the earlier versions (i.e. 1.0-rc draft) as I figured that this was beneficial and does not directly affect the content displayed in the specifications.

2023-03-16 15:06 UTC, arewm commented
A preview of the difference:
![Screenshot 2023-03-16 at 11 03 57 AM](https://user-images.githubusercontent.com/16674323/225659630-b49c15f9-aca2-4825-af64-7544bfafd368.png)

2023-03-17 12:20 UTC, lehors approved these changes
LGTM.

2023-03-17 13:10 UTC, arewm commented
@lehors, I rebased on a recent commit to deconflict, but I also inflated the descriptions in the v1.0 directory as I since realized that it is okay for the snippets to be more than just a simple short line.

@olivekl, FYI as well as I moved the first headings into the frontmatter as a title to ensure that it is picked up by the SEO plugin.

2023-03-17 13:24 UTC, joshuagl requested changes
This is a great set of changes, thank you! Two high-level questions/suggestions:
1. can we finish each description with a period (.) for consistency?
2. should we include the version in descriptions, so that it's easy to tell, i.e., v0.1 requirements form v1.0 requirements in a preview?

2023-03-17 13:24 UTC, joshuagl commented on docs/attestation-model.md
> +description: Overview of software attestations and is specifics related to SLSA.
```suggestion
description: Overview of software attestations and its specifics related to SLSA.
```
?

2023-03-17 15:24 UTC, joshuagl approved these changes
Thanks for the fixes Andrew. Your rationale for not including the versions seems sane to me, let's not do anything with that suggestion for now.

2023-03-17 17:01 UTC, lehors commented
We're better off not adding the version to this because it would be one more thing we'd have to maintain. We need to try and limit the number of things that need updating every time we produce a new release.

2023-03-20 16:35 UTC, trishankatdatadog approved these changes

2023-03-20 17:07 UTC, merged