Combine ephemeral and isolated to isolated
slsa-framework/slsa pull request #700
Opened 2023-03-17 18:36 UTC by arewm

In order to help reduce confusion around ephemeral and isolated properties, these have been merged into a single isolated property. Additional clarity is added to the isolated build requirement, relating it to the previous hermetic requirement.

Relates to #657

Some content taken from https://github.com/slsa-framework/slsa/pull/685#discussion_r1140522178 by @MarkLodato.

2023-03-17 19:33 UTC, MarkLodato requested changes
Thanks!

2023-03-17 19:33 UTC, MarkLodato commented on docs/spec/v1.0/threats.md
> +*Example 1 (Build L3):* Build service runs all builds for project MyPackage on
nit: do we need "(Build L3)"? That was only added to "Set values of the provenance" below because there are two different levels. None of the other examples have this.

2023-03-17 19:33 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    trust boundary. In other words, if any remote execution, like `ntp`, is
What is ntp? I always thought it was the Network Time Protocol, so I don't see how that's remote execution. Would something like [Bazel's Remote Build Execution](https://bazel.build/remote/rbe) be a better example?

2023-03-17 19:33 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    doing so could compromise the authenticity of the provenance.
nit: I think the "doing so could compromise the authenticity of the provenance" doesn't add much here. I had suggested it for the first bullet to explain why access to a key violates this principle. Here I think it's more clear?

```suggestion
-   The build SHOULD NOT call out to remote execution unless it's considered
    part of the build system within the trust boundary.
-   The build SHOULD NOT open services that allow for remote influence.
```

2023-03-17 19:33 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +
Is this still needed? I would imagine that the updated text addresses this possible source of confusion. Also, I think this statement only applies to the "Isolated" row and not the whole section?

2023-03-17 19:43 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    trust boundary. In other words, if any remote execution, like `ntp`, is
Yes, a better example can be used. I used `ntp` because I had it in the original issue and I was commenting about the lack of clarity around what is remote execution as we have no _guarantee_ that ntp servers are not doing some kind of execution.

2023-03-17 19:50 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    doing so could compromise the authenticity of the provenance.
I liked the pattern that you introduced with your original section -- providing explanation behind the suggestions. These _recommendations_ are here to ensure that there is proper provenance generation. Going back to my original questions, I think that this is something that I didn't understand before.

> * Would this prevent the vendoring of binary content as some process of the build was performed outside the trust boundary?

No, this would be fine since the dependency would be present in the provenance. We are not trying to make suggestions about the _content_ of the built artifact or the recursive provenance.

> * Would this prevent curling pre-built artifacts to be used in a resulting artifact?

This would be an anti-pattern assuming that the artifacts are not included in the provenance.

> * Would leveraging something like NTP within the build be remote execution?

It doesn't affect provenance.

> * Should this prevent pulling of untrusted container artifacts as well since this can also be a "building" process (i.e. https://github.com/imjasonh/kontain.me/tree/main/cmd/buildpack)?

That would be fine from a provenance perspective since we are not trying to create recursive provenance, but this might not fly for the build hardening aspect.

> * Since any remote access can potentially result in remote execution, should this be interpreted as a requirement for hermetic builds in complete network isolation?

This has been clarified to some extent at least.

2023-03-17 19:51 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +
It isn't needed. The hermetic link is also made in the `Isolated` row as well.

2023-03-20 13:24 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    doing so could compromise the authenticity of the provenance.
I think this section is trying to say that the "build system MUST" rules above are only about what is enabled by default. When a tenant properly configures the build system in the normal way, they MUST be secure. However, it is **not** a requirement to **prevent** tenants from making themselves insecure - that is a much more difficult task and might be a future level. (Relevant issue: #321)

The list here contains the most common situations that we would consider "less secure". We list them here for two reasons:

1. To call out things the build system need not prevent to give more clarify on where the line is.
2. To provide guidance to tenants on how to secure their own builds, even if not strictly required.

In particular, I think this needs to definitely answer the question of whether [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) allowed at Build L3 and if they need a separate `builder.id`. I believe where we landed on #321 was to say that self-hosted runners are OK at Build L3.

I'm kind of doubting the wisdom of reason 2 above (guidance to tenants). We got feedback in #423 that it's confusing to have "optional" requirements. SHOULD here is another form of optional requirement. Might be less confusing to just say that the build system need not prevent it.

2023-03-20 13:42 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    the build system.
I see a difference between these two bullets, at least in my intention of wording it like I did

### Second bullet
> It MUST NOT be possible for two builds that overlap in time to influence one
    another, such as by altering the memory of a different build process running
    on the same machine.

* This is about the builder enforcing isolation between each running build
* Any two running builds must be isolated from each other, one producer-triggered event cannot affect another producer-triggered event
* The build system should ensure that builds running cannot influence/affect one another

### Fifth bullet
> The build system MUST NOT open services that allow for remote influence
    because doing so would introduce additional attack vectors to compromise
    the build system.

* This is about the builder ensuring that builds run as _configured_
* Once the builder is configured, it cannot be changed until another deployment occurs (i.e. updating Tekton Pipeline definitions or GitHub actions updates)
* An example of this would be the ability to [debug Travis CI runs](https://docs.travis-ci.com/user/running-build-in-debug-mode/) -- if debug is enabled and remote influence is potentially introduced, then the resulting artifact would not be Build L3
* The support at this line might be misleading as it isn't necessarily around compromising the build system, but more about compromising the ability for the build system to know the steps called to build the artifact.

2023-03-20 13:53 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    considered.
I created this bullet initially because of the confusion around mentioning `build`s within the context of `build system`. Thinking about it more, this really just comes down to ensuring that appropriate build system threat modeling has been done to ensure that the build process is not affected by any process outside of the trust boundary. 

It makes sense that any build actions within the build system MUST be within the trust boundary. Would that mean that it MUST be considered part of the builder identified by the `builder.id`? If this is the place, what would be the best place to describe this detail -- within `build model` in the Terminology?

2023-03-20 14:16 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    considered.
Maybe on the provenance page? I filed #706 to track.

2023-03-20 14:19 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    the build system.
Oh, I see now. Thanks for explaining. I don't think the current wording quite gets that through because it's still a bit abstract. Maybe something like the following would be more clear?

> The build system MUST NOT open services on the build work that allow for external parties to run commands or otherwise alter the behavior of the running build process, such as [Debug Mode in Travis CI](https://docs.travis-ci.com/user/running-build-in-debug-mode/). Doing so would constitute an external parameter that is not captured in the provenance.

2023-03-20 14:22 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    doing so could compromise the authenticity of the provenance.
I think I follow. Could you propose some updated wording?

2023-03-20 15:28 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    the build system.
Ah, interesting wording. I can see how these would be considered external parameters. Based on the completeness wording for provenance L3

> -   External parameters MUST be fully enumerated.

we can actually change this wording since parameterless wasn't considered previously until L4, this _may_ still be fine.

> Any open services on the build system which allow for external parties to alter the behavior of the running build process, such as [Debug Mode in Travis CI](https://docs.travis-ci.com/user/running-build-in-debug-mode/), are considered external parameters and MUST be fully enumerated if allowed.

It isn't until the external parameters are not enumerable that the relevant services MUST NOT be opened.

2023-03-20 15:49 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    doing so could compromise the authenticity of the provenance.
I won't push content since it would remove the content that is in here right now. I am also not going to further address the build system isolation (i.e. L4) here as that just needs to go in a new issue. The best way I see to make it explicit (using a pattern I don't see elsewhere) would be to:

1. Add a row to the `Producer` table around isolation without any check-marks
2. Add a section under Producer for isolation similar to this:

>   There are no requirements set forth to producers related to isolation in order to achieve build L1-L3. If the build system allows package builds to occur with access to the network or the internet, producers SHOULD NOT intentionally subvert the build system's best effort for provenance completion.

3. Removing the section on the build system starting with:

> There are no sub-requirements on the build itself, but the following are
RECOMMENDED in order to honor the spirit of "Isolated":

2023-03-20 15:58 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    the build system.
> > Any open services on the build system which allow for external parties to alter the behavior of the running build process, such as [Debug Mode in Travis CI](https://docs.travis-ci.com/user/running-build-in-debug-mode/), are considered external parameters and MUST be fully enumerated if allowed.
> 
> It isn't until the external parameters are not enumerable that the relevant services MUST NOT be opened.

While this is technically correct, I suspect in practice that this might be more confusing than just disallowing such services. I imagine that almost all cases allow arbitrary commands or behavior to be injected, so they likely are never enumerable. Can you think of an example where such a thing would be enumerated as an external parameter?

2023-03-20 16:01 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    doing so could compromise the authenticity of the provenance.
Hmm. I'm hesitant to add a row with no check marks (might be confusing). It would be good to have other feedback on possible wording, if anyone else is reading this.

2023-03-20 17:07 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    the build system.
Actual example. 😁  Maybe we can just say it's generally disallowed, with a footnote or comment explaining that if you record all of the inputs in `externalParameters` then it's OK?

Regarding Travis, I'd say a `builder.id` should indicate that Travis was used in a configuration that prohibits Debug Mode (at least before provenance is fully generated). What do you think?

2023-03-20 17:59 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    the build system.
As long as a service like Travis who has this functionality has the ability to clearly indicate the L2/L3 differentiation that would happen, it comes down to an implementation detail. It doesn't even matter that it is used in a configuration that prohibits the debug mode -- even if it is enabled, what matters is whether an artifact was generated with the mode enabled.

IMO, adding a footnote will just introduce more confusion than addressing it _well_ in a bullet. Even just changing `open services on the build system` to `build system services` simplifies comprehension.

2023-03-20 18:09 UTC, MarkLodato commented
FYI I added "Fixes #291 by being more specific around build caches." to the description.

2023-03-20 20:15 UTC, abacchi commented on docs/spec/v1.0/requirements.md
> +    doing so could compromise the authenticity of the provenance.
I think its fair to show that the build system holds the burden for the L3 requirements- and eventually at L4 the producer will need to make some effort to meet the future requirement. 
I hesitate to show a blank row as well because it sort of makes the 1.0 release look unfinished - but I see the benefit of having it there as a placeholder for the future.
@arewm I like the 2 & 3 suggestions

2023-03-20 20:16 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    doing so could compromise the authenticity of the provenance.
I can also do 2&3 without 1, I just thought 1 would be needed for completeness/adhering to the pattern.

2023-03-20 20:49 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    doing so could compromise the authenticity of the provenance.
I'm not sure #2 is needed - it seems weird to talk about Isolation in the Producer section.

Why not just replace the "There are no sub-requirements..." with a more direct explanation that there are no requirements to block the build process from connecting to external resources, and that things like self-hosted runners are OK?

2023-03-21 00:48 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    doing so could compromise the authenticity of the provenance.
I only updated the content in the isolation table. I also modified the PR description to add `Fixes #321`.

2023-03-21 13:05 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +running with access to the internet as well as leveraging [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners)
I like where this is going, but provenance generation is not "best effort" at L3 - only the resolvedDependencies bit is. What do you think about the following alternative? I tried to more directly state what we discussed in the thread. (Also avoid linking to a specific vendor, though I'm open to re-adding the link.)

```suggestion
There are no sub-requirements on the build itself. Build L3 is limited to
ensuring that the a well-intentioned build runs securely. It does not require
preventing a producer from performing a risky or insecure build. In particular,
the "Isolated" requirement does not prohibit a build from calling out to a
remote execution service or a "self-hosted runner" that is outside the trust
boundary of the build platform.
```

2023-03-21 13:05 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +as part of a build system.
I like where this is going, but provenance generation is not "best effort" at L3 - only the resolvedDependencies bit is. What do you think about the following alternative? I tried to more directly state what we discussed in the thread. (Also avoid linking to a specific vendor, though I'm open to re-adding the link.)

```suggestion
There are no sub-requirements on the build itself. Build L3 is limited to
ensuring that the a well-intentioned build runs securely. It does not require
preventing a producer from performing a risky or insecure build. In particular,
the "Isolated" requirement does not prohibit a build from calling out to a
remote execution service or a "self-hosted runner" that is outside the trust
boundary of the build platform.
```

2023-03-21 14:25 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +as part of a build system.
I meant to indicate that provenance completeness is best effort, not that provenance generation is best effort as this is what is mentioned earlier in the requirements (https://github.com/slsa-framework/slsa/pull/700/files#diff-3a161534a67508acd917c97c9e5d57ed648c50c3a7da23acd58aede57fafbdb2R230-R231).

I like the wording in general. Do we want to tie back to provenance completeness as a best effort?

2023-03-21 14:38 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +as part of a build system.
Sure, maybe a few words either here or in the "hermetic" note?

2023-03-21 19:03 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +generated completeness is best effort. It does not require that build systems
I can't find the original thread, but "provenence generated completeness is best effort" doesn't make sense to me. What is the intention?

2023-03-21 19:44 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +generated completeness is best effort. It does not require that build systems
I can remove this line if the PR is ready to be merged without it and open another issue to discuss the confusion around this phrase in the provenance requirements and how I end up interpreting that across the board.

2023-03-21 21:33 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +generated completeness is best effort. It does not require that build systems
Yeah, let's just remove that line for now to get this merged, and then have a separate PR to discuss that particular piece. I think what you have so far (minus this) is a strict improvement so let's lock that in!

2023-03-22 12:20 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +generated completeness is best effort. It does not require that build systems
I opened #717 to continue the conversation.

2023-03-22 14:32 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    the build system.
@MarkLodato, this is the only remaining thread. We never settled on whether or how to include external parameters in isolation. To some extent, this comes down to implementation details. One possible change could be from 

> The build system MUST NOT open services that allow for remote influence
    because doing so would introduce additional attack vectors to compromise
    the build system.

to 

> The build system MUST NOT open services that allow for remote influence
    unless all such interactions are captured as `externalParameters` in the provenance.

2023-03-22 14:34 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    the build system.
I'm OK with that change!

2023-03-22 14:36 UTC, joshuagl approved these changes
Thank you for this change. I really appreciate all of the detailed discussion in this PR review, I'm sorry I missed it! 😁

2023-03-22 15:11 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +    the build system.
Change pushed, thanks.

2023-03-22 15:45 UTC, MarkLodato approved these changes
Thanks! I know this back-and-forth wasn't easy but I appreciate your hard work in resolving these issues!

2023-03-22 16:07 UTC, arewm commented
No problem. I enjoyed the back and forth I just wish that there was a better way to converse about it than in PR comment threads that get easily outdated. 

This PR should be ready to merge.

2023-03-22 17:10 UTC, merged