Rewrite Understanding SLSA sections
slsa-framework/slsa pull request #705
Opened 2023-03-18 13:37 UTC by olivekl

DRAFT, NOT FOR MERGING

Opening this for preliminary comments

Questions:

1. In "Who is SLSA for?" section, should the third term that goes with _producers_ and _consumers_ be _distributors_, _implementors_, or _infrastructure providers_?

2. In "What SLSA doesn’t cover" section, do we need to include examples of secure coding practices that SLSA doesn't cover (the TODO on line 133)?

3. I originally proposed combining the Introductory SLSA material with Guiding Principles on the same page, but now that they're together I think they should stay separated. Should it move after "Use Cases" in the structure outlined in index.md in this PR?

4. Any other feedback on content changes?

@lehors @mlieberman85 @joshuagl @di @MarkLodato @kpk47

2023-03-20 15:34 UTC, MarkLodato reviewed
Overall I think this is a big improvement. Thanks!

2023-03-20 15:34 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +    why, see the [FAQ](faq).
nit: Can we phrase this a bit more positively, like you did for the bullet above? Maybe something on how you can still apply SLSA to each dependency - it's just that we don't (yet?) have a single numeric to cover the transitive closure of dependencies?

2023-03-20 20:42 UTC, MarkLodato commented on docs/spec/v1.0/principles.md
> +    why, see the [FAQ](faq).
👍

2023-03-21 18:41 UTC, olivekl commented on docs/spec/v1.0/principles.md
> +    independent of its dependencies' levels. You can use SLSA recursively to
Sounds great, thanks!

2023-03-21 23:00 UTC, joshuagl commented on docs/spec/v1.0/about.md
> +Track. SLSA v1.0 consists of only a single track (Build), but future versions of
worth linking to the build track here?

2023-03-21 23:00 UTC, joshuagl commented on docs/spec/v1.0/about.md
> +to be possible in future revisions.
worth linking to future directions here?

2023-03-22 01:11 UTC, olivekl commented on docs/spec/v1.0/about.md
> +SLSA is a set of incrementally adoptable guidelines for supply-chain security,
In this case I was following the rule of not hyphenating when used as a noun and hyphenating when used as an adjectival phrase. It tends to look inconsistent, though, so the general trend these days is moving toward dropping the adjectival hyphen (as has happened almost universally with the phrase "open source software"). I'm okay with dropping the hyphen across the site for adjectival phrases.

2023-03-22 01:30 UTC, olivekl commented on docs/spec/v1.0/about.md
> +to be possible in future revisions.
Done!

2023-03-22 01:31 UTC, olivekl commented on docs/spec/v1.0/about.md
> +**Software producers**, such as a development team at a software company or open
Dropped

2023-03-22 01:31 UTC, olivekl commented on docs/spec/v1.0/about.md
> +In short: everyone involved in producing, consuming software, or providing
Oops, thanks for catching.

2023-03-22 01:31 UTC, olivekl commented on docs/spec/v1.0/about.md
> +-   Uploaded artifacts that were not built by a CI/CD system (by marking
Done

2023-03-22 01:31 UTC, olivekl commented on docs/spec/v1.0/about.md
> +## SLSA in layman's terms
Good catch, thanks.

2023-03-22 01:32 UTC, olivekl commented on docs/spec/v1.0/about.md
> +anyone involved in complex critical systems. SLSA is meant to support automation
Tweaked -- does this paragraph still work without it?

2023-03-22 12:38 UTC, joshuagl commented on docs/spec/v1.0/about.md
> +SLSA is a set of incrementally adoptable guidelines for supply-chain security,
Thanks for explaining the grammar rule. I admit, I am not familiar with it. I would be in favour of dropping the adjectival hyphen across the site.

2023-03-22 13:19 UTC, MarkLodato reviewed
Overall this looks good. Need to sync to main so that we can preview the latest changes.

2023-03-22 13:37 UTC, joshuagl commented on docs/spec/v1.0/about.md
> +anyone involved in complex critical systems. SLSA is meant to support automation
Thanks! It has lost a bit in the tweaking. Can we reintroduce the explicit mention of the automation protecting against tampering? Perhaps:

> SLSA is designed to support automation that tracks code handling from source to binary, so that regardless of the complexity of a software supply chain it is protected against tampering.

2023-03-22 13:52 UTC, lehors reviewed
This is looking pretty nice. Thanks!

2023-03-22 13:52 UTC, lehors commented on docs/spec/v1.0/about.md
> +    artifacts with a factory "stamp" that verifies which build service created it)
The stamp itself doesn't verify, it makes verification possible, so I think this should read:
```suggestion
    artifacts with a factory "stamp" that attests which build service created it)
```
Or possibly the following but that seems a bit too convoluted for this intro:
```suggestion
    artifacts with a factory "stamp" that provides a verifiable attestation of which build service created it)
```

2023-03-22 13:52 UTC, lehors commented on docs/spec/v1.0/about.md
> +software you produce reaches your consumers as you intended it.
nit:
```suggestion
software you produce reaches your consumers as you intended.
```

2023-03-22 13:52 UTC, lehors commented on docs/spec/v1.0/about.md
> +chain more frictionless for both of them.
nit:
```suggestion
producers and consumers, your adoption of SLSA makes a secure software supply
chain between them more frictionless. 
```
or maybe simply:
```suggestion
producers and consumers, your adoption of SLSA enables a secure software supply
chain between them. 
```

2023-03-22 13:52 UTC, lehors commented on docs/spec/v1.0/about.md
> +SLSA will add tracks that cover other parts of the software supply chain.
Should we hint on what those tracks might cover by adding something like "such as how source is managed" or maybe simply pointing to the section below about what's not currently covered?

2023-03-22 14:21 UTC, olivekl commented on docs/spec/v1.0/about.md
> +    artifacts with a factory "stamp" that verifies which build service created it)
Since this is the layperson's terms section, would you be open to "shows" rather than 
"attests"? As in: ...a factory "stamp" that shows which build service created it.

2023-03-22 16:28 UTC, olivekl commented on docs/spec/v1.0/about.md
> +anyone involved in complex critical systems. SLSA is meant to support automation
Updated!

2023-03-22 16:30 UTC, olivekl commented on docs/spec/v1.0/about.md
> +SLSA is a set of incrementally adoptable guidelines for supply-chain security,
Sounds good, I'm in agreement (this is a grammar rule in the process of dying out). 

I'll update this PR and then get to the remaining hyphens across other pages with the next PR.

2023-03-22 16:33 UTC, lehors commented on docs/spec/v1.0/about.md
> +    artifacts with a factory "stamp" that verifies which build service created it)
yes, that's fine.

2023-03-22 17:15 UTC, olivekl commented on docs/spec/v1.0/about.md
> +    artifacts with a factory "stamp" that verifies which build service created it)
Updated, thanks.

2023-03-22 17:23 UTC, olivekl commented on docs/spec/v1.0/about.md
> +practices that qualify it for that level.
Thanks for pointing this out -- I've tweaked the idea further to be more specific.

2023-03-22 17:24 UTC, olivekl commented on docs/spec/v1.0/about.md
> +SLSA will add tracks that cover other parts of the software supply chain.
How about linking to future-directions.md?

2023-03-22 19:17 UTC, di commented on docs/spec/v1.0/about.md
> +-   A way to judge the software you consume and secure your incoming supply chain
```suggestion
-   A way to secure your software supply chain by evaluating trust in the software artifacts you consume
```

Since SLSA is really only concerned with whether the _artifact_ can be trusted, not with the software _within_ the artifact.

2023-03-22 19:17 UTC, di commented on docs/spec/v1.0/about.md
> +software supply chain is needed, as evidenced by the
```suggestion
software supply chain is needed, as proposed by the
```
The evidence is the attacks themselves, not the EO.

2023-03-22 19:17 UTC, di commented on docs/spec/v1.0/about.md
> +from a compromised or malicious insider. Risk for code modification exists at
```suggestion
via compromise or malicious acts. Risk for code modification exists at
```

b/c "compromised insider" doesn't quite make sense.

2023-03-22 19:17 UTC, di commented on docs/spec/v1.0/about.md
> +    see the [FAQ](faq).
```suggestion
    see the [FAQ](faq#q-why-is-slsa-not-transitive).
```

2023-03-22 19:43 UTC, di commented on docs/spec/v1.0/about.md
> +from a compromised or malicious insider. Risk for code modification exists at
That makes sense, but I think that would be "insider compromise" rather than "compromised insider", right?

2023-03-22 19:50 UTC, arewm commented on docs/spec/v1.0/about.md
> +from a compromised or malicious insider. Risk for code modification exists at
I feel like these are usually just classified as "insider threats"

2023-03-22 19:54 UTC, arewm commented on docs/spec/v1.0/about.md
> +description: An introduction to SLSA
We have a lot of good information in this page. We can be more verbose about this description. It is okay to have multiple sentences here, either as a long line or (I assume) [multi-line](https://yaml-multiline.info/) yaml.

2023-03-22 19:57 UTC, arewm commented on docs/spec/v1.0/about.md
> +SLSA will add tracks that cover other parts of the software supply chain.
We already link there in the next paragraph. Can we combine these two paragraphs and just link to it once indicating the multiple ways that future directions might go (increasing breadth and strength)?

2023-03-22 19:58 UTC, arewm commented on docs/spec/v1.0/about.md
> +There are several areas outside SLSA's current framework:
Do we foresee any of these to be addressed in future directions as well?

2023-03-22 19:58 UTC, arewm commented on docs/spec/v1.0/faq.md
>  # FAQ
Did I miss this title? It should be moved into the yaml frontmatter as well.

2023-03-22 19:59 UTC, arewm commented on docs/spec/v1.0/index.md
> +description: Overview of SLSA information on this site
Can you move the title up into the frontmatter as well?

2023-03-22 19:59 UTC, arewm commented on docs/spec/v1.0/principles.md
> +# Guiding principles
This should be the title in the frontmatter.

2023-03-22 20:00 UTC, arewm commented on docs/spec/v1.0/index.md
> +description: Overview of SLSA information on this site
Never mind, it is already there, I guess this just has an out-of-date HEAD.

2023-03-22 20:04 UTC, MarkLodato commented on docs/spec/v1.0/about.md
> +from a compromised or malicious insider. Risk for code modification exists at
Right, I wanted to highlight insider threats, but also call out compromise of an insider's credentials. (Not sure how best to fix the paragraph though.)

2023-03-22 20:07 UTC, arewm commented on docs/spec/v1.0/about.md
> +from a compromised or malicious insider. Risk for code modification exists at
One option could be to just expand it further to get away from attempted parallel construction

> insider threats or compromised accounts/credentials/individuals/whatever word you want

2023-03-22 20:12 UTC, lehors commented on docs/spec/v1.0/about.md
> +SLSA will add tracks that cover other parts of the software supply chain.
Sure, works for me.

2023-03-22 20:16 UTC, lehors commented on docs/spec/v1.0/about.md
> +There are several areas outside SLSA's current framework:
Obviously we can't commit to anything but at least some of this yes, for instance with the source track which was tabled off for now.

2023-03-22 20:29 UTC, lehors commented on docs/spec/v1.0/about.md
> +-   A way to judge the software you consume and secure your incoming supply chain
Sorry but this doesn't sound quite right to me. One doesn't really evaluate trust, do they? I think it's more like you do some evaluation to determine whether (or how much) you can trust.
So in this case I would rather say something like:
```suggestion
-   A way to secure your software supply chain by evaluating whether you can trust the software artifacts you consume
```
Or closer to the original text:
```suggestion
-   A way to judge the trustworthiness of the artifacts you consume to secure your incoming supply chain
```

2023-03-22 20:58 UTC, di commented on docs/spec/v1.0/about.md
> +from a compromised or malicious insider. Risk for code modification exists at
Makes sense, how about:

```suggestion
via insider threats or compromise. Risk for code modification exists at
```

2023-03-22 21:02 UTC, MarkLodato commented on docs/spec/v1.0/about.md
> +from a compromised or malicious insider. Risk for code modification exists at
Yup, either "compromised accounts" or "compromise" works for me. I'd lean toward the former but defer to @olivekl.

2023-03-22 21:12 UTC, lehors commented on docs/spec/v1.0/about.md
> +-   A way to judge the software you consume and secure your incoming supply chain
Yes, I like that.

2023-03-22 22:54 UTC, olivekl commented on docs/spec/v1.0/about.md
> +software supply chain is needed, as evidenced by the
Ah, true. I'm not sure it's fair to say that the EO proposed the need for a universal framework for supply chain security, though (or at least not in those exact words). I think I meant it more like, "as borne out by the EO." As in, the EO supports the validity of stating there's a need. Would that phrase work?

2023-03-22 23:44 UTC, joshuagl commented on docs/spec/v1.0/about.md
> +anyone involved in complex critical systems. SLSA is meant to support automation
Thanks!

2023-03-23 00:06 UTC, di commented on docs/spec/v1.0/about.md
> +software supply chain is needed, as evidenced by the
Makes sense to me!

2023-03-23 19:21 UTC, olivekl commented on docs/spec/v1.0/index.md
> +description: Overview of SLSA information on this site
Yup, sorry, I've synced now!

2023-03-23 19:55 UTC, arewm commented on docs/spec/v1.0/index.md
> +description: Overview of SLSA information on this site
I cannot resolve these accidental conversations -- feel free to resolve them for me! :)

2023-03-23 19:59 UTC, arewm requested changes

2023-03-23 19:59 UTC, arewm commented on docs/spec/v1.0/faq.md
> +descriptions: Answers to questions frequently asked about SLSA.
```suggestion
description: Answers to questions frequently asked about SLSA.
```
I must have inserted an accidental `s`.

2023-03-23 21:57 UTC, olivekl commented on docs/spec/v1.0/about.md
> +# About SLSA
Done

2023-03-23 22:06 UTC, olivekl commented on docs/spec/v1.0/about.md
> +SLSA will add tracks that cover other parts of the software supply chain.
I added "such as how source code is managed" and didn't add a second link. I think I'd like to keep the paragraphs separate. To a new reader the ideas of tracks and levels could be confusing and I think breaking the ideas apart into two paragraphs can help reduce that  potential for confusion. Is that okay with you two?

2023-03-23 22:12 UTC, olivekl commented on docs/spec/v1.0/about.md
> +from a compromised or malicious insider. Risk for code modification exists at
Updated with @di's suggestion and "compromised accounts" to be clear about what could be compromised.

2023-03-23 22:20 UTC, olivekl commented on docs/spec/v1.0/about.md
> +software supply chain is needed, as evidenced by the
Updated to "affirmed by" for a warmer tone

2023-03-23 22:24 UTC, olivekl commented on docs/spec/v1.0/about.md
> +Track. SLSA v1.0 consists of only a single track (Build), but future versions of
Added

2023-03-23 22:27 UTC, olivekl commented on docs/spec/v1.0/about.md
> +description: An introduction to SLSA
Sure, is there anything you'd like to add specifically?

2023-03-23 22:54 UTC, di approved these changes
LGTM, all my concerns have been addressed. Thanks!

2023-03-24 06:56 UTC, lehors commented on docs/spec/v1.0/about.md
> +SLSA will add tracks that cover other parts of the software supply chain.
Works for me. Thanks.

2023-03-24 07:06 UTC, lehors requested changes
The title for prev_page and next_page is now taken from the page directly. Only the url should be specified so that we have less to maintain (and break).
Thanks.

2023-03-24 07:06 UTC, lehors commented on docs/spec/v1.0/about.md
> +  title: What's new in SLSA v1.0
```suggestion
```

2023-03-24 07:06 UTC, lehors commented on docs/spec/v1.0/about.md
> +  title: Supply chain threats
```suggestion
```

2023-03-24 07:06 UTC, lehors commented on docs/spec/v1.0/faq.md
> +  title: Supply-chain threats
```suggestion
```

2023-03-24 07:06 UTC, lehors commented on docs/spec/v1.0/faq.md
> +  title: Supply-chain threats
```suggestion
```

2023-03-24 12:02 UTC, arewm commented on docs/spec/v1.0/about.md
> +description: An introduction to SLSA
Maybe a brief statement about why it is needed (i.e. supply chain attacks are on the rise) and what it provides (i.e. common vocabulary/process and prescriptive incremental guidance)? You can even finish with a sentence commenting that SLSA is for everyone.

I initially thought that the layperson description would be better, but after further reflection, I think we should stay away from that for this description.

2023-03-24 12:05 UTC, arewm commented on docs/spec/v1.0/about.md
> +There are several areas outside SLSA's current framework:
All of these items seem to be clearly outside of the scope of SLSA, but we can include a comment that the breadth of the specification may increase with future versions.

2023-03-24 12:45 UTC, MarkLodato approved these changes
Nice!

2023-03-24 12:45 UTC, MarkLodato commented on docs/spec/v1.0/about.md
> +    Executive Order standards in the [Secure Software Development Framework (SSDF)](https://csrc.nist.gov/Projects/ssdf).
nit: remove period at end for consistency

```suggestion
    Executive Order standards in the [Secure Software Development Framework (SSDF)](https://csrc.nist.gov/Projects/ssdf)
```

2023-03-24 12:45 UTC, MarkLodato commented on docs/spec/v1.0/about.md
> +Track. SLSA v1.0 consists of only a single track [(Build)](levels.md#build-track), but future versions of
nit: parentheses outside the link looks nicer

```suggestion
Track. SLSA v1.0 consists of only a single track ([Build](levels.md#build-track)), but future versions of
```

2023-03-24 12:45 UTC, MarkLodato commented on docs/spec/v1.0/threats-overview.md
>    url: faq
next should be `principles`

2023-03-24 12:45 UTC, MarkLodato commented on docs/spec/v1.0/faq.md
>  prev_page:
prev should be `principles`, next should be `future-directions`

2023-03-24 17:07 UTC, olivekl commented on docs/spec/v1.0/about.md
> +There are several areas outside SLSA's current framework:
Good point! I added a couple sentences along those lines.

2023-03-24 17:16 UTC, olivekl commented
> 

I think this is solved by PR #724; just merged with those changes.

2023-03-24 17:38 UTC, arewm commented on docs/spec/v1.0/about.md
> +important to consider together with SLSA:
```suggestion
important to consider together with SLSA such as:
```
We do not want to imply that this is an exhaustive list.

2023-03-24 18:25 UTC, arewm commented on docs/spec/v1.0/about.md
> +There are several areas outside SLSA's current framework:
Looks good. I cannot resolve the conversation though.

2023-03-24 18:26 UTC, arewm approved these changes

2023-03-24 18:26 UTC, arewm commented on docs/spec/v1.0/about.md
> +description: An introduction to SLSA
@olivekl, this is the last comment that I have. If this will be addressed elsewhere (or another time), then it it is all good from me.

2023-03-24 18:37 UTC, olivekl commented on docs/spec/v1.0/about.md
> +description: An introduction to SLSA
Whoops, this comment got lost in the fold. Updated!

2023-03-24 18:48 UTC, lehors approved these changes
LGTM. Thanks.

2023-03-24 18:51 UTC, merged