Update supply chain threat model and diagrams.
slsa-framework/slsa pull request #715
Opened 2023-03-22 00:45 UTC by kpk47

- Break the cycle, making the diagram a DAG.
- Move threat C to the Source Track.
- Swap threats D and E. Now the division is ABC == Source, D == Dependencies, EFGH == Build.

Addresses #708 and #647.

2023-03-22 23:54 UTC, kpk47 commented on docs/images/supply-chain-threats-no-label.svg
I created images/v1.0 for the diagrams I'm updating in this PR. I'll send a separate PR to version the rest so that this one doesn't get encumbered by the unrelated difs.

2023-03-23 07:54 UTC, lehors approved these changes
LGTM. This is a nice improvement.

2023-03-23 12:26 UTC, MarkLodato requested changes

2023-03-23 12:26 UTC, MarkLodato commented on docs/images/v1.0/supply-chain-threats-build-verification.svg
Could you re-export these with a white background (to support dark mode) and with the original dimensions? Looks like something got changed.

2023-03-23 18:46 UTC, kpk47 commented on docs/images/v1.0/supply-chain-threats-build-verification.svg
Done

2023-03-23 18:46 UTC, kpk47 commented on resources/editable-diagrams/supply-chain-threats--editable.svg
Done

2023-03-23 18:58 UTC, MarkLodato commented on docs/images/v1.0/supply-chain-threats-no-labels.svg
Is this file used? I can't see a reference in the Markdown.

2023-03-23 19:58 UTC, kpk47 commented on docs/images/v1.0/supply-chain-threats-no-labels.svg
I can't find a reference either. I deleted it.

2023-03-23 20:04 UTC, MarkLodato approved these changes

2023-03-23 20:04 UTC, merged