v1 VSA: Update policy levels to indicate the track
slsa-framework/slsa pull request #734
Opened 2023-03-24 21:17 UTC by kpk47

Addresses #725

2023-03-24 22:08 UTC, laurentsimon commented on docs/verification_summary/v1.md
> +  "policy_level": {
nit: `policy_levels`? There is one policy per track.

2023-03-24 22:10 UTC, kpk47 commented on docs/verification_summary/v1.md
> +  "policy_level": {
Done

2023-03-24 22:27 UTC, laurentsimon commented on docs/verification_summary/v1.md
>      "<SlsaResult>": <Int>,
I think this must be changed too. Probably you should declare a new Object:
```yaml
policy_level {
  track_name: SlsaResult
}

policy_levels: []policy_level,
dependency_levels: []policy_level,
```

2023-03-28 13:22 UTC, TomHennen commented on docs/verification_summary/v1.md
> +`policy_level` _string ([SlsaResult]), repeated_
Would it make sense to rename this field to 'levels' ?

2023-03-28 13:34 UTC, MarkLodato commented on docs/verification_summary/v1.md
> +`policy_level` _string ([SlsaResult]), repeated_
or `verified_level` to be a bit more verbose

2023-03-28 13:36 UTC, TomHennen commented on docs/verification_summary/v1.md
> +`policy_level` _string ([SlsaResult]), repeated_
nit: if it's repeated should it be plural :)

2023-03-28 13:40 UTC, MarkLodato requested changes

2023-03-28 13:40 UTC, MarkLodato commented on docs/verification_summary/v1.md
> +  "policy_level": "SLSA_BUILD_LEVEL_3",
```suggestion
  "policy_level": ["SLSA_BUILD_LEVEL_3"],
```

2023-03-28 13:40 UTC, MarkLodato commented on docs/verification_summary/v1.md
> +`policy_level` _string ([SlsaResult]), repeated_
```suggestion
`policy_level` _array ([SlsaResult]), optional_
```

Also need to update the schema above to make this an array.

2023-03-28 18:10 UTC, kpk47 commented on docs/verification_summary/v1.md
> +> dependencies) were verified at or "FAILED" if policy verification failed.
Done

2023-03-28 18:10 UTC, kpk47 commented on docs/verification_summary/v1.md
> +`policy_level` _string ([SlsaResult]), repeated_
Done

2023-03-28 18:10 UTC, kpk47 commented on docs/verification_summary/v1.md
> +  "policy_level": "SLSA_BUILD_LEVEL_3",
Done

2023-03-29 19:09 UTC, MarkLodato approved these changes

2023-03-29 19:14 UTC, merged