WIP, DO NOT MERGE: Split 'expectations' into two terms
slsa-framework/slsa pull request #737
Opened 2023-03-24 22:45 UTC by kpk47

2023-03-31 16:01 UTC, olivekl commented on docs/spec/v1.0/terminology.md
> +| Verification policy | An exact copy of the expectations. |
Is "an exact copy of the expectation" in this example meant to show that in some cases you could choose to set exactly the expectations as the verification policy? I think that makes sense, but is there any chance this could be misunderstood as meaning the verification policy should always match expectations in an open source context? (Assuming that's not what you want to imply?)

2023-03-31 16:47 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +parameter to modify the build. Usually verification policy identifies the
```suggestion
parameter to modify the build. Usually the verification policy identifies the
```

2023-03-31 16:47 UTC, kpk47 commented on docs/spec/v1.0/requirements.md
> +manner such that verifiers can form a verification policy for the build process.
Done

2023-03-31 16:49 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +<td>Verification policy known
```suggestion
<td>Verification policy
```

2023-03-31 16:54 UTC, kpk47 commented on docs/spec/v1.0/terminology.md
> +| Verification policy | An exact copy of the expectations. |
This may be a lack of imagination on my part, but I can't think of any other way an OSS ecosystem would set their verification policy.  

I tried softening the language a bit. WDYT?

2023-03-31 20:19 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +    package and distributes them to the verifier; the verifier uses these
verifier --> consumer?

2023-03-31 20:20 UTC, olivekl commented on docs/spec/v1.0/verifying-artifacts.md
> +    in the source repository. This is how go works, for example, since the
nit, maybe "the go ecosystem"? just for clarity. Or do we capitalize Go?

2023-03-31 20:21 UTC, olivekl approved these changes
A few final comments, but LGTM. I think this division makes this document much clearer -- thank you!

2023-03-31 20:37 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +    package and distributes them to the verifier; the verifier uses these
Done

2023-03-31 20:37 UTC, kpk47 commented on docs/spec/v1.0/verifying-artifacts.md
> +    in the source repository. This is how go works, for example, since the
Done

2023-04-03 12:00 UTC, joshuagl reviewed
Thank you for this, I like the intent and think this will help improve clarity.

We had explicitly moved away from using the term "policy" as it has a lot of baggage. I think the more precise term "verification policy" helps a lot here, but I'd appreciate some broader feedback.

The proposed changes to the "requirements" and "terminology" pages draw a distinction between "expectations" and "verification policy" which is not continued in the "verifying artifacts" page. That makes sense for the "How to verify" section, but I think we want to mention expectations in the "Architecture options" and "Setting verification policy" sections --- WDYT?

2023-04-03 14:59 UTC, MarkLodato requested changes

2023-04-03 14:59 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> +| Verification policy | A set of constraints on the package's provenance metadata. The provenance consumer sets the verification policy based on the expectations. |
Use "verifier" for consistency with #782?

```suggestion
| Verification policy | A set of constraints on the package's provenance metadata. The provenance verifier sets the verification policy based on the expectations. |
```

2023-04-03 14:59 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> +| Verification policy | A set of constraints on the package's provenance metadata. The provenance consumer sets the verification policy based on the expectations. |
I'm having a hard time understanding the difference between these two concepts. They sound very similar, and I can't really follow why some places use "verification policy" while others use "expectations". I also find it confusing that *producers* set expectations.

Do we need both concepts? Can we get away with one?

I suspect that the original problem arose from two underlying issues:

1.  Trying to use "expectations" as a technical term with special meaning (jargon) rather than using natural English phrases whose meaning is obvious. Compare the following examples from [threats](https://slsa.dev/spec/v1.0/threats):
    -   OK: "Verifier requires the provenance’s source location to match an expected value."
        - This reads fine to me. I don't need a definition of "expected value" (though I might wonder where those expectations come from.)
    -   Confusing: "Modify the expectations to accept something that would not otherwise be accepted."
        - How can someone "modify expectations"? What does that mean? (Here it's referring to a particular record of expectations.)
2.   Trying to be too generic about how verification works, leading to confusion about whether the producer or consumer sets expectations. If instead we talked specifically about the different models (upload time, download time) that might avoid the need to define a new term.

2023-04-03 14:59 UTC, MarkLodato commented on docs/spec/v1.0/verifying-artifacts.md
> +## Setting verification policy
This section repeats a lot of what is already in Step 2 below. Should we just eliminate it? I wonder if it raises more questions than it answers.

2023-04-04 01:45 UTC, kpk47 commented
I think this change is too big to make it into RC2. I've instead mailed #795, which is a more modest change that may also clarify what we mean by setting and testing expectations.

2023-04-04 14:35 UTC, closed without merging