Add SLSA tracks blog
slsa-framework/slsa pull request #740
Opened 2023-03-26 17:29 UTC by mlieberman85

Based on the discussions in the SLSA (now SCI) positioning meeting, here's a blog discussing why things are being split up into different SLSA tracks. 

@melba-lopez 
@camaleon2016
@hepwori

2023-03-30 12:37 UTC, lehors requested changes
I think that's nice but we need to fix the date before we publish.

2023-03-30 12:37 UTC, lehors commented on docs/_posts/2023-03-26-the-breadth-and-depth-of-slsa.md
> +Ultimately, SLSA aims to create a comprehensive, adaptable framework that addresses critical pieces of Software Supply Chain Security. By starting with the **build track**, SLSA establishes a robust
That last sentence never ends! :-) There is at least one comma that's misplaced and I suggest something like this to break the monotonous series of "and".
```suggestion
Ultimately, SLSA aims to create a comprehensive, adaptable framework that addresses critical pieces of Software Supply Chain Security. By starting with the **build track**, SLSA establishes a robust foundation on which to build and expand the framework to address other critical aspects of the SDLC. This approach will help end users, whether they are open source project maintainers or stakeholders in a corporation, better understand and mitigate the risks associated with software supply chains, and ultimately develop more secure and reliable software.
```

2023-03-30 12:37 UTC, lehors commented on docs/_posts/2023-03-26-the-breadth-and-depth-of-slsa.md
> +For more information visit the SLSA website, give feedback on the SLSA-v1 release candidate before March 24, 2023, and get involved with the SLSA community.
That date is already past so I think we are better off leaving the date out:
```suggestion
For more information visit the SLSA website, give feedback on the SLSA v1.0 release candidate and get involved with the SLSA community.
```

2023-03-30 19:02 UTC, mlieberman85 commented on docs/_posts/2023-03-26-the-breadth-and-depth-of-slsa.md
> +Ultimately, SLSA aims to create a comprehensive, adaptable framework that addresses critical pieces of Software Supply Chain Security. By starting with the **build track**, SLSA establishes a robust
Thanks!

2023-03-31 08:08 UTC, lehors approved these changes
Thanks.

2023-04-03 13:07 UTC, MarkLodato approved these changes

2023-04-03 13:07 UTC, MarkLodato commented on docs/_posts/2023-03-26-the-breadth-and-depth-of-slsa.md
> +For more information visit the SLSA website, give feedback on the SLSA v1.0 release candidate and get involved with the SLSA community.
```suggestion
For more information visit the SLSA website, [give feedback](https://github.com/slsa-framework/slsa/issues) on the [SLSA v1.0 release candidate](https://slsa.dev/spec/v1.0/) and get involved with the SLSA [community](https://slsa.dev/community).
```

2023-04-03 13:07 UTC, MarkLodato commented on docs/_posts/2023-03-26-the-breadth-and-depth-of-slsa.md
> +Interested in getting involved? Now’s the chance to [provide your feedback on the foundational v1 release of the SLSA framework.](https://slsa.dev/blog/2023/02/slsa-v1-rc)
nit: use a relative link. (GitHub Pages has a plugin that auto-fixes links to `.md` files.)

```suggestion
Interested in getting involved? Now’s the chance to [provide your feedback on the foundational v1 release of the SLSA framework.](2023-02-24-slsa-v1-rc.md)
```

2023-04-03 16:50 UTC, merged