Explain attestation formats
slsa-framework/slsa pull request #743
Opened 2023-03-27 16:40 UTC by olivekl

PR to explain attestations in a series of documentation updates outlined in Issue #672.

Adds a section telling users how to choose among attestations formats based on whether they are using SLSA for first party, open source, or third party close source code.

@MarkLodato @kpk47 @arewm @lehors

2023-03-27 16:55 UTC, arewm commented on docs/attestation-model.md
> +will be consumed by others, you should use the [SLSA Provenance format].
> You probably use SLSA so that others can
trust how your code was developed.

This phrasing seems a little odd/presumptuous. Do we need it in there?

Maybe instead, we can word it in a way that the SLSA provenance format is recommended to use in the absence of any other provenance format requirements.

2023-03-27 17:01 UTC, olivekl commented on docs/attestation-model.md
> +will be consumed by others, you should use the [SLSA Provenance format].
Yeah, I can see that. I was trying to guide and disambiguate based on the likely use case. I'm okay with just removing it. The other use cases also make presumptions too, though; what do you think of those?

2023-03-27 17:37 UTC, arewm commented on docs/attestation-model.md
> +will be consumed by others, you should use the [SLSA Provenance format].
Apparently I didn't notice anything on a first pass, but I see what you are saying now. Instead of chunking up like you have it, maybe we can just reinforce in the parent section (`Formats`) that there are no requirements but that there may be certain criteria to include in making a decision. Then in each section, just highlight the potential questions/concerns that might be relevant.

We can then put a recommendation at the end with a brief defense similar to what you did..

2023-03-27 22:13 UTC, joshuagl requested changes

2023-03-27 22:13 UTC, joshuagl commented on docs/attestation-model.md
> +primarily manage insider risk. If you are developering entirely in
```suggestion
primarily to manage insider risk. If you are developing entirely in
```

2023-03-27 22:13 UTC, joshuagl commented on docs/attestation-model.md
> +will be consumed by others, you should use the [SLSA Provenance format].
I agree with the comments on presumptuousness and like the idea of communicating the criteria but not presuming why those criteria are relevant.

2023-03-27 22:33 UTC, olivekl commented on docs/attestation-model.md
> +will be consumed by others, you should use the [SLSA Provenance format].
Updated! Does this work better? @arewm @joshuagl

2023-03-28 13:02 UTC, arewm commented on docs/attestation-model.md
> +will be consumed by others, you should use the [SLSA Provenance format].
Generally better, yes. I added more comments.

2023-03-28 13:23 UTC, olivekl commented on docs/attestation-model.md
> +-   Is my code produced for third party consumers, back with contracts?
Mistake: "backed with contracts." To differentiate from open source licenses.

2023-03-28 13:30 UTC, arewm commented on docs/attestation-model.md
> +In these situations, no particular format is required for internal use.
I see what you are saying. How about if we change the first sentence slightly to something like

> If these are the main considerations, the organization can choose any format for internal use.

I am not attached to it, but I wanted to still impress that there may be some entity that has a format preference. It may be too specific.

2023-03-28 13:33 UTC, arewm commented on docs/attestation-model.md
> +-   Is my code produced for third party consumers, back with contracts?
I think we can still make that clearer. I feel like the fact that a contract exists doesn't matter as much as the fact that there is a specific delivery mechanism of the code. I think that I understand what you are trying to say but I don't have the words for it. I can think about it some more.

2023-03-28 13:41 UTC, olivekl commented on docs/attestation-model.md
> +In these situations, no particular format is required for internal use.
Sounds good to me. Updated (and combined with next paragraph)

2023-03-28 15:05 UTC, lehors reviewed
I think we need to be explicit what we wish and avoid making presumptuous claims.

2023-03-28 15:05 UTC, lehors commented on docs/attestation-model.md
> +In these situations, you should use the [SLSA Provenance format]. The SLSA
I suggest sticking with the same form:
```suggestion
In these situations, it is recommended you use the [SLSA Provenance format]. The SLSA
```

2023-03-28 15:05 UTC, lehors commented on docs/attestation-model.md
> +source ecosystem. Users can verify any provenance statement in this format
This sounds like wishful thinking to me at this point. I'd rather we use some more nuance form such as:
```suggestion
Provenance format offers a path towards interoperability and cohesion across the open
source ecosystem. Users can verify any provenance statement in this format
```

2023-03-28 16:43 UTC, lehors approved these changes
LGTM. Thanks!

2023-03-28 16:47 UTC, MarkLodato approved these changes

2023-03-28 19:19 UTC, arewm commented on docs/attestation-model.md
> +-   Is my code produced for third party consumers, back with contracts?
How about if we just change it to some wording like

> Is my code produced for the sole purpose of specific third party consumers?

I feel like this more clearly represents the specific targeted relationships between parties.

2023-03-29 12:06 UTC, arewm approved these changes

2023-03-29 12:36 UTC, lehors commented on docs/attestation-model.md
> +In these situation, you may not want to make all the details of your
nit:
```suggestion
In these situations, you may not want to make all the details of your
```

2023-03-29 13:02 UTC, olivekl commented
> I think RFC2119 isn't a very good fit for this actually but in my opinion there is no real harm in capitalizing it to make the linter happy. Otherwise you need to figure another way to say the same thing without using may! Which I know is something @MarkLodato has done in the past...

I agree, I'd rather this section be more about helpful guidance than MUST, MAY, etc. Maybe we can do a dance around all the linter words (though I think "recommend" is one of them and that could be hard).

2023-03-30 23:37 UTC, kpk47 approved these changes
I agree with @lehors that RFC2119 don't apply to the sections you're writing, but it's (unfortunately) easier to dance around the keywords than fix the linter. I left a few suggested dance moves, but otherwise LGTM.

2023-03-30 23:37 UTC, kpk47 commented on docs/attestation-model.md
> +there must be a way for external users to consume and verify your provenance.
```suggestion
there needs to be a way for external users to consume and verify your provenance.
```

2023-03-30 23:37 UTC, kpk47 commented on docs/attestation-model.md
> +In these situations, you may not want to make all the details of your
```suggestion
In these situations, you might not want to make all the details of your
```

2023-03-30 23:37 UTC, kpk47 commented on docs/attestation-model.md
> +attestations, and recommended formats for different use cases.
```suggestion
attestations, and suggested formats for different use cases.
```

2023-03-30 23:37 UTC, kpk47 commented on docs/attestation-model.md
> +Currently, [SLSA Provenance format] is the recommended format for SLSA
```suggestion
Currently, [SLSA Provenance format] is the suggested format for SLSA
```

2023-03-30 23:37 UTC, kpk47 commented on docs/attestation-model.md
> +In these situations, it is recommended you use the [SLSA Provenance format]. The SLSA
```suggestion
In these situations, it is suggested you use the [SLSA Provenance format]. The SLSA
```

2023-03-30 23:51 UTC, olivekl commented
> I agree with @lehors that RFC2119 don't apply to the sections you're writing, but it's (unfortunately) easier to dance around the keywords than fix the linter. I left a few suggested dance moves, but otherwise LGTM.

Thank you! I took all the suggestions. (Danced around? SLSAed around, surely.)

2023-03-31 07:18 UTC, lehors commented
I appreciate @kpk47's effort to workaround the linter but I think the change from recommended formats to suggested is wrong. Indeed, [the spec states that one SHOULD use SLSA Provenance](https://slsa.dev/spec/v1.0/distributing-provenance#format-of-the-attestation) so, it doesn't seem right to say here that this is merely a suggestion.

2023-03-31 07:23 UTC, lehors commented on docs/attestation-model.md
> +attestations and the easiest to verify using the [Generic SLSA Verifier].
```suggestion
Currently, SLSA recommends using the [SLSA Provenance format] for SLSA
attestations since it is easy to verify using the [Generic SLSA Verifier].
```

2023-03-31 07:28 UTC, lehors reviewed
Suggested a couple of changes to avoid triggering the linter but keeping in line with the recommendation we set in the spec.

2023-03-31 07:28 UTC, lehors commented on docs/attestation-model.md
> +attestations, and suggested formats for different use cases.
I think we can simply skip the word in this instance:
```suggestion
attestations, and formats for different use cases.
```

2023-03-31 07:28 UTC, lehors commented on docs/attestation-model.md
> +[SLSA Provenance format]: /provenance/v1.md
```suggestion
[Provenance format]: /provenance/v1.md
```

2023-03-31 20:36 UTC, olivekl commented
> Suggested a couple of changes to avoid triggering the linter but keeping in line with the recommendation we set in the spec.

Thank you! I've incorporated them.

I think that addresses everything. @joshuagl do you have any requests or is it okay to merge?

2023-03-31 22:23 UTC, marcelamelara requested changes
Thanks! I only a couple minor changes.

2023-03-31 22:23 UTC, marcelamelara commented on docs/attestation-model.md
> +-   Do you develope software with standard open source licenses?
Nit: 
```suggestion
-   Do you develop software with standard open source licenses?
```

2023-03-31 22:23 UTC, marcelamelara commented on docs/attestation-model.md
> +[Verification Summary Attestation]: /attestation-model.md
This link seems to point to this same document. Should this link be pointing to: verification_summary/v1.md?

2023-04-03 10:50 UTC, joshuagl reviewed
Apart from the fixes @marcelamelara suggested this LGTM. Thanks.

2023-04-03 10:50 UTC, joshuagl commented on docs/attestation-model.md
> +the attestation.
This doesn't read quite right, is it missing a word? Perhaps: 
```suggestion
This section explains how to choose the attestation format best suited for your
situation by considering factors such as use case and who will be consuming
the attestation.
```

2023-04-03 10:50 UTC, joshuagl commented on docs/attestation-model.md
> +In these situations, it is suggested you use the [SLSA Provenance format]. The SLSA
I'd be tempted to go so far as to say we encourage use of the SLSA Provenance format.

2023-04-03 15:44 UTC, olivekl commented on docs/attestation-model.md
> +the attestation.
Thanks! I took your suggestions and added even a bit more clarification:
"This section explains how to choose the attestation format that's best suited
for your situation by considering factors such as intended use and who will be
consuming the attestation."

2023-04-03 15:44 UTC, olivekl commented on docs/attestation-model.md
> +[Verification Summary Attestation]: /attestation-model.md
done, thank you!

2023-04-03 17:06 UTC, joshuagl commented on docs/attestation-model.md
> +the attestation.
nice, thanks

2023-04-03 17:06 UTC, joshuagl approved these changes

2023-04-03 18:59 UTC, marcelamelara approved these changes
Thanks @olivekl ! LGTM

2023-04-03 19:04 UTC, merged