Remove references to expectations from levels.md
slsa-framework/slsa pull request #750
Opened 2023-03-27 19:16 UTC by MarkLodato

de5117ad added expectations and verification to the build track in levels.md, but since then we have decided to split that into a separate concept ("Verifying Artifacts"). However, the old language remained in levels.md.

This change addresses those remnants by explaining that the build level is purely about the provenance, but mentioning that the primary purpose is to enable verification and matching against expectations. Hopefully this is the right balance to strike.

Also removes a now-irrelevant TODO.

Fixes #729.
Fixes #735.

2023-03-27 19:18 UTC, MarkLodato commented
@khalkie does this address your concerns?

2023-03-27 20:47 UTC, khalkie commented on docs/spec/v1.0/levels.md
> +| [Build L1]  | Attestation showing how the package was built | Documentation, mistake prevention, inventorying |
Does it still cover mistake prevention?

2023-03-27 20:47 UTC, khalkie commented
> @khalkie does this address your concerns?

Yes this makes sense, thanks!

2023-03-27 22:16 UTC, joshuagl approved these changes

2023-03-28 14:54 UTC, arewm commented on docs/spec/v1.0/levels.md
> +    the artifact was built, including: who built the package (person or system),
The `builder.id` is required by L1, so that should theoretically describe the system which built the artifact.

2023-03-28 14:54 UTC, arewm commented on docs/spec/v1.0/levels.md
>  <dl class="as-table">
I cannot comment higher at the section heading, but I see the provenance heading as confusing.

I understand that `Build L1` only requires provenance to be generated, but the initial reading of the sections feels like it is only a requirement for L1 and not that there are additional provenance requirements for L2/L3.

The summary of each section makes it clearer. Would it be reasonable to remove the content following the `:`, instead adding some subheading with more information?

2023-03-28 14:54 UTC, arewm commented on docs/spec/v1.0/levels.md
>  | [Build L3]  | Hardened build service | Strong tamper protection |
Can we qualify tamper protection a little more here?

2023-03-28 14:54 UTC, arewm commented on docs/spec/v1.0/levels.md
>  | [Build L2]  | Signed attestation, generated by a hosted build service | Reduced attack surface, weak tamper protection |
Attestation is used in the summary table, but it is `provenance attestation` elsewhere. Which should be the shortened version that is preferred if only using one word? I feel like we just use `provenance` elsewhere instead of just `attestation`.

2023-03-28 17:59 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
>  | [Build L2]  | Signed attestation, generated by a hosted build service | Reduced attack surface, weak tamper protection |
Fixed. I filed #758 to do a full pass throughout the spec.

2023-03-28 17:59 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
>  <dl class="as-table">
Do you mind filing a separate issue for this? It seems unrelated to this PR. I think it's useful to have a short description of each level to stick in the reader's minds, and I had been interpreting this as the difference from the prior level.

2023-03-28 17:59 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
>  | [Build L3]  | Hardened build service | Strong tamper protection |
Let's merge with the comment thread above since you're both getting at the same thing.

2023-03-28 17:59 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +| [Build L1]  | Attestation showing how the package was built | Documentation, mistake prevention, inventorying |
[joining with the other thread]

> (@khalkie) Does it still cover mistake prevention?
> (@arewm) Can we qualify tamper protection a little more here?

IMO it does *when verified against expectations*. My intention was to present the levels as:
L1 = mistake protections (stop unintentional badness)
L2 = weak tamper protection (stop unmotivated / risk-averse adversaries)
L3 = strong tamper protection (stop motivated adversaries)

Do you think that framing is useful? Is it confusing that it's "when verified against expectations"? Any other ideas on how to frame it that avoids those issues?

2023-03-28 17:59 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +    the artifact was built, including: who built the package (person or system),
Yeah, implicit in that statement is that at L1, the `builder.id` could be a person since it was built on their workstation. But I think that's more confusing than helpful. Let me think of alternatives...

2023-03-28 19:35 UTC, arewm commented on docs/spec/v1.0/levels.md
>  <dl class="as-table">
I just created a PR for it. I think that this might be sufficient: https://github.com/slsa-framework/slsa/pull/761

2023-03-28 20:28 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +| [Build L1]  | Attestation showing how the package was built | Documentation, mistake prevention, inventorying |
What about replacing the current "Benefits" column with the following?

Level | Focus
--- | ---
Build L1 | Mistakes, documentation
Build L2 | Unsophisticated adversaries
Build L3 | Sophisticated adversaries

(I'm not 100% sold, but maybe this spurs further ideas?)

2023-03-29 12:31 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +| [Build L1]  | Attestation showing how the package was built | Documentation, mistake prevention, inventorying |
Good point. What about the following?

| Level | Focus
| --- | ---
| Build L1 | Mistakes, documentation
| Build L2 | Tampering after build
| Build L3 | Tampering during build
| Build L4 | Completeness of provenance

2023-03-29 12:42 UTC, arewm commented on docs/spec/v1.0/levels.md
> +| [Build L1]  | Attestation showing how the package was built | Documentation, mistake prevention, inventorying |
I think that makes more sense. L4, when it comes, _can_ include reproducibility ... or it can also be included in a L5 as it also has a clear separation.

I also like how it clearly represents what _is not_ in focus in levels based on what _is_ in focus in future levels.

2023-03-29 12:51 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +| [Build L1]  | Attestation showing how the package was built | Documentation, mistake prevention, inventorying |
[cc812c3](https://github.com/slsa-framework/slsa/pull/750/commits/cc812c33a03ec98f8bdb9b22304a38b130e9f23e)

OK to resolve?

2023-03-29 12:54 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +    the artifact was built, including: who built the package (person or system),
I replaced with "what entity built the package". How does that sound?

2023-03-29 12:55 UTC, arewm commented on docs/spec/v1.0/levels.md
> +| [Build L1]  | Attestation showing how the package was built | Documentation, mistake prevention, inventorying |
I am okay with it, yes. Thanks!

2023-03-30 00:09 UTC, arewm requested changes

2023-03-30 00:09 UTC, arewm commented on docs/spec/v1.0/levels.md
> +Package has a provenance attestation showing how it was built. Can be used to
L1 just needs provenance, not a provenance attestation.

2023-03-30 00:09 UTC, arewm commented on docs/spec/v1.0/levels.md
> +| Track/Level | Requirements | Focus |
I am okay with the change up here, but it is inconsistent with the rest of the page as we talk about benefits lower down. If you want to be consistent, we should change it there too.

2023-03-30 13:33 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +Package has a provenance attestation showing how it was built. Can be used to
Done

2023-03-30 13:36 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +| Track/Level | Requirements | Focus |
It reads OK to me as-is? I interpret "focus" as a brief summary, while the "benefits" is a full list. The two contents are consistent; just the "focus" is a subset of "benefits.

@olivekl any opinions?

2023-03-30 13:38 UTC, arewm approved these changes

2023-03-30 13:42 UTC, MarkLodato commented on docs/spec/v1.0/levels.md
> +| Track/Level | Requirements | Focus |
Got it, thanks! I'll leave it as-is then.

2023-03-30 13:42 UTC, merged