Add some clarification related to #653.
slsa-framework/slsa pull request #751
Opened 2023-03-27 19:22 UTC by arewm

* Fixed vestigial section references
* Provenance accuracy is part of integrity
* Clarified producer and build system relationship

@jchestershopify, can you take a look at these changes as well?

2023-03-27 19:32 UTC, arewm commented
@jchestershopify, you can see the cross-referenced external parameters in the preview: https://deploy-preview-751--slsa.netlify.app/spec/v1.0/requirements

2023-03-27 19:43 UTC, MarkLodato requested changes
Thanks!

2023-03-27 19:43 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +[package ecosystem](verifying-artifacts.md#package-ecosystem) that requires
nit: can you use a [link reference definition](https://github.github.com/gfm/#link-reference-definitions) for this and `[package ecosystem]` to avoid having the same (long) target twice? That makes it easier to read the source and to maintain (updating one place instead of two).

2023-03-28 13:02 UTC, joshuagl approved these changes
LGTM, thanks.

2023-03-28 13:31 UTC, MarkLodato approved these changes

2023-03-28 13:34 UTC, jchestershopify approved these changes
One nit, otherwise LGTM.

2023-03-28 13:35 UTC, arewm commented on docs/spec/v1.0/requirements.md
> +configuration file, the producer MUST complete the confiuration file and keep
aha, thanks!

2023-03-28 13:40 UTC, merged