Address TODOs in Verifying build systems
slsa-framework/slsa pull request #771
Opened 2023-03-30 18:08 UTC by kpk47

- Align terminology with Build model
- Rewrite threat model in terms of Threats & mitigations page
- Remove diagrams that don't match style used in the rest of the spec

2023-03-30 18:47 UTC, olivekl commented on docs/spec/v1.0/verifying-systems.md
> +The provenance consumer is responsible for deciding whether they trust a builder
Might be good to link to guiding principles here, to explain the "trust systems, verify artifacts" aspect.

2023-03-30 18:47 UTC, olivekl commented on docs/spec/v1.0/verifying-systems.md
> +assessments, we provide a common threat model and builder model for reasoning
Is it still correct to say that we provide a common threat model, since it has moved? Or do you want to link to that section in threats.md?

2023-03-30 18:47 UTC, olivekl commented on docs/spec/v1.0/verifying-systems.md
> +use to describe their builders to consumers along with sample answers that do
Awesome, samples answers would be great. I didn't see them, though. Have they been added? I think they'll be really useful.

2023-03-31 15:03 UTC, MarkLodato requested changes

2023-03-31 15:03 UTC, MarkLodato commented on docs/spec/v1.0/verifying-systems.md
This change is really hard to review because there are a lot of formatting changes intermixed with subtle wording changes, so it looks like one giant diff hunk rather than a bunch of small changes. Could you split this into multiple commits so that it's practical to review? One commit should just change formatting (wrapping to 80 columns) without any content changes, and then the other commits can change the content. Separate PRs is also OK, since the former should be very quick to approve and merge.

2023-03-31 16:14 UTC, kpk47 commented on docs/spec/v1.0/verifying-systems.md
I sent https://github.com/slsa-framework/slsa/pull/777 for line wrapping.

2023-04-03 11:27 UTC, joshuagl reviewed
This LGTM overall. There are a few confusing sentences that mention environment in two different contexts since replacing executor with environment.

Following this change do you think the term environment still matches the definition in the terminology?

How does the updated build-model.svg here relate to build-model.svg changes in #781?

2023-04-03 11:27 UTC, joshuagl commented on docs/spec/v1.0/verifying-systems.md
> +environment arbitrarily. Build environments must have a means to fetch input
> "Build users are free to modify the environment inside the environment arbitrarily."

Fun artefact of replacing executor with environment. :-)

2023-04-03 11:27 UTC, joshuagl commented on docs/spec/v1.0/verifying-systems.md
> +    -   What tools and environment are available in environments on creation? How
This is another strange sentence since replacing executor with environment

2023-04-03 13:00 UTC, MarkLodato requested changes
Overall looks good. Just some minor consistency suggestions.

2023-04-03 20:11 UTC, kpk47 commented on docs/spec/v1.0/verifying-systems.md
> +    processed by the environment?
Done (with one notable exception in the definition of "build environment").

2023-04-03 20:11 UTC, kpk47 commented on docs/spec/v1.0/verifying-systems.md
> +#### Prompts for assessing the control plane
Done

2023-04-03 20:11 UTC, kpk47 commented on docs/spec/v1.0/verifying-systems.md
>          its own file system partitions on executors, hardware security modules
Done

2023-04-03 20:11 UTC, kpk47 commented on docs/spec/v1.0/verifying-systems.md
> +build user or project. Build users are free to modify the environment inside the
Done

2023-04-03 20:11 UTC, kpk47 commented on docs/spec/v1.0/verifying-systems.md
> +environment arbitrarily. Build environments must have a means to fetch input
Done

2023-04-03 20:11 UTC, kpk47 commented on docs/spec/v1.0/verifying-systems.md
> +    -   What tools and environment are available in environments on creation? How
Done

2023-04-03 20:16 UTC, MarkLodato approved these changes

2023-04-03 20:16 UTC, MarkLodato commented on docs/spec/v1.0/verifying-systems.md
> +expectations. To bypass this, the adversary tries to either (a) tamper with a
Could you link to verifying-artifacts in the first sentence (e.g. on 'verifiers' or 'only accept' or  'expectations')?

2023-04-03 20:19 UTC, kpk47 commented
> This LGTM overall. There are a few confusing sentences that mention environment in two different contexts since replacing executor with environment.
> 
> Following this change do you think the term environment still matches the definition in the terminology?
> 
I updated terminology.md to align them.
> How does the updated build-model.svg here relate to build-model.svg changes in #781?
I'll be sure they line up when merging.

2023-04-03 20:22 UTC, kpk47 commented on docs/spec/v1.0/verifying-systems.md
> +expectations. To bypass this, the adversary tries to either (a) tamper with a
Done

2023-04-04 10:42 UTC, lehors requested changes
LGTM. A couple of minor changes.

Side note: I noticed that you have been changing the capitalization of the section headers. I think it would be good to document somewhere what the rules are on this kind of stuff so that content contributors know what is expected. Otherwise, we are going to keep having variations.

2023-04-04 10:42 UTC, lehors commented on docs/spec/v1.0/verifying-systems.md
> +artifacts and provenance unless the have some proof that the provenance is
```suggestion
artifacts and provenance unless they have some proof that the provenance is
```

2023-04-04 10:42 UTC, lehors commented on docs/spec/v1.0/verifying-systems.md
> +This page describes the parts of a build system that consumers should assess
I wonder how that "should" did not trigger the linter, I think it should be capitalized:
```suggestion
This page describes the parts of a build system that consumers SHOULD assess
```

2023-04-04 14:33 UTC, MarkLodato commented
I applied the suggestions and resolved merge conflicts. Could someone do one last review? Thanks!

2023-04-04 14:46 UTC, merged