SLSA v1: re-add exceptions for tenant-generated provenance fields
slsa-framework/slsa pull request #779
Opened 2023-03-31 16:36 UTC by MarkLodato

Background: SLSA v0.1 exempted `subject` and `reproducible` from the service-generated requirement, but v1.0 unintentionally dropped these exceptions. In practice, the `subject` exception is necessary at a minimum.

Solution:

-   Re-add exception for `subject`.
-   Add exception for other fields in the provenance that are not required by SLSA Build L2, such as `resolvedDependencies`. Since they are not required by SLSA, they should not be subject to other requirements. However, recommend that such tenant-generated fields be documented.
-   Fully document the non-threat of an adversary forging the output digest.

Fixes #772.

/cc @bobcatfish @arewm

2023-03-31 16:39 UTC, kpk47 approved these changes

2023-03-31 16:39 UTC, kpk47 commented on docs/spec/v1.0/threats.md
> +registry. Solution: This is out of scope of SLSA.
How is this an example of this threat? It doesn't sound like the adversary forged the provenance in this case.

2023-03-31 17:44 UTC, MarkLodato commented on docs/spec/v1.0/threats.md
> +registry. Solution: This is out of scope of SLSA.
Removed.

2023-03-31 18:20 UTC, TomHennen requested changes
I think this is safe and makes sense.  Just a couple of things that might need clarification?

2023-03-31 18:43 UTC, arewm reviewed
You did not clarify this from the source issue. Were you planning on addressing that here too?
> Add guidance for documentation of builder.id on what fields are guaranteed by the builder vs tenant-generated.

Based on the original specification, I assume that `resolvedDependencies` will need to be specified from inside the build system at a L4-equivalent. Is that accurate?

2023-03-31 18:43 UTC, arewm commented on docs/spec/v1.0/requirements.md
>  *Accuracy:* The provenance MUST be generated by the build system (i.e. within
There isn't clear consistency across the requirements page. I see the build system as a generic term for the trusted boundary producing an artifact. It may be a service (GitHub Actions, etc.) or it may be a non-service (individual's machine). 

Since the isolation requirements for L2 are a build service, it is consistent to start talking about a build service at L2 requirements in provenance. 

That being said, consistency is likely preferable over the ability to reason about this.

2023-03-31 18:43 UTC, arewm approved these changes
Comments were just comments. I think this PR still looks good. Thanks!

2023-03-31 19:29 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
> +    -   Any field that is not marked as REQUIRED for Build L2. For example,
Filed https://github.com/slsa-framework/slsa/issues/780.

2023-03-31 19:29 UTC, MarkLodato commented on docs/spec/v1.0/requirements.md
>  *Accuracy:* The provenance MUST be generated by the build system (i.e. within
I'd prefer to keep this PR focused and leave terminology cleanup to #714. The inconsistency goes well beyond this one requirement, and this PR doesn't touch the text in question. The new uses of "build system" are consistent with the text of the previous paragraph.

2023-03-31 19:32 UTC, TomHennen commented on docs/spec/v1.0/requirements.md
>  *Accuracy:* The provenance MUST be generated by the build system (i.e. within
SGTM

2023-03-31 19:32 UTC, TomHennen approved these changes

2023-03-31 19:33 UTC, arewm commented on docs/spec/v1.0/requirements.md
>  *Accuracy:* The provenance MUST be generated by the build system (i.e. within
+1

2023-04-02 04:21 UTC, mlieberman85 commented on docs/spec/v1.0/threats.md
> +`evil/my-package` claims that it build artifact `abcdef` when it did not.
```suggestion
`evil/my-package` claims that it built artifact `abcdef` when it did not.
```

2023-04-02 04:26 UTC, mlieberman85 reviewed
other than typo looks good to me

2023-04-03 10:41 UTC, joshuagl approved these changes

2023-04-03 10:41 UTC, joshuagl commented on docs/provenance/v1.md
> +    verified by the trusted control plane, aside from the `subject`.
Nit: I find this phrasing clearer and more in-keeping with the rest of the language in the spec
```suggestion
-   Any fields that are generated by the tenant-controlled build process and not
    verified by the trusted control plane, except for the `subject`.
```

2023-04-03 11:44 UTC, MarkLodato commented
> Based on the original specification, I assume that `resolvedDependencies` will need to be specified from inside the build system at a L4-equivalent. Is that accurate?

Yes, that is the thinking, though the details are still to be worked out.

2023-04-03 11:44 UTC, merged