Add quick RC2 announcement
slsa-framework/slsa pull request #794
Opened 2023-04-03 20:38 UTC by mlieberman85

2023-04-03 21:07 UTC, kpk47 approved these changes

2023-04-03 21:22 UTC, MarkLodato requested changes

2023-04-03 21:22 UTC, MarkLodato commented on docs/_posts/2023-04-04-slsa-v1-rc2.md
> +We’re excited to announce the release of SLSA v1.0 Release Candidate 2 (RC2) following the valuable feedback we received on the first release candidate. With RC2, we are still looking for additional
nit: Could you wrap at 80 columns to make it easier to review, comment, and edit? Thanks!

2023-04-03 21:22 UTC, MarkLodato commented on docs/_posts/2023-04-04-slsa-v1-rc2.md
> +-   Are there any inconsistencies or discrepancies in the terminology used throughout the specification?
I think we want the opposite - we're mostly interested in **non-editorial** feedback. We can always make clarity changes, but now is the time to make breaking changes. We also need to use language that mirrors our governance doc. Finally it would be helpful to add a brief changelog.

Here's a suggestion:

```markdown
We’re excited to announce [SLSA v1.0 Release Candidate 2 (RC2)][RC2] following
the valuable feedback we received on the [first release candidate][RC1]. This is
intended to be the final release candidate before marking v1.0 as an [Approved
Specification].

We ask that all community members review the full specification and raise any
significant concerns as a [GitHub issue] **by April 17, 2023**. While we always
appreciate clarity or editorial feedback, during this review period we are
specifically looking to identify significant problems that would require a
breaking change---and thus a new version---to address. (We plan to continue to
addressing clarity issues via editorial changes after the v1.0 release,
particularly the [backlog] of editorial feedback from RC1 that we have not yet
addressed.)

Assuming there are no significant objections, we plan to mark this candidate as
an Approved Specification on April 19.

We appreciate the continued support and engagement from the SLSA community and
all early adopters who have provided valuable feedback on the previous release
candidate. Thank you for your contributions to the project!

[GitHub issue]: https://github.com/slsa-framework/slsa/issues
[RC1]: 2023-02-24-slsa-v1-rc.md
[RC2]: /spec/v1.0/
[backlog]: https://github.com/orgs/slsa-framework/projects/1/views/1
[Approved Specification]: /spec-stages#approved

## Summary of changes since RC1

There have been no major changes to requirements since [RC1]. Most of the
changes have been editorial in nature. The following is a summary of the most
significant changes:

-   Added [Distributing provenance](/spec/v1.0/distributing-provenance) page
-   Renamed "non-forgeable" to "unforgeable"
-   Updated [VSA](/verification_summary/v1) for v1.0
-   Updated [Threats & mitigations](/spec/v1.0/threats) for v1.0 and relabeled
    the diagram (swapped labels "D" and "E")
-   Resolved various inconsistencies, simplified terminology, and added more
    introductory material
```

2023-04-03 21:31 UTC, mlieberman85 commented on docs/_posts/2023-04-04-slsa-v1-rc2.md
> +-   Are there any inconsistencies or discrepancies in the terminology used throughout the specification?
Yeah, that makes sense. I'll just take your changes

2023-04-04 00:07 UTC, MarkLodato approved these changes

2023-04-04 01:39 UTC, mlieberman85 commented
Just leaving a note to not merge this until EMEA checks this and says we're good for RC2.

2023-04-04 06:07 UTC, lehors requested changes
Very nice. Need to fix the link to RC2 though.

2023-04-04 06:07 UTC, lehors commented on docs/_posts/2023-04-04-slsa-v1-rc2.md
> +[RC2]: /spec/v1.0/
I think this needs to point to the RC2 specific URL which, once published, should be:
```suggestion
[RC2]: /spec/v1.0-rc2
```

2023-04-04 08:24 UTC, joshuagl approved these changes

2023-04-04 15:16 UTC, di approved these changes
LGTM aside from my one comment

2023-04-04 15:37 UTC, MarkLodato commented on docs/_posts/2023-04-04-slsa-v1-rc2.md
> +[RC1]: 2023-02-24-slsa-v1-rc.md
It does work: https://github.com/benbalter/jekyll-relative-links

You can also see in the preview: https://deploy-preview-794--slsa.netlify.app/blog/2023/02/slsa-v1-rc

2023-04-04 15:44 UTC, lehors commented on docs/_posts/2023-04-04-slsa-v1-rc2.md
> +[RC1]: 2023-02-24-slsa-v1-rc.md
For what it's worth I too initially thought it wouldn't work but I checked the preview and saw that it does work indeed. The wonders of Jekylll...

2023-04-04 15:47 UTC, di commented on docs/_posts/2023-04-04-slsa-v1-rc2.md
> +[RC1]: 2023-02-24-slsa-v1-rc.md
TIL!

2023-04-04 18:20 UTC, lehors approved these changes

2023-04-04 18:20 UTC, merged