Add FAQ item on SBOMs
slsa-framework/slsa pull request #827
Opened 2023-04-12 11:20 UTC by joshuagl

An attempt at answering this frequent source of confusion for users.

2023-04-12 11:53 UTC, MarkLodato approved these changes
Thanks! This is great.

To make sure everyone is on board with this, I suggest we get a few more approvals, particularly the Positioning SIG. @melba-lopez @mlieberman85

2023-04-12 11:53 UTC, MarkLodato commented on docs/spec/v1.0/faq.md
> +Software Bill of Materials (SBOM) are a frequently recommended tool for
Link to https://ntia.gov/sbom?

2023-04-12 16:54 UTC, melba-lopez requested changes
Please see my concerns documented in review

2023-04-12 16:54 UTC, melba-lopez commented on docs/spec/v1.0/faq.md
Here are several definitions to provenance --- which folks are going to question versus slsa's definition in the faq vs slsa.dev.  SLSA.DEV seems to match NIST, but this post does not.  


**ON SLSA.DEV  IT STATES:** 
`To trace software back to the source and define the moving parts in a complex supply chain, provenance needs to be there from the very beginning. It’s the verifiable information about software artifacts describing where, when and how something was produced. For higher SLSA levels and more resilient integrity guarantees, provenance requirements are stricter and need a deeper, more technical understanding of the predicate.`


**NIST DEF**

```Definition(s):
  The chronology of the origin, development, ownership, location, and changes to a system or system component and associated data. It may also include personnel and processes used to interact with or make modifications to the system, component, or associated data.
Source(s):
[NIST SP 800-161r1](https://doi.org/10.6028/NIST.SP.800-161r1)
[NIST SP 800-37 Rev. 2](https://doi.org/10.6028/NIST.SP.800-37r2)

  The chronology of the origin, development, ownership, location, and changes to a system or system component and associated data. It may also include the personnel and processes used to interact with or make modifications to the system, component, or associated data.
Source(s):
[NIST SP 800-53 Rev. 5](https://doi.org/10.6028/NIST.SP.800-53r5)

  The records describing the possession of, and changes to, components, component processes, information, systems, organization, and organizational processes. Provenance enables all changes to the baselines of components, component processes, information, systems, organizations, and organizational processes, to be reported to specific actors, functions, locales, or activities.
Source(s):
[NISTIR 7622](https://doi.org/10.6028/NIST.IR.7622) under Provenance

  Metadata pertaining to the origination or source of specified data.
Source(s):
[NIST Privacy Framework Version 1.0](https://doi.org/10.6028/NIST.CSWP.01162020) under Provenance from [NISTIR 8112](https://doi.org/10.6028/NIST.IR.8112) - Adapted```

2023-04-12 16:54 UTC, melba-lopez commented on docs/spec/v1.0/faq.md
Another item is around this particular verbiage:

```
"While an SBOM is not well suited as a requirement for the Build track, SBOMs are good practice which may form part of a future SLSA Vulnerabilities track. Further, SLSA Provenance can increase the trustworthiness of an SBOM by describing how the SBOM was created."
```

If we follow SLSA.dev definition = NIST definition, then Provenance can be handled by SBOM (also referenced in NIST) ... The SBOM for the BUILD system effectively.  

If you want to say the build actions/configurations is not included in an SBOM (per specification), then that would be more accurate description.  There are other specifications being developed that are more equivalent to that.

2023-04-13 17:52 UTC, MarkLodato commented on docs/spec/v1.0/faq.md
Regarding the comment that SBOM is focused on more than vulnerabilities, here's a quote from NTIA's [Minimum Elements For a Software Bill of Materials (SBOM)](https://www.ntia.doc.gov/files/ntia/publications/sbom_minimum_elements_report.pdf):

> The primary security use case for SBOM today is to identify known vulnerabilities and risks in the software supply chain

2023-04-13 21:20 UTC, joshuagl commented
I just pushed a couple of extra commits which try to address the concerns raised here:
1. 2b6d97b attempts to convey Arnaud's suggestion, that the intersecting slsa/attestations and SBOM spaces are rapidly evolving in 
2. 7891bc3 adds some more detail to the claims of abstraction and granularity differences

2023-04-13 21:24 UTC, joshuagl commented
> What do you think about the following, breaking up the question into two sub-questions?

This could work. I'm curious what others think?

The answer to the question "(2) Why does SLSA not recommend an existing SBOM format for provenance?" seems especially useful to include.

2023-04-14 13:05 UTC, trishankatdatadog commented
> This could work. I'm curious what others think?

This is better, but it still handwaves how in-toto provenance attestations could be integrated with SBOMs. I don't think it's a good idea to allow for that much confusion while people are busy producing both SBOMs and in-toto attestations. What do others think?

2023-04-17 16:23 UTC, NicoleSchwartz commented
I love the revisions thank you - as discussed in the meeting today I like that we are linking out to SBOM documents as they are iterating frequently, and also I like us not taking a stance for requiring them.

2023-04-18 07:37 UTC, joshuagl commented
@lehors I'd appreciate your review, if you have time? Do my suggested edits address your concerns?

2023-04-18 11:10 UTC, lehors commented
I like Mark's proposed update. It defines SBOMs very broadly and remains open with regard to the future. This protects us from criticism of trying to paint SBOMs into a too narrow space which may be seen as inaccurate by some, especially given the various developments underway, and it protects us from criticism about not being willing to leverage work happening elsewhere. What is said about the current state of SBOM formats is factual.

2023-04-20 13:08 UTC, trishankatdatadog commented
As I discussed in the Spec meeting earlier this week, I can see that it's important not for SLSA to require any SBOMs at least for v1.0. However, at the same time, I think it might clarify the matter to say that, if the user so wishes, they _could_ add any SBOMs with released artifacts in the `subject` of any provenance. This will give them the benefit of strongly (especially in >= L2) associating SBOMs with artifacts. Or is even this optional way of integrating SLSA with SBOMs too strong to say right now, and we should defer it to the future?

2023-04-20 13:20 UTC, lehors commented
I for one think that we will get to see both SBOMs and Provenance used together but I think we're better off waiting for the dust to settle on this before getting into any specifics.

2023-04-20 13:35 UTC, trishankatdatadog commented
SGTM, @mlieberman85 and @lehors, and concur, clarifying the ways one can integrate SLSA and SBOMs can wait.

2023-04-20 13:35 UTC, trishankatdatadog approved these changes

2023-05-15 12:12 UTC, lehors commented
Sorry @joshuagl I didn't mean to stall this. I like Mark's proposal better but I can live with the current proposal.

2023-05-16 09:15 UTC, joshuagl commented
Thanks Arnaud. I'll merge as-is and we can iterate based on feedback and how the space evolves in the coming months.

2023-05-16 09:15 UTC, merged