feat: Add notice if viewing outdated versions of the spec
slsa-framework/slsa pull request #862
Opened 2023-05-16 06:23 UTC by ianlewis

When viewing older versions of the spec, this PR adds a notice at the top of pages linking them to the corresponding page in the newest version of the spec (or the top page if the page doesn't exist).

2023-05-16 10:24 UTC, joshuagl requested changes
Thanks for proposing this @ianlewis! I think this is a great addition.
I wonder if we would be better off using the styling, and perhaps mechanism, of the existing "working draft" banner? https://github.com/slsa-framework/slsa/blob/d799c7bf2f2f321e46956ee2bb2ad0bd85b31983/docs/_includes/header.html#L54

We could use the same styling and mechanism but with a different message if status is `retired`  vs. `draft`?

2023-05-16 10:24 UTC, joshuagl commented on docs/_data/versions.yml
> +  name: SLSA
```suggestion
  name: Core specification
```

2023-05-16 10:24 UTC, joshuagl commented on docs/_data/versions.yml
> +  name: Provenance
```suggestion
  name: Provenance attestation
```

2023-05-16 10:24 UTC, joshuagl commented on docs/_data/versions.yml
> +  name: VSA
```suggestion
  name: Verification summary (VSA)
```

2023-05-16 11:13 UTC, ianlewis commented on docs/_data/versions.yml
> +  name: Provenance
I think this describes the spec, so would it make sense to say something like "Provenance attestation version 1.0?".

2023-05-16 13:04 UTC, ianlewis commented
> Thanks for proposing this @ianlewis! I think this is a great addition. I wonder if we would be better off using the styling, and perhaps mechanism, of the existing "working draft" banner?
> 
> https://github.com/slsa-framework/slsa/blob/d799c7bf2f2f321e46956ee2bb2ad0bd85b31983/docs/_includes/header.html#L54
> 
> We could use the same styling and mechanism but with a different message if status is `retired` vs. `draft`?

I redid the message to use this and allowed both the draft and new version message to be dismissed separately. I also updated the versions data to be a list rather than an object so it could be ordered.

2023-05-16 13:04 UTC, MarkLodato commented on docs/_includes/old-version-warning.html
> +  NOTE: this is a naive sort and may need to be adjusted to sort semver in the future.
suggestion: instead of all this logic, what about just having a `current` field in _data/versions.yml? This was removed in d9308ee5dc02c6732c136b421aa69c72dc9c509d because it was unused, but if we now have a use case, let's just add it back. That seems easier to maintain.

2023-05-16 13:04 UTC, MarkLodato commented on docs/_includes/old-version-warning.html
> +        <div class="rounded-lg text-green p-5 border border-green-400 inline-block text-center w-full mt-6 h4">{{ spec_name }} {{ item[1].name | downcase }} is available now! See the newest documenta
nit: missing period at end

2023-05-16 13:43 UTC, ianlewis commented on docs/_data/versions.yml
On the other hand that might have implications regarding the Community Specification License that use the "Approved" language. IIUC an "Outdated" spec would still be "Approved" per the CSL, so changing it might be confusing.

https://github.com/slsa-framework/governance/blob/main/1._Community_Specification_License-v1.md

2023-05-16 13:43 UTC, ianlewis commented on docs/_includes/old-version-warning.html
> +  NOTE: this is a naive sort and may need to be adjusted to sort semver in the future.
Done.

2023-05-16 13:43 UTC, ianlewis commented on docs/_includes/old-version-warning.html
> +        <div class="rounded-lg text-green p-5 border border-green-400 inline-block text-center w-full mt-6 h4">{{ spec_name }} {{ item[1].name | downcase }} is available now! See the newest documenta
Done.

2023-05-16 15:23 UTC, MarkLodato commented on docs/_data/versions.yml
Right. Or some other language that differentiates latest from older, e.g. "Approved (outdated)"

2023-05-16 15:23 UTC, MarkLodato commented on docs/_includes/header.html
> +  {%- if version.draft -%}
nit: For consistency, all of the tags should be `{%- ... %}` to just consume leading whitespace.

2023-05-16 15:23 UTC, MarkLodato commented on docs/_includes/header.html
> -<input id="important-messages-checkbox" type="checkbox" hidden>
This needs to stay outside the `<section>` so that it's a sibling of `<main>`, otherwise the CSS rule to fix the scroll margin doesn't work. Example: https://deploy-preview-862--slsa.netlify.app/provenance/v0.2#schema - notice how the header is covered by the banner.

I suggest keeping the HTML and CSS structure the same (don't change IDs) and instead just change the contents with an if/else. We won't ever need to display both draft AND outdated.

That is:

```liquid
{%- assign spec = site.data.versions[spec_name] %}
{%- if spec_version != spec.current or spec.versions[spec_version].draft %}
<input ...>
<section ...>
  <div>
    <label for=...>✕</label>
    {%- if spec.versions[spec_version].draft %}
      <p>This is a working draft...</p>
      <p>...</p>
    {%- else %}
      ... link to current version ...
    {%- endif %}
  </div>
</section>
```

2023-05-16 16:11 UTC, ianlewis commented on docs/_includes/header.html
> -<input id="important-messages-checkbox" type="checkbox" hidden>
Ok, I tried to make them separate messages but I'll just make it all one message and put them both in the div.

2023-05-16 16:23 UTC, ianlewis commented on docs/_includes/header.html
> -<input id="important-messages-checkbox" type="checkbox" hidden>
Done.

2023-05-16 16:24 UTC, ianlewis commented on docs/_includes/header.html
> +  {%- if version.draft -%}
Done.

2023-05-16 16:54 UTC, MarkLodato approved these changes
Thanks, Ian1

2023-05-16 16:54 UTC, MarkLodato commented on docs/_data/versions.yml
> +      draft: true
remove (looks like it was added just for testing?)

2023-05-16 16:54 UTC, MarkLodato approved these changes
Thanks, Ian!

2023-05-16 17:11 UTC, ianlewis commented on docs/_data/versions.yml
> +      draft: true
ah, yeah... good catch. Done.

2023-05-16 17:13 UTC, ianlewis commented
@joshuagl PTAL. I think I need your approval to merge.

2023-05-17 10:45 UTC, joshuagl approved these changes
Looks great, thanks Ian!

2023-05-17 10:45 UTC, merged