Add more charities for build model terminologies (issue #714)
slsa-framework/slsa pull request #876
Opened 2023-06-07 18:38 UTC by chtiangg

In the build model section: 
1. Adds steps in the description for how we model a build, and moves the word "external" in front of the word "parameters" in step 1.
2. In the diagram, adds a tenant component, adds steps to align with the description in #1, adds a legend, uses the same font size for every component, uses solid arrow lines for workflows, and makes the diagram compact.
3. Sort the primary term table alphabetically, and define "Build Caches".
4. Adds a collapse card for "Ambiguous terms to avoid", and clarify "build recipe" and "builder".
5. Makes "Ambiguous terms to avoid" a collapse card in the Package model section.

After this change for the terms mentioned in [issue #714](https://github.com/slsa-framework/slsa/issues/714):

- Build process: is defined in "Build" before this PR, see [link](https://slsa.dev/spec/v1.0/terminology#:~:text=Build-,Process,-that%20converts%20input).
- Build: is defined before this PR.
- Build service: is defined in "Platform" before this PR, see [link](https://slsa.dev/spec/v1.0/terminology#:~:text=of%20software%20and-,services,-that%20must%20be) .
- Builder: is clarified in "Ambiguous terms to avoid".
- Build system: is defined in "Platform" before this PR, see [link](https://slsa.dev/spec/v1.0/terminology#:~:text=Platform-,System,-that%20allows%20tenants)
- Build environment: s defined before this PR.
- Build tools: is included in "Dependencies" before this PR, see [link](https://slsa.dev/spec/v1.0/terminology#:~:text=source%20artifacts%2C%20or-,build%20tools,-.)
- Build model: no need to define.
- Build platform: is defined before this PR.
- Build recipe: is clarified in "Ambiguous terms to avoid".
- Build infrastructure: **didn't change, but please let me know if it needs to be clarified.**
- Build configuration source: is clarified in "Ambiguous terms to avoid".
- Build worker: **didn't change, but not sure if this is really needed.**
- Build cache: is newly added to the term table. 
- Builder model: **didn't change, but not sure if this is really needed.**
- Build executor: is somewhat defined in "Build environment" before this PR, see [link](https://slsa.dev/spec/v1.0/terminology#:~:text=The%20independent-,execution,-context%20in%20which)
- Build definition: is clarified in "Ambiguous terms to avoid".
- Control Plane: is defined before this PR.

2023-06-07 18:40 UTC, chtiangg commented
Sorry, included a github action workflow script by mistake, and removing it now.

2023-06-07 19:35 UTC, chtiangg commented
Well, had a pretty bad experience with git rebase, but made it work.

2023-06-09 09:41 UTC, joshuagl requested changes
Thanks for working on these clarifications, these changes are a solid improvement.
I have a few minor requests and a couple of questions, LMK what you think.

2023-06-09 09:41 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +<details><summary>Ambiguous term to avoid</summary>
```suggestion
<details><summary>Ambiguous terms to avoid</summary>
```

2023-06-09 09:41 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +<details><summary>Ambiguous term to avoid</summary>
```suggestion
<details><summary>Ambiguous terms to avoid</summary>
```

2023-06-09 09:41 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +-   *Build recipe:* Could mean `external parameters`, but may include concrete
```suggestion
-   *Build recipe*: Could mean `external parameters`, but may include concrete
```

2023-06-09 09:41 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +performs arbitrary steps, (4) possibly fetching additional dependencies, (5) and
nit:
```suggestion
performs arbitrary steps, possibly (4) fetching additional dependencies, and (5)
```

I did initially wonder whether we should try and make these steps a list, but I worry that might reduce clarity by removing some of the context in the paragraph which doesn't map explicitly to the diagram. WDYT?

2023-06-09 09:41 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> -| Platform | System that allows tenants to run builds. Technically, it is the transitive closure of software and services that must be trusted to faithfully execute the build. It includes software, h
Can you undo the changes to sort the terms alphabetically? We have a (perhaps undocumented?) convention to sort the terminology such that no definition uses a term which hasn't already been defined (see the other two terminology tables before this one).

2023-06-09 09:41 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +    `build platform` which allows tenants to run builds.
```suggestion
    `build platform` to mean the system which allows tenants to run builds.
```
But, we define the term as 'platform' not 'build platform'

2023-06-09 12:00 UTC, lehors commented on docs/spec/v1.0/build-model.svg
Unfortunately this significantly reduces the size of all the labels. When they appear to be about the same size as the text on my browser they are now much smaller.
Old:
<img width="363" alt="Screenshot 2023-06-09 at 1 57 33 PM" src="https://github.com/slsa-framework/slsa/assets/6464618/7b9bd957-d423-40ea-ba19-8939fd5495df">
New:
<img width="456" alt="Screenshot 2023-06-09 at 1 57 21 PM" src="https://github.com/slsa-framework/slsa/assets/6464618/e23a7def-a41a-466f-b3b0-f2046e9c634b">
Could you keep the same size? If that's the result of adding the "tenant" I don't think it's worth it to be honest.

2023-06-09 12:44 UTC, lehors commented on docs/spec/v1.0/terminology.md
> +    `build platform` which allows tenants to run builds.
> But, we define the term as 'platform' not 'build platform'

Indeed and we can't claim that "we always use" either one because that's just not the case. We currently use a mix of these two forms through out.

2023-06-09 13:48 UTC, chtiangg reviewed
I will hold off on making any changes, before we resolve the comment thread for the "steps".

2023-06-09 13:48 UTC, chtiangg commented on docs/spec/v1.0/terminology.md
> +performs arbitrary steps, (4) possibly fetching additional dependencies, (5) and
Let me describe my observation since I have a fresh mind and firstly read this doc recently. I'll then ask for suggestions at the end.

Diagram, text content, and aligning both are three parts. In my personal opinion:
1. A diagram could give a reader the most straightforward view without reading any text content, even if they have no technique context. Normally, a clear diagram can defeat thousands of words. When I first see the original diagram, I found:
   *  The diagram is too crowded: 3 different colors, more than 5 shapes with different sizes, 2 types of arrows, 3 different font sizes, text in vertical and horizontal direction, and 1 single annotation to 1 arrow dot-line. And some empty space on the right side of "interface", which looks strange. Because of these differences for each component, I cannot tell if they have different implicit meanings at first. The combination of these properties distract me from reading the following of this page, since my brain kept processing different things at that time.
   *  No steps exist. As I mentioned, if I have no context, I don't know which component is the start point, from left to right then top to bottom or the other way. Meanwhile, components don't always have arrows connected to each other.
   *  (I guess, these are the reason triggered me to make the diagram change in this PR, but please see my ask at the end.)

2. The text content is above the diagram. When reading this section the first time, I read the content, look at the diagram, then go back to try to find each diagram component in the text content (especially hard), and go back and forward several times to find the difference. However, I do think text content is more important than the diagram in the SLSA doc, since it is more precise and should have no ambiguity. The diagram may not be displayed in extreme conditions (e.g. super bad network).
   *  Not talking about this section, I personally prefer looking at a diagram first, then reading content to verify if the impression I got from then diagram matches what I read later, then I don't have to go back to verify.

3. Aligning both. I absolutely agree. I again personally think:
   * If the content doesn't describe a component in the diagram, maybe, we should add the content for it, e.g. Build Cache.
   * If the content cannot describe the step by step workflow as the diagram depicts, maybe it means either the diagram needs some improvement or the content needs to be changed to match the diagram.

After I wrote this, I found the change for the diagram and these steps are out of the scope for the issue itself. Drawing a nice diagram is always time costly, and needs more rounds of reviews. To follow the [small change list](https://google.github.io/eng-practices/review/developer/small-cls.html) practice, how about I revert all the changes in the diagram and the content. I can create a new issue to list my feedback for the diagram here. If there is an existing issue about the diagram, I can also add my feedback over there. However, please let me know if reverting the change for the diagram in this PR sounds good to you. Thank you!

2023-06-09 13:48 UTC, chtiangg commented on docs/spec/v1.0/build-model.svg
Asked in the other comment. I will address this after the decision over there.

2023-06-12 10:05 UTC, lehors commented on docs/spec/v1.0/terminology.md
> +performs arbitrary steps, (4) possibly fetching additional dependencies, (5) and
I agree with @joshuagl You seem to have taken our comments as an opposition to this PR. It's not. I think your PR is moving us in the direction support it overall. In particular there is no doubt that adding labels to the diagram is a good idea. We just need to get it right. If you want to move that piece to a different PR that's fine but either way works for me.
Thanks.

2023-06-12 13:53 UTC, chtiangg reviewed
Thanks for the review! I will update the description and remove the reverted changes.

2023-06-12 13:53 UTC, chtiangg commented on docs/spec/v1.0/terminology.md
> +<details><summary>Ambiguous term to avoid</summary>
Done.

2023-06-12 13:53 UTC, chtiangg commented on docs/spec/v1.0/terminology.md
> +-   *Build recipe:* Could mean `external parameters`, but may include concrete
Done.

2023-06-12 13:55 UTC, chtiangg commented on docs/spec/v1.0/terminology.md
> -| Platform | System that allows tenants to run builds. Technically, it is the transitive closure of software and services that must be trusted to faithfully execute the build. It includes software, h
Done.

2023-06-12 13:56 UTC, chtiangg commented on docs/spec/v1.0/build-model.svg
Revert the change.

2023-06-12 15:26 UTC, lehors commented on docs/spec/v1.0/terminology.md
> +| Build caches | An intermediate artifact storage managed by the platform and keyed by the hash of input sources. A build may share build caches with another following build running on the platform.
But there is a big difference: In the text you are referring to it is used in an example. Here you are making it part of the definition of the term.

2023-06-14 10:55 UTC, lehors commented on docs/spec/v1.0/terminology.md
> +| Build caches | An intermediate artifact storage managed by the platform and keyed by the hash of input sources. A build may share build caches with any subsequent build running on the platform.
I'm really not sure why we can just leave it at "An intermediate artifact storage managed by the platform." but yes, that's already better. Thanks.

2023-06-14 14:17 UTC, chtiangg commented on docs/spec/v1.0/terminology.md
> +| Build caches | An intermediate artifact storage managed by the platform and keyed by the hash of input sources. A build may share build caches with another following build running on the platform.
Sounds good, I accepted the suggestion.

2023-06-23 20:12 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> +-   *Builder:* Is `build platform`, but sometimes is used as `build environment`
Actually the [general recommendation](https://english.stackexchange.com/a/9881) that "punctuation marks are printed in the same style of font of type as the word, letter, character, or symbol immediately preceding them." Otherwise it looks odd. See screenshot: 

![image](https://github.com/slsa-framework/slsa/assets/58860/e8a0d70a-b9b6-461a-8aa6-0d3d3e999947)

I'll push a commit to fix.

2023-06-23 20:21 UTC, MarkLodato approved these changes
LGTM. I just pushed a few minor fixes, so another review by @joshuagl would be appreciated.

2023-06-26 10:38 UTC, joshuagl approved these changes

2023-06-26 10:38 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +    environment*, the user who invoke the build, or a build tool from
```suggestion
    environment*, the user who invoked the build, or a build tool from
```

2023-06-26 12:26 UTC, lehors approved these changes

2023-06-26 16:00 UTC, merged