docs: propose blog post on announcement of a container-based builder
slsa-framework/slsa pull request #877
Opened 2023-06-07 19:09 UTC by asraa

slsa-github-generator released a new Container-based builder that builds artifacts created by running a command inside a user-supplied container and generates SLSA 3 provenance with the details of the build.

This blog post is an announcement of the first release, and a call for users to try it out and contribute feedback and features.

cc @rbehjati @olivekl

2023-06-07 19:16 UTC, olivekl approved these changes
A couple minor nits, but LGTM!

2023-06-07 19:16 UTC, olivekl commented on docs/_posts/2023-06-07-slsa-github-worofklows-container-based.md
> +The container-based SLSA 3 builder differs from earlier builders and generators in the content of the generated provenance statements, and therefore how they can be verified. Like all provenance gene
```suggestion
The container-based SLSA 3 builder differs from earlier builders and generators in the content of the generated provenance statements, and therefore how they can be verified. Like all provenance generated by all SLSA 3 builders and generators, you can trace the binary to its source code and verify the builder’s identity---with the addition of detailed verification of the build process.
```

2023-06-07 19:16 UTC, olivekl commented on docs/_posts/2023-06-07-slsa-github-worofklows-container-based.md
> +If your builds are already containerized, we encourage you to give the container-based SLSA 3 builder a try - see the step-by-step guide in our [onboarding tutorial.](https://github.com/slsa-framewor
```suggestion
If your builds are already containerized, we encourage you to give the container-based SLSA 3 builder a try---see the step-by-step guide in our [onboarding tutorial.](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/docker/README.md#provenance-format) Otherwise, we suggest containerizing your build, which also improves the [reproducibility](https://reproducible-builds.org/) of your binaries, and adopting the container-based SLSA 3 builder.
```

2023-06-07 19:24 UTC, asraa commented on docs/_posts/2023-06-07-slsa-github-worofklows-container-based.md
> +The container-based SLSA 3 builder differs from earlier builders and generators in the content of the generated provenance statements, and therefore how they can be verified. Like all provenance gene
Thanks! I'm struggling to read this correctly, it kind of sounds like "with the addition of ..." is now dangling because the sentence starts with "Like all ..."

Maybe "Like all provenance generated by builder you can trace X---now, you can additionally perform detailed verification of the build process."

2023-06-07 19:35 UTC, olivekl commented on docs/_posts/2023-06-07-slsa-github-worofklows-container-based.md
> +The container-based SLSA 3 builder differs from earlier builders and generators in the content of the generated provenance statements, and therefore how they can be verified. Like all provenance gene
Yes, that sounds good to me! Maybe add an "and" after the em dash to make it extra clear that this is not true of other builders. Thanks for catching!

2023-06-07 19:56 UTC, rbehjati approved these changes
Thanks :)

2023-06-08 19:22 UTC, asraa commented on docs/_posts/2023-06-07-slsa-github-worofklows-container-based.md
> +Once you have generated a SLSA provenance with the container-based SLSA 3 builder, the next step to complete the lifecycle is to provide instructions to [verify the artifacts](/docs/spec/v1.0/verifyi
Ah, got it! It wants the relative path without `docs` - fixed all of these

2023-06-09 15:24 UTC, asraa commented
@slsa-framework/slsa-steering-committee could you please take a look at this announcement blog? @kpk47 from our side as well, would you be able to take a review or defer to someone?

2023-06-09 15:26 UTC, trishankatdatadog approved these changes

2023-06-12 13:37 UTC, lehors requested changes
Looks good overall but I noticed a few things that need fixing.
Thanks

2023-06-12 13:37 UTC, lehors commented on docs/_posts/2023-06-07-slsa-github-worofklows-container-based.md
> +Following the recent [launch of SLSA v1.0](https://security.googleblog.com/2023/04/celebrating-slsa-v10-securing-software.html), we’re announcing a new, [GitHub Actions workflow](https://github.com/s
If this is meant to be from the SLSA community we ought to point to the OpenSSF press release rather than Google's blog post. Also we should point to the 1.0 final spec rather than RC1.
```suggestion
Following the recent [launch of SLSA v1.0](https://openssf.org/press-release/2023/04/19/openssf-announces-slsa-version-1-0-release/), we’re announcing a new, [GitHub Actions workflow](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/docker) that achieves SLSA Build Track Level 3 for provenance generation. This lets users generate [unforgeable provenance](/spec/v1.0/requirements#provenance-unforgeable), allowing consumers to trust _and_ verify how their software artifacts were built. The container-based SLSA 3 builder is the result of a collaboration between the Google Open Source Security Team (GOSST), the SLSA community, and [Project Oak](https://github.com/project-oak/oak).
```

2023-06-12 13:37 UTC, lehors commented on docs/_posts/2023-06-07-slsa-github-worofklows-container-based.md
> +The new container-based SLSA 3 builder runs a containerised build in a secure environment and generates a non-forgeable provenance statement of the execution, all in an ecosystem-agnostic way that’s
```suggestion
The new container-based SLSA 3 builder runs a containerised build in a secure environment and generates an unforgeable provenance statement of the execution, all in an ecosystem-agnostic way that’s easy to add to your GitHub CI.
```

2023-06-12 13:37 UTC, lehors commented on docs/_posts/2023-06-07-slsa-github-worofklows-container-based.md
> +To ensure non-forgeability of provenance, the container-based SLSA 3 builder uses the same secure build mechanisms used in other SLSA builders and generators, relying on GitHub reusable workflows and
```suggestion
To ensure unforgeability of provenance, the container-based SLSA 3 builder uses the same secure build mechanisms used in other SLSA builders and generators, relying on GitHub reusable workflows and ephemeral VM containers for isolation. For more details, see the [technical design document](https://github.com/slsa-framework/slsa-github-generator/blob/main/SPECIFICATIONS.md). As before, we rely on OpenID Connect (OIDC) with [Sigstore](https://www.sigstore.dev/) tooling to prove the identity of the workflow. These provide the workflow identity guarantees described in [an earlier blog post](https://security.googleblog.com/2022/04/improving-software-supply-chain.html) that announced the generic SLSA 3 generator.
```

2023-06-12 13:37 UTC, lehors commented on docs/_posts/2023-06-07-slsa-github-worofklows-container-based.md
> +Please share your success stories with us by creating a pull request to add your project to [the list of container-based SLSA 3 users](https://github.com/slsa-framework/slsa-github-generator/blob/mai
Nit:
```suggestion
Please share your success stories with us by creating a pull request to add your project to [the list of container-based SLSA 3 users](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/docker/README.md#users). Feel free to create issues on the [repository](https://github.com/slsa-framework/slsa-github-generator) if you have noticed any issues, or are missing features you need. We look forward to fulfilling new requests and accepting new contributors to create even more useful features going forward.
```

2023-06-12 13:42 UTC, asraa commented on docs/_posts/2023-06-07-slsa-github-worofklows-container-based.md
> +Following the recent [launch of SLSA v1.0](https://security.googleblog.com/2023/04/celebrating-slsa-v10-securing-software.html), we’re announcing a new, [GitHub Actions workflow](https://github.com/s
Thanks for catching these and the others! We drafted this a while ago, and had stale links. Also, thanks for the catch that nonforgeable is unforgeable - i'll update some other docs going forward.

2023-06-12 13:45 UTC, lehors approved these changes
LGTM!

2023-06-13 12:56 UTC, merged