impl: Update CONTRIBUTING.md.
slsa-framework/slsa pull request #890
Opened 2023-06-27 16:06 UTC by kpk47

- Add PR title/description requirements.
- Clarify review requirements and merge etiquette.
- Enable workflow to enforce PR title requirements.

fixes #821

2023-06-27 16:33 UTC, joshuagl commented on CONTRIBUTING.md
> +timestamp of either tha final required approval or the latest non-author
```suggestion
timestamp of either the final required approval or the latest non-author
```

2023-06-27 16:33 UTC, joshuagl commented on CONTRIBUTING.md
> +5. Once the waiting period has passed, squash+merge your PR. Always squash+merge
I don't think we should document being able to merge as the default path?

2023-06-27 16:33 UTC, joshuagl commented on CONTRIBUTING.md
> +3. Add @slsa-framework/slsa-steering-committee as a reviewer. You will need a
Right now the maintainers are tagged for a review on every PR. Do we want slsa-steering-committee to review every PR?

2023-06-27 17:16 UTC, kpk47 commented on CONTRIBUTING.md
> +5. Once the waiting period has passed, squash+merge your PR. Always squash+merge
What would you suggest instead? Should we wait for a maintainer to merge?

2023-06-27 17:36 UTC, kpk47 commented on CONTRIBUTING.md
> +3. Add @slsa-framework/slsa-steering-committee as a reviewer. You will need a
That's a holdover from the existing documentation I'm replacing. I've switched it to maintainers.

2023-06-28 11:11 UTC, joshuagl commented on CONTRIBUTING.md
> +your PR to be squashed+merged unless your reviewers advise you otherwise.
Maintainers will endeavour to merge PRs in a timely fashion, but PR authors shouldn't be afraid to check in on the status of a merge. WDYT to this addition?

```suggestion
4.  Once the waiting period has passed, a maintainer will merge your PR. Expect
your PR to be squashed+merged unless your reviewers advise you otherwise.
If your PR has not been merged within 48h of the waiting period having passed,
and a reason for that has not been added as a PR comment, use the PR's comment
thread to request the PR be merged.
```

2023-06-28 11:13 UTC, joshuagl commented on CONTRIBUTING.md
> +5. Once the waiting period has passed, squash+merge your PR. Always squash+merge
Your proposed text LGTM. I've made a suggestion that folks follow-up if approved changes are not merged within 48h.

2023-06-28 12:21 UTC, kpk47 commented on CONTRIBUTING.md
> +5. Once the waiting period has passed, squash+merge your PR. Always squash+merge
LGTM. Thanks!

2023-06-28 13:48 UTC, MarkLodato requested changes
Looks good, thanks! Just some suggestions

2023-06-28 13:48 UTC, MarkLodato commented on CONTRIBUTING.md
> +to the repo, then the PR only requires two additional approvers before merging.
nit: This only applies if # approvers > 2, right? You can't be the only approver of your PR.

2023-06-28 13:48 UTC, MarkLodato commented on CONTRIBUTING.md
> +| `docs` | A change to a non-specification page. | 24h | 2 |
nit: is `docs` too ambiguous, especially since all of the files live in the `docs/` directory?

Perhaps `non-spec`?

2023-06-28 13:50 UTC, MarkLodato commented
I just updated our repo settings to only allow "Squash & merge" and to use the PR title + description for the commit message.

If we have rare cases where we actually want to do a merge, we can just re-enable then re-disable the option in the settings.

2023-06-29 21:07 UTC, joshuagl commented
> I just updated our repo settings to only allow "Squash & merge" and to use the PR title + description for the commit message.

My only reservation with this is that it's a lot harder to follow standard git patch format conventions (i.e. wrap at 75 columns) in the GitHub description. Can we automatically wrap the messages at merge time?

2023-06-30 19:06 UTC, kpk47 commented on .github/workflows/enforce-tags.yml
> +          subjectPatternError: |
Done

2023-06-30 19:06 UTC, kpk47 commented on .github/workflows/enforce-tags.yml
> +  pull_request:
I've got it on so I can be sure it runs correctly using this PR. I'll remove it before merging.

2023-06-30 19:11 UTC, kpk47 commented on CONTRIBUTING.md
> +title. See the chart below for the list of tags and their meanings.
Done

2023-07-01 12:39 UTC, MarkLodato approved these changes
New names looks good to me. (A bit verbose, but I can't think of a more concise alternative.)

2023-07-01 12:39 UTC, MarkLodato commented on CONTRIBUTING.md
> +        section about tags.) Summary:
```suggestion
        section about tags.)
```

2023-07-01 12:39 UTC, MarkLodato commented on .github/workflows/enforce-tags.yml
> +            docs
Need to update this with the new names

2023-07-05 18:04 UTC, kpk47 commented on .github/workflows/enforce-tags.yml
> +            docs
Done

2023-07-05 18:05 UTC, merged