specContent: Add a verifier version field to VSA.
slsa-framework/slsa pull request #905
Opened 2023-07-07 20:10 UTC by kpk47

- Adds field `verifier.version` to VSA schema.

fixes #809

2023-07-07 20:41 UTC, MarkLodato requested changes
In the PR description, could you explain why this is needed? Issues are often long and meandering, so briefly summarizing the rationale is helpful for reviews and for posterity.

2023-07-07 20:41 UTC, MarkLodato commented on docs/verification_summary/v1.md
> +      "<COMPONENT>": "<VERSION>",
```suggestion
      "<COMPONENT>": "<VERSION>",
      ...
```

nit: starting with `...` is confusing

2023-07-07 20:41 UTC, MarkLodato commented on docs/verification_summary/v1.md
> +      "baz": "baz-alpha00"
Can we come up with a realistic example of how this might be used? It's not clear to me, so an example would help.

2023-07-07 20:41 UTC, MarkLodato commented on docs/verification_summary/v1.md
> +`verifier.version` _map (string→string), required_
```suggestion
`verifier.version` _map (string→string), optional_
```

2023-07-07 20:58 UTC, kpk47 commented on docs/verification_summary/v1.md
> +      "baz": "baz-alpha00"
Done. I switched it to slsa-verifier and the corresponding GHA installer.

2023-07-10 12:17 UTC, lehors commented
Given that this is requiring new info shouldn't that trigger some version change of the format?

2023-07-10 19:15 UTC, laurentsimon commented on docs/verification_summary/v1.md
> +    "version": {
I still feel that using resource descriptor is more flexible in general, especially if we need to update this structure in the future. In this example, `slsa-verifier-linux-amd64` is kinda arbitrary naming. If our goal is to help with vuln management, using more conventional naming, like purl, etc may be beneficial. Resource descriptors offer this flexibility.

2023-07-11 20:02 UTC, MarkLodato approved these changes

2023-07-11 20:03 UTC, MarkLodato commented
> Given that this is requiring new info shouldn't that trigger some version change of the format?

There are no required fields. (An earlier version said required, but it was a mistake.)

So this doesn't require a major version bump, but based on this week's spec meeting, all `content` changes should have a changelog entry and perhaps a minor version bump.

2023-07-11 21:13 UTC, lehors commented
> > Given that this is requiring new info shouldn't that trigger some version change of the format?
> 
> There are no required fields. (An earlier version said required, but it was a mistake.)

Why does line #68 read: "// Required" ?
Shouldn't this comment be deleted then?

2023-07-11 21:17 UTC, MarkLodato commented
> Why does line # 68 read: "// Required" ? Shouldn't this comment be deleted then?

The `verifier` (and `verifier.id`) was and still is required, but the new `verifier.version` subfield is not. Thus the following was and still is acceptable:

```json
"verifier": { "id": "..." }
```

But point taken - we should clarify in the docs since the comment can clearly be misread.

2023-07-11 22:51 UTC, kpk47 commented on docs/verification_summary/v1.md
> +    "version": {
I don't think that `ResourceDescriptor` is the right type for tracking versions since it doesn't appear to have a version field. Also, part of the motivation for this PR is making the `verifier` VSA more consistent with the `builder` provenance field. `builder` uses `map(string->string)`, so I think it's best to keep that type here.

I'm going to keep `map(string->string)` in this PR, and we can address whether or not to change both fields to `ResourceDescriptor` separately.

2023-07-11 23:10 UTC, kpk47 commented
> > Why does line # 68 read: "// Required" ? Shouldn't this comment be deleted then?
> 
> The `verifier` (and `verifier.id`) was and still is required, but the new `verifier.version` subfield is not. Thus the following was and still is acceptable:
> 
> ```json
> "verifier": { "id": "..." }
> ```
> 
> But point taken - we should clarify in the docs since the comment can clearly be misread.

I don't see a good way to clarify in the text since the fields are already clearly labeled required vs optional. I deleted the comment instead.

2023-07-11 23:15 UTC, kpk47 commented
> > Given that this is requiring new info shouldn't that trigger some version change of the format?
> 
> There are no required fields. (An earlier version said required, but it was a mistake.)
> 
> So this doesn't require a major version bump, but based on this week's spec meeting, all `content` changes should have a changelog entry and perhaps a minor version bump.

I added a changelog entry with a minor version bump, as required by the versioning rules (https://slsa.dev/spec-stages#versioning). 

Given the version bump, we shouldn't merge this PR until we're ready to have v1.1 on the website.

2023-07-12 05:12 UTC, lehors commented
> I don't see a good way to clarify in the text since the fields are already clearly labeled required vs optional. I deleted the comment instead.

That works. Thanks!

2023-07-12 05:14 UTC, lehors commented
> I added a changelog entry with a minor version bump, as required by the versioning rules (https://slsa.dev/spec-stages#versioning).
> 
> Given the version bump, we shouldn't merge this PR until we're ready to have v1.1 on the website.

Shouldn't we have this on a branch specific to the next version like we did when we were working on 1.0 before publication?

2023-07-21 20:11 UTC, MarkLodato commented
> Shouldn't we have this on a branch specific to the next version like we did when we were working on 1.0 before publication?

Yes, this is blocked by #742.

2023-08-18 12:11 UTC, MarkLodato commented
The v1.1 directory now exists as of #942.

2023-08-29 18:12 UTC, kpk47 commented
I moved the changes into the v1.1 directory, so this PR is ready for re-review.

2023-09-11 12:03 UTC, joshuagl reviewed
This LGTM, thanks. However, as this is a content change, could you please add a changelog entry (per [contributing](https://github.com/slsa-framework/slsa/blob/main/CONTRIBUTING.md#changelog-entry))?

2023-09-11 12:03 UTC, joshuagl commented on docs/spec/v1.1/verification_summary.md
> +`verifier.version` _map (string→string), optional_
nit: I don't think we have any uses of unicode in our Markdown, and instead let the Markdown/browser stack take care of convertion `->` to -> (i.e. in the "Change history" section of provenance.md).

```suggestion
`verifier.version` _map (string->string), optional_
```

2023-10-11 14:43 UTC, joshuagl approved these changes
LGTM, thanks!

2023-10-11 14:58 UTC, MarkLodato approved these changes

2023-10-13 17:01 UTC, merged