editorial: better explain the build model
slsa-framework/slsa pull request #908
Opened 2023-07-08 01:40 UTC by MarkLodato

Text changes:

-   Use "invokes" instead of "defines" to avoid confusion.
-   Clarify that the invocation can be direct or through a trigger.
-   Clarify that build steps are under the tenant control and that the
    platform isolates between build environments.
-   Use consistent terminology, e.g. adding "build" before "platform".
-   Increase clarity through some minor rewording.

Reformatting:

-   Convert the paragraph to an ordered list and italicize the main use
    of each term, to enhance readability and to make it easier to match
    up with the diagram and the table.
-   Move all text to be below the diagram and above the table, to make
    it easier to follow.

Diagram tweaks:

-   Draw a line from interface to control plane, to match the text.
-   Use "dependencies" instead of "resolved dependencies", for
    consistency with the text.
-   Use the same font size for all inputs and outputs.
-   Use solid lines between control plane, build environment, and
    build caches, to avoid visual clutter. There was no reason for
    these to be drawn differently.
-   Draw Build Caches in black, since there was no particular reason
    to draw it in green.

Issue: #714

Signed-off-by: Mark Lodato <lodato@google.com>

2023-07-10 08:34 UTC, lehors reviewed
LGTM, but made a few suggested edits.

2023-07-10 08:34 UTC, lehors commented on docs/spec/v1.0/terminology.md
> +    additional *dependencies*, and then writes one or more *output* artifacts.
```suggestion
    additional *dependencies*, and then produces one or more *output* artifacts.
```

2023-07-10 08:34 UTC, lehors commented on docs/spec/v1.0/terminology.md
> +    The build platform isolates between build environments to some
```suggestion
    The build platform isolates build environments from one another to some
```

2023-07-10 08:34 UTC, lehors commented on docs/spec/v1.0/terminology.md
> +artifact to be built, which is often a git repository; in the build model, the
This reads as if it's the source artifact that is to be built.
```suggestion
artifact to build from, which is often a git repository; in the build model, the
```

2023-07-10 09:06 UTC, joshuagl requested changes

2023-07-10 09:06 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +parameters and dependencies. Most build platforms have an explicit "source"
```suggestion
external parameters and dependencies. Most build platforms have an explicit "source"
```
should we also be more consistent in referring to parameters as "external parameters"?

2023-07-10 09:06 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +reference to this artifact is a parameter while the artifact itself is a
```suggestion
reference to this artifact is an external parameter while the artifact itself is a
```
some comment on consistency, and therefore clarity, of use of external parameter over parameter.

2023-07-10 09:06 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +For examples on how this model applies to real-world build platforms, see [index
nit:
```suggestion
For examples of how this model applies to real-world build platforms, see [index
```

2023-07-11 18:24 UTC, lehors approved these changes
LGTM

2023-07-11 18:31 UTC, MarkLodato commented on docs/spec/v1.0/terminology.md
> +    additional *dependencies*, and then writes one or more *output* artifacts.
Yeah, I wasn't sure how to handle it since all three bullets mentioned "dependency" but none really defined it. (I missed the italics on the first bullet.)

What do you think of the change I just pushed, adding a parenthetical comment to the first bullet explaining that params are literals while dependencies are artifacts, and removing italics from bullets 2 and 3?

If you like that phrasing, I could also add a legend to the diagram explaining that, but that may make it too busy.

2023-07-12 09:29 UTC, joshuagl approved these changes

2023-07-12 09:29 UTC, joshuagl commented on docs/spec/v1.0/terminology.md
> +    additional *dependencies*, and then writes one or more *output* artifacts.
This phrasing LGTM, thanks! Shall we consider a change to the diagram in a separate PR?

2023-07-17 12:29 UTC, merged