docs: blog post for Build-Your-Own-Builder on GHA
slsa-framework/slsa pull request #929
Opened 2023-07-24 19:27 UTC by laurentsimon

Adds a guest blog post for Build-Your-Own-Builder on GHA.

Images needed for the post:
![image1](https://github.com/slsa-framework/slsa/assets/64505099/2e8bc2a1-3a83-4e67-8254-578ecb980d61)
![image2](https://github.com/slsa-framework/slsa/assets/64505099/14ff1de1-a30c-4683-860c-352dc490c1ef)

Notes: a few TODOs in the text.

cc @aalmiray, @AdamKorcz, @steiza, @feelepxyz, @asraa @ianlewis @loosebazooka

2023-07-25 04:20 UTC, ianlewis commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +![BYOB architecture](https://github.com/slsa-framework/slsa/assets/64505099/51c796e3-754e-4cd8-b2ea-dd8c23662411)
I think the images should be checked into the repo somewhere rather than using the URL from the upload to the PR description.

Not sure where they should be located though.

2023-07-25 12:47 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +# Build Your Own Builder Framework
nit: All of these headings need to move down a level (`#` -> `##`, etc.).

2023-07-25 12:47 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The snippet below shows how the initialization step is performed: the builder initializes the BYOB framework for the ubuntu-latest runner, with a build Action path "./internal/callback_action" and as
Why is the initialization step needed? Can't it be folded into the one call? It would help to explain that to the reader who, like me, might be wondering.

2023-07-25 12:47 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +$ export PROVENANCE_URL="${ARTIFACT_URL}".build.slsa
nit: No need to export these variables.

```suggestion
$ ARTIFACT=test-artifact-0.1.0-jar
$ ARTIFACT_URL="https://repo1.maven.org/maven2/path/to/${ARTFACT}"
$ PROVENANCE_URL="${ARTIFACT_URL}".build.slsa
```

2023-07-25 12:47 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +$ export PROVENANCE_URL="${ARTIFACT_URL}".build.slsa
Not specific to this blog post, but it's unfortunate that they chose to use a non-standard extension. We should work within the Securing Repos WG to align on a convention, e.g. `.intoto.jsonl`. @di FYI.

2023-07-25 12:47 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The plugin automatically performs the verification when configured in the ["pom.xml"](TODO:link to doc). Or it may be run [manually](TODO:link to doc). See our [documentation](https://github.com/slsa
Reminder to add these links

2023-07-25 12:47 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The plugin is still POC, but it demonstrates what's possible with and likely to come from the BYOB Framework. With the framework producing L3 provenance for GitHub Actions users, and the plugin autom
```suggestion
The plugin is still a proof-of-concept, but it demonstrates what's possible with and likely to come from the BYOB Framework. With the framework producing L3 provenance for GitHub Actions users, and the plugin automatically verifying Maven packages, you can build an end-to-end solution for an entire ecosystem.
```

2023-07-25 12:47 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +## Conclusion
```suggestion
## Conclusion

```

2023-07-25 12:47 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +It has been an exciting quarter for supply chain security and SLSA, with the release of the [SLSA v1.0 specification](https://slsa.dev/blog/2023/04/slsa-v1-final), [SLSA provenance support for npm](h
suggestion: It would be helpful to explain what the main benefit of BYOB is (i.e. what the alternative to BYOB is) and how it differs from the generic SLSA builder. Right now it seems like, "You can do X" but I'm left wondering why.

Maybe something like:

[first paragraph: stating what we've done before, basically what you have now]

[second paragraph: setting up the problem and why existing solutions aren't suitable - expand on "what if you don't use any of these"]

[third paragraph: announcing BYOB and stating why it solves the problems above - combine "to empower" and "as a tool", but also go into more detail about *why* it's better]

[fourth paragraph: lead into the rest of the post]

2023-07-25 12:47 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The BYOB framework provides a set of GitHub Actions and workflows that a builder calls to generate provenance. The high-level architecture is depicted in the diagram below. The `builder_workflow.yml`
Right now it's just "how to use" but doesn't explain how it works. That might be worth getting into. Otherwise, as mentioned above, I'm left wondering what this actually does under the hood.

2023-07-25 14:31 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +It has been an exciting quarter for supply chain security and SLSA, with the release of the [SLSA v1.0 specification](https://slsa.dev/blog/2023/04/slsa-v1-final), [SLSA provenance support for npm](h
I'm not following. Can you give an example?

2023-07-25 14:32 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The snippet below shows how the initialization step is performed: the builder initializes the BYOB framework for the ubuntu-latest runner, with a build Action path "./internal/callback_action" and as
it's a quirk of how OIDC works on GitHub. We need to establish the identity of the caller, which can only be done via some code that runs in the context of the caller. I can try adding a line on it, but it's a little technical. Maybe better link to a design doc as a BYOB_TECHNICAL.md on the website?

2023-07-25 14:37 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +$ export PROVENANCE_URL="${ARTIFACT_URL}".build.slsa
"they" is actually "we". We decided to use this extension. The builders on the repo can generate signed provenance in various formats. It used to be an intoto DSSE, now it's a sigstore bundle. We don't want to break users who rely on file extension when the underlying format changes, so we decided to use a "universal" extension that says "it's a SLSA provenance for the build track". 

A verifier needs to know the builder to verify its generated provenance, therefore it must be aware of the format it creates.

2023-07-25 14:41 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +It has been an exciting quarter for supply chain security and SLSA, with the release of the [SLSA v1.0 specification](https://slsa.dev/blog/2023/04/slsa-v1-final), [SLSA provenance support for npm](h
@olivekl can you chime in?

2023-07-25 14:44 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +![BYOB architecture](https://github.com/slsa-framework/slsa/assets/64505099/51c796e3-754e-4cd8-b2ea-dd8c23662411)
please someone advise. I don't know either. I looked at the other posts and had the same-looking URIs and I could not infer where images were stored

2023-07-25 14:46 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +# Build Your Own Builder Framework
thanks, done

2023-07-25 14:58 UTC, olivekl commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +It has been an exciting quarter for supply chain security and SLSA, with the release of the [SLSA v1.0 specification](https://slsa.dev/blog/2023/04/slsa-v1-final), [SLSA provenance support for npm](h
+1 to adding the why. I like Mark's suggested structure, or if you're trying to make fewer changes, you could just add a few sentences at the beginning of the first body section ("BYOB Framework") that cover these points in one sentence each.

2023-07-25 15:03 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +![BYOB architecture](https://github.com/slsa-framework/slsa/assets/64505099/51c796e3-754e-4cd8-b2ea-dd8c23662411)
Does it work to include it in the _posts directory?

If not, let's just leave it as-is for this PR. Other posts use this same convention, so we can fix them all in one go.

2023-07-25 15:19 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +It has been an exciting quarter for supply chain security and SLSA, with the release of the [SLSA v1.0 specification](https://slsa.dev/blog/2023/04/slsa-v1-final), [SLSA provenance support for npm](h
Thanks. I'll update this comment once I have made some changes

2023-07-25 15:27 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +It has been an exciting quarter for supply chain security and SLSA, with the release of the [SLSA v1.0 specification](https://slsa.dev/blog/2023/04/slsa-v1-final), [SLSA provenance support for npm](h
Any links starting with "https://slsa.dev" should instead be relative URLs. Furthermore, links to other files in the same directory are often easier to link to the `.md` file rather than the URL in the browser.

Example: https://github.com/slsa-framework/slsa/blob/main/docs/_posts/2023-04-19-slsa-v1-final.md?plain=1#L25

```suggestion
It has been an exciting quarter for supply chain security and SLSA, with the release of the [SLSA v1.0 specification](2023-04-19-slsa-v1-final.md), [SLSA provenance support for npm](https://github.blog/2023-04-19-introducing-npm-package-provenance/), and the announcement of new SLSA Level 3 builders for [Node.js](2023-05-11-bringing-improved-supply-chain-security-to-the-nodejs-ecosystem.md) and [containers](2023-06-13-slsa-github-worfklows-container-based.md)! 
```

2023-07-25 15:27 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +# Build Your Own Builder Framework
Not done? This is still an h1 (`#`) but every thing should be h2 (`##`) and below

2023-07-25 15:27 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The snippet below shows how the initialization step is performed: the builder initializes the BYOB framework for the ubuntu-latest runner, with a build Action path "./internal/callback_action" and as
So are you saying that the parameters to pass to the SLSA Reusable Workflow are complicated, so instead of having the user copy-paste that all, you encapsulate that in an Action that runs in the client (Tool Reusable Workflow)? If so, saying that directly might help.

Also this isn't explained at all in BYOB.md, and the [diagram](https://github.com/slsa-framework/slsa-github-generator/blob/main/BYOB.md#design-overview) implies that `setup-token` is another workflow rather than an action. That would be good to document.

2023-07-25 17:45 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The snippet below shows how the initialization step is performed: the builder initializes the BYOB framework for the ubuntu-latest runner, with a build Action path "./internal/callback_action" and as
> Also this isn't explained at all in BYOB.md, and the [diagram](https://github.com/slsa-framework/slsa-github-generator/blob/main/BYOB.md#design-overview) implies that setup-token is another workflow rather than an action. That would be good to document.

I think we can improve the image. https://github.com/slsa-framework/slsa-github-generator/blob/main/BYOB.md#slsa-setup-action-ssa says it's an Action, but the diagram could be improved. +1

2023-07-25 17:50 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The BYOB framework provides a set of GitHub Actions and workflows that a builder calls to generate provenance. The high-level architecture is depicted in the diagram below. The `builder_workflow.yml`
The BYOB.md is user documentation. We have a design doc that can be turned into a BYOB_TECHNICAL.md. 
Which questions come to mind that you'd like to see answered?

2023-07-25 21:23 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The BYOB framework provides a set of GitHub Actions and workflows that a builder calls to generate provenance. The high-level architecture is depicted in the diagram below. The `builder_workflow.yml`
To reiterate, I suggest two things:

(1) Clarify who the audience ("you") is. At first I was assuming the reader was an end user (i.e. a developer who uses GitHub Actions to build), since the previous blog posts were focused on end users and the text says "what if you don’t use any of these languages?". But in reality the audience is the owner of an Action. It took me a while to realize that. Stating that up front would help.

(2) Clarify the what BYOB is and what the benefits are. In short, this wraps an Action around a reusable workflow such that consumers have confidence that the Action actually ran.
- For the Action owner, it makes it easier to get it to SLSA Build L3.
- For the Consumer, it makes it so that you only have to trust the BYOB infrastructure + the Action code (but not whatever machine runs the Action).

2023-07-25 21:33 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +SLSA now provides and maintains official builders for [Go](https://slsa.dev/blog/2022/06/slsa-github-workflows), [Node.js](https://slsa.dev/blog/2023/05/bringing-improved-supply-chain-security-to-the
removed all the links.

2023-07-26 21:00 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +It has been an exciting quarter for supply chain security and SLSA, with the release of the [SLSA v1.0 specification](https://slsa.dev/blog/2023/04/slsa-v1-final), [SLSA provenance support for npm](h
@olivekl can you make a suggestion to add just a few sentences?

2023-07-26 21:12 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +It has been an exciting quarter for supply chain security and SLSA, with the release of the [SLSA v1.0 specification](https://slsa.dev/blog/2023/04/slsa-v1-final), [SLSA provenance support for npm](h
I added the following paragraph:
```
Writing a builder from scratch is a tedious multi-month effort. The BYOB framework streamlines this process by cutting the development time down to a few days. As a builder writer, you need not worry about keeping signing keys secure, isolation between builds, the creation of attestations; all this is handled seamlessly by the framework, using the [same security design principles](https://github.com/slsa-framework/slsa-github-generator/tree/main#specifications) as our existing builders.
```

2023-07-26 21:27 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The BYOB framework provides a set of GitHub Actions and workflows that a builder calls to generate provenance. The high-level architecture is depicted in the diagram below. The `builder_workflow.yml`
I've made some updates. ptal

2023-07-28 13:13 UTC, feelepxyz commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +Writing a builder from scratch is a tedious multi-month effort. The BYOB framework streamlines this process and cuts the development time down to a few days. As a builder writer, you need not worry a
nit style suggestion
```suggestion
Writing a builder from scratch is a tedious multi-month effort. The BYOB framework streamlines this process and cuts the development time down to a few days. As a builder author, you don't need to worry about keeping signing keys secure, isolation between builds, the creation of attestations; all this is handled seamlessly by the framework, using the [same security design principles](https://github.com/slsa-framework/slsa-github-generator/tree/main#specifications) as our existing builders.
```

2023-07-28 13:13 UTC, feelepxyz commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +1. For Action maintainers, it makes it easy to meet the [SLSA Build L3](https://slsa.dev/spec/v1.0/levels#build-l3).
```suggestion
1. For Action maintainers, it makes it easy to meet the [SLSA Build L3](https://slsa.dev/spec/v1.0/levels#build-l3) requirements.
```

2023-07-28 13:14 UTC, feelepxyz commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The BYOB framework provides a set of GitHub Actions and workflows that helps builder writers generate provenance.
```suggestion
The BYOB framework provides a set of GitHub Actions and workflows that helps builder authors generate provenance.
```

2023-07-28 13:20 UTC, feelepxyz commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The snippet below shows how the initialization step is performed: the builder initializes the BYOB framework for the ubuntu-latest runner, with a build Action path "./internal/callback_action" and as
> but the BYOB framework needs a way to identify who's calling it, so that it can attest to it and its parameters

Curious about improvements to actions here. Would we not need the init stage if the BYOB framework could ask for an OIDC token that was minted in the caller context? Or are there other bits we need?

2023-07-28 13:21 UTC, feelepxyz commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The plugin automatically performs the verification when configured in the ["pom.xml"](TODO:link to doc). Or it may be run [manually](TODO:link to doc). See our [documentation](https://github.com/slsa
```suggestion

The plugin automatically performs the verification when configured in the ["pom.xml"](TODO:link to doc). Or it may be run [manually](TODO:link to doc). See our [documentation](https://github.com/slsa-framework/slsa-verifier/tree/main/experimental/maven-plugin).
```

2023-07-28 15:34 UTC, laurentsimon commented
Can someone advise on showing `$` signs correctly in the snippet (They don't show when viewing the webpage preview)?

2023-07-31 21:23 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The snippet below shows how the initialization step is performed: the builder initializes the BYOB framework for the ubuntu-latest runner, with a build Action path "./internal/callback_action" and as
good question. We may still want the separate init stage because reusable workflows can be chained. RW1 -> RW2 -> RW3 -> BYOB. If we're attesting to RW1, we want to ensure that RW2 and RW3 cannot tamper with the parameters. If that information was present in the GitHub token or an API, it would not be necessary.

2023-08-01 00:23 UTC, ianlewis commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The snippet below shows how the initialization step is performed: the builder initializes the BYOB framework for the ubuntu-latest runner, with a build Action path "./internal/callback_action" and as
Right, the key thing is we need the whole call chain of `job_workflow_ref`s and `inputs` or at least RW1s info to be in the token. We could explicitly only support one level of reusable workflow calls but we wouldn't be able to easily detect it if a builder workflow author did use multiple levels of RWs and that would result in it not working or potentially being insecure wrt `inputs` and `job_workflow_ref`.

2023-08-01 17:23 UTC, laurentsimon commented
@MarkLodato can you take a second look to see if your comments are addressed?

2023-08-01 17:32 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The plugin automatically performs the verification when configured in the ["pom.xml"](TODO:link to doc). Or it may be run [manually](TODO:link to doc). See our [documentation](https://github.com/slsa
Links added. Resolving.

2023-08-01 17:35 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The snippet below shows how the initialization step is performed: the builder initializes the BYOB framework for the ubuntu-latest runner, with a build Action path "./internal/callback_action" and as
Resolving.

2023-08-01 18:06 UTC, laurentsimon commented
Looking for a second round of reviews. Thanks everyone

2023-08-01 18:30 UTC, inferno-chromium commented
Can someone from @slsa-framework/slsa-steering-committee please take a look at this. Thanks!

2023-08-01 18:32 UTC, MarkLodato requested changes

2023-08-01 18:32 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The high-level architecture is depicted in the diagram below. The `builder_workflow.yml` represents the builder being created. The BYOB framework, on the right of the diagram, acts as an orchestrator
IMO this needs more introduction. Right now I'm not sure a reader will understand what `builder_workflow.yml` is, what the delta is before and after, or what is being accomplished. I suggest something like the following:

---8<---

Suppose you own a GitHub Action called `MyCoolAction` and want to generate provenance showing that it ran on some input and generated some output, without having to trust whatever Workflow called your Action. This is not possible using a regular Action because Actions run under the control of the calling Workflow.

(diagram showing `MyCoolAction` running within each of the callers' workflows)

To solve this problem, you could turn your Action into a Reusable Workflow. This results in `MyCoolAction` running in a VM under your control, not the caller's control. In fact, this is how the SLSA go, Node.js, and container builders work. (Q: Does this require changes to how clients call `MyCoolAction`? If so that should be documented.)

(diagram showing callers calling a central `MyCoolAction` reusable workflow, which runs the Action and generates provenance)

However, this is a lot of work can requires careful design and implementation. That's where the BYOB framework comes in! BYOB offloads all of the security critical work so that you can wrap your Action in a Reusable Workflow and call BYOB to do the heavy lifting.

(diagram showing callers calling `MyCoolAction` reusable workflow, which in turn calls the BYOB, which runs the Action and generates provenance)

2023-08-01 18:32 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The BYOB framework provides a set of GitHub Actions and workflows that a builder calls to generate provenance. The high-level architecture is depicted in the diagram below. The `builder_workflow.yml`
There are still some "yous" but I'll add more specific comments.

2023-08-01 18:32 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +## Verification for your projects
Who is the "you" here? Is this a user of Maven? A consumer of a Maven package? The owner of the Maven builder?

2023-08-01 18:32 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +## Verification for your dependencies
I don't really understand what this section is saying and who "you" is.

2023-08-01 18:32 UTC, MarkLodato commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +It has been an exciting quarter for supply chain security and SLSA, with the release of the [SLSA v1.0 specification](https://slsa.dev/blog/2023/04/slsa-v1-final), [SLSA provenance support for npm](h
Yes, and i made another suggestion along these lines. I'll mark this one resolved

2023-08-01 20:37 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +## Verification for your projects
Renamed to "Verification of Artifact"

2023-08-01 20:38 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +## Verification for your dependencies
Renamed to "Verification of Dependencies". Changed "you" to "we" in the text

2023-08-01 20:56 UTC, DavidKorczynski commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +author: "Andres Almiray (JReleaser), Adam Korczynski (AdaLogics), Philip Harrison (GitHub), Laurent Simon (Google)"
`AdaLogics` --> `Ada Logics`

2023-08-01 20:56 UTC, DavidKorczynski commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +2.  A [Maven builder](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/maven#readme), contributed by [AdaLogics](https://adalogics.com). This builder is currently h
`AdaLogics` --> `Ada Logics`  -- not in the url though :)

2023-08-01 20:56 UTC, DavidKorczynski commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +3.  A [Gradle builder](https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/gradle#readme), contributed by [AdaLogics](https://adalogics.com). This builder is currently
`AdaLogics` --> `Ada Logics` -- not in the url though :)

2023-08-01 21:35 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +The high-level architecture is depicted in the diagram below. The `builder_workflow.yml` represents the builder being created. The BYOB framework, on the right of the diagram, acts as an orchestrator
thanks for the input. I've made the changes. PTAL

2023-08-01 21:59 UTC, MarkLodato approved these changes
Thanks!

2023-08-01 22:02 UTC, trishankatdatadog reviewed
Thanks for the blog post! Great idea, but needs a bit more explication of what the problems are, why the solution addresses them, and what this all means for the everyday user. Thanks again!

2023-08-01 22:02 UTC, trishankatdatadog commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +```shell
This is not very user-friendly, but I suppose it works for now. Also, please concretely state exactly what security issues this verification does (and does not yet) solve for the unfamiliar reader.

2023-08-01 22:04 UTC, AdamKorcz requested changes

2023-08-01 22:04 UTC, AdamKorcz commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](ht
Suggestion: Have a more direct answer to the question in the previous sentence/paragraph.

2023-08-01 22:06 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +To solve this problem, you could turn your Action into a Reusable Workflow. This results in `MyAction` running in a VM under your control, not the caller's control. In fact, this is how the SLSA go,
great catch. Thank you!

2023-08-01 22:07 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +There are two main steps to using the BYOB framework. First, the builder (`MyReusableWorkflow`) initializes the BYOB framework (`BYOB_Initialize` box in the middle box). Then it calls the framework (
where would you like to move it to?

2023-08-01 22:13 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +```shell
added a sentence, ptal

2023-08-01 22:14 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +To solve this problem, you could turn your Action into a Reusable Workflow. This results in `MyAction` running in a VM under your control, not the caller's control. In fact, this is how the SLSA go,
sorry, this option does work. The Action is _not_ under the caller's control. SO it works, but it's tedious to implement and maintain all this. How shall I rephrase to make this more obvious?

2023-08-01 22:21 UTC, AdamKorcz commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](ht
It could for example be:

change 

"To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](https://github.com/slsa-framework/slsa-github-generator/tree/main#build-your-own-builder) for GitHub Actions."

to

"Today we release ["Build Your Own Builder" (BYOB) framework](https://github.com/slsa-framework/slsa-github-generator/tree/main#build-your-own-builder) for GitHub Actions which will empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders."

2023-08-02 02:29 UTC, trishankatdatadog commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +To solve this problem, you could turn your Action into a Reusable Workflow. This results in `MyAction` running in a VM under your control, not the caller's control. In fact, this is how the SLSA go,
I'm sure it works 🙂 What I mean is: what is the threat model, and the problems you solved? Right now, it simply isn't very clear. This can be easily fixed.

2023-08-02 18:10 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +![action-release](https://github.com/slsa-framework/slsa/assets/64505099/367ecc46-28f6-4029-853e-161a028e6a35)
Trying to address Mark's earlier comment to show that MyAction runs on the same machine as the workflow

2023-08-02 18:11 UTC, laurentsimon commented on docs/_posts/2023-08-07-bring-your-own-builder-github.md
> +To solve this problem, you could turn your Action into a Reusable Workflow. This results in `MyAction` running in a VM under your control, not the caller's control. In fact, this is how the SLSA go,
Can you make a suggestion? I'm running out of ideas :/

2023-08-02 18:11 UTC, laurentsimon commented
Please don't merge. I'll merge once we're ready (release cut, etc). Thanks

2023-08-02 21:38 UTC, trishankatdatadog approved these changes
LGTM in the interest of unblocking

2023-08-02 21:39 UTC, trishankatdatadog commented
> LGTM in the interest of unblocking

Bah, it didn't let me finish. I still think the threat model is unclear, but I think as long as readers get the idea that, "Hey, I really should use BYOB instead of my own stuff due to some apparently complicated details pertaining security", then that's good enough. Thanks for all of your hard work!

2023-08-14 18:30 UTC, lehors approved these changes
Reviewing this made me wonder about some meta questions about how this work is positioned with regard to the OpenSSF governance structure but I think this is a good post and I applaud the effort to make it easier for people to support SLSA.

2023-08-14 18:30 UTC, lehors commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](ht
Who decides what's an "official SLSA builder"? And who's "we"?
Sorry again for bugging everybody with process and governance questions... :-)

2023-08-14 19:25 UTC, laurentsimon commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](ht
good question. Till now we've been calling them "official" because their code lives under the slsa-framework org... Happy to re-phrase if you have a suggestion

2023-08-14 19:26 UTC, laurentsimon commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +SLSA already provides and maintains official builders for [Go](2022-06-20-slsa-github-workflows.md), [Node.js](2023-05-11-bringing-improved-supply-chain-security-to-the-nodejs-ecosystem.md) and [Cont
Shall I update to "[SLSA Generators Project](link_to_repo) already provides..."?

2023-08-15 01:51 UTC, ianlewis commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](ht
FWIW I don't think we've specifically used the word "official" to describe them in our blog posts or documentation so we could technically drop it.

We have used "SLSA Tooling SIG" and "SLSA Tooling working group" in our past blog posts to describe "us". I think that might be the best way to go instead of just saying "SLSA".
See: 
- https://slsa.dev/blog/2023/05/bringing-improved-supply-chain-security-to-the-nodejs-ecosystem
- https://slsa.dev/blog/2023/02/slsa-github-workflows-container-ga

The SLSA Tooling SIG is listed on the community page: https://slsa.dev/community

2023-08-15 01:52 UTC, ianlewis commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +SLSA already provides and maintains official builders for [Go](2022-06-20-slsa-github-workflows.md), [Node.js](2023-05-11-bringing-improved-supply-chain-security-to-the-nodejs-ecosystem.md) and [Cont
```suggestion
The SLSA Tooling SIG already provides and maintains official builders for [Go](2022-06-20-slsa-github-workflows.md), [Node.js](2023-05-11-bringing-improved-supply-chain-security-to-the-nodejs-ecosystem.md) and [Container](2023-06-13-slsa-github-worfklows-container-based.md) based projects. But what if you don't use any of these languages or use custom tooling that isn't supported by the official builders?
```

2023-08-15 02:10 UTC, ianlewis commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +To solve this problem, you could turn your Action into a Reusable Workflow. This results in `MyAction` running in a VM under your control, not the caller's control. In fact, this is how the SLSA Go,
nit: remove for brevity and clarity
```suggestion
To solve this problem, you could turn your Action into a Reusable Workflow. This results in `MyAction` running in a VM under your control, not the caller's control. This option is depicted in the diagram below: The project's `release.yml` calls the Reusable Workflow `MyReusableWorkflow` which in turn calls `MyAction` and generates provenance for the run.
```

2023-08-15 02:10 UTC, ianlewis commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +![Maven provenance link](https://github.com/slsa-framework/slsa/assets/64505099/14ff1de1-a30c-4683-860c-352dc490c1ef)
is it possible to scale this down a bit. It's a bit too big on the page. Maybe using some inline html?
https://deploy-preview-929--slsa.netlify.app/blog/2023/08/bring-your-own-builder-github#verification-of-artifact

2023-08-15 02:10 UTC, ianlewis commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +The [slsa-verifier](https://github.com/slsa-framework/slsa-verifier) can be used to verify the provenance. The tool verifies the signature on the provenance and the source used to build the artifact,
nit: singular
```suggestion
The [slsa-verifier](https://github.com/slsa-framework/slsa-verifier) can be used to verify the provenance. The tool verifies the signature on the provenance and the source used to build the artifact, as per the [SLSA specification](/spec/v1.0/verifying-artifacts).
```

2023-08-15 02:10 UTC, ianlewis commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](ht
Should we make the release status clear and say that BYOB is being released in beta?

2023-08-16 03:38 UTC, ianlewis commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](ht
I suppose the TAC page update would include the reporting WG.

2023-08-16 03:41 UTC, ianlewis commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](ht
This is also just a side note, but it seems strange that SLSA wouldn't be mentioned anywhere on the TAC page if it is indeed owned by OpenSSF

2023-08-16 21:10 UTC, lehors commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](ht
Ok, so I think what we should do is to get a page for the project in the SCI WG repo that is linked from its README. I don't think it's worth creating a whole new repo for that since it would merely contained a README. That page can just explain what the project is about and point to the different tools already available and any other info that is relevant.
Then we can get it also listed on and linked from the TAC page.
I'm happy to help with all of that.

I agree it's unfortunate that SLSA doesn't appear on the TAC page at all. This is because it's a SIG and currently SIGs are not listed... I think it'd be worth adding but that requires the WGs to play along and submit changes to reflect changes in their WGs.

2023-08-18 18:55 UTC, laurentsimon commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +![Maven provenance link](https://github.com/slsa-framework/slsa/assets/64505099/14ff1de1-a30c-4683-860c-352dc490c1ef)
i resized the image to 60% https://deploy-preview-929--slsa.netlify.app/blog/2023/08/bring-your-own-builder-github

2023-08-21 03:42 UTC, ianlewis commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +![Maven provenance link](https://github.com/slsa-framework/slsa/assets/64505099/14ff1de1-a30c-4683-860c-352dc490c1ef)
LG

2023-08-24 10:33 UTC, joshuagl approved these changes
Really nice work on BYOB and implementations for Java. 👏

2023-08-25 20:40 UTC, merged

2023-08-29 12:53 UTC, lehors commented on docs/_posts/2023-08-21-bring-your-own-builder-github.md
> +To empower the community to create their own provenance builders and leverage the secure architecture of the official SLSA builders we are releasing the ["Build Your Own Builder" (BYOB) framework](ht
FYI, I just submitted a PR to give the Tooling project a home page and official standing in the openssf governance structure: https://github.com/ossf/wg-supply-chain-integrity/pull/72