impl: use conventional names for parts of a PR
slsa-framework/slsa pull request #954
Opened 2023-08-21 18:43 UTC by MarkLodato

In CONTRIBUTING, switch to terminology that is consistent with GitHub
and Conventional Commits:

Before:

    <tag>: <title>

    <description>

After:

    <type>: <description>

    <body>

Where the first line is the "title" (unchanged).

2023-08-21 18:54 UTC, MarkLodato commented
/cc @arewm

2023-08-21 19:02 UTC, arewm requested changes
Are we unifying on conventional commits or https://github.com/amannn/action-semantic-pull-request? The latter uses `Subject` instead of description. If we are unifying on the GitHub action then we can include a reference to it here as well.

Can you also change the name of the workflow?

2023-08-22 12:29 UTC, MarkLodato commented
> Are we unifying on conventional commits or https://github.com/amannn/action-semantic-pull-request? The latter uses `Subject` instead of description. If we are unifying on the GitHub action then we can include a reference to it here as well.

Oh, I didn't realize the discrepancy. Done.

(My default would have been to align with the spec rather than an implementation, but I do think "subject" is better than "description".)

> Can you also change the name of the workflow?

Done. I changed the name to be more descriptive / self-documenting. What do you think?

2023-08-22 12:49 UTC, joshuagl approved these changes

2023-08-22 13:46 UTC, merged