content: recommend a VSA include the policy's digest
slsa-framework/slsa pull request #979
Opened 2023-10-10 09:17 UTC by joshuagl

Recommended that the `digest` field of `ResourceDescriptor` is set in a Verification Summary Attestation's (VSA) `policy` object.

Fixes: #803

2023-10-10 13:40 UTC, MarkLodato approved these changes
Related: I believe there was a separate issue/PR to make `policy` optional (maybe recommended?) since it's not strictly required. That doesn't impact this PR, but just FYI.

2023-10-10 14:05 UTC, joshuagl commented
> Related: I believe there was a separate issue/PR to make `policy` optional (maybe recommended?) since it's not strictly required. That doesn't impact this PR, but just FYI.

Thanks! That matches my mental model (I was surprised when working on this change that the policy was required). I agree, this change still works with that change (tracked as part of https://github.com/slsa-framework/slsa/issues/878 but should probably be a separate issue).

2023-10-12 10:55 UTC, lehors commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
I think that's fine anyway because it's a SHOULD but presumably one could have different URIs for different versions, no?

2023-10-12 17:11 UTC, joshuagl commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
yes, there could absolutely be different URIs for different policy versions

2023-10-12 20:54 UTC, kpk47 approved these changes

2023-10-13 05:44 UTC, lehors approved these changes

2023-10-13 16:48 UTC, arewm requested changes

2023-10-13 16:48 UTC, arewm commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
While I feel like `immutable` is a more precise word than `exact`, it might not be as well known. Is there a way that we can strengthen the wording to indicate a strongly persistent exactness?

2023-10-13 16:48 UTC, arewm commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
Should it be `digest` to indicate that it is a key value?

2023-10-13 16:48 UTC, arewm commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
The `digest` present in the schema above is different from the other digest representations. Is there a reason that we have it represented like this?

```
  "policy": {
    "uri": "<URI>",
    "digest": { /* DigestSet */ }
  }
```

2023-10-16 15:42 UTC, joshuagl commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
We're recommending digest as the mechanism and using exact to describe the purpose of that digest. We could use alternatives, such as: precise or explicit? I think I'd lean to "explicit version of that policy".

2023-10-16 15:48 UTC, joshuagl commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
Well spotted, I can change that to match.  I don't know of a reason it would be different (I thought perhaps because `policy.digest` optional, but so is an `inputAttestations`'s digest).

I will change `/* DigestSet */` to `<digest-of-policy-data>`.

2023-10-16 15:50 UTC, arewm commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
Explicit works for me. I am now questioning whether we should use `version` now. When I think of a version, SemVer tags come to mind and that doesn't jive with a digest. 

I cannot offer a _suggestion_ as I originally just commented on the one line, but how about something like
```
The entry MUST contain a `uri` identifying which policy version was applied and
SHOULD contain a digest to indicate the explicit reference of that policy.
```

2023-10-16 17:48 UTC, arewm commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
Thanks for the change. This can be resolved. :)

2023-10-16 17:48 UTC, arewm commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
Thanks for the change. This can be resolved. :)

2023-10-16 17:56 UTC, MarkLodato approved these changes

2023-10-20 13:35 UTC, MarkLodato commented on docs/spec/v1.1/verification_summary.md
> +> SHOULD contain a digest to indicate the exact version of that policy.
Personally I find the current wording more readable. I don't think people will be confused by the word "version", and any alternative seems less clear.

2023-11-13 18:57 UTC, merged