Fix Issue #982
slsa-framework/slsa pull request #983
Opened 2023-10-10 13:57 UTC by eruvanos

Replace 'package repo' with 'package registry', following the recommended terminology.

2023-10-10 18:13 UTC, MarkLodato requested changes
This is great, thank you so much for your contribution! There are some slight tweaks to make, but otherwise this change looks good.

2023-10-10 18:13 UTC, MarkLodato commented on docs/images/supply-chain-threats-build-verification.svg
Oops, this file is only used by v0.1 and v1.0-rc*. Could you please revert this file and update `docs/spec/v1.[12]/images/supply-chain-threats-build-verification.svg` instead? Thanks.

2023-10-10 18:13 UTC, MarkLodato commented on docs/_includes/use-cases-table.html
Oh, I didn't realize this file still existed. It's unused. I just sent #984 to delete it. You can revert this file.

2023-10-10 18:13 UTC, MarkLodato commented on docs/images/supply-chain-threats.svg
same

2023-10-10 18:13 UTC, MarkLodato commented on docs/spec/v1.1/threats-overview.md
Do you mind updating v1.0 as well for the these three files?

2023-10-10 20:24 UTC, eruvanos commented on docs/spec/v1.1/threats-overview.md
Done

2023-10-10 20:35 UTC, eruvanos commented
Applied the requested changes, please double check the right images are replaced now.

2023-10-10 20:54 UTC, MarkLodato approved these changes
Perfect, thank you so much!

2023-10-11 14:44 UTC, joshuagl approved these changes
This is great, thank you!

2023-10-13 10:58 UTC, eruvanos commented
@joshuagl anything missing from my side?

2023-10-13 15:43 UTC, merged

2023-10-13 15:43 UTC, joshuagl commented
Nothing missing, thanks again for the contribution @eruvanos