editorial: Clarify DependencyLevels, SlsaResult, and quote level keys.
slsa-framework/slsa pull request #988
Opened 2023-10-13 13:21 UTC by AdamZWu

This is related to issues #968, just a cleanup preparing the proposal to remove "FAILED" at v1.1 in a future commit.

2023-10-13 13:56 UTC, AdamZWu commented
Oh, hold on. `SLSA_BUILD_LEVEL_UNEVALUATED` got leaked from v1.1 into v1.0.
Let me fix that.

2023-10-20 20:16 UTC, MarkLodato requested changes
Thanks!

2023-10-20 20:16 UTC, MarkLodato commented on docs/spec/v1.0/verification_summary.md
> +> that the verifier does not disclose the dependency stats).
```suggestion
> [SlsaResult] MUST be interpreted as reporting _0_ dependencies at that level.
> An set-but-empty `dependencyLevels` object means that the artifact has **no**
> dependency at all, while an unset or null `dependencyLevels` means that the
> verifier makes no claims about the artifact's dependencies.
```

Minor wording suggestion.

2023-10-20 20:16 UTC, MarkLodato commented on docs/spec/v1.0/verification_summary.md
> +> the other `SLSA_BUILD` levels.
I find this change to be less readable. What was the motivation? L1 is the only level below L2, so it seemed clear to me that this was explaining that if it's L2, you don't also report it at L1.

2023-10-20 20:16 UTC, MarkLodato commented on docs/spec/v1.0/verification_summary.md
> +SHOULD contain one value per SLSA track:
This looks like a mistaken content change. This PR is just supposed to change formatting and minor wording changes. However, this change affects the schema, but also doesn't work. The field is a scalar String, but the new wording suggest it's a collection of strings.

2023-10-20 21:49 UTC, AdamZWu commented on docs/spec/v1.0/verification_summary.md
> +> the other `SLSA_BUILD` levels.
Oh good point, I think I overlooked that this is already in the context of "for example". :P

2023-10-20 22:05 UTC, AdamZWu commented on docs/spec/v1.0/verification_summary.md
> +SHOULD contain one value per SLSA track:
Oh right I think I got confused. WDYT I revise the description to clarify that the `SlsaResult` is a scalar that comprises values from multiple tracks (currently there are two: the "SLSA BUILD" track and "policy evaluation failure" track) This is to lead to the upcoming removal of the "policy evaluation failure" track values in v1.1.

2023-10-23 12:20 UTC, MarkLodato commented on docs/spec/v1.0/verification_summary.md
> +SHOULD contain one value per SLSA track:
I think it's still worse than before. Frankly, this particular field needs to be redesigned in the next version. I don't think we should bother trying to fix the v1.0 wording. Instead, we should put effort towards figuring out what a better API is. So I would revert this part of the change (in v1.0 and v1.1) and leave that to a separate PR.

2023-10-23 12:43 UTC, AdamZWu commented on docs/spec/v1.0/verification_summary.md
> +SHOULD contain one value per SLSA track:
Sounds good.

2023-11-15 15:23 UTC, lehors approved these changes
LGTM

2023-11-17 19:23 UTC, trishankatdatadog approved these changes
LGTM, thx!

2023-11-17 19:59 UTC, merged