Document some SLSA use cases
slsa-framework/slsa pull request #99
Opened 2021-07-19 15:57 UTC by TomHennen

Still very much draft.  Lots of work left to do.

2021-07-21 17:25 UTC, MarkLodato requested changes
Makes sense to me, but it would be good to get others to review as well.

2021-07-21 17:25 UTC, MarkLodato commented on use_cases.md
> +1.  Protect their users from malicious changes to the BarImage container image
nit: period at end of each sentence, here and down below (e.g. sub-bullets of item 4)

2021-07-21 17:25 UTC, MarkLodato commented on use_cases.md
> +    [source control attestations](https://github.com/in-toto/attestation/issues/47)) for BarImage
nit: remove "for BarImage" since that term is not defined in this section and the sentence reads fine without it.

2021-07-21 17:25 UTC, MarkLodato commented on use_cases.md
> +4.  Have the control-point check the candiate BarImage against it's provenance, checking:
Typos: "Having" (parallel construction), "candidate", "its" (multiple typos throughout the doc)

2021-07-21 17:25 UTC, MarkLodato commented on use_cases.md
> +    [in-toto Provenance](https://github.com/in-toto/attestation/blob/main/spec/predicates/provenance.md)
nit: use references for links that are used repeatedly:

\[in-toto Provenance]: https://github.com/...
\[source control attestations]: https://github.com/...

2021-07-21 18:41 UTC, kimsterv requested changes
lgtm! I added a suggestion for a third goal for vendors but we may want to pull that out as a standalone use case.

2021-07-21 18:41 UTC, kimsterv commented on use_cases.md
> +These are some of the use cases for SLSA.  Of these the first use case (a vendor checking their
Instead of vendor, how about developer? I think that would capture both vendors and maintainers of open source projects.

2021-07-21 18:41 UTC, kimsterv commented on use_cases.md
> +
3. Access to metadata for auditing and ad-hoc analysis.

2021-07-21 20:19 UTC, TomHennen commented on use_cases.md
> +    [source control attestations](https://github.com/in-toto/attestation/issues/47)) for BarImage
Done

2021-07-21 20:19 UTC, TomHennen commented on use_cases.md
> +1.  Protect their users from malicious changes to the BarImage container image
Done

2021-07-21 20:19 UTC, TomHennen commented on use_cases.md
> +4.  Have the control-point check the candiate BarImage against it's provenance, checking:
It's -> fixed.  I know the difference!  Somehow it's bad muscle memory.
candiate -> apparently the GitHub editor suppresses spelling mistakes squiggles
Having -> never actually heard of that before.  Fixed, I think.

2021-07-21 20:19 UTC, TomHennen commented on use_cases.md
> +    [in-toto Provenance](https://github.com/in-toto/attestation/blob/main/spec/predicates/provenance.md)
Done

2021-07-21 20:24 UTC, TomHennen commented on use_cases.md
> +These are some of the use cases for SLSA.  Of these the first use case (a vendor checking their
Yes that's better.  Changed here and in the first example.  First example still talks about 'BarInc' think that's fine?

2021-07-21 20:24 UTC, TomHennen commented on use_cases.md
> +
Sure.  Also added '6.  Storing the provenance and all other attestations for future reference.' below.

This is where Rekor would be nice for open source.

Look good?

2021-07-21 20:38 UTC, MarkLodato approved these changes

2021-07-21 20:40 UTC, TomHennen commented on use_cases.md
> +These are some of the use cases for SLSA.  Of these the first use case (a vendor checking their
LMK if you'd like that changed too, I can send another PR.

2021-07-22 17:47 UTC, kimsterv approved these changes
lgtm!

2021-07-22 17:48 UTC, TomHennen commented
Merging now.  Happy to make further changes if anyone has any subsequent thoughts.

2021-07-22 17:48 UTC, merged