content: add principle for defining levels/tracks
slsa-framework/slsa pull request #993
Opened 2023-10-27 13:06 UTC by MarkLodato

Document the principles around defining new levels and tracks. As we
expand SLSA, we need to ensure that SLSA remains focused and
understandable. A large part of that is having a consistent and simple
philosophy.

2023-10-27 18:39 UTC, arewm requested changes

2023-10-27 18:39 UTC, arewm commented on docs/spec/v1.1/principles.md
> +    a new track should be seen as a last resort. Each track should have a clear,
How should we handle the situation where some changes might need to be added to already-published levels in order to add balanced implementations? This action will require a bumping of the SLSA version, and I assume that we also want to create a balance to prevent that from happening too much.

Would it be preferable to start out with a combined track and then split them with a later major version bump if there was opposition or the reverse -- to start separate and major version bump to combine them later?

2023-10-27 18:39 UTC, arewm commented on docs/spec/v1.1/principles.md
> +    and remember, while too few makes each level hard to achieve. Try to bundle
```suggestion
    and remember; too few makes each level hard to achieve. Try to bundle
```
The comma confused me when glancing at it as I read the line "and remember, while [...]" so making the separation of opposing concerns clearer with a semicolon.

2023-10-27 18:39 UTC, arewm commented on docs/spec/v1.1/principles.md
> +    the same time.
Haven't there been some comments about the difference between Provenance L2/L3? Should we specifically call out that there needs to be _intentional_ implementer actions to clearly differentiate between successive levels?

2023-10-27 18:39 UTC, arewm commented on docs/spec/v1.1/principles.md
> +    provenance for the [Build track](levels#build-track). As a rule of thumb, a
How "protected" should this crisp objective be? For example, if a track is created with a specific objective, only to find out later that the objective isn't crisp/precise enough, would a modification of the objective require a version bump?

2023-10-27 18:39 UTC, arewm commented on docs/spec/v1.1/principles.md
> +    new track may be warranted the threats it addresses are unrelated to those
```suggestion
    new track may be warranted if the threats it addresses are unrelated to those
```

2023-10-27 18:39 UTC, arewm commented on docs/spec/v1.1/principles.md
> +    of other tracks. Try to avoid tracks that sound confusingly similar.
confusingly similar in "short name" (do we have a name for that, i.e. build) or objective.

2023-10-27 19:20 UTC, MarkLodato commented on docs/spec/v1.1/principles.md
> +    a new track should be seen as a last resort. Each track should have a clear,
Hmm, I don't have any particular thoughts here. Do you think we need to touch on this, or can we just omit it if we don't have a strong guideline?

2023-10-27 19:20 UTC, MarkLodato commented on docs/spec/v1.1/principles.md
> +    provenance for the [Build track](levels#build-track). As a rule of thumb, a
Hmm, I didn't touch on versioning at all here. Should that instead go in https://slsa.dev/spec-stages#versioning so that all considerations about version bumps are in one place?

2023-10-28 06:42 UTC, lehors reviewed
Thanks for putting this together.

2023-10-28 06:42 UTC, lehors commented on docs/spec/v1.1/principles.md
> +    a new track should be seen as a last resort. Each track should have a clear,
I don't have a problem with adding requirements to an existing level in a new version of the spec. I think it's easy enough to understand "SLSA 2.0 Build Level 3" vs "SLSA 1.0 Build Level 3" for instance, if we are consistently increasing the level of security provided.
On the other hand removing any requirement from an existing track+level, even through a split to a different track, would translate into something like "SLSA 2.0 Build Level 3" being less secure than "SLSA 1.0 Build Level 3" which would be terribly confusing.

2023-10-30 12:39 UTC, MarkLodato commented on docs/spec/v1.1/principles.md
> +    requirements into levels such that an implementer is likely implement all at
fixed

2023-10-30 13:21 UTC, arewm commented on docs/spec/v1.1/principles.md
> +    a new track should be seen as a last resort. Each track should have a clear,
I feel like a corollary to reducing the number of tracks would also be reducing the number of versions produced as that adds a different form of complexity to the specification -- more related to keeping up to date with the breaking changes introduced.

2023-10-30 13:25 UTC, arewm commented on docs/spec/v1.1/principles.md
> +    the same time.
The current guidance for creating new levels is this: 

> Each level should have clear and meaningful security value, such as stopping a particular class of threats

What we do _not_ want, however, is for levels to be created based on classes of threats without work being done by the necessary party/parties. In order to increase the levels, work needs to be undertaken. 

New levels should be defined based on clearly identified classes of threats that are mitigated _AND_ clearly defined implementations that need to be undertaken. If both are not present, then a new level is likely not needed.

2023-10-30 13:29 UTC, arewm commented on docs/spec/v1.1/principles.md
> +    provenance for the [Build track](levels#build-track). As a rule of thumb, a
It might make sense to go there, yes. It is also relevant for the conventional commits -- for example, would these changes be considered editorial or would they be content changes? The conventional commit considerations would likely be too hard to pre-classify though.

2023-10-30 16:05 UTC, trishankatdatadog approved these changes
LGTM, thanks for explicitly clarifying all this!

2023-10-30 19:42 UTC, MarkLodato commented on docs/spec/v1.1/principles.md
> +    a new track should be seen as a last resort. Each track should have a clear,
As discussed in today's spec meeting, I'll leave this to a future PR but leave the comment thread open for visibility.

2023-10-30 19:42 UTC, MarkLodato commented on docs/spec/v1.1/principles.md
> +    the same time.
(same - will leave to a separate PR)

2023-10-30 19:49 UTC, MarkLodato commented on docs/spec/v1.1/principles.md
> +    the same time.
OK, I gave an alternate wording a shot. How does this sound?

2023-11-01 13:02 UTC, MarkLodato commented on docs/spec/v1.1/principles.md
> +    the same time.
FYI I just added a sentence about splitting levels, which I think is in line with @sudo-bmitch's comments at the spec meeting.

2023-11-01 19:29 UTC, arewm approved these changes

2023-11-01 20:18 UTC, lehors approved these changes
LGTM

2023-11-06 18:05 UTC, merged