Guest Blog Post: `SLSA 3 Generator. and EC Validate`
slsa-framework/slsa pull request #995
Opened 2023-11-03 16:27 UTC by seanconroy2021

Guest Blog Post: `SLSA 3 Generator. and EC Validate`
slack discussion: [here](179&cid=C031J4KBFME)
Resloves: EC-214
Signed-Off-by: Sean Conroy sconroy@redhat.com [Enterprise Contract](https://github.com/enterprise-contract)

2023-11-03 17:09 UTC, seanconroy2021 commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +        image: ${env.IMAGE_REPO}
Fix: ${{x}} so the show up correctly in the blog post.

2023-11-03 18:41 UTC, arewm requested changes

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +### Validating with EC Validate
The SLSA GitHub generator has directions for how to [verify using various tools](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/container/README.md#verification). Do you want to additionally submit a PR there for how to achieve verification with EC?

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +As a user of SLSA, you may have come across [Enterprise Contract](https://enterprisecontract.dev), which securely verifies supply chain artifacts and enforces policies regarding their construction an
"SLSA 3" is not a complete reference to a specification (i.e. you need a version, track, and a level). While the GitHub Actions workflow has , the repository seems to mostly refer to itself simply as a "SLSA generator": https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/container/README.md#referencing-the-slsa-generator

The aspect of this comment related to SLSA 3 being non-complete is relevant in other locations throughout the blog post as well.

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +EC Validate is a GitHub Action provided by Enterprise Contract, designed to validate container images. It supports SLSA 3 provenance generated by the SLSA 3 Container Generator and assesses it agains
> It supports SLSA 3 provenance generated by the SLSA 3 Container Generator

How does it support the provenance? It supports making policy-based decisions based on attestations using the SLSA provenance format (and which format -- 0.1, 0.2, 1.0)?

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +EC Validate is a GitHub Action provided by Enterprise Contract, designed to validate container images. It supports SLSA 3 provenance generated by the SLSA 3 Container Generator and assesses it agains
"customized according to your organization's requirements" You link to predefined policies. Do you want to link to the customization process/support as well?

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +Supply chain attacks often exploit the lack of secure and verifiable provenance in software artifacts. SLSA level 3 compliance ensures that every artifact in the software supply chain is built in a c
This is likely to be redundant information for many people reading this blog as the would likely be familiar with the specification. You can also just link readers to an appropriate location on the SLSA website so that they can get a detailed view of the need for provenance without having to repeat content here.

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +Enterprise Contract has incorporated the SLSA 3 Container Generator into their [Golden Container Release workflow](https://github.com/enterprise-contract/golden-container/blob/main/.github/workflows/
abbreviate GHCR instead as ghcr.io? If you use the former, an expounding of what it stands for would be more necessary.

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +- **Automated and Enhanced Security**: It takes the heavy lifting out of the validation process, automating what would typically be a complex and meticulous task.
There are other tools that can do this validation, i.e. https://github.com/slsa-framework/slsa-verifier and others [documented](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/container/README.md#verification). Are there specific benefits to EC in this aspect or does this benefit apply to all within the class of verifiers?

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +- **Increased Trust**: By ensuring the artifacts comply with SLSA level 3 standards and passing the EC Validate checks, users can have increased confidence in the security of their software supply ch
Are there specific attack vectors that consumers are able to mitigate against if using EC over other verification methods?

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +```
This is cool, but is is related to the provenance verification by the EC workflow? Can EC take advantage of the generated SBOM and attestation when consuming the artifact?

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +The SLSA 3 Container Generator signs the provenance using a trusted key, which is then uploaded to the container registry, providing an additional layer of verification for the final image.
Do you want to replicate this information here or just point to other documentation for readers to follow (which will stay up to date)? It is fine if you decide to include it here -- there may be _explicit_ benefit to it that I am not aware of.

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +- **Custom Policy Enforcement**: Organizations can enforce their specific security policies during the validation process, ensuring that every artifact meets set requirements.
Do you have an example of what can be done with this for in a GitHub Action workflow?

2023-11-03 18:41 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +In the real world, Enterprise Contract has implemented this approach to secure a critical application deployment:
The term "real world" doesn't seem necessary.

2023-11-03 18:46 UTC, arewm commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +    image: ${ needs.build.outputs.image }}@${{ needs.build.outputs.digest }
I think the double brackets are breaking Netlify's build

2023-11-09 11:17 UTC, seanconroy2021 commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +### Validating with EC Validate
yes will do :)

2023-11-27 13:02 UTC, seanconroy2021 commented
Apologies for the delay in the blog fix. I'm dedicating my day off today to get this sorted out.

2023-11-27 13:56 UTC, seanconroy2021 commented on docs/_posts/2023-10-26-slsa-and-action-validate.md
> +- **Custom Policy Enforcement**: Organizations can enforce their specific security policies during the validation process, ensuring that every artifact meets set requirements.
We don't have an example of using a custom policy with the GitHub Action currently.

2023-12-05 14:15 UTC, closed without merging